### ISSUE TITLE
Фронтэнд старонкі Як карыстацца модулем (FAQ)

### ISSUE THREAD

**Issue by svetasemashko** [diglabby/doika#10]
https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346124777675

**Comment by falanster** [comment]
@nastyafrosty ці ёсць у нас гэта старонка на РТБ?

**Comment by fr0zen** [comment]
@falanster @svetasemashko як лічыце, адкуль лепш браць тэкст для гэтай старонкі?

- [ ]  Залінкаваць спасылку на борд са скрынам

**Comment by falanster** [comment]
@fr0zen пакуль пакінуць пустой, бо гэта не прыярытэтна зараз. толькі пасля пераносу коду.

**Comment by svetasemashko** [comment]
@fr0zen мы яшчэ не пісалі такі тэкст, будзе шорт відэа, есць лэндінг. Можна будзе на аснове гэтага зрабіць

**Comment by nastyafrosty** [comment]
it's better to make the type of the question bigger on 2pt or **bold**

**Comment by nastyafrosty** [comment]
- When question is closed the symbol should be "+"
- to open it a user should tap on "+"
- and when the question opens, the symbol turns to "-"

**Comment by rizomaa** [comment]
@nastyafrosty @fr0zen ці дастаткова тут разумення наконт структуры FAQ старонкі?

@Olya147 падумай якую инфу лепей занесці на старонку карыстання модулём?

**Comment by fr0zen** [comment]
Зараз FAQ хутчэй тэставае, разглядзець, якія аспекты працы модуля мы можам ўжо дадаць у FAQ

**Comment by fr0zen** [comment]
https://docs.google.com/document/d/1rtnML9M-gQD_BifhTumMOdSyyVd83wt5p8Db5NLGJKg/edit спасылка на док, адказаць на пытанні і дадаць у модуль.

**Comment by rizomaa** [comment]
@Olya147 пагутары з @cema93 магчыма атрымаеш адказы на 70% пытанняў тут

**Comment by ghost** [comment]
@rizomaa @fr0zen @cema93 @lptn @alexap13 Ознакомьтесь со списком возможных вопросов пользователей, пожалуйста. Если есть замечания, знаете ответы или появились ещё какие-то идеи - оставьте свои комментарии:
https://docs.google.com/document/d/1rtnML9M-gQD_BifhTumMOdSyyVd83wt5p8Db5NLGJKg/edit

**Comment by cema93** [comment]
@Olya147 мне вопросы наравятся

**Comment by ghost** [comment]
@rizomaa @fr0zen @lptn что думают остальные?

**Comment by rizomaa** [comment]
@Olya147 агульныя заўвагі. ствары спіс таго, што гатова. дадатковыя пытанні пасля дададзім
