### ISSUE TITLE
Праверыць, як працуюць спасылкі, ці няма 500, або 403, або 404 памылак пры пераходзе па старонках. Калі есць, задакументаваць.

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#100]
Спасылка на тэст http://it3donate-landing.falanster.by/doika/admin/campaigns.
Прайсціся па ўсіх спасылках на модулі і выявіць непрацуючыя.

**Comment by ursar** [comment]
**Ошибка 404 при смене языка с помощью меню Language.**

**Environment:** Google Chrome 71.0.3578.98 (32 бит)

**Steps of reproduce:**
1.	Нажать на меню Language;
2.	Выбрать пункт Беларуская;
3.	Нажать кнопку в браузере назад;
4.	Выбрать пункт Русский;
5.	Нажать кнопку в браузере назад;
6.	Выбрать пункт English.

**Actual result:** Ошибка 404(Not Found)
Для пункта меню Беларуская открывается URL http://it3donate-landing.falanster.by/be/admin/campaigns
Для пункта меню Русский открывается URL http://it3donate-landing.falanster.by/ru/admin/campaigns
Для пункта меню English открывается URL http://it3donate-landing.falanster.by/en/admin/campaigns

**Expected result:** происходит смена языка при выборе пункта меню:
•	Беларуская на белорусский язык;
•	Русский на русский язык;
•	English на английский язык.

**Comment by andrey1999999** [comment]
Headline: Ошибка в написании в меню приложения.
Severity: Enhancement.
Description: 
1.Открыть приложение- http://it3donate-landing.falanster.by/doika/admin/campaign  
Result:
1.В списке компаний - орфографическая ошибка. 2.В меню приложения - орфографическая ошибка.
![screenshot_1](https://user-images.githubusercontent.com/30193031/50934935-e8701e80-1472-11e9-836b-927a51593e72.png)

**Comment by andrey1999999** [comment]
2. Headline: Неверный перенос слова.

Severity: Enhancement.

Description: 
1.Открыть приложение- http://it3donate-landing.falanster.by/doika/admin/campaign
2.Открыть из меню пункт "Campaigns".
3.Нажать пункт "First campaign".   

Result:
1.Неверный перенос слова "Finish at".      

Attachments:
![screenshot_2](https://user-images.githubusercontent.com/30193031/51001554-14ee6e00-1539-11e9-916c-d14de2431b74.png)

**Comment by andrey1999999** [comment]
3.Headline: При заполнении одного окна, данные дублируются в остальные три окна.

Severity: Average.

Description: 
1.Открыть приложение- http://it3donate-landing.falanster.by/doika/admin/campaign
2.В окно "Bepaid Market Id" ввести данные, например 1.

Result:
Введенные данные дублируются во все остальные окна.

Expected result: 
Данные введенные в окно "Bepaid Market Id" не должны дублироваться в остальные окна.    
       Attachments:
![screenshot_3](https://user-images.githubusercontent.com/30193031/51002326-9d6e0e00-153b-11e9-9b8a-8a102224d27b.png)


4. Headline: Не корректное написание слова.

Severity: Enhancement.

Description: 
1.Открыть приложение- http://it3donate-landing.falanster.by/doika/admin/campaign

Result:
Некорректное написание слова "Bepaid".

       Attachments:
![screenshot_4](https://user-images.githubusercontent.com/30193031/51002388-c5f60800-153b-11e9-8ec2-449b998e0306.png)

5.	Headline: Не выполняется вставка изображения.
Severity: Average.

Description: 
1.Открыть приложение- http://it3donate-landing.falanster.by/doika/admin/campaign
2.Открыть из меню пункт "Payment systems".
3.Нажать вкладку "Insert image".
4.Выбрать изображение.
5.Нажать "ок" на всплывающей вкладке.
      
Result:
1.Не выполняется вставка изображения.
       Attachments:
![screenshot_5](https://user-images.githubusercontent.com/30193031/51002423-dd34f580-153b-11e9-97f9-e3dbc2df96a0.png)

6.  Headline:Не выполняется функция создать нового пользователя.
Severity: Average.

Description: 
1.Открыть приложение- http://it3donate-landing.falanster.by/doika/admin/campaign
2.Открыть из меню пункт "Users".
3.Заполнить поле "Name", “Email”, “Password”, Repeat password”.
4.Нажать “Create”.
      
Result:
1.Не выполняется функция создать нового пользователя.

**Comment by rizomaa** [comment]
@fr0zen стварылі асобныя карткі. таму зачыняем
