### ISSUE TITLE
Хинты для полей Shortcode и Title оформлены на русском языке

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#101]
Environment: google chrome.

![1](https://user-images.githubusercontent.com/46268205/50550997-3f177480-0c8b-11e9-863a-c9a7acb53190.jpg)
Steps of reproduce:
1. Открыть модуль Campaings;
2. Нажать на кнопку Create campaign;

Actual result: при наведении курсора на поля Shortcode и Title появляются всплывающие подсказки на русском языке.

Expected result: все всплывающие подсказки выполнены на английском языке.

**Comment by rizomaa** [comment]
@Olya147 зачыняем карту, залежыць ад лакалі кампа кліента
