### ISSUE TITLE
Длина текстовых полей не ограничена

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#103]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль Campaigns;
2. Нажать кнопку Create campaign;
3. Ввести в поле Shortcode запись, превышающую 256 символов;
4. Повторить шаги 1-3 для полей Title, Description. 

Actual result: поле полностью принимает введённое значение.

Expected result: поле должно быть ограничено количеством n-символов.

**Comment by rizomaa** [comment]
чаму лічыш неабходна гэта абмежаванне? @Olya147 
@fr0zen @Tyuba4 якія значэнні у базе будуць для гэтага значэння?

**Comment by fr0zen** [comment]
Зараз верстка павінна адаптоўвацца пад колькасць існуючага тэксту. Думаю размер тэкста трэба пакінуць пад адказнасць карыстальнікаў, таму абмежаванне знята.
