### ISSUE TITLE
Бэкэнд. Создать новую кампанию

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#104]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль Campaigns;
2. Нажать кнопку Create campaign;
3. В поле Shotcode ввести 100;
4. В поле Title ввести АБВ;
5. В поле Start at 01.12.2018;
6. В поле Finish at 31.12.2018;
7. Нажать на кнопку Save.

Actual result: появляется сообщение об ошибке "exceptions general". Кампания не создана. 

Expected result: кампания успешно создана и отражается в общем списке. Все обязательные поля отмечены *. В случае, если какое-либо из них не заполнено, появляется сообщение об ошибке.

**Comment by rizomaa** [comment]
Выдатна, гэта картка для рэалізацыі пры рэактарынгу

**Comment by alies-dev** [comment]
а ў мяне атрымліваецца стварыць кампанію, а вось карцінка кампаніі неяк дзіўна аплоадзіцца, @fr0zen глянь калі ласка 
![image](https://user-images.githubusercontent.com/5278175/57813455-d2ec6780-7778-11e9-9474-2d5f9ff484e8.png)

**Comment by ghost** [comment]
@lptn  только что переустановила модуль. При попытке создать кампанию и пользователя как и раньше появляется надпись exeptions.general.

**Comment by fr0zen** [comment]
@Olya147 падкажы калі ласка, ці змяняеш базу, калі пераўсталеўваеш?

**Comment by ghost** [comment]
@fr0zen  всё удаляю.

**Comment by alies-dev** [comment]
@fr0zen 
Дарэчы ці можаш паказваць тэкст памылкі рэальны (а не “exeptions.general.“)? -- хочацца мець болей дэталевыя баг-репорты

**Comment by alies-dev** [comment]
@Olya147
на жаль бяз логаў нічока не магу зрабіць(

**Comment by fr0zen** [comment]
@lptn я бачыў, тэстану гэтую штуку, наконт лога згодны

**Comment by ghost** [comment]
@lptn  @fr0zen я поняла: она не создаётся, если не заполнено описание кампании. 
Но поле не отмечено, как обязательное к заполнению.

**Comment by ghost** [comment]
[#120](https://github.com/diglabby/doika/issues/120)
