### ISSUE TITLE
В календаре нельзя ввести дату с помощью клавиатуры

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#105]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль Campaigns;
2. Нажать кнопку Create campaign;
3. Установить курсор в поле Start at;
4. Ввести с клавиатуры 2018.12.01;
5. Повторить шаг 4 для поля Finish at.

Actual result: поле не заполнено.

Expected result: введённая дата отображается в поле.

**Comment by rizomaa** [comment]
@fr0zen што значыць тэг прыпынена?

**Comment by Gordonshik** [comment]
Занимаюсь этим, пока разбираюсь

**Comment by Gordonshik** [comment]
Не могу разобраться с этим заданием, что-то никак у меня не получается пока что.
По поводу того, что для решения сделал:
1) Сначала посмотрел с помощью инструмента разработчика на элемент
увидел этот readonly="readonly", предположил, что вводить с клавиатуры нельзя именно по этой причине. Удалил ридонли в инспекторе и все заработало.
2) Решив, что надо искать файл с этим инпутом, чтобы удалить ридонли стал искать, но ридонли так и не нашел
3) Дальше искал что-нибудь подобное в ответах на стэковерфлоу и т.д.
4) Нашел откуда был скачан плагин датапикера (https://cdnjs.com/libraries/bootstrap-datetimepicker, http://eonasdan.github.io/bootstrap-datetimepicker/#time-only) но ничего для себя полезного увидеть не смог.
5) Знакомый предложил заменить плагин на другой, где данная функциональность уже будет реализована (https://ej2.syncfusion.com/vue/documentation/datepicker/date-format/), но из-за того, что с такими большими и сложными (для меня) проектами до этого не работал не смог это реализовать. То есть я не совсем пока понимаю как подключить плагин и дальше сделать роутинг, или как он называется. То есть я плагина содержимое менял, но сайт падал просто с кучей ошибок, а как это изменить представления не имею, пока что.
6) Пробовал обновленную версию датапикера подгружать, само собой ничего не поменялось.
7) На хабре нашел статью по vuejs, в ходе чтения установил Vue Devtools в браузуер, но мне он помог примерно ничем.
Пытался явно установить readonly="disabled", сравнивал код подобных компонентов из интернета и т.д. Сейчас уже все и не упомню, но если резюмируя, то пока я не совсем понимаю с какой стороны ко всему этому подступиться.

**Comment by rizomaa** [comment]
@Gordonshik дзякуй, што апісалі вашы шляхі рашэння. пакуль мы тады адкладзем гэту картку і папрацуем з іншай. пасля вернеся да гэтай

**Comment by Gordonshik** [comment]
https://stackoverflow.com/questions/17825537/how-to-make-a-input-field-readonly-with-javascript
![изображение](https://user-images.githubusercontent.com/51483246/76683522-bf6a9100-6615-11ea-9fb9-72437bd2b4fd.png)

пробовал сделать как тут, потому что просто убрать readonly не выходит
![изображение](https://user-images.githubusercontent.com/51483246/76683479-6bf84300-6615-11ea-9d8b-56fce813d0ab.png)
по запросу выдает такое, но как я понял в .php файлах смысла ничего менять нет вообще, потому что ничего и не меняется

https://ej2.syncfusion.com/vue/documentation/datepicker/date-format/ этот datepicker интегрировать, код просто не вставился, пытался путем создания компонента и его дальнейшей интеграции пойти, но ни к чему хорошему так и не пришел, сайт полностью разваливался.
Из интернета единственный выход, который я нашел, это поработать с jQuery

**Comment by rizomaa** [comment]
@Gordonshik а гэты datepicker натыўны, або бібліятэка? адчуваю. што бібліятэка. якая, ведаеш?

**Comment by Gordonshik** [comment]
@rizomaa http://eonasdan.github.io/bootstrap-datetimepicker/#time-only
Наш:
![изображение](https://user-images.githubusercontent.com/51483246/76854444-1ebbe180-6860-11ea-8ac6-d8280c0ec76b.png)
а на том только это написано:
![изображение](https://user-images.githubusercontent.com/51483246/76854519-490d9f00-6860-11ea-956a-c2a14a07ff99.png)

**Comment by Gordonshik** [comment]
Сейчас положняк такой:
дзякуй документации я осознал, что эта вещь фиксится, и как оказалось достаточно просто, надо лишь...
Надо лишь ввести button-only вместо data-input в теге инпут датапикера, воть так:
было
![изображение](https://user-images.githubusercontent.com/51483246/77002010-e30e3e00-696b-11ea-8f59-dba0eb34b29e.png)
стало
![изображение](https://user-images.githubusercontent.com/51483246/77002042-f02b2d00-696b-11ea-91e0-57ae0abf37c9.png)
Если интересно: 
![изображение](https://user-images.githubusercontent.com/51483246/77002170-1d77db00-696c-11ea-87fd-e55399987470.png)

**Comment by Gordonshik** [comment]
Ах, ну да, батон-онли оказалось отключает кнопку, удивительно, ищу дальше

**Comment by Gordonshik** [comment]
Продолжаю изучать данный вопрос:
1. В документации увидел такую строчку: By default, <b-form-datepicker> returns dates as a string in the YYYY-MM-DD format, which is the same format returned by native browser <input type="date"> controls.
В нашем DateTimePicker написано в инпуте type="text"
Опустился вниз CampaignForm, так это: 
![изображение](https://user-images.githubusercontent.com/51483246/77223463-e40ebd80-6b6d-11ea-85ad-c371517c50d6.png)
2. 
![изображение](https://user-images.githubusercontent.com/51483246/77223573-cee65e80-6b6e-11ea-9dd6-7976b01e3224.png)
После этого опять прихожу к мысли об этом ридонли и как его убрать
![изображение](https://user-images.githubusercontent.com/51483246/77223624-5502a500-6b6f-11ea-861c-001b8395d967.png)
Из этого примера видно, что состояние datepicker будет определяться значением value, однако, в нашем случае мы имеем readonly, хотя это нигде не указано.
Пораскинув мозгами, начинаю догадываться, что disabled и readonly указываются явно, в то время как normal явно нигде не указывается, а лишь является состоянием изначальным и сохраняется до тех пор пока не указано иное
Из экспериментов понял, что buttononly и все такое фактически отключает только саму кнопку календаря этого, однако там где кликаешь на инпут, он вполне себе открывается.

**Comment by rizomaa** [comment]
@Gordonshik мне найбольш гэта штука з усяго падабаецца. Ці глядзеў тут?
https://bootstrap-vue.js.org/docs/components/form-datepicker/#button-only-mode

**Comment by Gordonshik** [comment]
@rizomaa да, два комментария назад. Что-то не получилось тогда, попробую еще

**Comment by rizomaa** [comment]
@Gordonshik дзякуй. 
1. па магчымасці пакідай прамыя лінкі на сорсы. бо я не злавіў гэтысорс. праз пошук на старонцы. 
2. калі нешта імплеменціш, посці код тэкстам, так зручней глядзець на магію=)

зы
калі бачу занадта шмат блытанага коду, бяру чыстую кампаненту ў дакументацыі. так прасцей рабіць рэверс інжынірынг і знаходзіць працоўнае рашэнне.

у мяне чэшуцца рукі пакалупацца з тваёй задачай, але яе ўжо пачаў з іншай, таму тут пакуль не буду супер глыбока ўмешвацца)

**Comment by Gordonshik** [comment]
Пытаюсь интегрировать новый датапикер, пытался и в код вставить того датапикера в код campaignform.vue, ничего не получилось.
Далее создал новый компонент и туда занес датапикер, чтобы его уже передать по export-import  <new-time-picker /> но ничего все равно не выходит, проблема в том, что как я его не интегрирую, все время кнопка самого датапикера куда-то исчезает и пока что мне не совсем понятно, надо будет конечно посмотреть куда эту кнопку интегрирую, есть мысли по этому поводу пока что еще
![изображение](https://user-images.githubusercontent.com/51483246/77324264-8c1bb680-6d27-11ea-9c05-9a2736d3e4e6.png)
пока так, и проблема не в том, что верстка едет, у меня она и не ехала, а button куда-то исчезал все равно
Есть мысля наш датапикер привязать к инпуту, который button-only
![изображение](https://user-images.githubusercontent.com/51483246/77328919-4b736b80-6d2e-11ea-8a3a-8f7b3bd2ab50.png)
Например вот, вроде все норм, но 
```
<b-input-group-append>
        <b-form-datepicker
          v-model="value"
          button-only
          right
          locale="en-US"
          aria-controls="example-input"
        ></b-form-datepicker>
      </b-input-group-append>
```
куда-то исчезает, если наши кнопки меняю на ту, что из презентации, то в итоге исчезает все, да и если перед ними вставить датапикер этот, то же самое

**Comment by Gordonshik** [comment]
Короче говоря по сто раз пытался со свойствами разобраться, менять их, ничерта не работает. По сути, что я тот из документации компонент беру, что пытаюсь изменить уже встроенный в проект результат один - появляется возможность писать в инпут, но исчезает функция выбора datapicker при клике на инпут.
Есть мысль вызов привязать к клику на кноку календаря, а инпут просто оставить, попробую так сделать.

**Comment by rizomaa** [comment]
Зачыняю гэту картку, бо яна не ключавая зараз аніяк. І без яе можна запускааць праект
