### ISSUE TITLE
Значение поля Finish at в календаре может быть меньше, чем в поле Start at

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#106]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль Campaigns;
2. Нажать кнопку Create campaign;
3. Ввести в поле Start at 2018.12.01;
4. Ввести в поле Finish at 2018.01.01.

Actual result: отсутствует сообщение об ошибке, форма принимает заданный интервал.

Expected result: появляется сообщение об ошибке "Проверьте даты".

**Comment by cema93** [comment]
Логика:
Действия при изменении поля start_time:
1. Установить текущее значение поля start_time как минимальное для поля finistAt
2. Проверить,  не является ли текущее значение поля finistAt меньшим, чем значение поля  start_time. Если finistAt <= start_time  удалить значение finistAt

Действия при изменении поля finistAt:
1. Установить текущее значение поля finistAt как максимальное для поля start_time
2. Проверить,  не является ли текущее значение поля start_time меньшим, чем значение поля  finistAt. Если start_time >= finistAt   удалить значение start_time

**Comment by cema93** [comment]
Реализация на jquery:
$("#start_at").set("onChange", function(d){ $("#finistAt").set( "minDate" , d ); });
$("#finistAt").set("onChange", function(d){ $("#start_at").set( "maxDate" , d ); });

Пишу, чтобы не забыть, позже перепишу на vue

Материалы по теме
[https://vuejs.org/v2/guide/events.html#ad](https://vuejs.org/v2/guide/events.html)

**Comment by cema93** [comment]
@diglabby/frontend  Что-то я не очень понимаю, куда лучше всего писать функции для фронта. В какой файл?

**Comment by rizomaa** [comment]
@cema93 тут разабраўся?
