### ISSUE TITLE
Запись Finish at в календаре не вмещается в строку

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#107]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль Campaigns;
2. Нажать кнопку Create campaign;

Actual result: запись разделена на 2 строчки как "Finis" и "h at". 

Expected result: при нехватке места перенос происходит по целым словам.
![3](https://user-images.githubusercontent.com/46268205/50551490-22326f80-0c92-11e9-896b-118d23240394.jpg)

**Comment by rizomaa** [comment]
@Olya147 бага пазщтараецца. закрываю гэту
