### ISSUE TITLE
При выборе даты календарь не сворачивается

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#108]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль Campaigns;
2. Нажать кнопку Create campaign;
3. Установить курсор в поле Start at;
4. В появившемся календаре выбрать произвольную дату;
5. Повторить шаг 4 для поля Finish at.

Actual result: при выборе числа календарь не сворачивается. Его можно закрыть либо нажав на пиктограмму, либо щёлкнув за его пределами.

Expected result: при выборе числа календарь исчезает.

http://it3donate-landing.falanster.by/doika/en/admin/campaigns/1/edit

**Comment by KahjuksEi** [comment]
@Olya147 это уже исполненная https://github.com/diglabby/doika/issues/99 . В новой версии при выборе числа календарь исчезает.

**Comment by rizomaa** [comment]
@Olya147 @KahjuksEi тады добра пратэсціць і калі будзе працаваць закрывайце ішшу
