### ISSUE TITLE
В календаре поля принимают любые значения года в промежутке от 1000 до 9999

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#110]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль Campaigns;
2. Нажать кнопку Create campaign;
3. Внести в поле Start at "1000";
4. Внести в поле Finish at "9999".

Actual result: форма принимает введённые значения. Нет сообщений об ошибке.

Expected result: значения полей имеют временные ограничения (приближенные к текущему моменту).

**Comment by fr0zen** [comment]
Не актуальна
