### ISSUE TITLE
Прыбраць Recurrent укладку

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#112]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль Campaigns;
2. Нажать кнопку Create campaign;
3. Внести запись в поле Recurrent. 

Actual result: поле не активно. Запись не набрана.

Expected result: введённые символы отображаются.

http://it3donate-landing.falanster.by/doika/en/admin/campaigns/1/edit#

**Comment by rizomaa** [comment]
![selection_005](https://user-images.githubusercontent.com/9870374/53107776-d9d35780-3546-11e9-8f08-724a8ff73ca7.png)
