### ISSUE TITLE
Дадаць лакализацыю Delete Image на старонцы кампаніі

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#114]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль Campaigns;
2. Нажать кнопку Create campaign;
3. нажать на кнопку Browse;
4. в появившемся окне выбрать любой файл допустимого формата (gif, jpg, jpeg, png);
5. нажать на кнопку Открыть.

Actual result: Выбранная картинка загружена. Вместо кнопки Delete Image есть только ссылка buttons.campaign.deleteImage. 
Невозможно удалить загруженное изображение без потери внесённых данных.

Expected result: в форме есть кнопка Delete Image. При нажатии на неё загруженная картинка удаляется.

**Comment by rizomaa** [comment]
![selection_003](https://user-images.githubusercontent.com/9870374/52521029-0606f280-2c82-11e9-8196-04e27af0f761.png)

**Comment by ghost** [comment]
исправлено.
