### ISSUE TITLE
Загрузка повреждённых файлов в поле Title image

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#115]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль Campaigns;
2. Нажать кнопку Create campaign;
3. Нажать на кнопку Browse;
4. загрузить заранее повреждённый графический файл.

Actual result: фото загружено.

Expected result: появляется сообщение об ошибке "Файл повреждён". Изображение не загружено.

**Comment by rizomaa** [comment]
@Olya147 я вось падумаў, што загружаць адразу пашкоджаны файл, гэта даволі рэдкі выпадак. таму пакуль картку зачыняем. Калі выпаўзе яшчэ, тады можам папрацаваць над гэтай праблемай. дзякуй за працу.
