### ISSUE TITLE
При нажатии на строку “Title image” исчезает ссылка на загруженное изображение

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#116]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль Campaigns;
2. Нажать кнопку Create campaign;
3. Нажать на кнопку Browse;
4. Загрузить произвольный графический файл (допустимый формат png, gif, jpg, jpeg);
5. Нажать на кнопку Browse;
6. В появившемся окне нажать на кнопку Отмена.

Actual result: ссылка на загруженное изображение пропадает.

Expected result: ссылка остаётся на прежнем месте.

**Comment by fr0zen** [comment]
Не актуальна, механізм загрузкі змяняўся.
