### ISSUE TITLE
Нет сообщения об ошибке при попытке загрузить файлы недопустимых форматов.

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#117]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль Campaigns;
2. Нажать кнопку Create campaign;
3. Нажать на кнопку Browse;
4. Загрузить текстовый файл.

Actual result: файл загружен.

Expected result: документ не загружается. Появляется сообщение об ошибке "Недопустимый формат файла".

**Comment by rizomaa** [comment]
@Tyuba4 @fr0zen якія фарматы дапускаем?

**Comment by fr0zen** [comment]
@rizomaa jpg, png, jpeg

**Comment by alies-dev** [comment]
> fr0zen added the гарачая 🔥  label yesterday

Я думаю гэта не актульана, прынамкі валідацыя на бэке есць
