### ISSUE TITLE
UI Распрацаваць агульны выгляд адмін панэлі

### ISSUE THREAD

**Issue by svetasemashko** [diglabby/doika#12]
@nastyafrosty дапрацаваць

- [ ] #8 
- [ ] #9 
- [ ] #11 
- [ ] #12 
- [ ] #13 
- [ ] #15

**Comment by nastyafrosty** [comment]
@fr0zen сделать новый репозиторий и себе закинуть?

**Comment by fr0zen** [comment]
@nastyafrosty так, калі нешта будзе з'яўляцца лей у асобны рэпазіторый. Бачу ен ужо створаны https://github.com/diglabby/doika-design

**Comment by falanster** [comment]
@fr0zen гэта вельмі агульная задача, паглядзі калі ласка ёсць яшчэ 

- [ ] #8 
- [ ] #9 
- [ ] #11 
- [ ] #12 
- [ ] #13 
- [ ] #15 

паглядзі, калі гэта гартка рабіваецца іншымі, трэба тады там пісаць усе дэталізацыі па кожнай старонцы.

**Comment by falanster** [comment]
@svetasemashko удакладні калі, ласкашто ты мела на увазе пад словам "дапрацаваць"?

**Comment by falanster** [comment]
@svetasemashko @fr0zen калі няма каментароў, я зачыню картку праз 2 дні...

**Comment by svetasemashko** [comment]
@nastyafrosty прататып гэтай старонкі гатовы? ці трэба яшчэ час каб над ім працаваць?

**Comment by nastyafrosty** [comment]
@svetasemashko  прототипы старые https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346112938063     
из нового - скрины @fr0zen
