### ISSUE TITLE
Захоўваць дадзеныя пры выпадковым пераходзе ў іншы раздел

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#122]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль Campaigns;
2. Нажать кнопку Create campaign;
3. Заполнить все поля формы;
4. Перейти в раздел Payments.

Actual result: пользователь переходит на страницу выбранного пункта меню; введённые ранее данные не сохранены.

Expected result: появляется сообщение "Сохранить введённые данные?" или "Покинуть форму?".

**Comment by rizomaa** [comment]
@fr0zen у мяне пытанне, калі задача не пачыналася,як яна можа быць прыпынена? )

**Comment by rizomaa** [comment]
@darth-tesla бачу карта у прагрэсе. Напішы, што змянілася за апошні тыдзень?

**Comment by rizomaa** [comment]
@darth-tesla Знайшлі багу рэалізацыі гэтай задачы. Тут дэталі: https://github.com/diglabby/doika/issues/771
