### ISSUE TITLE
Прыбраць квітанцыі аб аплаце

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#123]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль  Payments; (Payments = Спіс ахвяраванняў 
Па спасылцы: http://doika2/doika/doika/dashboard/transactions)
2. Выбрать в таблице First campaign;
3. нажать на кнопку Print.

Actual result: документ не распечатан. Появляется сообщение "exceptions.general".

Expected result: квитанция успешно распечатана.

**Comment by rizomaa** [comment]
@fr0zen дарэчы гэта функцыя непатрэбна зараз таму кали ласка прыбяры

**Comment by fr0zen** [comment]
@Olya147 дзякуй за грунтоўны падыход, @rizomaa так, згодны, прыбіраю

**Comment by rizomaa** [comment]
Тут проста трэба схаваць гэты значок, бо ў скоўпе такога не значылася

**Comment by Gordonshik** [comment]
Не понятно где этот модуль payments, пооткрывал все в меню, но такого модуля не нашел, где он вообще?

**Comment by rizomaa** [comment]
@Gordonshik тут апісанне задачы трэба адрамантаваць

1.
Payments = Спіс ахвяраванняў (дадаў гэта ў апісанне карткі.)
Па спасылцы: http://doika2/doika/doika/dashboard/transactions

2. Трэба зрабіць 3-4 тэставых плацяжа (можна проста не рэкурэнтных). 

3. Пасля з'явіцца спасылка на кампанію па яко зроблены данат. 

4. Там згодна з апісаннем убачыш кнопку, якую трэба схаваць.

На мой погляд сама задача магчыма не такая складаная, як шлях да яе =) Таму ўдачы. Чакаю ад цябе пытанняў, калі што няясна.

**Comment by Gordonshik** [comment]
@rizomaa тестовые платежи через виджет делается, так?

**Comment by rizomaa** [comment]
@Gordonshik 

Праз віджэт зараз або базу наўпрост. 

Але будзе прафесійней:
1. Спачатку занесці наладкі bepaid у модуль.
2. Пасля ўсталяваць на нейкай старонцы віджэт і праз яго пракруціць плацяжы.

ЗЫ
Таксама важна пагартаць вікі, дзесці былі дадзеныя для тэставых плацяжоў там)

**Comment by Gordonshik** [comment]
@rizomaa дадзеные эти посмотрел уже, да, буду разбираться

**Comment by Gordonshik** [comment]
Что-то не то может делаю, но пока что через виджет платежи не появляются. При чем ни в списке компаний не появляется изменений, ни в списке ахвяраванняу.
Думал проблема в том, что срок компании уже прошел, но изменил, до конца 6 дней, но все равно ничего не меняется. При чем сам виджет из компании информацию получает, текст, название и т.д.
Было бы неплохо еще проверить у других как и что.

**Comment by rizomaa** [comment]
@Gordonshik 

Некалькі пытанняў да цябе. 

1. Наогул самі плацябы праходзяць без праблем?
2. Ці захоўваюцца ў цябе наладкі пацёжнага шлюза ў самім модулі? бо дзесці бачыў ішшу #550 што яны наогул не запісваюцца.
3. Дарэчы ў самой таліцы базы звестак з'яўляюцца плацяжы?
