### ISSUE TITLE
Невозможно отправить по электронной почте отчёт об оплате

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#124]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль  Payments;
2. Выбрать в таблице First campaign;
3. Нажать на кнопку Send email.

Actual result: появляется сообщение "exceptions.general". Документ не отправлен. Внешний вид страницы не изменился.

Expected result: пользователь переадресован на страницу ввода почтового адреса.

**Comment by rizomaa** [comment]
@fr0zen гэта таксама непатрэная сёння функцыя. трэба пачысцмць. 
патэнцыйна цікава але пасля
