### ISSUE TITLE
Фронт. Змяніць назвы палёў. 

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#125]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль  Payments;

Actual result: счёт в графе Backer имеет длину 13 символов.

Expected result: счёт состоит из 16 цифр.

**Comment by rizomaa** [comment]
@Tyuba4 удакладні сткрутурку поля у азе дадзеных ?

**Comment by rizomaa** [comment]
![selection_006](https://user-images.githubusercontent.com/9870374/53108616-63cff000-3548-11e9-94c0-5e63ecf5fa5c.png)

**Comment by fr0zen** [comment]
- [ ] Змяніць назву поля Backers на Name.
- [ ] Дадаць поле статус карты

**Comment by fr0zen** [comment]
Фармат карты заменены на фармат, які пастаўляе нам Bepaid. Пераклад зроблены.
