### ISSUE TITLE
Поля в отчёте “Show payment” не заблокированы 

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#126]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль  Payments;
2. Выбрать в таблице First campaign;
3. Заполнить все поля.

Actual result: в поле отражается вся вводимая информация.

Expected result: текстовые поля заблокированы.

**Comment by rizomaa** [comment]
@fr0zen пракаментуй

**Comment by fr0zen** [comment]
Рэалізавана табліца транзакцый, дадзеныя выводзяцца. Магчымасці выдаліць транзакцыі без выдалення кампаніі няма.

**Comment by rizomaa** [comment]
@fr0zen як твой каментар суадносіцца з назвай дадачы?
