### ISSUE TITLE
При увеличении масштаба до 125-150 % таблица выходит за пределы экрана

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#127]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль  Campaigns;
2. Установить масштаб страницы = 125%

Actual result: таблица выходит за пределы поля.
![8](https://user-images.githubusercontent.com/46268205/50555097-ae678580-0cd8-11e9-92f8-934e92639c9f.jpg)

Expected result: таблица полностью видна пользователю. Вид страницы изменяется пропорционально установленному масштабу.

**Comment by rizomaa** [comment]
@Olya147 а якія чакаемыя паводзіны на твой погляд павінны быць?

**Comment by maxmatoha** [comment]
исправлено
