### ISSUE TITLE
Текст в графе Title выровнен по ширине

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#128]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль  Campaigns;

Actual result:
![9](https://user-images.githubusercontent.com/46268205/50555184-af4ce700-0cd9-11e9-96e9-1756573b2def.jpg)
Expected result: выровнять столбец по левому краю.

**Comment by rizomaa** [comment]
@nastyafrosty так насамрэч, можаш неяк прапанаваць больш месца для назвы кампаніі, бо ткім чынам толькі адно слова будзе нармалёва ўлазіць.
