### ISSUE TITLE
Фронтэнд старонкі Асобная кампанія. Дадаць поле "патрэбная сума"

### ISSUE THREAD

**Issue by svetasemashko** [diglabby/doika#13]
https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346109946739

**Comment by fr0zen** [comment]
- [ ]  Зроблена верстка
- [ ]  Даданы шляхі унутры ларавел

**Comment by nastyafrosty** [comment]
https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346287486767   асобная кампанiя

**Comment by falanster** [comment]
@nastyafrosty можаш удакладниць спасылку, бо гэта вядзе не дакладна...

**Comment by nastyafrosty** [comment]
https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346287518747

**Comment by falanster** [comment]
@fr0zen а дзе ў нас тэставы дамен тут?

**Comment by fr0zen** [comment]
@fr0zen http://it3donate-landing.falanster.by/doika/admin/campaigns/1/edit

**Comment by nastyafrosty** [comment]
http://it3donate-landing.falanster.by/doika/admin/campaigns/create
1)can't find the field with "needed sum"
2) the function of switching on/off the top banner. it exists (i mean in admin panel in link), but it.s new, important, we should write about it (make issue)
3)what should happen after clicking on "recurrent"?

**Comment by falanster** [comment]
@fr0zen ці усё тут відавочна па апісанню?

**Comment by KahjuksEi** [comment]
Нужен ассайн @fr0zen

**Comment by Hellsingi** [comment]
nastyafrosty   А дзе павінанна быць поле "needed sum"?

**Comment by rizomaa** [comment]
@fr0zen перадаю картку @Hellsingi калі ласка сфакусуйся на іншых задачах у спрынце

**Comment by nastyafrosty** [comment]
@Hellsingi https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346287518747 на ртб прототип "кампания", поле "патрэбная сума"

**Comment by rizomaa** [comment]
@KahjuksEi як тут ідзе ў цябе?

**Comment by KahjuksEi** [comment]
в процессе 
![qip shot - screen 693](https://user-images.githubusercontent.com/39082880/51249737-3c17c600-19a5-11e9-99e0-80e4012b9200.png)

**Comment by rizomaa** [comment]
@KahjuksEi прачытай калі ласка назву карткі

**Comment by lptn** [comment]
@diglabby/backend

**Comment by KahjuksEi** [comment]
@nastyafrosty напиши пожалуйста подробнее, что и где надо сделать, в идеале скрин с ртб с обозначенным расположением планируемого поля Требуемой Суммы.

**Comment by rizomaa** [comment]
@fr0zen абнаві тут калі ласка

**Comment by fr0zen** [comment]
@rizomaa з @KahjuksEi сумовіліся, што я зраблю гэтую issue. Змены ўжо в dev. Былі прыняты ў [166](https://github.com/diglabby/doika/pull/166)
