### ISSUE TITLE
Данные в табличной части не соответствуют сведениям кампании, указанным в личной карточке

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#130]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль  Campaigns;
2. В графе Title  выбрать First campaign.

Actual result: данные в таблице не соответствуют сведениям, указанным в личной карточке кампании.
![10](https://user-images.githubusercontent.com/46268205/50555324-904f5480-0cdb-11e9-990e-1a2ff41b77d8.jpg)

Expected result: данные одноимённых столбцов полностью совпадают.

**Comment by rizomaa** [comment]
пакуль гэта заглушка. бо працуе толькі фронтэнд. таму зачыняю картку @Olya147
