### ISSUE TITLE
Форма не сохраняет внесённые в режиме редактирования изменения

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#131]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль  Campaigns;
2. Нажать на пиктограмму Edit в графе Actions;
3. В появившейся карточке изменить значение в любом из полей;
4. Нажать на Save.
Actual result: появляется сообщение об ошибке "exceptions.general". Изменения не записаны. 

Expected result: все изменения сохранены.

**Comment by rizomaa** [comment]
пакуль гэта заглушка. бо працуе толькі фронтэнд. таму зачыняю картку @Olya147
