### ISSUE TITLE
Наличие пиктограммы “Delete” для кампаний, в пользу которых уже осуществлялись платежи

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#132]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль  Campaigns;

Actual result: кнопка Delete напротив кампаний, в пользу которых прошёл платёж (Received>0), активна.

Expected result: Нельзя удалить кампании, у которых значение графы Received больше 0. Пиктограмма отсутствует либо не активна.

**Comment by rizomaa** [comment]
пакуль гэта тэставыя дадзеня. бо працуе толькі фронтэнд. таму зачыняю картку @Olya147
