### ISSUE TITLE
Выбранная кампания не удаляется при нажатии на пиктограмму “Delete” 

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#133]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль  Campaigns;
2. Для First campaign нажать на пиктограмму Delete;
3. В появившемся диалоговом окне выбрать Delete. 

Actual result: появляется сообщение об ошибке "exeptions.general". Данные о кампании не удалены.

Expected result: кампания удалена.

**Comment by rizomaa** [comment]
пакуль гэта тэставыя дадзеня. бо працуе толькі фронтэнд. таму зачыняю картку @Olya147
