### ISSUE TITLE
Суммы в гр. Received (раздел Compaigns) и гр. Amount (раздел Payments) не совпадают

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#134]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль Payments;
2. Открыть модуль Campaigns;

Actual result: общая сумма платежей в гр. Received и Amount не совпадают (в разрезе кампаний).
![11](https://user-images.githubusercontent.com/46268205/50555631-3604c280-0ce0-11e9-8056-7c1396eb0079.jpg)

Expected result: сумма, указанная в гр. Received, должна соответствовать общей сумме принятых платежей гр. Amount.

**Comment by rizomaa** [comment]
пакуль гэта тэставыя дадзеня. бо працуе толькі фронтэнд. таму зачыняю картку
