### ISSUE TITLE
Значения переключателя в графе “Status” не подписаны

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#135]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль Campaigns;

Actual result: значения переключателя в графе Status не подписаны. Пользователю не понятно, что изменится при переключении.

**Comment by rizomaa** [comment]
@Olya147 маеш на увазе не падсвечана?

**Comment by ghost** [comment]
@rizomaa Не понятно, что он означает: действующая кампания или что-то ещё. 
Кроме того, его можно переключать прямо в общем списке кампаний (не заходя внутрь для редактирования).
На макете вместо тумблера статус прописан словами https://miro.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346284206864

**Comment by rizomaa** [comment]
> @rizomaa Не понятно, что он означает: действующая кампания или что-то ещё.
> Кроме того, его можно переключать прямо в общем списке кампаний (не заходя внутрь для редактирования).
> На макете вместо тумблера статус прописан словами https://miro.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346284206864

@Olya147 маеш на ўвазе слупок падпіску з макета?

**Comment by ghost** [comment]
@rizomaa  Нет. На макете есть столбик "Статус кампаніі". На мой взгляд, он более информативен, чем вкл/выкл переключатель.

**Comment by darth-tesla** [comment]
Можно поменять тумблер на [надпись](https://ibb.co/dD0TmqR), что я и хотел сделать сегодня, но есть одно но. Описание будет статическим и не будет меняться при переключении тумблера в разделе "Рэгадаваць кампанию" не происходит ровным счётом ничего. Подробнее описал проблему в ишью #459

**Comment by rizomaa** [comment]
@darth-tesla тут каментар па затыку https://github.com/diglabby/doika/issues/459#issuecomment-647544647 як разумею фіча не  зроблена пакуль наогул
