### ISSUE TITLE
Включённый чек-бокс не добавляет пользователю новых функций

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#136]
Environment: google chrome.

Steps of reproduce:
1. Открыть модуль Campaigns;
2. Активизировать чек-бокс напротив любой кампании.

Actual result: выбранная строка не подсвечивается. Включенный чек-бокс не добавляет новых опций, не влияет на отображение страницы.

**Comment by fr0zen** [comment]
@fr0zen скрыть чек-бокс

**Comment by nastyafrosty** [comment]
@Olya147 @fr0zen ребят, а что тут?) і откуд этот чекбокс

**Comment by ghost** [comment]
Исправлено.

**Comment by cema93** [comment]
@Olya147 просьба уточнить, каким образом это исправлено?
только что установил doika, ситуация описанная в данной issue сохраняется

**Comment by ghost** [comment]
@cema93  чек-бокс скрыт. 
![123](https://user-images.githubusercontent.com/46268205/59683988-cc229b80-91e1-11e9-8986-5cc52a52dbb6.png)
