### ISSUE TITLE
Фронтэнд старонкі Збор дадзенных данэйцераў (Кліентская частка)

### ISSUE THREAD

**Issue by svetasemashko** [diglabby/doika#14]
Кліентская частка. https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346136710150

**Comment by falanster** [comment]
@nastyafrosty залінкуй калі ласка сюды новы дыйзайн

**Comment by falanster** [comment]
@fr0zen гарачы піражок

**Comment by rizomaa** [comment]
@fr0zen @lptn як тут, можа гэта задача ужо вырашана? дублюецца?

**Comment by alies-dev** [comment]
Здаецца гэта дублікат ад  "Фронтэнд. Дадаць старонку ўнясення дадзеных карыстальніка (рэкурэнтныя плацяжы)" #33

Закрываю (Duplicate of #33)
