### ISSUE TITLE
Намаляваць дызайн кліентскай частцы для мабілкі

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#140]

**Comment by nastyafrosty** [comment]
- [ ] полный від

- [ ] без прогесс бара

- [ ] без кнопкі рекурентності
- 

- [ ] верхній баннер

- [ ] без картінкі

**Comment by nastyafrosty** [comment]
https://www.figma.com/file/RlVbECuyzs25TCVHZ1Sls87E/Doika-module-%D0%BA%D0%BBi%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%B0%D1%8F-%D1%87%D0%B0%D1%81%D1%82%D0%BA%D0%B0?node-id=55%3A0

**Comment by nastyafrosty** [comment]
сделала во всех прямоугольниках закругление в 4 пикселя (в выборе рекурентности в прямоугольниках только с двух сторон) , так смотрится чуть "добрее", не слишком строго. в десктопе тоже

**Comment by Olya147** [comment]
@nastyafrosty @fr0zen Можно закрывать?
