### ISSUE TITLE
Выкарыстоўваецца розны мова

### ISSUE THREAD

**Issue by romanromanenko** [diglabby/doika#143]
Steps to reproduce:
1. Адкрыць старонку "http://it3donate-landing.falanster.by/doika/campaign/1".

Actual result: Выкарыстоўваецца розны мова.
Expected result:Выкарыстоўваецца аднолькавая мова.

Severity: Нізкая.

<img width="695" alt="screen shot 2019-01-05 at 9 18 30 pm" src="https://user-images.githubusercontent.com/2761212/50727718-ea16ab00-112f-11e9-945e-68ba0bfeea42.png">

**Comment by rizomaa** [comment]
ага, дзякуй гэта часовая сітуацыя. але так па факту бага.
