### ISSUE TITLE
Terms of Use - не клікабельна

### ISSUE THREAD

**Issue by romanromanenko** [diglabby/doika#144]
Steps to reproduce:
1. Адкрыць старонку "http://it3donate-landing.falanster.by/doika/campaign/1".
2. Націснуць на "Terms of Use".

Actual result: Старонка "Terms of Use" не адчыняецца.
Expected result: Старонка "Terms of Use" адчыняецца.

Severity: Высокая.

**Comment by fr0zen** [comment]
@rizomaa выпраўлена тут [#157](https://github.com/diglabby/doika/pull/157)
