### ISSUE TITLE
Дадаць валідацыю палёў уводу сумы ахвяравання

### ISSUE THREAD

**Issue by romanromanenko** [diglabby/doika#145]
Steps to reproduce:
1. Адкрыць старонку "http://it3donate-landing.falanster.by/doika/campaign/1".
2. Увесці "-1251523" у поле "Summ".

Actual result: Адмоўнае значэнне ўводзіцца.
Expected result: Адмоўнае значэнне не ўводзіцца.

Severity: Сярэдні.

<img width="309" alt="screen shot 2019-01-05 at 9 51 07 pm" src="https://user-images.githubusercontent.com/2761212/50727966-09afd280-1134-11e9-946a-f2d1b0c2fbc2.png">

**Comment by rizomaa** [comment]
ага, будзем дадаваць валідацыю

**Comment by rizomaa** [comment]
@lptn @fr0zen пазначце калі ласка дзе абываецца валідацыю на бэке або на фрнаце?

**Comment by alies-dev** [comment]
@rizomaa 
На бэке валідацыя рэалізавана, адпісваюся

**Comment by rizomaa** [comment]
@fr0zen ці патрэбна на франце яе рабіць?

**Comment by rizomaa** [comment]
@KuhniaDruggist дзякуй за хуткі ПР =) Прыняў ПР, картку адправіў на рэўю)
