### ISSUE TITLE
Пры адкрыцці старонкі ў новай вокладцы, старонка не адлюстроўваецца 

### ISSUE THREAD

**Issue by romanromanenko** [diglabby/doika#146]
Steps to reproduce:
1. Адкрыць старонку "http://it3donate-landing.falanster.by/doika/campaign/1".
2. Адкрыць "Confirm" у новай вокладцы.

Actual result: Старонка не знойдзена(404).
Expected result: Адкрываецца старонка "http://it3donate-landing.falanster.by/en/doika/campaign/1/donate".

Severity: Высокая.

<img width="635" alt="screen shot 2019-01-06 at 11 01 38 am" src="https://user-images.githubusercontent.com/2761212/50733661-7b266a00-11a2-11e9-8836-13e180b9ce3f.png">

**Comment by rizomaa** [comment]
@romanromanenko перафармулюй загаловак
