### ISSUE TITLE
Існуе магчымасць працягваць данад без yказанні пэўнай сумы ахвяраванне

### ISSUE THREAD

**Issue by romanromanenko** [diglabby/doika#147]
Steps to reproduce:
1. Адкрыць старонку "http://it3donate-landing.falanster.by/doika/campaign/1".
2. Націснуць кнопку "Confirm"

Actual result: Адкрываецца старонка "http://it3donate-landing.falanster.by/en/doika/campaign/1/donate"..
Expected result: Нічога не адбываецца.

Severity: Сярэдняя.

**Comment by rizomaa** [comment]
@romanromanenko перафармулюй загаловай калі ласка
