### ISSUE TITLE
Няма абмежавання на колькасць знакаў у поле Phone на старонцы User credentials page

### ISSUE THREAD

**Issue by romanromanenko** [diglabby/doika#149]
Steps to reproduce:
1. Адкрыць старонку "http://it3donate-landing.falanster.by/doika/campaign/1".
2. Выбраць "recurrent".
3. Націснуць кнопку "Confirm".
4. Увесці "1234567890123456789".

Actual result: Уведзеныя дадзеныя адлюстроўваюцца ў полі.
Expected result: Дадзеныя абразаюцца на 12-м сімвале

Severity: Сярэдняя.

**Comment by nastyafrosty** [comment]
@lptn @fr0zen ребят,а что это за странічка User credentials page?

**Comment by alies-dev** [comment]
@nastyafrosty 
@romanromanenko
А які патэрн ці правілы валідацыі мусяць быць для тэлефона? (зараз на бэкэндзе можна макс 20 сымбалаў)

>Expected result: Дадзеныя абразаюцца на 12-м сімвале

то бок прабелы мы не дазваляем выкарыстоўваць? Ці падтрымліваем толькі беларускія нумары без коду краіны? Адкуль гэтыя 12 узяліся?
![image](https://user-images.githubusercontent.com/5278175/59165981-4bea9f00-8b2c-11e9-9c8f-ceced9a05478.png)

**Comment by nastyafrosty** [comment]
@lptn скорее тут вопрос сам, что готовы реализовать. можно сделать и через +3.... и без плюса, и через 8.. (может так еще кто-то пишет). можно чтобы одним скопом писалось, и через проблемы или / ...   если будет шаблон, то его нужно показать в инпуте

**Comment by rizomaa** [comment]
гэта задача, але не гарачая

**Comment by alies-dev** [comment]
@nastyafrosty 
[Такая](https://github.com/jackocnr/intl-tel-input) штука прыблізна?
![image](https://user-images.githubusercontent.com/5278175/60384901-e6833180-9a8b-11e9-8983-d82f2b5588d4.png)

Вядома РБ будзе па дэфолту выбарана

Ці пытаць код краіны увесці рукамі?

**Comment by KuhniaDruggist** [comment]
@rizomaa  Привет. Не совсем понимаю где необходимо внести исправления? Переход по ссылке указанный в описании issue нельзя осуществить. Ошибка: "Не удается получить доступ к сайту"

**Comment by rizomaa** [comment]
@KuhniaDruggist вось скрын.

Як паўтарыць:
1. Ствараеш кампанію
2. Бярэш шорткод з яе
3. Устаўляеш у вакно браўзера і загружаеш 
4. Калі выбраў суму абіраем "Падпіскі"
5. І клікаеш "Пацвердзіць"

Далучаю скрын поля.
![Selection_050](https://user-images.githubusercontent.com/9870374/82763711-486e2780-9e12-11ea-9251-23050733f4f2.png)

**Comment by KuhniaDruggist** [comment]
@rizomaa  Дорого дня. Посидел над этой issue и у меня по этому поводу три реализации.
1. Если речь идет лишь об ограничении количества вводимых знаков, то в данном случае решение простое: input добавляем maxlength="12" и все, проблема решена.
2. Подключить плагин masked input и реализовать маску ввода поля +375 (99) 999-99-99,однако это введет ограничения на ввод данных (в доступе останутся лишь мобильные номера РБ).
3. Реализовать валидацию через атрибут pattern у input, который пропустит поле лишь с правильно внесенными данными, однако есть проблема. Опять таки все сверстано на div и тег form с кнопкой внутри него теряет свой функционал, так как кнопки не привязаны к форме реализация через pattern становится затруднительной - необходимо семантически переверстывать форму.
Какой из способов необходимо реализовать? Возможно я упускаю особенности верстки на bootstrap и данную issue можно закрыть по-другому? Подскажите в каком направлении идти?

**Comment by alies-dev** [comment]
>Опять таки все сверстано на div и тег form с кнопкой внутри него теряет свой функционал, так как кнопки не привязаны к форме реализация через pattern становится затруднительной - необходимо семантически переверстывать форму.

у button ёсць атрыбут `form`, на крайняк можна заюзаць яго каб выкарыстоваць сабміт баттн па-за межамі формы. Я верстку не бачыў, але не думаю што пераверстаць будзе праблемай каб кнопкі былі ўнутры формы

Але тут трэба рашэнне дызайнера лепей, тут кульгае UX. З майскай быў бы лепшы варыянт але можна абыцскіся і болей простым варыянтам. Цягнуць цяжкі пакет не хацелася б (як https://www.npmjs.com/package/vue-phone-number-input)

**Comment by alies-dev** [comment]
>Если речь идет лишь об ограничении количества вводимых знаков, то в данном случае решение простое: input добавляем maxlength="12" и все, проблема решена.

неадназначна

+375 (29) 7821892 // 17
+80297821892 // 12

плюс розныя варыяцыі з прабеламі і дужкамі

найпрасцейшы думаю будзе з 2ма інпутамі 
![image](https://user-images.githubusercontent.com/5278175/83011839-3911f880-a023-11ea-9a6e-7aa1d228d94f.png)

**Comment by rizomaa** [comment]
@KuhniaDruggist так, у гэтай задачы дастаткова абмежаванне 
1. на 12 сімвалаў і 
2. толькі лічбы на ўвод і "+" . 

Астатнія паляпшэнні, калі ўзнікне патрэба будуць ў іншай задачы.

**Comment by KuhniaDruggist** [comment]
@lptn 
@rizomaa 
Хорошо. Я все понял. Тогда делаю минимал только цифры и количество знаков. Если будет по данному вопросу новая issue подкиньте её мне.)))

**Comment by rizomaa** [comment]
@KuhniaDruggist маю на ўвазе =)
