### ISSUE TITLE
В IE не открывается страница Campaigns после прохождения авторизации

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#155]
Environment: IE
Steps of reproduce:
1. Открыть в браузере страницу localhost/doika/admin;
2. Заполнить email и password;
3. нажать Login

Actual result: открывается пустая страница.
![image](https://user-images.githubusercontent.com/46268205/51071738-e66eb100-1666-11e9-958b-abb063152dca.png)

Expected result: пользователь перенаправлен на страницу Campaigns.

**Comment by fr0zen** [comment]
@Olya147 можаш глянуць, як  яно зараз?

**Comment by rizomaa** [comment]
@Olya147 пінгпінг.... я пакуль зачыняю картку. калі выпаузе пераадчыні
