### ISSUE TITLE
Праблемы з усталёўкай модуля.

### ISSUE THREAD

**Issue by KahjuksEi** [diglabby/doika#158]
Пры запуску модуля ў браўзэры выводзіцца памылка з за вынясення тэчкі vendor з гіта ў новай версіі.

**Comment by rizomaa** [comment]
@KahjuksEi дык якая памылка выводзіцца?

**Comment by KahjuksEi** [comment]
![qip shot - screen 697](https://user-images.githubusercontent.com/39082880/51455552-2b779f00-1d5b-11e9-9063-ea8767e0a0b4.png)
