### ISSUE TITLE
Скласці масіў усіх запісаў на адной мове для зручнага пераключэння моўнасці

### ISSUE THREAD

**Issue by nastyafrosty** [diglabby/doika#16]
1. Выпісаць усе радкі з адмінскага і карыстальнічкага інтэрфейсу модуля на беларускай мове у эксэль табліцу
2. Перакласці усе у асобны слопок на рускую версію
3. Улічваць элементы са склонамі (аранжавым), пазначаць зялёным паўторныя надпісы, глядзець дзе патэнцыйна могуць быць ўайлдкарткі.

- [x] сабраць усе словы на бел мове

- [x] перакласці ўсе словы на рус мову

- [x] аформіць у масіў (на скарочаным English)
- [ ]  alerts
- - [ ] ru
- - [ ] be
- [ ] buttons
- - [ ] ru
- - [ ] be
- [ ] labels
- - [ ] ru
- - [ ] be

**Comment by svetasemashko** [comment]
- [ ] сабраць усе словы на бел мове

- [ ] сабраць усе словы на english

- [ ] сабраць усе словы на рус мове

- [ ] аформіць у масіў

**Comment by falanster** [comment]
@KsenjaV як тут у цябе ідзе, ці дастаткова інфармацыі?

**Comment by falanster** [comment]
@fr0zen @KsenjaV я зачыняю задачу #53 бо яна дублюе гэту. 

лінк адтуль https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346292135916

**Comment by KsenjaV** [comment]
Чакаю на інфу ад Аляксея па тым блокам, дзе тэкста не хапае

**Comment by falanster** [comment]
@KsenjaV як у цябе тут ідзе?

**Comment by KsenjaV** [comment]
@falanster чакаю https://github.com/diglabby/doika/issues/16#issuecomment-447090175

**Comment by falanster** [comment]
@KsenjaV перасунуў табе картку

**Comment by rizomaa** [comment]
@fr0zen @KsenjaV абнавіце тут статус карткі

**Comment by fr0zen** [comment]
Масівы перакладаў створаны, рэалізацыя шматмоўнасці - іншая issue. Зачыняю.
