### ISSUE TITLE
Аўтаматычна ствараць архіў-істалятар для рэлізаў

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#160]
## Смежнае

- Рэалізаваць аўта-дэплоймент на тэставыя асяродкі #319
- Прыняць стандарт найменавання версій рэлізаў #416

_______________________

Зноў вяртаюся да пытання, як і дзе будзем фіксаваць версію модуля пры рэлізах. Пакуль бачу наступную схему:
1. Робіцца мерж dev у master.
2. Дадаем у master файл кшталту VERSION.md у якім рукамі змяняем версію.
3. Jenkins з нашага боку захоплівае master, робіць рэлізную версію, 
4. Чытае інфу з VERSION.md
5. Робіць архіў рэлиза з адпаведнай назвай. Кшталту 1.3.2.zip
6. Залівае яго у дэрыкторыю для спампоўвання з сэрвера, кшталту http://doika.falanster.by/download.php?release=1.3.2.zip

Думки на гэты конт? @lptn @Tyuba4 @KahjuksEi @Hellsingi

**Comment by lptn** [comment]
@fr0zen 
>Зноў вяртаюся да пытання, як і дзе будзем фіксаваць версію модуля пры рэлізах. Пакуль бачу наступную схему:

Хачу спачатку зразумець НАВОШТА там "Версіянаванне"

Такжа лічу што https://github.com/diglabby/doika/releases лепшае месца для такіх чэнджлогаў, мы можам адмовіцца ад галіны `dev` і мержыць у масцер нашы ПР. Новым рэлізам будзе толькі код які адзначыны новым тэгам тут https://github.com/diglabby/doika/releases , тамжа пісаць што змянілася, наш Джэнкінс такжа будзе збіраць білды толькі калі мы пратэгалі код на master

**Comment by lptn** [comment]
@fr0zen 
>@lptn мне падаецца, што варыянт з dev->master->release таксама добры, dev - нестабільная версія, master - якая прайшла тэставанне, releases - гатовыя рэлізы. У чым плюс таго, што пакінем толькі master?

Я яшчэ крыху падумаў і вырашыў што рана пакуль прапановаць выдаліць `dev`: у нас ен сапраўды надта нестабільны можа быць, так што давай сфакусуемся на галоўным.

Галоўнае у гэтым іш'ю -- гэта як весці чэнджлог, так?

**Comment by fr0zen** [comment]
@lptn так, я жадаю нейкі changelog з якога можна спарсіць версію праз shell і сабраць на сэрверы рэліз з адпаведным нумарам.

**Comment by fr0zen** [comment]
@lptn проста я не ўяляю сабе сходу як яе зручна спарсіць)

**Comment by lptn** [comment]
@fr0zen 
>@lptn проста я не ўяляю сабе сходу як яе зручна спарсіць)

Не, я пытаю навошта парсіць, ці не можам мы абыйсціся ТОЛЬКІ старонкай https://github.com/diglabby/doika/releases і болей нічога не парсіць і абслушоўваць

Ці, магу задаць пытанне па-іншаму: для каго і чаго нам changelog?

**Comment by fr0zen** [comment]
@lptn крута было б, калі на сэрвере пры усталёўцы трэба было выконваць як мага менш дадатковых каманд. Значыць трэба уключыць залежнасці ў рэліз. Калі мы будзем фарміраваць рэлізы публікуючы майстар-галіну час ад часу, без уключэння залежнасцяў у майстар-галіну не абысціся. Changelog я буду чытаць з дженкінсам на нашам сэрвере і адпаведна яму раздаваць імя кожнай новай зборке.

**Comment by lptn** [comment]
@fr0zen 
калі толькі для імя, то мы таск створым на джэнкінсе каб збіраў праект ТОЛЬКІ калі мы дадалі новы тэг тут https://github.com/diglabby/doika/releases

Усе, болей нічога ня трэба

Калі яшчэ есьць пытанні -- можам сазваніцца ці заўтра адберкаваць

калі няма -- то можна проста закрыць гэты іш'ю

**Comment by fr0zen** [comment]
@lptn так, выдатна, заўтра абмяркуем

**Comment by rizomaa** [comment]
@fr0zen @lptn навошта зачыняць ішу калі мы яшчэ не абмеркавалі ?

**Comment by fr0zen** [comment]
@rizomaa так, дзякуй за reopen, на сустрэчы мы не прыйшлі да агульнага бачання

**Comment by lptn** [comment]
GitHub дазваляе заліваць білды рэлізаў на яго: https://developer.github.com/v3/repos/releases/#upload-a-release-asset

 [скрыпт](https://gist.github.com/stefanbuck/ce788fee19ab6eb0b4447a85fc99f447)

Рэлізы і чэнджлогі можна таксама на GH весці https://github.com/diglabby/doika/releases
Калі хочаце асобны CHANGELOG.md, то можна і яго весці (але я б пачаў бы з GH)


Засталося пытанне дзе збіраць архівы рэлізаў, але думаю на трэвісе зможам без праблемаў

**Comment by lptn** [comment]
@fr0zen 
ці задавальняе такая схема (глядзі мае паведамленне вышэй)

**Comment by alies-dev** [comment]
@fr0zen 
Я перайменаваў задачу каб назва нас не блытала

**Comment by nastyafrosty** [comment]
@lptn по какому прінціпу сейчас создается архів реліза? опіші его,пожалуйста. раотаешь над автоматізаціей?

**Comment by alies-dev** [comment]
@nastyafrosty 
Пры стварэнні новага рэліза на GitHub

1. дадаецца задача ў чаргу задач на Travis CI
2. калі чарга падыходзіць, ствараецца арзіў ([код для стварэння)](https://github.com/diglabby/doika/blob/7c2df71f78e0a09a072fb8a357b7f366c4eecd51/.travis.yml#L44-L65)
3. калі архіў створаны, ен аўтаматычна заліваецца як Asset для рэліза, паглядзець можна [тут](https://github.com/diglabby/doika/releases)


>раотаешь над автоматізаціей?

ну гэта удо працуе, але трэба яшчэ дробязі (на якія пакуль часу бракуе)
 - кампіліць frontend assets для прадакшэна (а не develop)
 - не падцягваць dev-залажнасці кампозера
 - упэўнецца што усе патрэбныя файлы уключаны ў зборку/архіў
 - упэўнецца што лішніх файлаў у зборку ня ўключана

**Comment by rizomaa** [comment]
@lptn што тут яшчэ засталося не зробленым?

**Comment by alies-dev** [comment]
@rizomaa 
ну можна сказаць зроблена, можна і палепшыць але працуе і так

Чаго няма -- дакументацыі

**Comment by rizomaa** [comment]
@lptn які трыгер для раблення рэліза зараз?

**Comment by alies-dev** [comment]
@rizomaa 
git tag, вось тут гэта зададзена: https://github.com/diglabby/doika/blob/ce45d41b7eb300fa0e22646760016497289c28ec/.travis.yml#L45

**Comment by rizomaa** [comment]
@lptn ага, дзякуй прыняў =)

**Comment by rizomaa** [comment]
@lptn тады тут усё гатова і гэту картку зачыняем. так?

**Comment by alies-dev** [comment]
Можна зачыняць, так. Але ёсць прастора для паляпшэнняў (напрыклад ставіць
толькі non-requre-dev залежнасці і падчышчаць файлы тэстаў у залежнасцях,і
перанесці стварэнне архіву на GitHub actions і інш)

**Comment by rizomaa** [comment]
@lptn насамрэч, калі гэтыя паляпшэнні набаляць можна сварыць асобнуб ішу. гэту зачыняю
