### ISSUE TITLE
Стварэнне агульнай структуры БД

### ISSUE THREAD

**Issue by svetasemashko** [diglabby/doika#17]
Спіс неабходных табліц і сувязей.

- [ ] Стварыць спіс неабходных табліц.
- [ ] Запоўніць табліцы палямі наколькі магчыма.
- [ ] Прааналізаваць мэтазгоднасць менавіта такой структуры (гэта можна ў чацвер разам зрабіць)

**Comment by falanster** [comment]
@svetasemashko калі ласка пасынай маляваць структуру базы дадзеных у рбт пачні з назваў усіх табліц..

**Comment by svetasemashko** [comment]
@fr0zen не забыць дадаць прэфікты да табліц БД doika_

**Comment by falanster** [comment]
@svetasemashko @fr0zen ёсць нейкі канспект, што абмяркоўвалі па табліцах на мінулай стустрэчы?

**Comment by falanster** [comment]
@svetasemashko ці патрэбна табе тут дапамога, бо задача стала гарачай. варта мабілізаваць высілкі 
?

**Comment by falanster** [comment]
@svetasemashko  патэнцыяна можа, але тут тоеж пытанне пащстае, 

1. ці усё у кодзе адпавядае дакументацыі? (RTB?)
2. калі не адпавядае. ці абноўлена дакументацыя?
3. ці ёсць праўкі па зменам? як яны выглядаюць і дзе?

калі ласка гэта пытанне вельмі аператыўна зрабіце. каб мы не трацілі час для сінфранізацыі наступным разам

**Comment by rizomaa** [comment]
гэту картку я выношу са спрынта, бо яе актуальнасць пакуль ніхто не бачыць @svetasemashko

**Comment by rizomaa** [comment]
@rizomaa закрываю картку з-за таго, што вельмі агульна напісана.
