### ISSUE TITLE
Дадаць канфіг docker для паляпшэння DX (developer experience)

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#171]
Дадаць канфіг docker для паляпшэння DX (developer experience)

**Comment by lptn** [comment]
@rizomaa 
гэта на гадзіну працы, буду карыстацца толькі я, пасьля паступова усіх падсажу і зробім дакументацыю (#172)

то бой мой план -- нейкі час уціхую юзаць і адпаліраваць, потым толькі несці ў свет

**Comment by pro2s** [comment]
Я может начну с #172 закину конфиг на вики, и структуру продумать надо, локально проект в докере поднялся, миграция прошла :)

**Comment by lptn** [comment]
@pro2s 
я думаю вікі ня варта выкарыстоўваць увогуле

Як правільна зазначыў Барыс, дакументацыя мусіць версіянавацца разам з кодам

а вікі -- гэта асобнае незалежнае сховішча

Калі ў цябе ужо есьць гатовы docker compose канфіг - стварай PR, я адрэвіювлю і параз палепшым яго калі будуць ідэі і заўвагі, а пасля докі замуцім

**Comment by rizomaa** [comment]
@lptn вікі будзе, бо ёсць больш, чым распрацоўка (!!!)

1. дзе будзеш збіраць пытанні карыстальнікаў і адказы на іх?
2. дзе будуць гайды па карыстанню модулямі.
3. дзе будуць розныя спецыфічныя докі, ў якіх мы яшчэ не ўпэўнены, але распрацоўшчыкам трэба іх дзесці зафіксаваць?
4. ці напрыклад гэта спецыфічныя інсталяцыі (як рабіў @cema93 на джэнкінс)?

я бы не хацеў, каб мы вынеслі гэта яшчэ на нейкія пляцоўкі, або кавыраліся у каментах ішшу

наогул наколькі ты ужо бачыш усю структуру дакументацыі зараз?

@lptn @pro2s чаму нельга нешта закінуць у вікі?

**Comment by lptn** [comment]
@rizomaa 
>@lptn вікі будзе, бо ёсць больш, чым распрацоўка (!!!)

Згодны, я тут кажу толькі пра докі для docker і то пра іх часовае месцазнахлджанне, пасля можам у wiki як стабілізуецца, пакуль жа лепей за ўсе самым простым шляхам ісці IMO

**Comment by fr0zen** [comment]
@lptn па гэтай issue вясіць пул. Калі есць заўвагі-прапановы, выкажыцеся калі ласка.

**Comment by lptn** [comment]
я так разумею ПР вось гэты https://github.com/diglabby/doika/pull/229 і ен ужо ў dev, закрываю
