### ISSUE TITLE
Ствараць  дадзеныя для першага ўваходу (разам з міграцыямі)

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#178]
На бягучы момант гэтыя дадзеныя знаходзяцца ў `doika.sql`

задача аўтаматызаваць іх разгортванне разам з міграцыямі

**Comment by lptn** [comment]
>вядзенне першасных дадзеных?

так точно, мой капітан!

**Comment by lptn** [comment]
першы сюрпрыз

```sql

INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `active`, `remember_token`, `locale`, `timezone`, `slug`, `last_access_at`, `created_at`, `updated_at`) VALUES
(1, 'Super admin', 'superadmin@example.com', '2018-10-24 16:13:17', '$2y$10$AQlsiM6XRfGZXRdu58Qo7OjVRRkZCXNekV/lst2OQUKCX59FDH/Ie', 1, 'kY7C1LGaVfYGM1ElqYKiO1nPy8kpsaWqIuQX8o6HFJANMIzP32hdnGAULRWI', 'en', 'UTC', 'super-admin', '2018-11-04 11:14:38', '2018-10-24 16:13:17', '2018-11-04 11:14:38'),
(2, 'Administrator', 'admin@example.com', '2018-10-24 16:13:17', '$2y$10$AQlsiM6XRfGZXRdu58Qo7OjVRRkZCXNekV/lst2OQUKCX59FDH/Ie', 1, 'yh7Siw8GyH2P4om2u8pmA7EMdUuqfC3zySTPK9QrfIWj8wr80tw2NgzVzWNc', 'en', 'UTC', 'administrator', '2018-11-05 14:34:43', '2018-10-24 16:13:17', '2018-11-05 14:34:43'),
(4, 'Demo', 'demo@example.com', '2018-10-24 16:13:17', '$2y$10$AQlsiM6XRfGZXRdu58Qo7OjVRRkZCXNekV/lst2OQUKCX59FDH/Ie', 1, 'P6oRtEtT9rLLCcd1YHudQMyFYUsfysWfOcDE7pPdye2rCZbvKbF3PnaUbgRP', 'en', 'UTC', 'demo', '2018-11-07 19:02:10', '2018-10-24 16:13:17', '2018-11-07 19:02:10');
COMMIT;

``` 

ведае хто навошта аж тры і што рабіць з паролямі, лакаллю?

**Comment by lptn** [comment]
@rizomaa 
@fr0zen 
так, стаяначка нумар два

Бачу што у нас ужо есьць сідэры для карыстольнікаў тут https://github.com/diglabby/doika/blob/dev/database/seeds/UsersTableSeeder.php


Аляксей можаш распавесці пра іх і нафіга нам столькі там усяго? Мо step by step будзем рухацца?

**Comment by fr0zen** [comment]
@lptn стварыў [новы пул](https://github.com/diglabby/doika/pull/194), дзе выдаліў усе залішнее.

**Comment by fr0zen** [comment]
@lptn зараз ужо змержана актуальная версія сідаў і неабходная структура, давай замержым твой брэнч, каб забраць змены гэтага [каміта](https://github.com/diglabby/doika/commit/63add4c18c8da64969d9402f3f28f724eca4f6de) і выдалім  Якія думкі на гэты конт?

**Comment by lptn** [comment]
@fr0zen 
я зараз не гатовы адказацт бо трэба праанализаваць што там змеражана. Давяраю табе ў гэтай сітацыі

**Comment by lptn** [comment]
@fr0zen 
даддзеныя есьць, закрываем іш'ю, так?

**Comment by fr0zen** [comment]
@lptn так, дзякуй, зачыняю
