### ISSUE TITLE
Не магчыма усталяваць dev composer залежнасці на PHP 7.3

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#179]
```
  Problem 1
    - Installation request for friendsofphp/php-cs-fixer v2.13.1 -> satisfiable by friendsofphp/php-cs-fixer[v2.13.1].
    - friendsofphp/php-cs-fixer v2.13.1 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.3.0) does not satisfy that requirement.

```

@fr0zen 
што скажаш наконт friendsofphp/php-cs-fixer , можам часова выдаліць?

**Comment by pro2s** [comment]
Я бы пока посоветовал воздержатся от использования 7.3, для разработки еще нет стабильного xdebug а имеющаяся бета падает при первом удобном случае :).

**Comment by lptn** [comment]
@pro2s 
распрацоўка распрацоўкаю, але на прадакшане таксама ужо могуць выкарыстоўваць 7.3, трэба  быць гатовым

**Comment by rizomaa** [comment]
@pro2s @lptn каб нічога не прыдумваць праглядзіце тут зроблена даследванне па патрабаваннях асноўных шарэхостынгаў Беларусі. па іх арыентуемся зараз. бо гэта для грамадскіх арганізацый стандарт https://trello.com/c/0Q6isDLI/

**Comment by lptn** [comment]
@pro2s 
дзякуй, але тут пытанне збольшана у тым каб ВЫДАЛІЦЬ гэты пакет бо мы яго не выкарыстоўваем пакуль што

**Comment by fr0zen** [comment]
@Tyuba4 @lptn @pro2s залежнасць выдалена

**Comment by lptn** [comment]
@fr0zen 
>залежнасць выдалена

як жа яна выдалена, у маім ПР я толькі абнавіў яе версію каю запускалася на 7.3 :)

**Comment by fr0zen** [comment]
@lptn так, дзякуй, што аднавіў пад 7.3 з dev залежнасцяў не прыбрана
