### ISSUE TITLE
Пабудаваць сувязі з працуючымі БД

### ISSUE THREAD

**Issue by svetasemashko** [diglabby/doika#18]
Падчас аднаўлення ўжо працуючай БД на існуючых праэктах захаваць старыя дадзенныя, улічваючы змены структуры БД

**Comment by falanster** [comment]
трэба удакладнне на гэту задачу або буду выдаляць у бліжэйшчы час @svetasemashko

**Comment by svetasemashko** [comment]
@fr0zen @rizomaa @falanster @cema93 калі я верна разумею, крок 1: Ствараем табліцы БД, крок 2: праглядаем і дадаем сувязі, якіх не хапае, прагаворваем дзе трэба дадаць primary/foreign keys. так ці не?

**Comment by falanster** [comment]
@Tyuba4 ты зараз гэта робиш, або мы тое ўжо скончылі?
