### ISSUE TITLE
Новыя групы (user-groups/teams) тут і у слэку

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#182]
@pro2s @lptn @Tyuba4 @fr0zen @cema93 @Olya147 @KahjuksEi @nastyafrosty @svetit @diglabby/core

тут паступіла прапанова ад @lptn стварыць групы ўдзельнікаў. Алесь можаш апісаць практычны сэнс.

наогул для ўсіх, якія групы нам зараз на ваш погляд найбольш патэрбны, каб мы пратэсцілі гэта пачынанне? і магчыма калі пакаціць больш шырока інтэгравалі.

тое самае пытанне па слэку.

**Comment by lptn** [comment]
@rizomaa 
пасля прыняцця інвайта у выпадашцы з'явіліся нашы групы:
![image](https://user-images.githubusercontent.com/5278175/51606908-41848b80-1f24-11e9-8bb2-7b4baa41dc1e.png)


Але гэта значыць што падаваны хто па-за diglabby не могуць гэтым карыстацца :(

**Comment by lptn** [comment]
болей інфы будзе сення на мітапчыку

**Comment by lptn** [comment]
@rizomaa 
групы створаны, давай даб'ем гэтае пытанне

Што на тваю думку трэба па яму яшчэ зрабіць каб пачаць нармальна выкарыстоўваць ці прызнацца ў тым што эксперымент выявіў няўдалую ідэю?

**Comment by rizomaa** [comment]
@lptn Можна паспрабаваць з двух груп:

1. Ядро каманды @diglabby/core - пытанні якія патрабуюць абмеркавання і рашэння.
2. Каманда @diglabby/qa-autotesting  - пытанни якія патрабуюць тэставання.

Ці пакуль не фарсіраваць задачу. Насамрэч зараз важна каб людзі проста сталі пісаць у гітхаб часцей і будзе бачна, якія найбольш частыя звароты ...

**Comment by lptn** [comment]
@rizomaa 
Важна каб групы і іх удзельнікі былі адныя і тыя ж тут і ў слэк

Як я бачу групы:
1. @diglabby/core
1. @diglabby/frontend 
1. @diglabby/backend 
1. @diglabby/testers
1. @diglabby/translaters 

пакуль што так, далей можна будзе развіваць і мяняць

@diglabby/qa-autotesting -- гэта ужо надта падрабязнае падзяленне, не думаю што трэба вылучаць асобную групу для аўта-тэсцераў (хаця я можа чагосці ня ведаю): Проста тое хто будзе прасіць напісаць АЎТАтэсты хутчэй за ўсе ведае КАГО ён будзе пра гэта прасіць

**Comment by rizomaa** [comment]
акей назвы можна простыя, як ты прапануеш... 

можна тады праз тыдзень, як пачнем наступны спрынт, людзям зрабіць дагонку па працы з гітхабам. каб інтэграваць пару пілотных групаў @lptn  Дзе будзе гэта апісана дарэчы?

**Comment by lptn** [comment]
>можна тады праз тыдзень, як пачнем наступны спрынт, людзям зрабіць дагонку па працы з гітхабам. каб інтэграваць пару пілотных групаў 

👍 

>Дзе будзе гэта апісана дарэчы?

Думаеш гэта трэба апісаць? Ну гэта можна і ў вікі ў README. Адзінае што яшчэ трэба зраьіць -- дадаць префікс "doika" каб не было праблем у лалейшым з ребутам і іншымі праектамі:
1. @diglabby/doika-core
1. @diglabby/doika-frontend
1. ...

**Comment by rizomaa** [comment]
Так, неяк лаканічна у вікі можна.

**Comment by Olya147** [comment]
@rizomaa @lptn Карточка ещё актуальна или можно закрывать?

**Comment by lptn** [comment]
@Olya147 
Дзякуй, не, яшчэ трэба працаваць над гэтым

**Comment by rizomaa** [comment]
абсулютна не гарачая
