### ISSUE TITLE
Стварэнне старонкі выбара сумы данэйта на кліентскай частке

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#19]
- [x] выбраць суму на кліентскай часцы
- [x] увесці суму на кліентскай часцы

**Comment by falanster** [comment]
@fr0zen гэта твая частка, або патэнцына можна даваць новым людзям?

**Comment by fr0zen** [comment]
@falanster пакуль мая, магчыма вылучу падзадачы

**Comment by nastyafrosty** [comment]
http://it3donate-landing.falanster.by/    done
