### ISSUE TITLE
Ошибка в написании в меню приложения

### ISSUE THREAD

**Issue by andrey1999999** [diglabby/doika#193]
Summary: Ошибка в написании в меню приложения.

Steps of reproduce:
1.Открыть приложение- http://it3donate-landing.falanster.by/doika/admin/campaign

![image](https://user-images.githubusercontent.com/30193031/51753578-27d17880-20cb-11e9-96cb-9855729d0dfb.png)

Environment:
Google Chrome

- Версія Doika: 
- Платформа і версія: Windows10
- Браўзер і версія: Chrome

**Comment by fr0zen** [comment]
@andrey1999999 так, дзякуй, што заўважыў, фіксанем.

**Comment by lptn** [comment]
@fr0zen 
@andrey1999999 
Я дарэчы версіі дойкі ня бачу ні ў issue ні на скрыншоце. Наколькі складана дадведацца пра версію? Як на конт таго каб дадаць яе на бачнае месца (напрыклад у footer)?

**Comment by nastyafrosty** [comment]
@Olya147 сейчас есть ошибки в словах?

**Comment by ghost** [comment]
Сейчас модуль поддерживает только белорусскую версию. Карточка не актуальна. 
Закрываю.
