### ISSUE TITLE
Дадаць версію Дойка у футэр

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#196]
Зараз не бачна, якая версія выкарыстоўваецца, трэба дадаць версію у футэр адмінкі.

**Comment by rizomaa** [comment]
@fr0zen 

1. ці можна гэта неяк аўтаматызаваць, або будзем ручкамі?
2. памятаеш дзе мы запісвалі правілы версіравання?

**Comment by fr0zen** [comment]
@rizomaa 
1. змяняць прыйдзецца ручкамі ў любым выпадку. у @lptn была цікавая ідэя выкарыстоўваць пад гэту справу тэгі гіта.
2. не памятаю, трэба удакладняць

**Comment by rizomaa** [comment]
Вось арыгінальны файл https://trello.com/c/X32NkJzB/

X.Y.Z

1. першая лічба мажорнае абнаўленне (архітэктруныя змены)
2. другая лічба - ітэрацыя (набор фічаў)
3. трэцяя лічба - рэліз пасля спрынта (фіча)
4. чацвёртая лічба абазначае праўкі багаў

Напрыклад, 1.3.1, 1.2.3, 2.0.1.23

@Tyuba4 @lptn @KahjuksEi @fr0zen @maxmatoha 
калі ласка азнаёмцеся.

**Comment by rizomaa** [comment]
@lptn нагадай кали ласка, дзе ў нас было абмеркаванне разгорвання або апісаны працэс... нешта не знаходжу

**Comment by KahjuksEi** [comment]
@rizomaa Карточка не найдена. По ходу доступ не всех есть.

**Comment by rizomaa** [comment]
@KahjuksEi спрабуй зараз

**Comment by lptn** [comment]
@rizomaa 
>@lptn нагадай калі ласка, дзе ў нас было абмеркаванне разгорвання або апісаны працэс... нешта не знаходжу

[semver 2.0](https://semver.org/) маеш на ўвазе? Не памятаю, думаю мы гэта не апісвалі

**Comment by rizomaa** [comment]
> @rizomaa
> 
> > @lptn нагадай калі ласка, дзе ў нас было абмеркаванне разгорвання або апісаны працэс... нешта не знаходжу
> 
> [semver 2.0](https://semver.org/) маеш на ўвазе? Не памятаю, думаю мы гэта не апісвалі

тут мы адвалімся на колькасці літар. можаш напісаць ці ёсць заўвагі да вышэй прапанавай разметкі? лаканічна)

**Comment by lptn** [comment]
@rizomaa 
так. заўсега есьць. майлстоўны ў нумеры версіі не пабрэбныя, майлстоўн !== рэліз, гэта нас будзе абмяжоўваць і прыгнятаць

**Comment by rizomaa** [comment]
@lptn як глядзіш на візуалізацыю версіі у адмінцы модуля?

**Comment by alies-dev** [comment]
@rizomaa 
Станоўча :)
Я дадаў мінммальны код, цяпер версія дойкі даступна праз `window.appVersion` на франце, а каб  зняніць яе трэба змяніць значэнне `APP_VERSION` у `.env` (і `.env.example` ПЕРАД кожным рэлізам).

@fr0zen 
Леха, твой ход!

**Comment by rizomaa** [comment]
@lptn праверыў window.appVersion там пуста. Магчыма шлях да версіі іншы. Удакладні

**Comment by alies-dev** [comment]
Я думаю па такое дробязі дзёгаць ня варта. Мае каміты тут прычэплены да іш'ю калі трэба паўтарыць (гучыць шматзначна асабліва 9га траўня). Я лепей чым сер'езным дапамогу :Р

**Comment by rizomaa** [comment]
@lptn тут была заяўлена працуючая пераменная, яна не працуе. На мой погляд гэта варта пазначыць. Асабліва, каб разумець не толькі рухавік, але і дэталі. Пра прыярытэт задач мы ўжо гутарылі ;)

зы
наогул лічу зараз патрэбным зачыняць задачы, якія не асабліва важныя для асноўнага функцыяналу.

**Comment by andrei-roh** [comment]
Хочу сделать эту задачу, подскажите, пожалуйста, правильно ли я понял: 
- необходимо взять страницу http://localhost/doika/doika/dashboard/campaigns и добавить в тег <footer> div, в котором отобразится версия Дойки, взятая, например из файла .env?
- брать конкретно страницу campaigns?
- брать именно файл .env либо другой?

**Comment by alies-dev** [comment]
@rizomaa 
>наогул лічу зараз патрэбным зачыняць задачы, якія не асабліва важныя для асноўнага функцыяналу.

Мне ідэя падабаецца! Я проста за тое што калі мне прымаць удзел на праекце, то на болей важных і складаных задачах, чым гэтая

**Comment by rizomaa** [comment]
@andrei-roh 
1.1. Кожная старонка складаецца з кампанентаў. Ёсць кампаненты, якія паказваюць верхнюю ніжнюю частку для ўсіх старонак, ёсць якія размяшчаюцца пасярэддзіня, як правіла, яны адказваюцць за асноўную функцыю старонак. Таму тут хутчэй трэба знайсці патрэбны кампанент. Які падхгружаецца для адлюстравання футара.
1.2. "например из файла .env?" Магчыма і так.
2. Павінна адлюстроўвацца не толькі на старонцы кампаній, а на ўсіх. Часткова адказ у пункце  1.1.
3. Паспрабуцей з .env папрацаваць. Самае цікавае як вы арганизуеце узаемадзеянне визуальнай частки з файлавай сістэмай сэрвера)

**Comment by alies-dev** [comment]
@rizomaa 
@andrei-roh 
адносна таго што было зроблена: я пракінуў версію з бэкэнда на фронтэнд, выкарыстаўшы падыход які ужо быў: https://github.com/diglabby/doika/blob/ce45d41b7eb300fa0e22646760016497289c28ec/resources/views/dashboard/layouts/app.blade.php#L14-L24

як выцягвалі (і ці выцягвалі ўвогуле) гэтыя дадзеныя на візуальны слой - я не правяраў (гэта задача была па-за межамі майго скоўпа [як бэкэндзера]).

**Comment by alies-dev** [comment]
задача вельмі простая. у залежнасці ад таго дзе нам трэба гэта версія (у Vue app ці ў шаблоне старонкі) вырашаецца па-рознаму.

**Comment by rizomaa** [comment]
@lptn слушна. тут пакінуў табе пытанні па развіццю архітэктуры рашэння. Чакаю тваіх каментароўю
https://github.com/diglabby/doika/issues/692#issuecomment-629835280

**Comment by andrei-roh** [comment]
@rizomaa есть пару вопросов: 
- шаблон страницы есть в .html или .php.? Как его отыскать?
- чем работать с .vue ?

**Comment by rizomaa** [comment]
@andrei-roh прывітанне,

1. шаблоны ляжаць у тэчцы resources/js ...
2. так, vue - гэта ключавое слова на франце праекта doika

**Comment by andrei-roh** [comment]
Добрый вечер. Я нашел файл для footer, сверстанный с помощью фреймворка vue.js, но когда я вношу изменения в файл, то в модуле ничего не меняется. Я так понимаю, что надо пересобрать модуль, как это сделать? В какой среде разработки работает фронтэнд?

**Comment by rizomaa** [comment]
@andrei-roh 
1. так, пасля кожнай змены вам варта рабіць перазборку франта, я карыстаюся `npm run watch` вельмі зручна.
2. Гэта пытанне удакладніце "В какой среде разработки работает фронтэнд?"

**Comment by andrei-roh** [comment]
@rizomaa Добрый вечер! Я разыскал footer, пробовал редактировать. Возникли вопросы по самому заданию:
- я решил считать в файле .env часть строки с версией и написал небольшой php скрипт, но не могу понять, как можно передать из php файла переменную в .vue или .js

**Comment by rizomaa** [comment]
@andrei-roh ці спрабавалі рухацца ў бок які падказаў @lptn  https://github.com/diglabby/doika/issues/196#issuecomment-630751357

**Comment by rizomaa** [comment]
Вось яшчэ спасылка трапілася, падумалася, што цікавая.
https://alligator.io/vuejs/file-reader-component/

**Comment by alies-dev** [comment]
Не, ня трэба быць файлы на франце, неабходныя дадзеныя мусяць пракідывацца
праз blade в'юхі (што зараз і робіцца) і мусяць быць зашыты ў лэйаўт (як
json ці як js)

**Comment by rizomaa** [comment]
@lptn дзякуй, уцяміў =)

@andrei-roh можа табе будзе цікава
калі заходзіш на старонку /doika/doika/dashboard/login
і глядзіш яе сорсы. Убачыш такі кавалак:
```
<script type="application/json" data-settings-selector="settings-json">
--
  | {"locale":"be","appName":"Doika","appVersion":"2.0","homePath":"http:\/\/doika2\/doika\/doika\/dashboard","locales":"en","user":null}
  | </script>
```

1. Трэба гэты джэйсан забраць, распарсіць 
2. і узяць частку "appVersion":"2.0" ... 
3. і пасля яе прыгожа вывесці на старонцы

так больш відавочна?

**Comment by rizomaa** [comment]
@andrei-roh 
бачу такі алгарытм.
1. Трэба выняць з html аб'ект json
2. Распарсіць яго. Можа тут класічны спосаб https://www.w3schools.com/Js/js_json_parse.asp
3. Далей зрабіць рэактыўную пераменную у кампаненце футэра. секцыя script файла кампаненты  футэра
4. Далучыць гэту пераменную да месца дзе неабходна адлюстрощваць у секцыи template файла футэра

Для мяне паколь не відавочна як выняць гэты джэйсон са старонкі, але думаю гэта задачы вырашальная з дапамогай гуглай. Плёну!

**Comment by andrei-roh** [comment]
@rizomaa ![Аннотация 2020-05-25 125646](https://user-images.githubusercontent.com/65450338/82806147-dd623680-9e8d-11ea-8ccb-642fcb959cc0.jpg)
Вроде вышло. По итогу чуть-чуть поменял только файл footer'a. 
Вопрос по верстке: какой должен быть размер и расположение текста? Кроме того, я так понимаю, что текст должен быть на 3 языках?

**Comment by rizomaa** [comment]
@andrei-roh пакуль усё акей па вёрстцы, 
калі ласка далучай пулрэквэст у dev галіну. цікава паглядзець, што атрымалася накодзіць=)
