### ISSUE TITLE
Наладзіць адпраўку паведамленняў карыстальніку і распрацоўшчыкам

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#198]
Сама юзэр сторы ёсць https://trello.com/c/iMyZ81Hm/

Трэба стварыць клас і табліцы, якія будуць рабіць перасылкі і пратэставаць:
1. па крону (
1.1. перад/пасля рэукрэнднага працяжу (для пачатку можна нейкай падзеі), 
1.2. або першага плацяжу (калі карыстальнік увёў мэйл)
2. з адмінкі модуля (адправіць фідбэк карыстальніку)

Заўвагі прапановы:
1. Для пачатку тэксты вітальнага, папераджанага і удзячнага мэйла можна пакуль у асобным файле складаць, пасля перанясем у табліцу.
2. ёсць яшчэ дадатковая задача па хэшу для спасылкі для адпіскі #49 , але мы да яе можам вярнуцца пасля запуска мэйлінга.

@Tyuba4 што ў цябе з базай карыстальнікаў ці ёсць

зы 
пытанне: ці у нас адна табліца для карыстальінкаў з разавымі плацяжамі і рэкурэнтнымі? @Tyuba4 @lptn @fr0zen

**Comment by rizomaa** [comment]
@Hellsingi гэта картка на даследванне. Дэдлайн навыкананне - субота, 2.2.2019

**Comment by Hellsingi** [comment]
Вось што я знайшоў на гэту тэму:
https://laravel.com/docs/5.7/mail#driver-prerequisites
https://github.com/Snowfire/Beautymail
https://github.com/mlanin/laravel-email-templates-optimization
https://github.com/dena-a/laravel-elastic-email

І апісанні спосабаў настройкі:
https://scotch.io/tutorials/ultimate-guide-on-sending-email-in-laravel
https://code.tutsplus.com/ru/tutorials/how-to-send-emails-in-laravel--cms-30046

**Comment by rizomaa** [comment]
@Hellsingi дзякуй. тырымай далей сувязь з @Tyuba4 

@Tyuba4 скажы калі ласка, у які бок далей варта рыць?

**Comment by Tyuba4** [comment]
@Hellsingi Привет, спасибо. Сегодня завтра, буду просматривать. @lptn может у тебя какие мысли есть по данному поводу?

**Comment by lptn** [comment]
@Tyuba4 
У Laravel есьць [фасад `Mail`](https://laravel.com/docs/master/mail) і некалькі яго імплементацый, гэтага мусіць хапіць (калі не хочаце нейкай экзотыкі)

**Comment by rizomaa** [comment]
@Hellsingi праз што працуе гэты клас? праз функцыю mail або smtp?

**Comment by lptn** [comment]
>@Hellsingi праз што працуе гэты клас? праз функцыю mail або smtp?

`Mail` гэта абстракцыя якая мае некалькі рэалізацый, якія можна легка мяняць праз канфіг

Есьць і рэалізацыя якая працуе наўпрост з smtp

**Comment by Tyuba4** [comment]
@lptn @rizomaa  @Hellsingi @fr0zen Еще можно использовать систему Notifications, мне кажется больше подходит для нас. https://laravel.com/docs/5.3/notifications https://laravel.ru/docs/v5/notifications

**Comment by lptn** [comment]
@rizomaa 
Спадарства, спачатку трэба разумець ШТО мы хочам а пасля ЯК гэта рэалізаваць

Якія патрабаванні да імэйлаў? Будуць гэта толькі імэйлы ці яшчэ СМС і тэлеграмы слэкі і інгыя чэрці?

**Comment by rizomaa** [comment]
@lptn 

Функцыя мэйлаў патрэбна:
1. Боту для адсылкі паведамленняў ахвярадаўцам (перад ахвяраваннем і пасля), вітальнага мэйла.
2. Для адсылкі мэйлаў фідбэкаў ад карыстальнікаў стваральнікам (праз адмінку)

іншы функцыянал зараз непатрэбны.

**Comment by lptn** [comment]
@rizomaa 
убудаваных функцый Laravel болей чым дастаткова для усяго гэтага

**Comment by rizomaa** [comment]
@Tyuba4 тады тут спняем абмеркаванне і пераходзім да рэалізацыі?

@lptn можаш накідаць класы у якіх гэтыя функцыі ляжаць?

я пераношу патрэбы адсылкі у чэк ліст

**Comment by lptn** [comment]
@rizomaa 
я вось стварыў ПР https://github.com/diglabby/doika/pull/220

Дасылаць імэйл лепей за ўсе па крону (cron), так што трэба будзе каб адміны наладзілі не толькі mail driver (smtp, amazon, etc) але і крон

Есьць болей карстыльныя і яшчэ болей складаныя альтэрнатывы, не думаю што іх варта у сур'ез разглядаць

**Comment by rizomaa** [comment]
ёсць картка #222

**Comment by lptn** [comment]
@rizomaa 
добра, зачымняем гэты іш'ю?

**Comment by rizomaa** [comment]
> @rizomaa
> добра, зачымняем гэты іш'ю?

магчыма лепей пераіменаваць "Наладзіць адпраўку паведамленняў..." і працягнуць рэалізацыю

**Comment by lptn** [comment]
ок, прызначай "счасліўчыка" :)

**Comment by rizomaa** [comment]
Заўвагі прапановы:
1. Для пачатку тэксты вітальнага, папераджанага і удзячнага мэйла можна пакуль у асобным файле складаць, пасля перанясем у табліцу.
2. ёсць яшчэ дадатковая задача па хэшу для спасылкі для адпіскі #49 , але мы да яе можам вярнуцца пасля запуска мэйлінга.

@Tyuba4 што ў цябе з базай карыстальнікаў ці ёсць?

зы 
пытанне: ці у нас адна табліца для карыстальінкаў з разавымі плацяжамі і рэкурэнтнымі? @Tyuba4 @lptn @fr0zen

**Comment by lptn** [comment]
@rizomaa 
>пытанне: ці у нас адна табліца для карыстальінкаў з разавымі плацяжамі і рэкурэнтнымі? 

для аднаразовых данэйцераў праблема ў тым што мы не пытаем email і іншай унікальный інфармацыі па якой мы можам іх ідэнтыфікаваць, нават па-харошаму не змадам группіраваць данэйты без такой інфы (можна праз дадзеныя карткі даступныя нам ці па айдзішкам якія будзем генерыць на франце (але яны будуць для усіх дэвайсаў рознымі) ці па ішныя ускосным і недакладным прыкметам)
