### ISSUE TITLE
Фронтэнд. Пераключэнне плацёжных сістэмаў ў канфігурацыі модуля. Запоўніць табу

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#199]
Зрабіць працуючы таб  з назвай "Artpay"

- [ ] 1. Скапіраваць элементы з існуючай тады, якая адчыяецца па змоўчанню.
- [ ] 2. І уставіць ў табу "Artpay"

**Comment by maxmatoha** [comment]
https://probusiness.io/sales/5045-kak-podklyuchit-priem-onlayn-platezhey-prostoy-chek-list.html
Возможно полезная информация

**Comment by rizomaa** [comment]
@maxmatoha дзякуй, калі інфа не тычыцца канрэтна карткі, лепей закідвай у канала слэку

**Comment by rizomaa** [comment]
@Olya147 гэта задача рэалізавана @maxmatoha ?
пракаментуй

**Comment by Olya147** [comment]
@rizomaa @maxmatoha Вкладка Artpay создана. 
Есть похожая [#75](https://github.com/diglabby/doika/issues/75) и связанная [#8](https://github.com/diglabby/doika/issues/8) незакрытые задачи.
![Artpay](https://user-images.githubusercontent.com/46268205/56862793-696a0c00-69b7-11e9-91e3-a5d7fdbb2714.png)

**Comment by rizomaa** [comment]
ага, дзякуй. @Olya147
