### ISSUE TITLE
Адмінка. Фронтэнд. Стварэнне старонкі са спісам кампаній

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#20]

**Comment by falanster** [comment]
@fr0zen гэта твая задача, або пакуль сваобная?

**Comment by falanster** [comment]
@nastyafrosty далучы кали ласка схему сюды

**Comment by fr0zen** [comment]
@falanster дакладна мая

**Comment by nastyafrosty** [comment]
![image](https://user-images.githubusercontent.com/41231823/49960050-47984d00-ff20-11e8-8332-4585616e8ad9.png)
1)tumbler which turns on and turns off the campaign. in prototypes it was just mention of the status. is it important to make this feature now?
2) backers...in prototypes there are backers and subscribers

**Comment by KahjuksEi** [comment]
Коммент для получения задачи по фронтенду. Задача по тестированию. @fr0zen
