### ISSUE TITLE
Фронтэнд. На усіх старонках MODULE CONFIGURATION зрабіць каб табы былі адчынены па змоўчанню

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#201]
Напрыклад, тут трэба, каб таб быў адчынены 
http://it3donate-landing.falanster.by/doika/en/admin/notifications

**Comment by rizomaa** [comment]
@maxmatoha так, магчымасць згортвацца павінна захавацца. 

@nastyafrosty тваё меркаванне?

**Comment by nastyafrosty** [comment]
@rizomaa а еслі все подпункты конфігураціі ітак разделены, зачем скрывать содержімое? в плане, нет мешаніны

**Comment by fr0zen** [comment]
@rizomaa @nastyafrosty класная заўвага вышэй, мне таксама падаецца, што згортванне зараз мае мала сэнсу і з'яўляецца залішней.

**Comment by rizomaa** [comment]
@maxmatoha тады заблакуй закрыццё зараз
