### ISSUE TITLE
Абмеркаваць інтэграцыю аўтатэставання

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#204]
Якія прыйшлі думкі зараз:

- [ ] Запаўненне сумаў
- [x] Лагін. разлагін
- [x] Стварэнне кампаніі
- [x] Рэдагаванне кампаніі
- [x] Выдаленне кампаніі
- [ ] Наладка знешняга выгляду кліентскай часткі.
- [ ] Наладка плацёжнага шлюза.
- [ ] Усталёўка (калі будзе усталёўшчык)

@lptn @pro2s @Tyuba4 @fr0zen цікавы вашыя думкі на гэты конт?

1. якую прыладу можна для гэтага выкрастаць.
2. якія пазіцыя тэставання можна дадаць
3. можа ужо мелі досвед ці бачылі як працуе аўтатэставанне?

**Comment by lptn** [comment]
@rizomaa 
>якую прыладу можна для гэтага выкрастаць.

phpunit для unit і feature тэстаў

Laravel Dusk для браўзерных тэстаў


>якія пазіцыя тэставання можна дадаць

не зразумеў пытання

>можа ужо мелі досвед ці бачылі як працуе аўтатэставанне?

так, вядома

**Comment by rizomaa** [comment]
@lptn 

у спісе вышэй пералічыў сітуацыі дзе на мой погляд можна пратэставаць аўтаматычна. можа што дадаш?

"якія пазіцыі тэставання можна дадаць

не зразумеў пытання"

**Comment by lptn** [comment]
Калі я правільна зразумеў то іш'ю гэтая задае нам некалькі пытанняў:
 1. Што будзем тэсціць
 2. Чым будзем тэсціць (тулзы)
 3. Як гэта тэнсцінг інтэгруем у CI

На дадзены момант я на першае пытанне адказаць не магу, на другое ужо адказаў, на треццяе пакуль рана адказваць (калі каротка -- можна і на джэнкінс і ў аблоках але з Laravel Dusk  і там і там могуць быць праблемы (вырашальныя))

**Comment by rizomaa** [comment]
@lptn тут першы спис што будзем тэсціць

https://github.com/diglabby/doika/issues/204#issue-406076222

**Comment by lptn** [comment]
@rizomaa 
крута, значыць маем адказы амаль на ўсе пытанні

**Comment by Olya147** [comment]
@lptn Могу закрывать?

**Comment by lptn** [comment]
>@lptn Могу закрывать?

так, але варта стварыць падзадачы для нерэализаваных аўта-тэстаў (не чэкнутыя чэкбоксы), я зраблю
