### ISSUE TITLE
Дакументацыя. Дадаць гайд па усталёцы на win-сістэмы у файл readme.md

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#208]
@Olya147 прывітанне,

Трымай задачу. 

Усё дадаць сюды.
https://github.com/diglabby/doika/blob/dev/README.md

Трэба прымяніць і адаптаваць гайд лінукс з патрэба для лінукс.

Забываем пра doika.sql карыстаемся толькі міграцыямі, кампозераі і нпээмамі.

Камунікуй з @maxmatoha @KahjuksEi @ursar @Hellsingi

**Comment by ursar** [comment]
@rizomaa предлагаю, если Оля не против, переасайнить issue на меня.

**Comment by rizomaa** [comment]
@ursar канешне бяры. 
разам з @Olya147  пратэсціце гэты гайд. каб яна паставіла па яму. гэта будзе паказчык якасці гайда.

**Comment by ursar** [comment]
@Olya147 протестируй  установка doika на Open Server по этому гайду

1. Адкрыць налады Open Server(min PREMIUM edition), укладка дамены, ручное кіраванне, напісаць імя дамена, на прыклад doika, папка дамена выбраць localhost
2. Адкрыць укладку сервер, налады выкарыстання зменнай Path выбраць `Свой Path + Win Path`, паставіць каўку ў чэк-боксе `запускаць сервер ў агрэсіўным рэжыме`
3. Адкрыць ўкладку модулі, выбраць Apache 7.2, php 7.2, mySQL 5.7, захоўваем, запускаем сервер
4. Заходзім у рэпазіторый https://github.com/diglabby/doika.git і націскаем clone or download і капіруем адрас
5. Запускаем кансоль git из Open Server (мае закладкі - Git-CMD). З кансолі заходзім у тэчку localhost (напрыклад, cd d:\OSPanel\domains\localhost {шлях да тэчцы localhost}) і клоніруем туды праект пры дапамозе git clone  (git clone https://github.com/diglabby/doika.git)
6. Заходзім з кансолі ў тэчку doika (каманда cd doika) і пры дапамозе гіт пераключаемся на dev branch (git checkout dev)
7. З тэрмінала запусціць каманду `composer install`. Вы павінны запусціць з карнявой дырэкторыі doika
8. З тэрмінала запусціць каманду `npm install`. Вы павінны запусціць з карнявой дырэкторыі doika
9. Выконваем зборку фронтэнда `npm run build`. Вы павінны запусціць з карнявой дырэкторыі doika
10. Рыхтуем пустую Mysql базу. Адкрываем PhpMyAdmin (127.0.0.1/openserver/phpmyadmin/index.php), ствараем новую БД.
11. Рыхтуем канфіг файл. Для гэтага ў тэчцы doika ствараем копію файла .env.example і надаем яму імя .env
12. Дадаем у файл .env свае дадзеныя, для падключэння к базе, створанай на папярэднім кроку DB_DATABASE={назва_базы} DB_USERNAME=root(калі не мянялі) DB_PASSWORD=(пуста калі не устонаўлівалі пароль)
13. Разгортваем базу дадзеных камандай `php artisan migrate`. Вы павінны запусціць з карнявой дырэкторыі doika
14. Пасля дадаем зыходныя дадзеныя камандай `php artisan db:seed`. Вы павінны запусціць з карнявой дырэкторыі doika
15. Генерым ключ для laravel камандай `php artisan key:generate`. Вы павінны запусціць з карнявой дырэкторыі doika
16. Усталяваная версія павінна запускацца на Вашым лакальным хасце са шляхам http://doika/doika/be/admin/login
17. Выкарыстоўваеце дадзеныя для ўвахода Лагін: demo@example.com , Пароль: demo

**Comment by rizomaa** [comment]
@ursar дадавай інфу адразу у readme.md праз пулрэквэст

**Comment by Olya147** [comment]
@rizomaa @ursar Всё получилось!

**Comment by rizomaa** [comment]
@Olya147 @ursar а дзе пулрэквэст?

**Comment by ursar** [comment]
@rizomaa  
Pull Request https://github.com/diglabby/doika/pull/219

**Comment by rizomaa** [comment]
@ursar @Olya147 падштурхніце аснову, каб яны праглязелі вашы праўкі=)

**Comment by fr0zen** [comment]
@rizomaa @ursar @Olya147 бачыў змены, сення абкатаю гэты гайд

**Comment by Olya147** [comment]
@ursar Нам обязательно нужно работать с премиум версией Openserver или можно использовать базовую?

**Comment by KahjuksEi** [comment]
Пункт 1 - предлагаю обобщенно писать, просто open server
Пункт 2 - ??? не приходилось с этим сталкиваться, возможно какое то индивидуальное решение

**Comment by ursar** [comment]
> 
> 
> @ursar Нам обязательно нужно работать с премиум версией Openserver или можно использовать базовую?

@Olya147 можно, но придется git отдельно ставить

**Comment by ursar** [comment]
> 
> 
> Пункт 1 - предлагаю обобщенно писать, просто open server
> Пункт 2 - ??? не приходилось с этим сталкиваться, возможно какое то индивидуальное решение

Агрессивный режим нужен чтобы освобовить необходимые для работы порты(например 80), он иногда бывает занят сторонними приложениями. Если не изменить Path на `Свой Path + Win Path`
консоль Open Server не видит npm.

**Comment by KahjuksEi** [comment]
![qip shot - screen 707](https://user-images.githubusercontent.com/39082880/52727967-6a4ded00-2fc7-11e9-8c02-17f4c08a3e9f.png)
у меня работает без win path просто
