### ISSUE TITLE
Адмінка. Напаўненне старонкі канфігурацыі знешняга выгляду модуля

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#21]
Зрабіць па прыкладу ітэрацыі 1.2. перанесці ўсе кампаненнты.

Старонка на версіі 1.3.
http://it3donate-landing.falanster.by/doika/en/admin/layout#

**Comment by KahjuksEi** [comment]
@fr0zen @rizomaa здесь надо собрать такой функционал?
![qip shot - screen 703](https://user-images.githubusercontent.com/39082880/52319342-30368700-29da-11e9-838f-4a2cb46b5633.png)

**Comment by fr0zen** [comment]
@KahjuksEi с кропкі гледжання функцыяналу - так

**Comment by nastyafrosty** [comment]
@fr0zen эта задача в какой спринт входит?  будет ли таким образом (внешний вид) сделана эта страничка? или необходимо или можно сделать изменения?

**Comment by rizomaa** [comment]
@nastyafrosty гэта не уваходзіць у спрынт. таму як будзе час напішы, каб @KahjuksEi разаграваўся

**Comment by fr0zen** [comment]
@nastyafrosty будет на третьем спринте, если есть какие-то мысли, как можно освежить дизайн, было бы круто

**Comment by rizomaa** [comment]
@nastyafrosty як тут ідзе?

@fr0zen ці яшчэ актуальна?

**Comment by nastyafrosty** [comment]
@rizomaa @fr0zen залача на следующий спринт?

**Comment by rizomaa** [comment]
@rizomaa глядзі гэта з большага рэфактарынг. ён патрэбну у гэтай ітэрацыі.

можа проста паажы @fr0zen , як яно павінна выглядаць зараз.

**Comment by fr0zen** [comment]
@nastyafrosty так, на наступны, я зараз магу зрабіць як сам гэта разумею, але над UX трэба будзе падумаць

**Comment by fr0zen** [comment]
Дададзены наладкі колераў. Дубляваны функцыянал версіі 1.2. Развіваць функцыянал будзем больш мелкімі issue.
