### ISSUE TITLE
Абнавіць FAQ вікі новымі пытаннямі

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#213]
- [ ] 1. Узяць пытанні з трэла карткі https://trello.com/c/6zwNPGPD/
- [ ] 2. Праверыць, якія новыя ў параўнанні з тымі, што існуюць на старонцы FAQ https://github.com/diglabby/doika/wiki/FAQ
- [ ] 3. Дадаць спіс новых пытанняў са зручнай для чытання грамадскімі арганізацыямі фармулёўкай сюды у канцоўку https://github.com/diglabby/doika/wiki/FAQ
- [ ] 4. Абмеркаваць кожнае новае  пытанне з камандай падчас сустрэч у рэале або чатам тут ці слэку.
- [ ] 5. Запісаць адказы на пытанні.
- [ ] 6. Даць на вычутку 2-3 чэлам з каманды

**Comment by Olya147** [comment]
ниже приведена ссылка на задаваемые общественными организациями вопросы
https://docs.google.com/spreadsheets/d/1q9kL0pnd4nk_toIkBuLph7kNZ9srLingKPLtRn8D-Ps/edit?usp=sharing

**Comment by Olya147** [comment]
Сбрасываю всем ссылку на лист с ответами к новым FAQ.  Пожалуйста, ознакомьтесь. Если окажется, что вы с чем-то не согласны или "тема нераскрыта", оставляйте свои пожелания и комментарии в документе::  https://docs.google.com/document/d/17RwZLe8UxTLjX_Q7EjE6l4iUUBbpsvD0ILodfmli3yA/edit?usp=sharing
