### ISSUE TITLE
Пачысціць README.md

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#216]
## Мэты

1. зрабіць статус праекта празрыстым (зараз -- "арытыўная распрацоўка")
2. перанесці інфу пра усталеўку модуля у асобныя дакументы (wiki) -- так прасцей кідаць спасылку і падртымліваць докі
3. Фокус на галоўным на дадзеным этапе (распрацоўка, пошук распрацоўшыкаў)
4. Прыбраць візуальны шум (вялікі даўгі док ніхтоне хоча чытаць)
5. Зрабіць візуальна прывабным для распрацоўшчыкаў
6. Зрабіць ясным як гэта праце для патэнцыйнх карыстальнікаў

## Матэрыялы
https://m.dotdev.co/how-to-write-a-readme-that-rocks-bc29f279611a

**Comment by rizomaa** [comment]
@lptn задача не дэтализавана зачыняю... не бачна, што павінна быць як вынікам.

**Comment by lptn** [comment]
@rizomaa 
У ПР да гэтай задачы усе добра распісана, я толькі што перенес і дапоўніў інфу адтуль, пера-адкрываю задачу

**Comment by rizomaa** [comment]
@lptn зараз зроблена? 

наогул яе назва патрэбна каб была больш дакладная інакш чыстакаміможна бясконца займацца

**Comment by alies-dev** [comment]
гатова!

**Comment by fr0zen** [comment]
@lptn 👍
