### ISSUE TITLE
Бэкэнд. Стварыць функцыю генерацыі старонкі для адпіскі (неабходна мэйлінгу ў выпадку рэкурэнтных плацяжоў)

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#217]
- [ ] 1. База крыстальнікаў ад @Tyuba4 ... 
- [ ] 2. Алгартым хэшаў.
- [ ] 3. Захаванне тэксты мэйлаў

**Comment by rizomaa** [comment]
@pro2s паглядзі гэту картку. можам абмеркаваць

**Comment by pro2s** [comment]
@rizomaa надо подробности, карточка в трело или user story.

**Comment by rizomaa** [comment]
@pro2s сама юзэр сторы ёсць https://trello.com/c/iMyZ81Hm/

Вось тут сумежныя issues пагартай: #198 #222 

Трэба стварыць клас і табліцы, якія будуць рабіць перасылкі і пратэставаць:
1. па крону (
1.1. перад/пасля рэукрэнднага працяжу (для пачатку можна нейкай падзеі), 
1.2. або першага плацяжу (калі карыстальнік увёў мэйл)
2. з адмінкі модуля (адправіць фідбэк карыстальніку)

Заўвагі прапановы:
1. Для пачатку тэксты вітальнага, папераджанага і удзячнага мэйла можна пакуль у асобным файле складаць, пасля перанясем у табліцу.
2. ёсць яшчэ дадатковая задача па хэшу для спасылкі для адпіскі #49 , але мы да яе можам вярнуцца пасля запуска мэйлінга.

@Tyuba4 што ў цябе з базай карыстальнікаў ці ёсць

зы 
пытанне: ці у нас адна табліца для карыстальінкаў з разавымі плацяжамі і рэкурэнтнымі? @Tyuba4 @lptn @fr0zen

**Comment by Tyuba4** [comment]
@rizomaa @pro2s Необходимо создать миграции для таблиц donators и transactions, и ORM-модели, которые будут работать с этими таблицами. Над полями полями этих таблиц я подумаю и напишу завтра.

**Comment by rizomaa** [comment]
@Tyuba4 адкуль нам брац саму структуру табліц?

**Comment by Tyuba4** [comment]
@rizomaa Я тут напишу.

**Comment by rizomaa** [comment]
@lptn ци у нас ёсць бэк энд гэтай фічы?

**Comment by alies-dev** [comment]
@rizomaa 
ну глядзі, вось якія імэйлы рэалізаваны пакуль што: https://github.com/diglabby/doika/tree/develop/app/Mail

гэта усе што есьць

**Comment by rizomaa** [comment]
Дзякуй
У нас ёсць нейкі прыклад як генеруецца спасылка для адпіскі? @lptn

**Comment by alies-dev** [comment]
@rizomaa 
так, вось https://github.com/diglabby/doika/blob/865db113041fff4623de0418323a46db9db45a59/resources/views/emails/subscriptions/charge--failed.blade.php#L21

```php
$subscription->getCancelationUrl()
```
