### ISSUE TITLE
Стварыць старонку пацверджання адпіскі і яе апрацоўшчык

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#218]
1. Рэалізаваць бэкэнд - #217 
1.1. Функцыя генерацыі хэша.
1.2. Апрацоўшчык адпіскі (па урлу ці па клавішы)
2. Рэалізаваць старонку з надпісам (мінімалістычны фронт - магчыма пашырэнне да #541)

**Comment by lptn** [comment]
@rizomaa 
пацверджання чаго?

**Comment by rizomaa** [comment]
@lptn адпіскі

дзякуй за заўвагу
