### ISSUE TITLE
Рэалізаваць аб'екты Базы дадзенных для перанясенных таблiц з версii 1.2 праз PHP (стварыць міграцыі)

### ISSUE THREAD

**Issue by svetasemashko** [diglabby/doika#22]

**Comment by falanster** [comment]
@Tyuba4 на мой погляд ёсць дубляванне з #7 

Якую картку пакидаем якую выдяляем?

**Comment by Tyuba4** [comment]
@falanster Задачи похожи, но все же они разные. В одной надо сделать миграции (файлы которые создают таблицы), а в другой задачи нужно создать php классы (модели), которые уже будут управлять этими созданными таблицами.

**Comment by falanster** [comment]
@Tyuba4 Тады скарэктуй назвы, бо і там і там ёсць слова міграцыі, гэта трохі заблытвае, ці зрабі больш дакладнае апісанне.

Такое пытанне вынікае:
Аб'екты будуць кіраваць міграцыямі. ці наогул працай з БД?

**Comment by rizomaa** [comment]
@Tyuba4 тут таксама не ведаю, што тэсціць трэба... апішы крытэры прыёмкі

**Comment by Tyuba4** [comment]
@rizomaa Я доделаю завтра-послезавтра, отправлю на пулл-реквест. Тестированием этой задачи будет код ревью.

**Comment by rizomaa** [comment]
@Tyuba4 я пазначыў важны прыярытэт задачы, каб мы яе заўтра вырашылі, бо чакаюць іншыя справы.

**Comment by rizomaa** [comment]
@Tyuba4 ці ёсць прычына не выдалць doika,sql з рэпазіторыя?

**Comment by Tyuba4** [comment]
@rizomaa Пускай, пока будет

**Comment by rizomaa** [comment]
@Tyuba4 трэба вырашыць па якой гайду жывем, бо зараз мы даем уводныя задачы на устанощку, калі працуюць міграцыі хай людзі іх тэстуюць.

Што яшчэ не гатова?

**Comment by Tyuba4** [comment]
@rizomaa Ok, работаем по миграциям.

**Comment by Tyuba4** [comment]
@rizomaa Все готово

**Comment by Tyuba4** [comment]
Закрываем ишью.
