### ISSUE TITLE
Оформить фавикон, используя логотип doika

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#221]
## Апісанне бага

На вкладке сайта отсутствует значок (логотип) doika
## Дзеянні каб паўтарыць памылку

1. Открыть в браузере страницу http://doika/doika/be/admin/login

![1](https://user-images.githubusercontent.com/46268205/52695314-3bab2480-2f7d-11e9-9572-acbf5a8031ca.jpg)

## Тэставыя ўмовы

- Версія Doika: 1.3
- Платформа і версія: Windows7
- Браўзер і версія: Chrome/Firefox/Opera

**Comment by KahjuksEi** [comment]
@fr0zen а куда прописать фавикон, если index.php для этого не подходит?

**Comment by fr0zen** [comment]
@KahjuksEi для админки https://github.com/diglabby/doika/blob/develop/resources/views/dashboard/layouts/app.blade.php

**Comment by cema93** [comment]
@Olya147 Просьба проверить

**Comment by ghost** [comment]
Да, появился. 

![1](https://user-images.githubusercontent.com/46268205/59946646-d2c84180-9473-11e9-8505-fe98ff6ea8ac.png)
