### ISSUE TITLE
Напісаць тэксты мэйлаў 1. вітальны ліст 2. для рэкурэнтных плацяжоў 3 для апрацоўкі памылак

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#222]
1. Вітальны ліст.

- [x] 1.1. Калі карыстальнік падключыўся на рэкурэнтныяплацяжы (ПАСЛЯ ПЕРШАЙ АПЛАТЫ)
- [x] 1.2. Калі карыстальнік проста набраў свой мэйл у разавым плацяжы

2. Мэйлы папярэджанні і падзякі.

- [x] 2.1. Мэйл перад тым як сума будзе знята за 2 дні да аплаты.
- [x] 2.2. Мэйл падзяка за тое што сума знялася.

3. Мэйлы памылкі пасля плацяжу, калі карстальнік набраў свой мэйл:

- [ ] 3.1. Няма грошай
- [ ] 3.2. Сцякла картка.

**Comment by lptn** [comment]
@rizomaa 
>Напісаць тэсты мэйлаў

што значыць тэсты? Толькі тэсты?

**Comment by rizomaa** [comment]
> @rizomaa
> 
> > Напісаць тэсты мэйлаў
> 
> што значыць тэсты? Толькі тэсты?

дзякуй выправіў = тэксты

**Comment by nastyafrosty** [comment]
с этой задачей дубліруется что-то? @lptn

**Comment by alies-dev** [comment]
@nastyafrosty 
магчыма вось гэта толькі Напісаць тэкст імэйлаў па рэкурэнтным плацяжам #464 (але не дублюецца)

Прапаную проста сесці і падумаць якія імэйлы мы плануем дасылаць і напісаць да іх тэксты (да УСІХ), ну а мы рэалізуем

**Comment by rizomaa** [comment]
@lptn спіс лістоў апісаны тут у задачы. ці ёсць нейкія яшчэ думкі на гэты конт?

**Comment by alies-dev** [comment]
@rizomaa 
> 1.1. Калі карыстальнік падключыўся на рэкурэнтныяплацяжы (ПАСЛЯ ПЕРШАЙ АПЛАТЫ)

Дадаў "(ПАСЛЯ ПЕРШАЙ АПЛАТЫ)", бо падпіска ствараецца пасля першага паспаховага плацяжа

>1.2. Калі карыстальнік проста набраў свой мэйл у разавым плацяжы

Не зразумеў(

> 2.1. Мэйл перад тым як сума будзе знята за 2 дні да аплаты.

пакуль рэализаваць не можам

>2.2. Мэйл падзяка за тое што сума знялася.

👍 

>3.1. Няма грошай

👍 (але и иншыя прычыны могуць быць адхілення транзакціі (скрадзена ці згублена картка), шлюзы дасылаюць тэкст памылкі, прапаную яго перасылаць бяз зменаў, як есьць)

>  3.2. Сцякла картка.

Хутчэй за ўсе тое ж самае як і пункт вышэй

**Comment by nastyafrosty** [comment]
@lptn @rizomaa "1.2. Калі карыстальнік проста набраў свой мэйл у разавым плацяжы

Не зразумеў(" тут наверное о том, что человека просто поблагодарить за едино разовое пожертвование

**Comment by rizomaa** [comment]
> @rizomaa
> 
> > 1.1. Калі карыстальнік падключыўся на рэкурэнтныяплацяжы (ПАСЛЯ ПЕРШАЙ АПЛАТЫ)
> 
> Дадаў "(ПАСЛЯ ПЕРШАЙ АПЛАТЫ)", бо падпіска ствараецца пасля першага паспаховага плацяжа
> 

https://github.com/diglabby/doika/issues/217#issue-408712732
@lptn

**Comment by rizomaa** [comment]
> 
> > 3.1. Няма грошай
> 
>  (але и иншыя прычыны могуць быць адхілення транзакціі (скрадзена ці згублена картка), шлюзы дасылаюць тэкст памылкі, прапаную яго перасылаць бяз зменаў, як есьць)
> 
> > 3.2. Сцякла картка.
> 
> Хутчэй за ўсе тое ж самае як і пункт вышэй


@lptn https://github.com/diglabby/doika/issues/26#issuecomment-504430036

**Comment by rizomaa** [comment]
https://github.com/diglabby/doika/issues/583 тут усё гатова. па 3 пункту пакуль не будзем распыляцца. пакінем, калі будзе дасканалая база
