### ISSUE TITLE
Надпись "Помоги команде..." выходит за пределы кнопки

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#224]
## Апісанне бага
В русской и белорусской версиях сайта надпись "Помоги команде doika" выходит за пределы кнопки. 

## Дзеянні каб паўтарыць памылку:
1. Открыть doika
![3](https://user-images.githubusercontent.com/46268205/52705270-88015f00-2f93-11e9-8bc2-74dc8a39b8d4.jpg)

## Тэставыя ўмовы
- Версія Doika: 1.3
- Платформа і версія: Windows7
- Браўзер і версія: Chrome/Firefox/Opera

**Comment by fr0zen** [comment]
@nastyafrosty хочу посоветоваться с тобой, как будем решать в дальнейшем проблемы с длинным текстом, чтобы он не сильно разрушал внешний вид. 
Пока вижу такие варианты:
1. Растягивать кнопку по высоте автоматически в зависимости от текста. Текст становится в несколько строк.
2. Уменьшаем шрифт (будет выглядеть коряво по-моему)
3. Изменяем текст так, чтобы влезал)
4. Просто обрезаем текст, который не влазит (не круто)

Мне нравятся 1 и 3 вариант больше других. Твое мнение на этот счет?

**Comment by nastyafrosty** [comment]
@fr0zen текст в кнопке в две строчки - это плохо(
надо подумать над задачей

**Comment by KahjuksEi** [comment]
Можно еще какими нибудь SVG заменять например.

**Comment by rizomaa** [comment]
@KahjuksEi пазначай ник, калі з нейкім камунікуеш

**Comment by KahjuksEi** [comment]
@fr0zen правильный ли это путь для редактирования данных? doika.loc/doika/resourses/lang/be/

**Comment by rizomaa** [comment]
@KahjuksEi а ў чым сумнеў? 
1. калі напраклад правільны, што збіраешся далей рабіць? 
2. калі няправільны, што будзеш рабіць?

**Comment by fr0zen** [comment]
@KahjuksEi так, дакладна ён, што думаеш змяніць?

**Comment by KahjuksEi** [comment]
@fr0zen просто изменения не проходят когда слова меняешь

**Comment by fr0zen** [comment]
@KahjuksEi трэба перагенераваць масіў перакладаў: php artisan vue-i18n:generate

**Comment by rizomaa** [comment]
@fr0zen дзе у нас гэта можна прачытаць?

**Comment by KahjuksEi** [comment]
@fr0zen в вики страницу создал https://github.com/diglabby/doika/wiki/Праца-з-кодам-модуля-(для-распрацоўшчыкаў), мое предложение такое:
![qip shot - screen 711](https://user-images.githubusercontent.com/39082880/52897155-3f8bb080-31e2-11e9-993c-f3e050e9f33b.png)
все влезает, смысл данных остается понятен.

**Comment by nastyafrosty** [comment]
there should be not too much words in button, cause it is a call to action thing
so, if we want to have button - we can make button from one word (call to action word) or shorten phrase
or just to make the phrase noticeable (underlined, maybe bold etc)

**Comment by KahjuksEi** [comment]
So, what to do? To wait final decision or to make screenshots with your own variations?

**Comment by fr0zen** [comment]
> there should be not too much words in button, cause it is a call to action thing
> so, if we want to have button - we can make button from one word (call to action word) or shorten phrase
> or just to make the phrase noticeable (underlined, maybe bold etc)

@KahjuksEi согласно того что написано выше, пойдем просто путем изменения текста. Кнопка будет фиксированного размера.

**Comment by fr0zen** [comment]
5 min

**Comment by rizomaa** [comment]
@KahjuksEi выдатна
