### ISSUE TITLE
Список кампаний не вмещается по ширине экрана

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#225]
## Апісанне бага
В русской и белорусской версиях сайта список созданных кампаний не вмещается на странице. Целиком таблицу можно увидеть, установив масштаб страницы = 75%.

## Дзеянні каб паўтарыць памылку
1. Открыть раздел "Список кампаний"
![4](https://user-images.githubusercontent.com/46268205/52705870-027eae80-2f95-11e9-9b76-f4fb0c235c5a.png)

## Тэставыя ўмовы

- Версія Doika: 
- Платформа і версія: Windows10/Linux/MacOS/Android9/iOS12
- Браўзер і версія: Chrome/Firefox/Edge/Internet explorer/Safari

**Comment by KahjuksEi** [comment]
@rizomaa появляется вопрос по адаптиву модуля, на каких экранах какой вид должна иметь таблица? 10 полей же не помещается даже в стандартной ширине при открытом навбаре, предлагаю взять эту тему в оборот.

**Comment by rizomaa** [comment]
@KahjuksEi табліца можа не ўмяшчацца, гэта нармальна

Завагі
1. Палі Сабраная сума і Мэтавая сума аб'яднаць у адно. праз слэш запісваць 

Сабраная сума /
Мэтавая сума

123 / 350

такі чынам будзе адзін слупок. 

2. Колькасць дзён да заканчэння пераіменаваць у "Засталося дзён"

**Comment by ghost** [comment]
@maxmatoha @KahjuksEi Карточку рано закрывать. Что осталось исправить:
1) переименовать поле "Колькасць дзён да заканчэння";
2) объединить гр. "Сабраная сума" и "Мэтавая сума".
