### ISSUE TITLE
Выправіць тэсты phpunit, прыбраць залежнасці.

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#226]
@fr0zen падпраў сабе усё тут...

**Comment by fr0zen** [comment]
Пасля чысткі базы, у роутах засталіся залежнасці, якія звязваюць іх з мадэлямі. Праглядзець і выправіць.

Каб пратэсціць:

- [ ] 1. Актуалізаваць бд на тэст-сэрвере http://it3donate-master.falanster.by

**Comment by rizomaa** [comment]
@fr0zen як можа табе астатняе каманда дапамагчы?
ці ёсць нейкі спіс залежнасцяў, якія непатрэбны?

**Comment by rizomaa** [comment]
@fr0zen можаш удакладніць што тут неабходна абмеркаваць?

1. Ці усё зусім там не зразумела, 
2. Ці ўсё ж такі ты схіляешся на нейкі варыянт(ы) проста не упэўнены ў ім?

наогул, мне цікава бачыць нейкае апісанне непатрэбных залежнасцяў у роўтах?

так назва гучыць супер не зразумела "Выправіць залежнасці у роутах Laravel". На што выправіць, на усё харошае або у нас ёсць нейкая архітэктура, на якую абапіраемся, ці зацяб спіс?

Бо атрымліваецца, што пасля абмеркавання (ці калі яго не будзе) захаваецца нябачнасць логікі рашэння і ніхто не зможа далучыцца да працы. 

1. Можа ёсць нейкія логі, 
2. або апісанні роўтаў, якія патрэбны?
2. Або рэквэст, які цягне на дно?

**Comment by rizomaa** [comment]
@Tyuba4 можаш пракаментаваць?

**Comment by Tyuba4** [comment]
@rizomaa Просмотрю код и прокомментирую

**Comment by fr0zen** [comment]
- [ ] Выдаліць middleware meta з [Kernel.php](https://github.com/diglabby/doika/blob/dev/app/Http/Kernel.php)

- [ ] Выдаліць middleware meta з [RouteServiceProvider.php](https://github.com/diglabby/doika/blob/dev/app/Providers/RouteServiceProvider.php)

**Comment by rizomaa** [comment]
@fr0zen як разумею мы адмащляемся ад гэтай ішус у сувязі з #258 ?

**Comment by lptn** [comment]
зроблена ў межах задачы "Заліць чысты ларавел" #258
