### ISSUE TITLE
Изменить в форме обратной связи название поля "E-mail"

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#227]
## Дзеянні каб паўтарыць памылку
1. Открыть раздел "Обратная связь"

## Апісанне бага
Пользователю не ясно, чей эл. адрес следует ввести в поле "Email".

![1](https://user-images.githubusercontent.com/46268205/52883511-441d7e00-317c-11e9-951f-89c38ead9910.jpg)

## Чаканы вынік
Дополнить название поля. Например "Ваш email", "Email, на который будет отправлен ответ" и т. д.
## Тэставыя ўмовы
- Версія Doika: 1.3
- Платформа і версія: Windows7
- Браўзер і версія: Chrome/Firefox/Opera

**Comment by maxmatoha** [comment]
планую зрабiць за гадзiну

**Comment by Olya147** [comment]
займёт не более 5 минут.

**Comment by Olya147** [comment]
Исправлено.
