### ISSUE TITLE
Зрабiць макеты внешнего вида модуля (на сайте)

### ISSUE THREAD

**Issue by cema93** [diglabby/doika#23]
@nastyafrosty

**Comment by fr0zen** [comment]
@nastyafrosty пакуль у мяне есць усе, што мне патрэбна па дызайну.

**Comment by falanster** [comment]
@cema93 @nastyafrosty @fr0zen на мой погляд гэта занадта агульная дубляваная задача. 

прапаную выдаліць?

**Comment by nastyafrosty** [comment]
https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346340375940   
- поменялся вид инпута (iншая сума) - внешняя тень исчезла,появилась внутренняя (углубление)
- кнопки "разава" "кожны месяц" стали чуть меньше (высота 40px)
- когда юзер не выбирает периодичность, кнопки приобретают обводку в цвет надписи на кнопке, появляется уведомление о том,что необходимо выбрать
