### ISSUE TITLE
Фронтэнд. Выправіць перанос словаў на старонцы рэдагавання кампаніі

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#231]
2. Headline: Неверный перенос слова.

Severity: Enhancement.

Description: 
1.Открыть приложение- http://it3donate-landing.falanster.by/doika/en/admin/campaigns/1/edit
2.Открыть из меню пункт "Campaigns".
3.Нажать пункт "First campaign".   

Result:
1.Неверный перенос слова "Finish at".      

Attachments:
![screenshot_2](https://user-images.githubusercontent.com/30193031/51001554-14ee6e00-1539-11e9-916c-d14de2431b74.png)

_Originally posted by @andrey1999999 in https://github.com/diglabby/doika/issues/100#issuecomment-453283481_

**Comment by maxmatoha** [comment]
Можно закрыть
