### ISSUE TITLE
Фронтэнд. Пераіменаваць айдішнікі палёў на старонцы канфігурацыі плацежнай сістэмы.

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#232]
3.Headline: При заполнении одного окна, данные дублируются в остальные три окна.

Severity: Average.

Description: 
1.Открыть приложение- http://it3donate-landing.falanster.by/doika/en/admin/paymentSystems
2.В окно "Bepaid Market Id" ввести данные, например 1.

Result:
Введенные данные дублируются во все остальные окна.

Expected result: 
Данные введенные в окно "Bepaid Market Id" не должны дублироваться в остальные окна.    
       Attachments:
![screenshot_3](https://user-images.githubusercontent.com/30193031/51002326-9d6e0e00-153b-11e9-9b8a-8a102224d27b.png)

4. Headline: Не корректное написание слова.

Severity: Enhancement.

Description: 
1.Открыть приложение- http://it3donate-landing.falanster.by/doika/admin/campaign

Result:
Некорректное написание слова "Bepaid".

       Attachments:
![screenshot_4](https://user-images.githubusercontent.com/30193031/51002388-c5f60800-153b-11e9-8ec2-449b998e0306.png)

5.	Headline: Не выполняется вставка изображения.
Severity: Average.

Description: 
1.Открыть приложение- http://it3donate-landing.falanster.by/doika/admin/campaign
2.Открыть из меню пункт "Payment systems".
3.Нажать вкладку "Insert image".
4.Выбрать изображение.
5.Нажать "ок" на всплывающей вкладке.
      
Result:
1.Не выполняется вставка изображения.
       Attachments:
![screenshot_5](https://user-images.githubusercontent.com/30193031/51002423-dd34f580-153b-11e9-97f9-e3dbc2df96a0.png)

6.  Headline:Не выполняется функция создать нового пользователя.
Severity: Average.

Description: 
1.Открыть приложение- http://it3donate-landing.falanster.by/doika/admin/campaign
2.Открыть из меню пункт "Users".
3.Заполнить поле "Name", “Email”, “Password”, Repeat password”.
4.Нажать “Create”.
      
Result:
1.Не выполняется функция создать нового пользователя.

_Originally posted by @andrey1999999 in https://github.com/diglabby/doika/issues/100#issuecomment-453289944_

**Comment by ghost** [comment]
@maxmatoha @fr0zen После обновлений в разделе "Паведамленні" появились новые поля "Шаблон эл. ліста..." и "Удзячнасць за зроблены плацеж...", записи в которых также дублируются.

![3](https://user-images.githubusercontent.com/46268205/57650497-a0553a00-75d3-11e9-8ae8-6bfeebfa9fc1.png)

**Comment by maxmatoha** [comment]
Подправлю

**Comment by ghost** [comment]
Исправлено.
