### ISSUE TITLE
Бэкэнд. Арганізаваць заліўку выявы (!) у тэкставым полі на старонцы апісання кампаніі.

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#233]
5.	Headline: Не выполняется вставка изображения.
Severity: Average.

Description: 
1.Открыть приложение- http://it3donate-landing.falanster.by/doika/admin/campaign
2.Открыть из меню пункт "Payment systems".
3.Нажать вкладку "Insert image".
4.Выбрать изображение.
5.Нажать "ок" на всплывающей вкладке.
      
Result:
1.Не выполняется вставка изображения.
       Attachments:
![screenshot_5](https://user-images.githubusercontent.com/30193031/51002423-dd34f580-153b-11e9-97f9-e3dbc2df96a0.png)

6.  Headline:Не выполняется функция создать нового пользователя.
Severity: Average.

Description: 
1.Открыть приложение- http://it3donate-landing.falanster.by/doika/admin/campaign
2.Открыть из меню пункт "Users".
3.Заполнить поле "Name", “Email”, “Password”, Repeat password”.
4.Нажать “Create”.
      
Result:
1.Не выполняется функция создать нового пользователя.

_Originally posted by @andrey1999999 in https://github.com/diglabby/doika/issues/100#issuecomment-453289944_

**Comment by ghost** [comment]
Исправлено.
