### ISSUE TITLE
Змяніць фармат даты на старонцы рэдагавання кампаніі у абодвух палях

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#234]
Патрэбны фармат: DD/MM/YYYY

![selection_004](https://user-images.githubusercontent.com/9870374/53107288-c5db2600-3545-11e9-84c7-24e8308965af.png)

**Comment by cema93** [comment]
@Olya147 @rizomaa  просьба проверить. Если всё хорошо - issue закрываем

**Comment by ghost** [comment]
@cema93 Исправлено. Закрываю.
![234](https://user-images.githubusercontent.com/46268205/60041789-e1f1fe00-96c4-11e9-9105-fad56348dc59.png)
