### ISSUE TITLE
Прапанова: Выкарыстоўваем тэрмін `Dashboard` замест `Backend`

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#236]
## Мэты
 - пазбегнуть двухсэнсоўнасці: у кодзе мы выкарыстоўваем слова Frontend для Віджэта, Backend -- для адмінкі. Усе гэта стварае праблемы ў камунікацыі

### Тэрміны (я прапаную)
`Dashboard` - адмінка дойкі
`Widget` - форма данэйта і сумежны стаф

`Backend` - любы код на PHP
`Frontend` - любы JS + CSS + HTML код на нашым праекце

## Што рабіць?
 - Памяць крыху ў кодзе (за раз, бяру на сябе)
 - Памяняць крыху ў вікі (можна паступова)

## Галасуем
👍  - згода!
👎 - не-а (пішыце чаму не)
👀 - паглядзеў але нічорта не зразумеў і вырашыў не лезці (а то лясне)

**Comment by lptn** [comment]
@fr0zen @Tyuba4 @svetit таксама хачу пачуць вашы меркаванні

**Comment by rizomaa** [comment]
@lptn я за усё харошае =) але у мяне асацыяцыя з дашбордам, гэта панэль праз якую працуеш з нечым, ну карацей з кодам няма асацыяцыі. цікава што іншыя скажуць

**Comment by lptn** [comment]
@rizomaa 
Я крыху адакладню прапанову:
Зараз "Backend" у нас гэта і тэхнічны тэрмін і даменны тэрмін адначасова, вельмі дзішна бачыць класы напісанные на PHP якія называюцца "Frontend"

Мая прапанова па-ранейшаму выкарыстоўваць `Backend` для апісання ўсяго што мы робім на сэрверы (у нашым выпадку гэта PHP код)
Dashboard - гэта наш "даменны" тэрмін (не тэхнічны),

**Comment by lptn** [comment]
@rizomaa 
@Tyuba4 
@fr0zen 
@nastyafrosty 
@KahjuksEi 
@Olya147 
@svetit 
@cema93 
Штука простая, але важная, знайдзіце калі ласка 5 хв і прагаласуйце (можаце чытаць толькі першае паведамленне тут)

**Comment by fr0zen** [comment]
@lptn калі прымаем, значыць дзелім Backend і Frontend код на тэчкі Dashboard і Widget, гэта прапаноўваеш? Ці проста агульны слоўнік складаем?

**Comment by lptn** [comment]
@fr0zen
Прапаноўваю гэтыя тэрміны ў кодзе выкарыстоўваць. На дадзены момант гэты здаецца толькі кантроллеры бэкэнда (але код на Vue я не глядзеў, магчыма і там ёсць што перайменаваць)

**Comment by lptn** [comment]
прынята!

**Comment by lptn** [comment]
Тэрміны перанес сюды https://github.com/diglabby/doika/blob/dev/docs/glossary.md
