### ISSUE TITLE
Выправіць назву composer package

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#237]
>$ composer --version
Deprecation warning: Your package name Doika is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.

Прапаную выкарыстоўваць `diglabby/doika`

**Comment by fr0zen** [comment]
@lptn крутая заўвага, дзякуй
