### ISSUE TITLE
Апрацоўшчык памылак каннэктра (калі пусты, калі памылка) фронт!

### ISSUE THREAD

**Issue by cema93** [diglabby/doika#24]
Апрацоўшчык памылак каннэктра (калі пусты, калі памылка) фронт!  стварыць блок схемы з магчымымі памылкамі 2г @svetanazarova обсудить мозгоштурмом

**Comment by falanster** [comment]
@cema93 @fr0zen @Tyuba4 

чаму тольки каннэктара, ці ёсць у нас нейки клас для усіх памылак?

**Comment by rizomaa** [comment]
@fr0zen гэта не твая юрысдыксцыя? мы з @Tyuba4

**Comment by fr0zen** [comment]
@rizomaa на фронте так, мая

**Comment by rizomaa** [comment]
@fr0zen гэта яшчэ актуальна?
