### ISSUE TITLE
Назва тэкста на англiйскай мове.

### ISSUE THREAD

**Issue by andrey1999999** [diglabby/doika#240]
Тэсцiраванне старонкi «Term of use»
Summary: Назва тэкста на англiйскай мове.
Environment: Google chrome.
Steps of reproduce:
1.Прайсцi па ссылцы: http://it3donate-landing.falanster.by/
2.Перайсцi на укладку «Модуль прыёма ахвяраванняу» (пракруцiць скрол унiз).
3.Адкрыць Term of use (клiкам правай клавiшы мышы).
Actual result: 
Назва старонкi напiсана на англiйскай мове.
 
![image](https://user-images.githubusercontent.com/30193031/53278580-c248ca00-3712-11e9-9aa4-0b7f7fcfed86.png)

Expected result:
Назва старонкi павiнна быць на той жа мове што i асноуны тэкст (у гэтым выпадку на беларускай мове).

**Comment by Olya147** [comment]
Исправлено ("На гэтай старонцы ахвяраванне робіцца банкаўскай картай")
