### ISSUE TITLE
Тэкст «Term of use» не падзелены на абзацы.

### ISSUE THREAD

**Issue by andrey1999999** [diglabby/doika#242]
Тэсцiраванне старонкi «Term of use»
Summary: Тэкст «Term of use» не падзелены на абзацы.
Environment: Google chrome.
Steps of reproduce:
1.Прайсцi па ссылцы: http://it3donate-landing.falanster.by/
2.Перайсцi на укладку «Модуль прыёма ахвяраванняу» (пракруцiць скрол унiз).
3.Адкрыць Term of use (клiкам правай клавiшы мышы).
Actual result: 
Тэкст «Term of use» не падзелены на абзацы..
 
![image](https://user-images.githubusercontent.com/30193031/53278653-2c616f00-3713-11e9-8141-99de7c94bc52.png)

Expected result:
Падзялiць тэкст на абзацы у адпаведнасцi з абразцом «Роадмэп Doika » .

**Comment by Olya147** [comment]
Исправлено.
