### ISSUE TITLE
Тэсцiраванне старонкi «Модуль прыёма ахвяраванняу»

### ISSUE THREAD

**Issue by andrey1999999** [diglabby/doika#243]
Тэсцiраванне старонкi «Модуль прыёма ахвяраванняу»   

Summary: Модуль прыёма ахвяраванняу. Пасля   скарочаннага слова не хапае кропкi. 

Environment: Google chrome.   

Steps of reproduce: 
1.Прайсцi па   ссылцы: http://it3donate-landing.falanster.by/  
2.Перайсцi на   укладку «Модуль прыёма ахвяраванняу» (пракруцiць скрол унiз).  

Actual result:    Пасля скарочаннага слова не хапае кропкi.     
![image](https://user-images.githubusercontent.com/30193031/53278754-d50fce80-3713-11e9-990d-f40554d335c4.png)

Expected result:   Пасля скарочанных слоу паставiць кропкi .

**Comment by Olya147** [comment]
исправлено.
