### ISSUE TITLE
Дадаць пасля "сардэчка" Фаланстэр з лінкам

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#247]
![selection_008](https://user-images.githubusercontent.com/9870374/53287683-d501e400-3790-11e9-8d0f-9262382f849f.png)

**Comment by Gordonshik** [comment]
Беру это на себя.
Из вопросов:
1) with сердечко by у меня отсутствует это доделать надо самому или у меня не обновлен проект? понять не могу
2) Language то же самое, отсутствует в хедере и язык изменить не могу.
Быть может это просто дизайн вообще и надо просто сделать with serdechko by Falanster?
Пока по структуре буду смотреть с чем разбираться.

**Comment by Gordonshik** [comment]
Пока наверстал саму надпись. Начал делать стили, пока ничего не отображается вообще, пытаюсь разобраться с этим. Гуглю атрибуты, вспоминаю стили. Немного видимо придется почитать про scss.
Увидел связь с props, изучаю способ взаимодействия с ними.
Пришел к выводу о том, что судя по всему создаются переменные в labels.php и в vue-i18n-locales.generated.js, которые используются в качестве строковых значений, которые в свою очередь интегрируются в footer.vue (и куда угодно) посредством export defaults.
При чем labels.php и в vue-i18n-locales.generated.js содержат в себе все данные на всех использующихся языках, что приводит к вопросу, а не надо ли написать на всех языках? made by, зроблена, сделано или только как на картинке? Судя по надписи все же на eng с сердечком надо, но идея такая возникла.
Пока для себя вижу вариант сделать что-то по аналогии, опираясь на то, каким образом сделано: "Powered by Doika. Supported by the European Union".

**Comment by Gordonshik** [comment]
Развидел связь с labels.php и в vue-i18n-locales.generated.js, пытаюсь понять откуда данные поступают.
Уже есть мысль, о других связях.
Но наверное, для начала, я прочитаю https://ru.vuejs.org/v2/guide/components-props.html

**Comment by rizomaa** [comment]
@Gordonshik для сардэчка карыстайцеся шрыфтам awesome

**Comment by Gordonshik** [comment]
Пока прочитал про: создание экземпляра Vue, Данные и методы, Хуки жизненного цикла экземпляра, Диаграмма жизненного цикла. И про другие принципы vue, но по структуре пока еще не вкурил. Только больше вопросов возникло после некоторых поисков. Вроде того, что есть два файла footer.vue, у них разные пути, но как они друг с другом связаны пока не очевидно. Кое что общее у них вроде как есть.

**Comment by Gordonshik** [comment]
Прочитал это: https://ru.vuejs.org/v2/guide/syntax.html#%D0%A1%D1%8B%D1%80%D0%BE%D0%B9-HTML.
Пытаюсь сделать, пока не выходит

**Comment by Gordonshik** [comment]
Начал по аналогии менять структуру футера во всех файлах и где видел по аналогии передавал переменные по пропсам, уже кучу раз переделывал, пока безрезультатно.

**Comment by rizomaa** [comment]
@Gordonshik 
Я бачу, што вы шмат усяго зрабілі, паспрабуем сістэматызаваць працу.

1. Напішыце алгарытм рашэння, як вы яго бачыце. 1, 2, 3.... пакрокава.
2. Будзем разам думаць...

Як разумею вы спадзяваліся: 
1. Знайсці радок пераклада у масівах перакладаў... напрыклад, тут https://github.com/diglabby/doika/tree/develop/resources/lang/be
2. Дадаць атрыбуты у патрэбны кампанент і запоўніць у яго "Фаланстэр"
3. Адмаляваць спасылку.
4. Пулрэквэст. Так?


Але атрымалася, што кантэнт ляжыць у нейкім іншым месцы. І вы зараз шукаеце яго хаатычна? што паказвае пошук са словамі: with 'with 'with' ?

Я як і вы не ведаю рашэння, але паспрабую выбудаваць яго алгарытм.

**Comment by Gordonshik** [comment]
@rizomaa 
Как раз хотел отписать.
В какой-то момент я увидел такое в Footer.vue({{ $t('labels.admin.common.footer.with') }}), глянул где и что это и вышел на перевод, подумал, что надо объявить там, Дадаць атрыбуты у патрэбны кампанент і запоўніць у яго "Фаланстэр", как и написали
НО!
На данный момент моя логика такая (по шагам)
1. Из того, что я прочел я сделал вывод, что надо от full.vue спустить по пропсам объекты
То есть я создал в data во full.vue 2 переменных falanster и withLove,
2) Далее я попытался передать пропсы из data в FooterApp (:falanster="falanster"
:withLove="withLove")
3)Далее я попытался принять их в footer.vue(
`    withLove: {
      type: String,
      default: ''
    },
    falanster: {
      type: String,
      default: ''
    }
`
)
4) Далее уже в <template> аналогично с уже написанным с помощью полученных из пропс сведений написать то же самое практически, только с нашими данными. Но не работает так у меня.
Если не так, то пока я не совсем понимаю, откуда еще (из какого внешнего источника) можно получить пропсы, где их объявить и куда еще расшарить.
Я натыкался на много похожих по структуре футеров в разных файлах, иногда в них встречались отличия, уровня: вместо <div> строк была в <p> и т.д.
По поводу поиска  with 'with 'with':
Выводит практически все варианты с labels.php.
Заранее скажу, что там я уже тоже пробовал все объявлять на всех языках
`'falanster' => 'Falanster',` примерно так у меня получилось, но выхлопа от этого, я конечно же не получил.
В logging.php `'with' => [
                'stream' => 'php://stderr',
            ]`
Ну и как я уже писал в начале: в какой-то момент я увидел такое в Footer.vue({{ $t('labels.admin.common.footer.with') }}), тут тоже with находит.

**Comment by Gordonshik** [comment]
Прочитал:
https://ru.vuejs.org/v2/guide/list.html
https://ru.vuejs.org/v2/guide/computed.html
https://ru.vuejs.org/v2/guide/class-and-style.html

**Comment by rizomaa** [comment]
@Gordonshik пакуль тут трохі прытармозім. 

зробім простую задачу (1-2) і вернемся да гэтых 

паглядзіце: https://github.com/diglabby/doika/issues/680

**Comment by rizomaa** [comment]
Вітаю, @Gordonshik 

Падкажы калі ласка, ці змэрджылі мы гэту задачу? 
Бо нешта гляджу ПР https://github.com/diglabby/doika/pull/683 Ён проста стопнуты.

**Comment by Gordonshik** [comment]
@rizomaa видимо не мерджанули, reopen pr сделать не могу,
во всяком случае я пуллил, но не добавилось ничего
![изображение](https://user-images.githubusercontent.com/51483246/80639474-bd944a00-8a6a-11ea-90bc-63ab516186aa.png)

**Comment by rizomaa** [comment]
Прывітанне @Gordonshik,

Проста твары новы ПР з гэтымі жа зменамі.

**Comment by darth-tesla** [comment]
Эта ишью ещё актуальна? "Фаланстэр" со ссылкой же уже есть в футере.

**Comment by rizomaa** [comment]
@darth-tesla а сардэчка там? (зы чырвогана колеру)

**Comment by rizomaa** [comment]
@darth-tesla заасайніў табе картку. напішы як тут прагрэс?

**Comment by rizomaa** [comment]
@darth-tesla дзякуй, ПР прыняў
