### ISSUE TITLE
Праблемы устаноўкі: памылка 404 пасля устаноўкі*

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#248]
Хаця ніякіх зменаў не уносіў яшчэ...
@lptn @Tyuba4 @fr0zen 

![selection_010](https://user-images.githubusercontent.com/9870374/53340745-c0e9ee00-391a-11e9-996d-b0f474ecc434.png)

**Comment by rizomaa** [comment]
Карацей гэта ішуа блакуе тэставанне https://github.com/diglabby/doika/pull/212

**Comment by rizomaa** [comment]
Поўны спіс тэчак:

```
tests
routes
storage
resources
public
database
config
app
artisan

```
якія паказвае што зменены:

```
bootstrap/app.php
bootstrap/cache/.gitignore
composer.json
composer.lock
doika.sql
index.php
nginx_app.conf
package-lock.json
package.json
phpunit.xml
CONTRIBUTING.md
Procfile
README.md
```

**Comment by rizomaa** [comment]
![selection_011](https://user-images.githubusercontent.com/9870374/53353134-2ba82300-3935-11e9-9839-41c11ee983b8.png)

**Comment by rizomaa** [comment]
Змесціва gitignore

  1 # Dev/IDE (normally they shold be ignored on developer local machine level)
  2 /.idea
  3 /.vscode
  4 /.vagrant
  5 .phpstorm.meta.php
  6 _ide_helper.php
  7 _ide_helper_models.php
  8 
  9 # node.js
 10 /node_modules
 11 npm-debug.log
 12 
 13 # Laravel
 14 .env
 15 /vendor
 16 
 17 /public/build
 18 /public/dist

**Comment by rizomaa** [comment]
![selection_012](https://user-images.githubusercontent.com/9870374/53353410-affaa600-3935-11e9-9d61-d442d5161129.png)

**Comment by rizomaa** [comment]
![selection_013](https://user-images.githubusercontent.com/9870374/53353654-48912600-3936-11e9-93b8-a0e21bdda99c.png)

**Comment by rizomaa** [comment]
@fr0zen @Tyuba4 так два файла усёж падсвяціліся, што зменены

Пасля дургой усталёўцы

modified:   package-lock.json
modified:   package.json

Вашы думкі?

**Comment by rizomaa** [comment]
```
diff --git a/package.json b/package.json
index 476bf17..5e72862 100644
--- a/package.json
+++ b/package.json
@@ -39,7 +39,7 @@
     "jquery": "^3.3.1",
     "lodash": "^4.17.11",
     "mini-css-extract-plugin": "^0.4.3",
-    "node-sass": "^4.9.3",
+    "node-sass": "^4.11.0",
     "noty": "^3.2.0-beta",
     "perfect-scrollbar": "^1.4.0",
     "popper.js": "^1.14.4",

```

Другі файл доўгі таму усе змены падшыў @fr0zen @Tyuba4 

[package-lock.json.txt](https://github.com/diglabby/doika/files/2905065/package-lock.json.txt)
[package.json.txt](https://github.com/diglabby/doika/files/2905066/package.json.txt)

**Comment by lptn** [comment]
@rizomaa 
калі гэта адбылося пасля таго як ты першы раз зпуліў змены ПАСЛЯ ЧЫСТКІ рэпазіторыя якую рабіў @fr0zen , то хутчэй за ўсе гэта норма, бо перепісана уся гісторыя (як у савецкія часы)

**Comment by rizomaa** [comment]
@lptn калі вы павыцягваеце усе макароніны з італьянскага коду, і мы паставім дойку без гэтых багаў, можна будзе зачыніць. дамовіліся?

**Comment by Olya147** [comment]
@lptn Исправлено?

**Comment by lptn** [comment]
@Olya147
>Исправлено?

гэта ў @rizomaa трэба пытаць

**Comment by Olya147** [comment]
@rizomaa проблема решена?

**Comment by rizomaa** [comment]
@Olya147 дзякуй, што дапытала, я паспрабую зрабіць устаноўку і тады напішу. таму ішу пакідаем. будзем над ёй працаваць

**Comment by rizomaa** [comment]
gyp verb download contents checksum {"node-v11.15.0-headers.tar.gz":"e738ca0fa48e1b43a4edb8d3accb7ed6ce65aa27e74ccfd26989eb87a0add509"}
gyp verb validating download checksum for node-v11.15.0-headers.tar.gz (e738ca0fa48e1b43a4edb8d3accb7ed6ce65aa27e74ccfd26989eb87a0add509 == e738ca0fa48e1b43a4edb8d3accb7ed6ce65aa27e74ccfd26989eb87a0add509)
gyp verb get node dir target node version installed: 11.15.0
gyp verb build dir attempting to create "build" dir: /var/www/html/donate3/public_html/doika/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/var/www/html/donate3/public_html/doika/node_modules/node-sass/build'
gyp ERR! System Linux 4.4.0-154-generic
gyp ERR! command "/usr/bin/node" "/var/www/html/donate3/public_html/doika/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/html/donate3/public_html/doika/node_modules/node-sass
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.4 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.9.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by rizomaa** [comment]
Выйшаў на такія пірагі:

![Selection_021](https://user-images.githubusercontent.com/9870374/61577707-d2af7600-aaf3-11e9-8d4c-c263088e3f5a.png)

**Comment by rizomaa** [comment]
@ilyaaki @fr0zen @cema93 ёсць ідэі у чым праблема?

**Comment by fr0zen** [comment]
@rizomaa адчыні калі ласка [Лагін](http://donate3/doika/doika/dashboard/login)

**Comment by rizomaa** [comment]
зараз такая буба

"UnexpectedValueException
The stream or file "/var/www/html/donate3/public_html/doika/storage/logs/laravel-2019-07-20.log" could not be opened: failed to open stream: Permission denied"

**Comment by rizomaa** [comment]
@fr0zen 
UnexpectedValueException
The stream or file "/var/www/html/donate3/public_html/doika/storage/logs/laravel-2019-07-20.log" could not be opened: failed to open stream: Permission denied

**Comment by fr0zen** [comment]
@rizomaa трэба chmod 775 на /var/www/html/donate3/public_html/doika/storage/

**Comment by rizomaa** [comment]
@fr0zen дзякуй. запрацавала, але па лагину пытанне...

**Comment by rizomaa** [comment]
"Пасля дадаем зыходныя дадзеныя камандай php artisan db:seed"
Адсутнічаў у старым гадзйен. выдаліў стары,. зараз у нас толькі адзін
