### ISSUE TITLE
Стварыць магчымасць разгортваць рэпазіторый у АДНУ тэчку

### ISSUE THREAD

**Issue by svetasemashko** [diglabby/doika#25]
Праблема Doika_1.2: 
Стаўлю модуль на сайт працуючай арганізацыі. Карыстаюся git clone. Файлы і папкі распакоўваюцца ў тэчку doika_1.2 ці любую іншую якую я пазначу, але тэчка павінна быць пустой. Гэта правіла!
Пасля перакідваю рукамі тэчкі client-side і doika у корань сайта (звычайна public_html), бо наш модуль працуе менавіта ў корані сайта.
Пасля, дабавілі пару важных камітаў і аднавілі наш агульны рэп на гітхабе. Змены важныя, трэба дадаць на сайт працуючай арганізацыі, якая ўжо карыстаецца модулем. 
На хосцінге есць магчымасць адным клікам забраць змены з гітхаба ў праэкт, але ў нашым выпадку гэта не працуе, бо асноўныя тэчкі папярэне былі вынесены рукамі. 

Вывад, у выпадку маленькай праўкі кода - прыходзіцца ісці на сайт арганізацыі, усе выдаляць, чысціць і ставіць модуль з самага пачатку 

- [ ] 1. чоткая структура праекта
- [x] 2. праект увесь ляжць у адной тэчцы

**Comment by svetasemashko** [comment]
рэалізуецца ў версіі 1.3

**Comment by falanster** [comment]
@fr0zen як тут пратэставаць?

**Comment by fr0zen** [comment]
@soonreal не ведаю што тут тэставаць, праект зараз працуе праз адну тэчку дакладна. Структуру лепш паставіць асобнай issue, на мой погляд
