### ISSUE TITLE
Паўначыць пашырэнні zip gd curl у інструкцыі па усталёўцы модуля

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#252]
пры инсталяцыя кампощзера выдае  sudo composer install

```

  Problem 1
    - The requested PHP extension ext-gd * is missing from your system. Install or enable PHP's gd extension.
  Problem 2
    - Installation request for arcanedev/no-captcha 7.0.0 -> satisfiable by arcanedev/no-captcha[7.0.0].
    - arcanedev/no-captcha 7.0.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 3
    - Installation request for phpoffice/phpspreadsheet 1.5.2 -> satisfiable by phpoffice/phpspreadsheet[1.5.2].
    - phpoffice/phpspreadsheet 1.5.2 requires ext-gd * -> the requested PHP extension gd is missing from your system.
  Problem 4
    - Installation request for teamtnt/tntsearch v1.4.0 -> satisfiable by teamtnt/tntsearch[v1.4.0].
    - teamtnt/tntsearch v1.4.0 requires ext-pdo_sqlite * -> the requested PHP extension pdo_sqlite is missing from your system.
  Problem 5
    - Installation request for facebook/webdriver 1.6.0 -> satisfiable by facebook/webdriver[1.6.0].
    - facebook/webdriver 1.6.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 6
    - phpoffice/phpspreadsheet 1.5.2 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - maatwebsite/excel 3.1.3 requires phpoffice/phpspreadsheet ^1.4 -> satisfiable by phpoffice/phpspreadsheet[1.5.2].
    - Installation request for maatwebsite/excel 3.1.3 -> satisfiable by maatwebsite/excel[3.1.3].

```
Карацей трэба у інструкцыю Readme.md запісаць 
zip
gd
curl
пашырэнні для php

**Comment by lptn** [comment]
gd  і zip ужо не патрэбныя пасля чыстцы праведзенай  у межах Заліць чысты ларавел #258

**Comment by rizomaa** [comment]
curl + zip....

@lptn + @fr0zen + @Tyuba4 дагэтуль няма ні ў гайдзе па усталёўцы, ні ў асяродку

**Comment by alies-dev** [comment]
мы НЕ выкарыстоўваем `arcanedev/no-captcha` які патрабаваў `ext-gd` + `ext-curl`. Забываем пра  `ext-gd` але `ext-curl` патрэбны распрацоўшчыкам (на прадакшане не абавязковы наколькі а бачу з логаў)

`ext-pdo_sqlite` хутчэй за ўсе болей не патрэбны, ці на крайняк патрэбны толькі распрацоўшчыкам

**Comment by alies-dev** [comment]
@rizomaa 
было б файна каб ты паказаў вынікі composer install на бягучай версіі (develop)

**Comment by rizomaa** [comment]
@lptn добра калі вы абновіце патрабаванні да асяродка

**Comment by alies-dev** [comment]
@rizomaa 
>@lptn добра калі вы абновіце патрабаванні да асяродка

залежнасці залезнасцяў складана кантраляваць, я абнавіў неабходную інфармацыію ў composer.json , цяпер класна было б праверыць: запусціць composer install на тваім асяродку. Калі усе ок -- то абнаўляем докі і закрываем issue

**Comment by alies-dev** [comment]
PS: цяпер усе звузілася да наступнага сэтапу
```json
{
   "platform": {
        "php": "^7.1.3",
        "ext-pdo": "*",
        "ext-curl": "*",
        "ext-json": "*",
        "ext-mbstring": "*"
    },
    "platform-dev": {
        "ext-zip": "*"
    }
}
```
Варта зазначыць што сярод патрабаванняў ніякай экзотыкі няма (як гэта было раней): усе гэтыя ext апроч можа быць ext-mbstring з'яўляюцца core ext -- ідут у камплекце з дэфолтавымі пастаўкамі PHP. ext-mbstring ж бадай самы папулярны з не каробачных ext і да таго ж выкарыстоўвацца ва усіх краінах з не-лацінкаю (то бок у нас усе хостэры маюць гэты ext)


## ext-pdo
https://www.php.net/manual/en/pdo.installation.php

PDO and the PDO_SQLITE driver is enabled by default as of PHP 5.1.0

## ext-curl
https://www.php.net/manual/en/curl.installation.php

Не ясна, здаецца не ідзе ў камплекце з PHP АЛЕ звычайна ідзе у камплекце з Linux дыстрыбуцівамі і іншымі зборкамі PHP

## ext-json
https://www.php.net/manual/en/json.installation.php

>As of PHP 5.2.0, the JSON extension is bundled and compiled into PHP by default.

## ext-mbstring
https://www.php.net/manual/en/mbstring.installation.php

>mbstring is a non-default extension. This means it is not enabled by default. You must explicitly enable the module with the configure option. 

## ext-zip
https://www.php.net/manual/en/zip.installation.php

#### Windows 
> As of PHP 5.3 this extension is built-in. Before, Windows users need to enable php_zip.dll inside of php.ini in order to use these functions.

#### Linux
Not default (але даволі папулярна)

**Comment by alies-dev** [comment]
Вынікі: на большасці сістэм нічога дадаткова да PHP ставіць не патрэбна (на прадакшане/хостынгах -- стопудняк). Але распрацоўшчыкам трэба быць упэўненым што стаяць `ext-mbstring`  + `ext-zip` (`composer install` пакажа памылкі калі іх няма ў сістэме)

**Comment by alies-dev** [comment]
@rizomaa 
Прачытай калі ласка мае апошнія 3 паведамленні тут і скаардынуй ўто далей рабіць. Мне падаецца што ня варта ўвагу завастраць на php extentions зусім: на хостынгах усе што трэба есьць, а распрацоўшчыкі ці ужо маюць усе усталяваным ці могуць паставіць самастойна (а калі выкарыстоўваць Docker дык і ставіць нічога апроч самога докера ня трэба). Калі ж раптам праблема у распрацоўшчыкаў будзе узнікаць (у тых якія не хочуць па нейкім прычынам выкарыстоўваць Doker)  -- то проста абновім FAQ для рапрацоўшчыкаў

Мы вядома ж можам пісаць php extentions у патрабаваннях але на маю думку гэта будзе проста пужаць людзей ("ай, складана, у мяне відаць гэта не стаіць на лакалкі ці хостынгу")

**Comment by rizomaa** [comment]
@lptn напішыце спіс патрабуемых пашырэнняў, калі гэта будзе у радок нікога не спужае, а можа сэканоміць горы часу на устаноку. 

пасля пераходу на докер кантэёнеры, можна будзе падумаць пра выдаленне гэтага, але насамрэч не, бо неяк жа самі докер кантэёнеры канфігураваць трэба, калі распрам мы і будзем перазбіраць

**Comment by alies-dev** [comment]
Гатова, тут можна глянуць

https://github.com/diglabby/doika/wiki/Устаноўка-для-Распрацоўшчыкаў#Тэхнічныя-патрабаванні-да-распрацоўкі


Гаўвага: докаў па усталяўцы дойкі для арганізацый яшчэ няма, я парпавіў толькі доку для распрацоўшчыкаў

**Comment by rizomaa** [comment]
дзякуй
