### ISSUE TITLE
Што трэба змяніць ва ўсталёшчыку. Асабліва пытанні лічацца доступаў.

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#253]
1. Неабходна вызначыць групу і карыстальніка для ўсіх файлаў модуля камандай: sudo chown -R www-data:www-data .

2. Неабходна улічыць бячпечную устаноўку sudo npm install node-sass --unsafe-perm на лакальную тэчку праектаў

3. Дадаць судо sudo cp .env.example .env і усюды дзе ёсць код. асабліва гэта актуальна, калі працуеш з хастамі не у дамаўняй дырэкторыі.

**Comment by nastyafrosty** [comment]
@Olya147 есть лі эті данные в докуентаціі?

**Comment by InaFK** [comment]
Неабходна абнавіць дакуменатцыю на выпадак, калі, пры разгортванні праекту лакальна пад macOC узнікае наступная "памылка" пры запуску каманды 
**sudo chmod 777 -R storage/** (п.6):
https://prnt.sc/qukkt7 
(тэчка "**storage**", відавочна, існуе).
 З чым гэта звязана і як "лекуецца"?

**Comment by rizomaa** [comment]
@InaFK прывітанне,
дзякуй за каментар і пытанне:
1. удакладніце, ці атрымалася паставіць?
2. чаму вы вырашылі зрабіць 777, ці спрабавалі іншыя правы 755, 775?
3. у якой тэчцы у вас ляжаць сама doika?

**Comment by InaFK** [comment]
@rizomaa прывітанне,
дзякуй за аказ

> удакладніце, ці атрымалася паставіць?
_не удалося да гэтай пары_
> чаму вы вырашылі зрабіць 777, ці спрабавалі іншыя правы 755, 775?
_спроба запусціць пад іншыя правамі плёну, нажаль, не дала.._
_а 777 рабіла, бо так у мануале_ - http://prntscr.com/qv3gom
> у якой тэчцы у вас ляжаць сама doika?
_сама doika скланіравана ў адвольную тэчку falansterWork  - http://prntscr.com/qv3i7i_

**Comment by rizomaa** [comment]
@InaFK falansterWork гэта тэчка віртуальнага хаста?
пакажыце як у вас вяглядае старонка ў браўзеры, з якой вы запускаеце дойка?

**Comment by InaFK** [comment]
@rizomaa 
так - http://prntscr.com/qv9ac8

**Comment by rizomaa** [comment]
@InaFK Звярніце ўвагу. Вы кіруецеся гайдам для докера, але робіце натыўную ўсталёўку.
Раю вам пачаць усё з нуля па спасылцы (з якарам на Лінукс):
https://github.com/diglabby/doika/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BB%D1%91%D1%9E%D0%BA%D0%B0-%D0%B4%D0%BB%D1%8F-%D0%A0%D0%B0%D1%81%D0%BF%D1%80%D0%B0%D1%86%D0%BE%D1%9E%D1%88%D1%87%D1%8B%D0%BA%D0%B0%D1%9E#linux
Прайдзіцеся па гэтаму гайду і напішыце, як яно=)

**Comment by InaFK** [comment]
@rizomaa 
На сёння спрабую яшчэ разабрацца, як зрабіць лакальнае разгортванне праекта з дапамогай Docker.

**Comment by rizomaa** [comment]
https://github.com/diglabby/doika/issues/690
