### ISSUE TITLE
Заліць чысты ларавел

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#258]
Скінуць сборку ларавел на стандарт і перанесці апошнія каміты туды.

**Comment by lptn** [comment]
@fr0zen 
а што за "зборка" Laravel, я пра зборкі не чуў раней

Як гэта "перенесці апошнія каміты"? Капі-паста кода?

**Comment by Tyuba4** [comment]
@lptn Адкажу за @fr0zen. Пад зборкай ён мае на ўвазе homestead. Але гэта не важна. Мы жадаем заліць "чысты" laravel, i перакінуць (капiпастнуць) ў яго нашыя роўты, маделi, адзін нясчасны кантроллер. Мы разумеем, што гэта не па фэншуе. Але падаецца гэта зменшыць час, які мы змарнуем на разблытанне макаронных вырабаў.

**Comment by lptn** [comment]
Дык можна ж амаль усе что наша заліць у адну тэчку, а роднае ларавеля -- у іншую. Для гэтага трэба толькі рут нэймспэйс дадаць новы ў кампозеры. Я магу за гэты таму узяцца. Але я так і не зразумеў пры чым тут homestead

**Comment by rizomaa** [comment]
@lptn пазначай імя (тэгуй) @Tyuba4 бо ён можа незащважаць твае каментары

**Comment by rizomaa** [comment]
@lptn @Tyuba4 @lptn @pro2s дадаў картку ў спрынт. яна зараз самая важная па прыярытэту. калі лкаска сфакусуйцеся на ёй. бо астатняя праца будзе стаяць

**Comment by fr0zen** [comment]
План:
1. Усталёўваем чыстую сборку. 
2. Дадаем бібліятэкі 
https://github.com/mcamara/laravel-localization

**Comment by fr0zen** [comment]
План:
- [ ] Усталёўваем чыстую сборку.
- [ ] Дадаем бібліятэкі 
https://github.com/mcamara/laravel-localization
https://github.com/LaravelCollective/html
https://github.com/martinlindhe/laravel-vue-i18n-generator
- [] Дадаем канфігі(env, travis, docker, eslint)
- [] Пераносім views+vue
- [] Пераносім апошнія змены
- [] Тэсцім

**Comment by lptn** [comment]
гатова!
