### ISSUE TITLE
Рэалізаваць вывад памылак рэкурэнтных плацяжоў пры валідацыі ў кліенскай часцы (віджэце)

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#26]
- [ ] 1.уведзена сума больш/менш, чым дазволена ў канфігу.
- [ ] 2. уведзене не сума
- [ ] 3. валідацыя мэйла
- [ ] 4. валідацыя тэлефона
+ сумежная задача https://github.com/diglabby/doika/issues/120

**Comment by lptn** [comment]
>вывод ошибок
вывад куды?)

**Comment by falanster** [comment]
@lptn тут мы маем на ўвазе, як будзе выглядаць вывад памылак для ахвярадаўцы у кліентскай часцы інтэрфейса.

Для адміна - гэта іншая задача.

Падсумую.
Зараз цалкам свадобна тэма "Апрацоўшчыка памылак" як для адмінскай часткі, так і для кіентскай часткі. У архітэктуры пуста на гэты конт: https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346135802429
Найбольш прыбліжаныя да гэтай тэмы карткі  #40 #24

**Comment by rizomaa** [comment]
@nastyafrosty ці можаш сюды залінкаваць свае макеты, каб арспрацоўшчыкі маглі дадаць?

**Comment by rizomaa** [comment]
Трэба абмеркаваць:

### Першы від памылкі

1. Калі проціць няправільныя дзадзеныя.
2. Няма грошай на карцвы.
3. Тэхнічныя збоі.

Біпэйд можа даслаць націфікейшн.
Рэдырэкт (які мы зададзім) - і напіша статус аперацыі. (success, ...)

### Другі від памылкі

1. Няма грошай.
2. Картка сцякла.

Можна адзначаць памылкі ў адмінцы.

**Comment by Tyuba4** [comment]
@fr0zen Тут наша совместная задача, надо это будет обсудить

**Comment by lptn** [comment]
```
### Першы від памылкі
1. Калі проціць няправільныя дзадзеныя.
2. Няма грошай на карцвы.
3. Тэхнічныя збоі.

Біпэйд можа даслаць націфікейшн.
Рэдырэкт (які мы зададзім) - і напіша статус аперацыі. (success, ...)
```

тут справа ідзе пра сінхроннае узаемадзеянне з PG, так? Адпаведна вывад памылак ніяк не звазан з РЭКУРЭНТНАСЦЮ

```
### Другі від памылкі
Праз месяц, напрыклад:

1. Няма грошай.
2. Картка сцякла.

Можна адзначаць памылкі ў адмінцы.
```

Такія штукі толькі імэйлам ці СМС ці іншымі каналамі можам дасылаць, так? Тут ужо рэкурэнтнасць адчуваецца)

**Comment by fr0zen** [comment]
@fr0zen зрабіць адказы аб памылках больш відавочнымі. Большасць варыянтаў у каменце вышэй.

**Comment by rizomaa** [comment]
@fr0zen 

удакладні, што не відавочна?

**Comment by rizomaa** [comment]
@Olya147 як у нас апрацощваюцца гэтыя памылкі?

@lptn @fr0zen

**Comment by nastyafrosty** [comment]
@Olya147 
@lptn @fr0zen  это блокирующая задача? или уже решено что-то?

**Comment by alies-dev** [comment]
@nastyafrosty 
@rizomaa 

>як у нас апрацощваюцца гэтыя памылкі?

>это блокирующая задача? или уже решено что-то?

Я да сяго часу не разумею які з межах гэтай задачы рабіць

Інфармацыю пра няўдалыя транзакцыі мы запісваем у БД, дасылаем імэйлы пра няўдалыя рэкурэтныя плацяжы (ініцыяваныя шлюзам), а @fr0zen  рэалізваў старонку дзе паказвае памылку калі транзакцыя ініцыявана карыстальнікам. Не думаю што штосці яшчэ варта рабіць тут

То бок мне здаецца што усе зроблена і задачу зачыняем

**Comment by rizomaa** [comment]
@lptn  што наконт:
Клиентска частка
1.уведзена сума больш/менш, чым дазволена ў канфігу.
2. уведзене не сума
3. валідацыя мэйла
4. валідацыя тэлефона

https://github.com/diglabby/doika/issues/120

**Comment by alies-dev** [comment]
@rizomaa 
Зразумеў. Проста лэйбл задачы стаіць "бэкэнд/backend" а па факту задача для франта толькі, адпісваюся

**Comment by rizomaa** [comment]
@lptn дзякуй
