### ISSUE TITLE
Выправіць пераклад у адмінскай частцы

### ISSUE THREAD

**Issue by KsenjaV** [diglabby/doika#261]
Неабходна тэставанне пераклада адмінскай частцы модуля Doika.

**Comment by KsenjaV** [comment]
прыблізны час працы 2-2,5 гадзіны.

**Comment by Olya147** [comment]
займёт не более 1 часа

**Comment by KsenjaV** [comment]
@Olya147 
Што патрэбна зрабіць:
Зайсці на адмінскую частку Doika і пратэставаць пераклад рускай, англійскай і беларускай мовы.
1) наяўнасуь перакладу
2) правільнасць перакладу
3) супадзенне перакладу

**Comment by nastyafrosty** [comment]
@Olya147 как тут дела? можно закрыть карточку?

**Comment by ghost** [comment]
@KahjuksEi @maxmatoha @fr0zen Нужно исправить названия вкладок:
![1](https://user-images.githubusercontent.com/46268205/59598782-ac1daa00-9105-11e9-895b-40fea53650fa.png)
![2](https://user-images.githubusercontent.com/46268205/59598787-b049c780-9105-11e9-9a31-6ba8e15bf142.png)
 
Исправить опечатки:
![FAQ (опечатка)](https://user-images.githubusercontent.com/46268205/59598986-20584d80-9106-11e9-922d-a0a9567d9a36.png)
![Авторизация (опечатка)](https://user-images.githubusercontent.com/46268205/59598993-23ebd480-9106-11e9-82aa-5628e9696d2e.png)

**Comment by KahjuksEi** [comment]
ок, сделаем

**Comment by KahjuksEi** [comment]
готово, через какое то время появится ПР

**Comment by ghost** [comment]
@KahjuksEi  нужно поправить перевод.
![11](https://user-images.githubusercontent.com/46268205/60193320-1dfd9e00-9840-11e9-8b93-513cdd18c822.png)

**Comment by ghost** [comment]
Нужно исправить стр. восстановления пароля:
![06-07-19](https://user-images.githubusercontent.com/46268205/60757418-05953c80-a013-11e9-9014-a73aa65cbae5.png)

**Comment by ghost** [comment]
Исправить название вкладок: 
![261 (19-07)](https://user-images.githubusercontent.com/46268205/61494907-2ae55b80-a9c0-11e9-8f0d-9535934a1696.png)

**Comment by AlekseyKrivitskiy** [comment]
@rizomaa 
![image](https://user-images.githubusercontent.com/59744681/73196708-20f79e80-4141-11ea-96e1-b88f3f166cb3.png)
Сделал перевод сообщения об успешном выполнении
Почему-то нету текста остальных элементов -> добавил текст
![image](https://user-images.githubusercontent.com/59744681/73196923-89468000-4141-11ea-942b-b0e2264af3ca.png)

**Comment by AlekseyKrivitskiy** [comment]
![](https://sun9-5.userapi.com/c205720/v205720208/4dcb9/SSWlr46UuD8.jpg)
Удалося зрабіць пераклад для старонкі аднаўлення пароля, затрымаўся на старонцы апавяшчэнняў.

Пачаў глыбей разбірацца і зразумеў што там яшчэ і ад мовы залежнасці ёсць. А я выправіў у тым, што першае знайшоў.

У файлах беларускай мовы пераклады прысутнічаюць, але не адлюстроўваюцца на старонцы.

**Comment by rizomaa** [comment]
@AlekseyKrivitskiy ці ўсе імёны ключоў супадаюць?

**Comment by rizomaa** [comment]
@KuhniaDruggist наступная картка.

Актуальны толькі праверка 2 пунктаў гэтага спісу (астатняе ігнорым пакуль):
- [ ] 1. https://user-images.githubusercontent.com/46268205/59598986-20584d80-9106-11e9-922d-a0a9567d9a36.png
- [ ] 2. https://user-images.githubusercontent.com/46268205/59598993-23ebd480-9106-11e9-82aa-5628e9696d2e.png

**Comment by KuhniaDruggist** [comment]
@rizomaa Не понял что нужно сделать? Все ошибки, указанные на скриншотах исправлены.

**Comment by rizomaa** [comment]
@KuhniaDruggist выдатна, тады чэкніце кожны пункт спіса https://github.com/diglabby/doika/issues/261#issuecomment-627306670
і зачыняйце картку

**Comment by KuhniaDruggist** [comment]
@rizomaa 

![Screenshot_109](https://user-images.githubusercontent.com/48412681/81702956-a2ff9f00-9474-11ea-981d-bc163bf94980.png)
![Screenshot_108](https://user-images.githubusercontent.com/48412681/81702973-a85ce980-9474-11ea-8271-48308737f4c8.png)

**Comment by rizomaa** [comment]
@KuhniaDruggist  добра.
можаце зачыніць картку?
