### ISSUE TITLE
Рэалізаваць CRUD для старонкі канфігурацыі модуля

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#262]
Роут http://it3donate-landing.falanster.by/doika/en/admin/paymentSystems
- [ ] Рэалізаваць магчымасць захоўваць наладкі ў базе
- [ ] Рэалізаваць выбарку дадзеных із базы

RTB: https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346287455693

**Comment by rizomaa** [comment]
@fr0zen гэта крутаю задача. калі ласка візуалізуй яе) магчыма каго яшчэ задзейнічаць асабліва па часцы прымянення патэрнай праеткавання для падключэння рохных плацёжных сустэмаў @lptn @pro2s

**Comment by lptn** [comment]
@fr0zen 
шмат наладаў будзе?

https://github.com/spatie/valuestore - есьць вось такі пакет (і падобныя іншыя) якія захоўваюць у ФАЙЛ (json)

Такжа есьць пакеты якія дазволюць захоўваць у базу, але перад тым як выбраць, распавядзіце калі ласка што мы туды збіраемся захоўваць

**Comment by lptn** [comment]
Яшчэ вось такі пакет есьць: https://github.com/efriandika/laravel-settings

што цікава, у яго есьць магчымасьць фалбэку дадзеных ад `config()`
