### ISSUE TITLE
Пачысціць роўты

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#271]
На дадзены момант у нах іх машмат, а разам з лакалізацыямі гэта переўтвараецца у грымучую сумесь

**Comment by lptn** [comment]
@fr0zen 
можаш сказать што з роўтам зараз важна а што можна павыладяць?

**Comment by fr0zen** [comment]
@lptn вось такая схема роутаў мне патрэбна у ідэале. Мне падаецца не занадта шмат. Але мне у vue-роутэре змяніць не складана, калі спатрэбіцца

Admin part:

#Login system actions
-[] /doika/<locale_code>/admin/login
-[] /doika/<locale_code>/admin/logout
-[] /doika/<locale_code>/admin/logout
-[] /doika/<locale_code>/admin/password/reset

#Campaigns table actions
-[] /doika/<locale_code>/admin/campaigns
-[] /doika/<locale_code>/admin/campaigns/create
-[] /doika/<locale_code>/admin/campaigns/<campaign_id>/edit
-[] /doika/<locale_code>/admin/campaigns/<campaign_id>/delete

#Payments table actions
-[] /doika/<locale_code>/admin/payments
-[] /doika/<locale_code>/admin/payments/<payment_id>

#Module configuration actions
-[] /doika/<locale_code>/admin/config/paymentSystems
-[] /doika/<locale_code>/admin/config/layout
-[] /doika/<locale_code>/admin/config/notifications

#User management actions
-[] /doika/<locale_code>/admin/users
-[] /doika/<locale_code>/admin/users/create
-[] /doika/<locale_code>/admin/users/<user_id>/edit
-[] /doika/<locale_code>/admin/users/<user_id>/delete

#FAQ page
-[] /doika/<locale_code>/help/

#Feedback page
-[] /doika/<locale_code>/feedback/


Widget part:

#Widget actions
-[] /doika/<locale_code>/campaign/<campaign_id>
-[] /doika/<locale_code>/campaign/<campaign_id>/donate

**Comment by lptn** [comment]
Заблакавана вось гэтай іш'ю: "Прапанова: Выкарыстоўваем тэрмін `Dashboard` замест `Backend`" #236 (не хачу зрабіць а пасля перарабліваць)

**Comment by lptn** [comment]
@fr0zen 
звярні увагу, мы перайменавалі мадэлі і адпаведна трэба змяніць роўты:
 1. user -> donator
 1. payment -> transaction

+
1. admin -> dashboard


# Http methods
давай на прыкладзе кампаніі разбярэм якія роўты у нас будуць

1.   /doika/{locale}/dashboard/campaigns
2.   /doika/{locale}/dashboard/campaigns/create
3.   /doika/{locale}/dashboard/campaigns/{campaign_id}/edit
4.   /doika/{locale}/dashboard/campaigns/{campaign_id}/delete

Я бачу што мы не выкарыстоўваем http method амаль зусім, замест гэтага пішам постфіксы: "create", "edit", "delete". Я прапаную выкарыстоўваць REST API падыход:

1. GET. URL мусіць быць `/doika/{locale}/dashboard/campaigns` (у нас тут усе правільна)
2. POST. URL мусіць быць `/doika/{locale}/dashboard/campaigns`
3. PUT. URL мусіць быць `/doika/{locale}/dashboard/campaigns/{campaign_id}`
4. DELETE. URL мусіць быць `/doika/{locale}/dashboard/campaigns/{campaign_id}`

Што думаеш?

Калі згодны, ці можаш новым пастом адпісаць роўты якія табе патрэюны на франце?

**Comment by fr0zen** [comment]
@lptn прапанова крутая дарэчы. Зараз шляхі ўжо моцна расцягнуліся

**Comment by fr0zen** [comment]
@lptn 

# Dashboard
## Login system actions
- [ ] [GET]: /doika/{locale}/dashboard/login
- [ ] [GET] /doika/{locale}/dashboard/logout
- [ ] [GET] /doika/{locale}/dashboard/password/reset
- [ ] [POST] /doika/{locale}/dashboard/password/reset

## Campaign actions
- [x] [GET]: /doika/{locale}/dashboard/campaigns
- [ ] [POST]:  /doika/{locale}/dashboard/campaigns
- [ ] [PUT]: /doika/{locale}/dashboard/campaigns/{campaign_id}
- [x] [DELETE]: /doika/{locale}/dashboard/campaigns/{campaign_id}

## Transaction actions
- [x] [GET]: /doika/{locale}/dashboard/transactions
- [x] [GET]: /doika/{locale}/dashboard/transactions/{payment_id}
- [ ] [POST]: /doika/{locale}/dashboard/transactions

## Configuration actions
- [ ] [GET]:  /doika/{locale}/dashboard/config/paymentSystems
- [ ] [PUT]:  /doika/{locale}/dashboard/config/paymentSystems
- [ ] [GET]:  /doika/{locale}/dashboard/config/layout
- [ ] [PUT]:  /doika/{locale}/dashboard/config/layout
- [ ] [GET]: /doika/{locale}/dashboard/config/notifications
- [ ] [PUT]:  /doika/{locale}/dashboard/config/layout

## User management actions
- [x] [GET]: /doika/{locale}/dashboard/donators
- [ ] [GET]: /doika/{locale}/dashboard/donators/{donator_id}
- [ ] [POST]: /doika/{locale}/dashboard/donators
- [ ] [PUT]: /doika/{locale}/dashboard/donators/{donator_id}
- [x] [DELETE]: /doika/{locale}/dashboard/donators/{donator_id}

# Widget

## Campaign actions
- [ ] [GET]: /doika/{locale}/campaigns/{campaign_id}
- [ ] [GET]: /doika/{locale}/campaigns/{campaign_id}/donate
- [ ] [POST]: /doika/{locale}/campaigns/{campaign_id}/donate

## FAQ page
- [ ] [GET]:  /doika/{locale}/help

## Feedback page
- [ ] [GET]:  /doika/{locale}/feedback
- [ ] [POST]:  /doika/{locale}/feedback

**Comment by lptn** [comment]
@fr0zen 
Здаецца зрабіў пустышкі амаль для усіх роўтаў, апроч "Configuration actions". Думаю разглядзіць гэты функцыянал асобна і дадаць мадэль переад рэалізацыяй роўтаў. З чаго мне пачаць вывучэнне - RTB?

Ашчэ вось па гэтым пытанні - што тут тут чакаеш на уваход і выхад
```
 [GET]: /doika/{locale}/campaigns/{campaign_id}/donate
 [POST]: /doika/{locale}/campaigns/{campaign_id}/donate
```
Машчыма POST /donate мы хацеў для функцыянала які рэалізаваны вебхук хэндлерам, глядзі Add webhook handler for "donated" event from bePaid #315

Ну і апошняе: да сяго часу мне зсім не ясна што вартаць будуць ледзь не усе роўты: html, json ці кавалкі html. Калі тут табе трэба дапамога ў рашэнні - можам выдзеліць час

**Comment by lptn** [comment]
Закрываю, канфігі будзем рабіць тут: Рэалізаваць CRUD для старонкі канфігурацыі модуля #262
