### ISSUE TITLE
Перагенераваць composer.lock пад новыя залежнасці

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#273]
Згодна https://travis-ci.org/diglabby/doika/jobs/503749024 стары package.lock утрымлівае у сябе стары набор залежнасцяў. Прапаную выдаліць, аднавіць, заліць. @lptn @Tyuba4 што думаеце? Тэсты не праходзяць на php < 7.1.8

**Comment by lptn** [comment]
насамрэч прамылка выклакана Laravel Dusk v5 які патрэбны толькі для тэставання

Ен у сваю чаргу хоча Carbon v2 а той php ^7.1.8 || ^8.0

Я выправіў ;)
