### ISSUE TITLE
Стварыць гайд па усталеўцы праз Docker

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#276]
Апісаць, як выкарыстоўваць batch і make файлы для хуткай усталеўкі модуля на лакальных машынах.

**Comment by lptn** [comment]
Вось тут быў аналагічны issue https://github.com/diglabby/doika/issues/172 (закрываю яго як дублікат)

**Comment by fr0zen** [comment]
@lptn @Tyuba4 дадаў гайд па запуску Dосker-кантэйнераў, можам тэсціць

**Comment by lptn** [comment]
@fr0zen 
>@lptn @Tyuba4 дадаў гайд па запуску Dосker-кантэйнераў, можам тэсціць

Добра б адразу дадаваць спасылку ;)
