### ISSUE TITLE
Проблемы с artisan migrate

### ISSUE THREAD

**Issue by KahjuksEi** [diglabby/doika#286]
При установке текущей версии модуля в консоли после команды $ php artisan migrate
получаем проблему, аналогичное уже происходило https://github.com/diglabby/doika/issues/165
![QIP Shot - Screen 719](https://user-images.githubusercontent.com/39082880/54075187-699a3500-42ad-11e9-95ce-6bd4fdf7cca1.png)

**Comment by lptn** [comment]
@KahjuksEi 
Мы паламалі свядома міграцыі, трэба выбаліць існуючыя табліцы і стварыць новыя, робіцца гэта камандай 

`php artisan migrate:fresh`

Дарэчы мы яшчэ будзем ламаць міграцыі, так што запомні каманду)

**Comment by lptn** [comment]
PS: Закрывай іш'ю калі праблема вырашана

**Comment by KahjuksEi** [comment]
Проблема не решена
![QIP Shot - Screen 720](https://user-images.githubusercontent.com/39082880/54083706-6d26ce00-4338-11e9-981b-b4ab2df89e7f.png)

**Comment by lptn** [comment]
@KahjuksEi 
Запусці з ключом `-v` калі ласка і спакіруй увесь стэктрэйс памылкі: `php artisan migrate:fresh -v`

Але парад гэтым калі ласка правер каннэнт да БД  -- ты нічога не мяняў ў падключэнні ці канфігураціі? З гэтага кароткага паведамлення пра памылку бачна што дойка не можа з БД злучыцца

**Comment by KahjuksEi** [comment]
С ключом установилось без проблем, инфу по нему добавил в вики. Но при запуске происходит странное:
![image](https://user-images.githubusercontent.com/39082880/54084252-8b43fc80-433f-11e9-81a5-3d0641b2d504.png)

**Comment by lptn** [comment]
>Но при запуске происходит странное:

 так трэба (@fr0zen  часова памламаў  каб зрабіць яшчэ лепей)
