### ISSUE TITLE
Абнавіць мадэль Campaign

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#290]
На дадзены момант гэтая мадэль не мае усіх палеў якія мы чакаем на фронендзе (асабліва звязаных х кастамізацыяй выгляду)

Вось даступныя палі на дадзены момант: https://github.com/diglabby/doika/blob/123952d28b8ee3b3fe2b1de6e19de8dc2a1aecef/database/migrations/2018_12_20_112906_create_campaigns_table.php#L16-L26

Так жа назвы некаторых палеў выглядаюць дзіўнымі (`title_picture_url `) і не прадугледжана мягкае выдаленне кампаніі (SoftDelete)

**Comment by lptn** [comment]
@fr0zen 
можаш падзяліцца "жадалкамі" да кампаній?

**Comment by lptn** [comment]
@fr0zen 
>можаш падзяліцца сваімі "жадалкамі" да кампаній?

яшчэ актуальна, чакаю!

**Comment by fr0zen** [comment]
@lptn @Tyuba4 яшчэ прапаную дадаць наступныя палі
 `
$table->integer('layout_id'); //Preset of styles for company
$table->string('terms_of_use'); //Custom "terms of use text" (appears in popup)
$table->string('donate_amount'); //Array to represent donation values(Digits inside buttons on widget)
`

**Comment by lptn** [comment]
@fr0zen 
> layout_id

Штоз за ID гэта будзе? Ці можам адтэрмінаваць такую фічу калі яна складаная (лепей сфакусавацца на болей важным) 

> terms_of_use

у якім фармаце: plain text ці HTML?

> donate_amount

Назва не падабаецца (адзіночны лік). Што думаеш пра `amount_preset`?

**Comment by fr0zen** [comment]
@lptn 
`layout_id` - так, гэта на перспектыву
`terms_of_use` - HTML
`amount_preset` - падабаецца, але фіча таксама больш на перспектыву пакуль

**Comment by lptn** [comment]
@fr0zen 
добра, давай дададзім палі `layout_id ` і `amount_preset ` як будзе патрэба, каб не было хвастоў  такіх -- яны спіхалагічна ствараюць адчуванне нязрэласці прадукта і негатыўна адбіваюцца на якасці кода

Іх дадаць не складана, калі трэба будзе -- адразу ж дададзім. Ну а terms_of_use трэба зараз, так?

**Comment by fr0zen** [comment]
@lptn так, terms зараз патрэбны, з астатнім поўнасцю згодны

**Comment by lptn** [comment]
@fr0zen 
А terms_of_use на адной мове будзе?

**Comment by lptn** [comment]
@fr0zen 
Леш, слухай, ці існуе патрэба переакладаць іншыя мадэлі як гэта робім з кампаніяй? Проста існуе пакет https://github.com/spatie/laravel-translatable (і яшчэ адзін падобны) які дазваляе гэта рабіць лягчэй. Ім варта карыстацца калі у нас будзе болей чым адна перакладаемая мадэль. Пакуль жа усе файна.
