### ISSUE TITLE
Выправіць канфіг на Scrutinizer CI

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#293]
На дадзены момант у нас не наладжаны канфіг Scrutinizer CI (а менавіта база дадзеных), таму мы атрымліваем такія памылкі:
https://scrutinizer-ci.com/g/diglabby/doika/inspections/04efb180-9af6-495e-a69c-58043c901d34

На дадзены момант я гэтага зрабіцт не магу -- адсутнічаюць правы, патрэюна дапамога @rizomaa

**Comment by Tyuba4** [comment]
@fr0zen У цябе раптоўна няма такіх правоў?

**Comment by fr0zen** [comment]
@lptn @Tyuba4 мне здаецца падыходзяць толькі owner правы? У мяне такіх дакладна няма

**Comment by lptn** [comment]
так, трэба Міхась з правамі

Створым на scrutinizer-ci арганізацыю і раздадзім правы актыўным удзельнікам

**Comment by rizomaa** [comment]
![Selection_001](https://user-images.githubusercontent.com/9870374/54717533-67678e80-4b69-11e9-8b41-706f61f9a5e8.png)

такое выдаляю

**Comment by rizomaa** [comment]
@lptn

**Comment by lptn** [comment]
тут прыбраў https://github.com/diglabby/doika/settings/branch_protection_rules/4001999
цупер яго няма
![image](https://user-images.githubusercontent.com/5278175/54810711-d511d880-4c97-11e9-83a8-09ad28ad42fb.png)

Ура! Закрываю!
