### ISSUE TITLE
Установленный модуль 1.3 не открывается

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#299]
## Дзеянні каб паўтарыць памылку
1. Установить модуль по инструкции (для Win) https://github.com/diglabby/doika
## Апісанне бага
Модуль не открывается. Вместо него появляется страница со списком ошибок.
![image](https://user-images.githubusercontent.com/46268205/54146115-566b9e80-4440-11e9-8b35-88825f1c0e5a.png)

## Тэставыя ўмовы
- Версія Doika: 1.3
- Платформа і версія: Windows10
- Браўзер і версія: Chrome/Opera

**Comment by KahjuksEi** [comment]
Не могу вспомнить из за чего конкретно, но такое обычно вылетает при неправильной установке модуля. Композер не отработал или еще что..

**Comment by lptn** [comment]
Я амаль упэщнены што гэта часовыя непаразуменни звязаныя глабальным выдаленнем кода (Пачысціць роўты #271). Вярнуся да гэтай issue пасля #271 

На дадзеный момант думаю амаль ниякия рощты не працуюць

**Comment by lptn** [comment]
@Olya147 
Ну як апошняя версія сябе паходзіць?

**Comment by Olya147** [comment]
@lptn  По-прежнему не запускается. 
![404](https://user-images.githubusercontent.com/46268205/54497262-8ec02080-4909-11e9-8f05-7692ce6c50b6.png)

**Comment by lptn** [comment]
@Olya147 
Дзякуй, цяпер гэта ужо іншая праблема, на яе есьуь issue: Пачысціць роўты #271
