### ISSUE TITLE
Фронтэнд. Реализовать обработчик ошибок страниц рекурентых платежей

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#30]
Правалідзіраваць палі (фронтэнд).

На стронцы уводу дадзеных 
https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346136710150

**Comment by KahjuksEi** [comment]
Напишите плиз, где в коде проекта искать эти данные.

**Comment by rizomaa** [comment]
@KahjuksEi глядзеў спаслыку вышэй?

**Comment by KahjuksEi** [comment]
@rizomaa глядел, думаю эффективнее было бы писать путь до файла в проекте, по возможности конечно.

**Comment by rizomaa** [comment]
> @rizomaa глядел, думаю эффективнее было бы писать путь до файла в проекте, по возможности конечно.

чаму сам не знаходзіш? @KahjuksEi

**Comment by KahjuksEi** [comment]
@rizomaa я не понимаю, где это окно находится и как его вызвать.

**Comment by rizomaa** [comment]
@KahjuksEi 
1. ці глядзеў гэты лінк? https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346137809254
2. ці паставіў сабе модуль?
3. ці бачыш кленсткую частку на пастаўленым модулі?

**Comment by fr0zen** [comment]
@KahjuksEi [тут](https://github.com/diglabby/doika/tree/dev/resources/js/client/views) асноўныя шаблоны

**Comment by KahjuksEi** [comment]
@fr0zen благодарю, вот так бы сразу😊 . Но как можно повесить валидацию, для каждого поля по отдельности, если они выводятся через список?
![qip shot - screen 712](https://user-images.githubusercontent.com/39082880/52897545-f427d100-31e6-11e9-86bd-d7a35c69b904.png)

**Comment by fr0zen** [comment]
@KahjuksEi кожнаму полю можна сгенераваць свой id, калі патрэбная розная логіка валідацыі. Для якіх выпадкаў думаеш зрабіць валідацыю зараз?

**Comment by KahjuksEi** [comment]
Ок, понял в каком направлении работать.

**Comment by KahjuksEi** [comment]
@fr0zen  Нашел такое решение,
1. как его протестить?
2. нужно ли массив errors объявлять в data или оставлять в теле функции?
3. правильное ли у меня имя функции, если в шаблоне написано :id="`type-${type}`"?
![qip shot - screen 717](https://user-images.githubusercontent.com/39082880/53146583-d4f9bc80-35b5-11e9-9352-79f0822bfc0b.png)

**Comment by fr0zen** [comment]
@fr0zen ping ping

**Comment by rizomaa** [comment]
@fr0zen ты сам сябе пінгаваў? або гэта бот?

**Comment by fr0zen** [comment]
@lptn мяркую, што картку можна зачыніць, на бэке мне падаецца ўсе есць у плане памылак. Усе патрэбныя адказы аддаюцца.

**Comment by alies-dev** [comment]
@fr0zen 
так зачыняем!

**Comment by rizomaa** [comment]
@fr0zen @lptn толькі для рэкурэнтных зараз апрацоўвае ці наогул?

**Comment by rizomaa** [comment]
@lptn пытанне, вышэй

**Comment by rizomaa** [comment]
Дублюе задачу https://github.com/diglabby/doika/issues/26
