### ISSUE TITLE
Модуль "Апісанне спосабу аплаты" - прапушчаны коскi памiж словамi.

### ISSUE THREAD

**Issue by andrey1999999** [diglabby/doika#306]
У тэксце апiсання спосабу аплаты прапушчаны коскi памiж словамi.
## Дзеянні каб паўтарыць памылку

1.Прайсцi па ссылцы: http://it3donate-landing.falanster.by/
2.Пракруцiць унiз да укладкi «Падтрымай лiчбавую майстэрню».
3.Ва укладцы «Падтрымай лiчбавую майстэрню» нацiснуць «Апiсанне спосабу аплаты»

![image](https://user-images.githubusercontent.com/30193031/54300899-e2abcc00-45ce-11e9-859f-ef44d41732d8.png)

## Тэставыя ўмовы

- Версія Doika: 1.3
- Платформа і версія: Windows10
- Браўзер і версія: Chrome

Actual result: 
 У тэксце апiсання спосабу аплаты прапушчаны коскi памiж некаторымi словамi.

Expected result:
У абазначаных месцах дабавiць коскi.

**Comment by Olya147** [comment]
Здесь ничего не нужно исправлять (https://ru.wikipedia.org/wiki/PCI_DSS ).
