### ISSUE TITLE
Рэалізваць webhook handler на стварэнне Donate/Transaction для bePaid

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#311]
route `webhooks.bepaid.donated`

**Comment by lptn** [comment]
@fr0zen 
@rizomaa 
@Tyuba4 
Хлопцы, у межах гэтай задачы прапаную перайменаваць мадэль Transaction у Donate. 

Імя Transaction было маей ідэяй, але тады я думаў што мы будзем запісываць дадзены пра усе транзакцыі, але цяпер я бачу што мы будзе пісаць толькі пра ПАСПЯХОВЫЯ данэйты. Ці я памыляюся і будзем ствараць запісы ў БД для любыя аперацыі з грашыма (нават не паспяховымі)? Гэта важнае пытанне, адкажыце калі ласка

**Comment by fr0zen** [comment]
@lptn на мой погляд трэба пакінуць яе пад Transaction. Пакуль імплементуем толькі паспяховыя плацяжы, потым дойдзем да агульнай статыстыкі, не прыйдзецца вяртаць на Transaction назад)

**Comment by Tyuba4** [comment]
@lptn @fr0zen Згодзен з Лезхай.
