### ISSUE TITLE
Прапанова: Перайменаваць dev галіну ў develop

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#313]
Чаму: так прынята ў іншым свеце (https://nvie.com/posts/a-successful-git-branching-model/ ці https://www.digitalocean.com/community/tutorials/how-to-use-git-branches)

Што трэба будзе мяняць: докі (я зраблю)

**Comment by lptn** [comment]
@fr0zen 
@Tyuba4 
@rizomaa 
цікава ваша меркаванне

**Comment by fr0zen** [comment]
@lptn я не супраць, але можа заўтра стандартам стане dev? Ці гэта раздражняе суадносна с часам, які трэба патраціць на змены ў дакументацыі?

**Comment by lptn** [comment]
@fr0zen 
стандартам здаецца становицца адсутнасць dev/develop зусім: можна мець рэлізы (git tags) для фіксаваных версій, master для бягучай версіі ў распрацоўцы і фіча-галіны якія мержыць праз ПР

А докі... іх жа легка правіць вельмі, "знайсці і замяніць", прчым вікі гэта д таксама репа: https://github.com/diglabby/doika.wiki.git :  можна склоніць і выкарыстаць find and replace

**Comment by lptn** [comment]
done!
