### ISSUE TITLE
Прапанова: Дамовіцца пра структура View файлаў

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#314]
@lptn па вьюсах прапаную усе прапановы пакідаць тут:
Як глядзіш на наступны варыянт?
```
resourses
	assets
		dashboard
			images
			fonts
			...			
		widget
			images
			fonts
			...		
		
	js
		dashboard
		widget	
		vendor	
	lang
		be
		en
		ru	
		...	
	sass	
		dashboard
		widget
		vendor	
	views
		dashboard
			auth
			emails
			errors
			layouts
				partials
			includes
			pages
		widget		
			errors
			layouts
				partials
			includes
			pages
	vendor	
	components
```

**Comment by lptn** [comment]
@fr0zen 
Добра, але малыя заўвагі па views:

## views
![image](https://user-images.githubusercontent.com/5278175/54498143-29bdf800-4914-11e9-83fe-342a41030a08.png)


`resources/sass/vendor` - пад "vendor" распрацоўшчыкі звычайна разумеюць 3rd party файлы, а  у нас там НАШЫ ляжаць

**Comment by fr0zen** [comment]
Выдаляем includes. components

**Comment by lptn** [comment]
Здаецца дамовіліся, закрываю
