### ISSUE TITLE
Рэалізаваць аўта-дэплоймент на тэставыя асяродкі (CD)

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#319]
## Сумежнае
 - Распрацоўка. Арганізаваць працэс стварэння рэлізаў на сэрверы і гітхабе. #84
 - Версіянаванне рэлізаў #160
_____________
@rizomaa 
Для гэтай задачы мне патрэбна ведаць:
 - Умовы пры якіх робім дэплоймент (пуш у `develop`, новы git tag/github release)
 - Куды мы заліваем змены (тэставыя сайты)
 - Любыя іншыя жадалкі

## Сэрверныя дадзеныя
https://trello.com/c/gaUoN6ur/109-%D0%BA%D0%B0%D1%80%D1%8B%D1%81%D0%BD%D1%8B%D1%8F-%D1%81%D0%BF%D0%B0%D1%81%D1%8B%D0%BB%D0%BA%D1%96-%D0%BF%D0%B0-%D0%BF%D1%80%D0%B0%D0%B5%D0%BA%D1%86%D0%B5

**Comment by fr0zen** [comment]
@lptn @Tyuba4 бачу наступную схему: Калі пушым у dev -> код забіраецца на наш сэрвер і разгортваецца там (для візуальнага тэставання и пад дэма-дамен)
Калі робім гітхаб рэліз -> збіраем усе неабходнае ў архіў і падстаўляем пад спасылку на лэндынгу. Як на такое глядзіце?

**Comment by lptn** [comment]
@fr0zen 
Я не супраць, але я ж зусім не ня ведаю якія у нас тэставыя дамены есьць, якія магчымасці і нават якія патрабаванні

Я думаю што план мінімум ты правільна агучыў: трэба мець сайт куды мы аўтаматычна можам разгануць
 - `develop` галіну
 - `master` галіну (яна ж апошні рэліз)

Дадаткова было б добра мець яшчэ адзін інстанц на якія мы можам легка тэсціць нейкі любы іншы брэнч перад тым каб уліць у develop

**Comment by rizomaa** [comment]
@lptn прывітанне,

1. Дамен табе шарылі некалькі разоў. Трымай картку, там усё па палічках раскладзена https://trello.com/c/gaUoN6ur/

У астатнім цалкам як сказаў @fr0zen 

2. Кожны пул рэквэст у dev робіць дэплоймэнт на тэставы дамен.
3. Рэлізы пасля тэгавання рэпазіторыя.

@fr0zen ці у наснеяк інакш зараз працуе?

**Comment by lptn** [comment]
@rizomaa 
>Кожны пул рэквэст у dev робіць дэплоймэнт на тэставы дамен.

гэта не будзе працаваць, у нас УЖО есьць выпадкі калі у нас некалькі ПР адначасова, але я памятаю размову, зробім пакуль як прасцей

**Comment by rizomaa** [comment]
@lptn адначасова, не можа быць.

**Comment by lptn** [comment]
@rizomaa 
>@lptn адначасова, не можа быць.

Прабач, не зразумеў. У нас на мінулым тыдні было 6 ПР адначасова

**Comment by fr0zen** [comment]
> @lptn прывітанне,
> 
> 1. Дамен табе шарылі некалькі разоў. Трымай картку, там усё па палічках раскладзена https://trello.com/c/gaUoN6ur/
> 
> У астатнім цалкам як сказаў @fr0zen
> 
> 1. Кожны пул рэквэст у dev робіць дэплоймэнт на тэставы дамен.
> 2. Рэлізы пасля тэгавання рэпазіторыя.
> 
> @fr0zen ці у наснеяк інакш зараз працуе?
> 
> зы
> @lptn усё дадатковае можна абмеркаваць калІ зробім рэфактарынг і ўвойдзем з спакойны працэс распрацоўкі

@lptn вышэй @rizomaa апісаў схему. "Рэлізы" раней збираліся па мержам ў майстар. Пакуль не бачу, як нам аўтаматызаваць тэставанне галін, каб было зручна.

**Comment by rizomaa** [comment]
Напішы, што значыць у цябе адначасова? @lptn

**Comment by lptn** [comment]
@rizomaa 
>Напішы, што значыць у цябе адначасова? @lptn

напрыклад у адну гадзіну

**Comment by rizomaa** [comment]
@lptn гэткая састата вялікі выклік для паслядоўнай аўтаматычнай апрацоўкі пры разгорванні?

**Comment by lptn** [comment]
@rizomaa 
тут праблема хутчэй для тэсцераў а не для dev ops

**Comment by rizomaa** [comment]
@lptn прапаную яе вырашаць каля яна ўзнікне чотка.

нейкія вельмі спецыфічныя выпадкі можна агаворваць. 
а калі у цябе 6ПР па розных брэнчах. адзін дамен не дапаможа.

ці тлумач больш тэталёва навошту тут будаваць касмічны карабель =)

**Comment by alies-dev** [comment]
@rizomaa 
ды я наадварот за кнопачку дзе небудзь каб рукамі выбраць якую галіну дэплоіць на сервак)

**Comment by rizomaa** [comment]
@lptn @fr0zen 
вельмі чакаем наладу дэплоймэнта бягучыз зменаў develop галіны на тэставым сэрверы.

з арыентуйце, на калі у вас стаіць гэта задача?

**Comment by alies-dev** [comment]
@rizomaa 
пасля 15/18 траўня дакладна -- есьць болей гарачыя штукі пасля

Загадваць не хачу зараз -- падчат інтэграцыі FE + BE могуць велезці неспадзяванкі з вялікім прыярытэтам якія ў дадатак могуць забраць шмат часу, пагэтаму пасля 18 буду будуваць новы план

**Comment by rizomaa** [comment]
@lptn 
 FE + BE???

так, тады @fr0zen проста гэта дэплоіць як можа, бо нам трэба нейкі онлайн тэставы варыянт...

**Comment by alies-dev** [comment]
@rizomaa 
>FE + BE???

frontend + backend: мы маглі штосці забыць рэалізаваць з любога доку (ці проста ня ведаць што штосіць трэба было рэалізаваць)

**Comment by rizomaa** [comment]
"з любога доку" ? што за докі? @lptn

**Comment by alies-dev** [comment]
доку -> боку (памылачка) :)

**Comment by rizomaa** [comment]
@lptn @fr0zen гэта фіча важная трэба яе зрабіць як мага хутчэй. стаўлю у гарачыя.

**Comment by rizomaa** [comment]
#522

**Comment by rizomaa** [comment]
@lptn як тут ідзе, нам зараз вельмі патэрбны працуючы тэставы дамен, для дэманстрацыі
