### ISSUE TITLE
Зрабіць прыціскі "Штомесяцова" і "Адзінаразова"

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#32]

**Comment by falanster** [comment]
- [ ] Намаляваць макет
- [ ] Звярстаць яго
- [ ]

**Comment by falanster** [comment]
тэкст

**Comment by nastyafrosty** [comment]
https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346340375940     https://github.com/diglabby/doika/issues/23#issuecomment-444623935
