### ISSUE TITLE
Абмеркаваць логіку апрацоўкі тэставых плацяжоў

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#328]
Якія праблемы могуць узнікнуць? (напрыклад статыстыка)

**Comment by lptn** [comment]
Працяг будзе тут: Вырашыць, як маркіруем тэставыя дадзеныя для модуля #335

**Comment by rizomaa** [comment]
Пытанні да чыста візуальнага афармлення, або нешта яшчэ маеце на увазе?
