### ISSUE TITLE
Фронтэнд. Дадаць старонку  ўнясення дадзеных карыстальніка (рэкурэнтныя плацяжы)

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#33]

**Comment by falanster** [comment]
Тут трэба распрацаваць старонку 
https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346136710150

Бо тут яе не заўважыў 
https://it3donate-landing.falanster.by/doika/campaign/1

Скрын старонкі у айфрэйме 
![doika input-data](https://user-images.githubusercontent.com/1325280/50538317-c4f9c980-0b7e-11e9-8880-f2aae0cd7b23.jpg)

@fr0zen гэты піражок для другой ітэрацыі

**Comment by KahjuksEi** [comment]
@fr0zen Хотел бы пока решается вопрос по issue#11 взяться за эту работу.

**Comment by rizomaa** [comment]
@KahjuksEi пакуль сфакусуйся на #13 тым больш яна цябе чакае

**Comment by rizomaa** [comment]
Картка, для Вадзіма

**Comment by rizomaa** [comment]
@fr0zen прагаварыце з @nastyafrosty усю візуальшчыну, каб у нас было мінімум перапрацовак на гэтым вакне.

адразу падкажу, што варта уключыць націфікейшны калі поле няправільна запоўнена. (пакуль можаце без валідатараў іх прамаляваць)

**Comment by nastyafrosty** [comment]
@nastyafrosty design

**Comment by nastyafrosty** [comment]
https://www.figma.com/file/RlVbECuyzs25TCVHZ1Sls87E/Doika-module-%D0%BA%D0%BBi%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%B0%D1%8F-%D1%87%D0%B0%D1%81%D1%82%D0%BA%D0%B0?node-id=0%3A1     тут клиентская часть, добавила окно данных, плюс там все остальное будет 
![donor info](https://user-images.githubusercontent.com/41231823/52311514-361b7080-29b8-11e9-90c3-7813336b7cfa.png)
![example](https://user-images.githubusercontent.com/41231823/52311515-361b7080-29b8-11e9-872b-b91cddf8f03d.png)

**Comment by nastyafrosty** [comment]
наверное пусть пока это окно будет белым как и окно с карточкой (до него) и страница после.  (у нас же пока не предусмотрен выбор фона для этих окон? @fr0zen ), чтобы не было неожиданного фона, как на первом экране,

**Comment by fr0zen** [comment]
@nastyafrosty даже если фон будет меняться (а он будет определенно) - это уже дело пользователей, какие сочетания цветов они захотят. От нас нужен только качественный стоковый дизайн.
Круто, что есть ссылка на фигму, так максимально удобно.

**Comment by nastyafrosty** [comment]
@fr0zen  иногда выбор может сыграть не самую полезную штуку :)

**Comment by fr0zen** [comment]
@nastyafrosty всегда есть возможность поэкспериментировать и выбрать более подходящее, тут не минное поле)

**Comment by svetit** [comment]
Мне падабаецца белы фон, і нават я б яго прапаноўвала не змяняць.
Для змены - колер кнопкі, і іншых кнопка, якія зараз ружовыя, напрыклад.

Хай змяняюць выгляд самога модуля.. Але вось на конд дадатковых вокан прапаноўвала бы па-мінімуму штосці змяняць.

**Comment by rizomaa** [comment]
@fr0zen @lptn @KahjuksEi тут як зараз?

**Comment by alies-dev** [comment]
@rizomaa 
Я ня ведаю: гэта 100% фронтэнд задача

**Comment by rizomaa** [comment]
@fr0zen ?

**Comment by fr0zen** [comment]
@rizomaa гэта старонка звярстана, зачыняю
