### ISSUE TITLE
Рэалізаваць функцыю папярэджэнная падпісчыкаў, калі змяняецца перыяд кампаніі.

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#332]
Забараніць змену дат кампаніі пасля стварэння кампаній з рэкурэнтнымі плацяжамі.

Ліст змены даты кампаніі (нумар шэсць):
https://docs.google.com/document/d/1CP19vpVUDnBsbQlVzZ0uP7CrpLjfZrCKk8Kw-6oKsY4/edit#

**Comment by rizomaa** [comment]
важная але не гарачая.

актуальна пасля 3-4 месяцаў абкаткі

**Comment by rizomaa** [comment]
чаму такая ідэя наогул узнікла? магчыма нам гэта фіча у бліжэйшы час непатрэбна @fr0zen 

напрыклад,
кали людзі зрабілі кампанію на 3 месяцы и различвали на 100 падпісчыкаў, але падпісалася 50, чаму яны не могуць зрабіць на 6.

Магчыма проста трэба рэалізаваць функцыю папярэджэнная падпісчыкаў, калі змяняецца перыяд кампаніі. @fr0zen

**Comment by rizomaa** [comment]
Ліст змены даты кампаніі (нумар шэсць):
https://docs.google.com/document/d/1CP19vpVUDnBsbQlVzZ0uP7CrpLjfZrCKk8Kw-6oKsY4/edit#
