### ISSUE TITLE
Спыненне падпісак па спыненню/закрыццю кампаніі

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#333]
Калі адмін выключае кампанію ці кампанія скончылася, выдаляем падпіскі.

Ліст спынення:
https://docs.google.com/document/d/1CP19vpVUDnBsbQlVzZ0uP7CrpLjfZrCKk8Kw-6oKsY4/edit#

**Comment by rizomaa** [comment]
@fr0zen каментар

проста спыненне кампаніі не павінна выдаляць падпіскі.

толькі выдаленне самой кампаніі цягне выдаленне падпісак. 
дарэчы тут важна распрацаваць выдаленне з пайвержданнем. 

але статыстыка па аперацыям павінна захавацца.

**Comment by lptn** [comment]
@rizomaa 
а што, спыненне і выдаленне падпіскі -- розныя функцыі? А нам увогуле патрэюны функцыянал "спынення"?

Наконт выдалення - мы амаль для усяго будзем выкарыстоўваць "мяккая выдаленне" - гэта калі запісы з БД толькі пазначаны як выдаленыя, але яны усе адно даступны і мы можам на іх падставе будаваць статыстыку

**Comment by rizomaa** [comment]
@lptn так,

1. прыпыніць кампанію = значыць ёсць магчымасць яе абнавіць.
2. выдаліць = няма магчымасці яе абнавіць.

**Comment by lptn** [comment]
@rizomaa 
>прыпыніць кампанію = значыць ёсць магчымасць яе абнавіць.

гэта дадае даволі шмат н'юансаў у код, нам рэальна патрэбны такі функцыянал?

**Comment by rizomaa** [comment]
@fr0zen кампания спыняецца, калі

1. 

заканчваецца яе тэрмін

тады яна хаваецца ад прагляду, але падпіскі не выдаляюцца. бо магчыма праз дзень або два адмін зойдзе у адмінку і вырашыць працягнуць на пару месяцаў, таму што неданабралі суму, або набралі, але ёсць патрэба у яшчэ дадатковай.

2. сапраўды тут няма функцыянала "прыпыніць" кампанію https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346294415052 Тады у мяне пытанне, да @fr0zen чаму ён абазначыў гэта ў ішу. Трэба звузіць задачу, і стварыць "прыпыніць" як прапанову на іншы спрынт, бо гэта пажаданая, але не ключавая функцыя.

**Comment by rizomaa** [comment]
важная але не гарачая.

актуальна пасля 3-4 месяцаў абкаткі

**Comment by rizomaa** [comment]
@lptn @Tyuba4  як зараз працуе алгарытм падпіскі асабліва па часцы фінальнай даты падпіскі?

**Comment by Tyuba4** [comment]
@rizomaa Тут да Алеся пытанне, ён больш знае апошнюю версію Дойкi

**Comment by alies-dev** [comment]
@rizomaa 
>@lptn @Tyuba4 як зараз працуе алгарытм падпіскі асабліва па часцы фінальнай даты падпіскі?

Для bepiad мы ствараем падпіску на  x транзакцый якія мы разлічваем маючы дату заканчэння кампаніі,  інтэрвал і бягучы час, вось код
https://github.com/diglabby/doika/blob/e903d326583948942e0a0b4210ca7dbe996daa38/app/Models/SubscriptionIntend.php#L62-L71

Гэта нам дапаможа пазбавіцца ад праблемаў калі хтосці захоча працягнуць кампанію на 2 гады а людзі падпісаліся толькі на 1 год, падпіснты па-ранейшаму будуць плаціць толькі год. Але усе складаней з укарачэннем дзеяння кампаніі -- тут мы не маем кантролю над падпіскамі

Калі адмін чамусці выдаляе кампанію, мы пакуль што падпіскі не выдаляем. Я думаю іх трэба выдаляць

**Comment by rizomaa** [comment]
@lptn ведаеш гэта фича не адназначная вось каб так проста выдаляць.

1. Напрыклад, арганізацыя вырашае працягнуць кампанію (калі яшчэ сама кампанія не скончылася). Гэта практыка вельмі характэрна. Арганізацыі, напрыклад, могуць ствараць кампаніі для збора членскіх унёскаў. І гэта рэальная патрэбна, якую яны апісваюць пры размовах.

2. Па другое, у скрайнім выпадку адпісацца магчыма праз свой анлайнбанкінг, калі модуль гэта не дасць, або будзе завалены самой арганізацыяй.

3. Можна вырашыць гэта пытанне, праз папярэджанні падпісчыкаў, пры любых зменах даты кампаніі.

Вядома, калі кампанія скончылася, заднім чыслом нельга працягнуць кампанію - гэта нармалёва.

Рашэнне:

1. Абмяжоўваць перыяд падпісак не трэба (на дадзеным кроку)
2. Рэалізаваць мэйлінг пры змене даты кампаніі, з папярэджаннем падпісантаў пра дзеянні арганізацыі.
3. Змяняць дату скончанай кампаніі нельга, падпіскі ануліруюцца.

**Comment by alies-dev** [comment]
@rizomaa 
Пра сяброўскія ўнескі: можна ж ствараць каманію на колькі заўгодна гадоў, так?

Дадаткова памятай што карткі маюць свой тэрмін прыданасці (калі 4 гадоў), так што перападпісвацца ўсе адно давядзецца сябрам НДА


Магчыма вырашыць праблему проста не пазначая дату фініша кампаніі, у такім выпадку мы не будзем абмяжоўваць колькасць данэйтаў на падпіску

**Comment by rizomaa** [comment]
> @rizomaa
> Пра сяброўскія ўнескі: можна ж ствараць каманію на колькі заўгодна гадоў, так?
> 
> Дадаткова памятай што карткі маюць свой тэрмін прыданасці (калі 4 гадоў), так што перападпісвацца ўсе адно давядзецца сябрам НДА
> 
> Магчыма вырашыць праблему проста не пазначая дату фініша кампаніі, у такім выпадку мы не будзем абмяжоўваць колькасць данэйтаў на падпіску

@lptn так апошні варыянт мне падабаецца. можна зрабіць такую і адпаведна улучыць гэты кейс у рыбу мэйла @Olya147

**Comment by alies-dev** [comment]
@rizomaa 
Згода! Але думаю гэта траба знабіць яўнымна ўроўне UX/UI (хаця б дапамагашку дадаць)

**Comment by rizomaa** [comment]
@nastyafrosty цікавы твае думкі тут...

**Comment by cema93** [comment]
Чтобы решить вопрос с приостановкой\возобновлением компании предлагаю следующее:
1) убрать возможность приостановить\возобновить компанию компанию
2) добавить возможность отключить компанию (без возможности повторного запуска).

**Comment by rizomaa** [comment]
@lptn вітаю,

1. Усе кампаніі на баку біпэйда безтэрміновыя (!!!)
2. У модулі можна задаваць канцоўку кампаніі.
3. Калі наступае каноцўка кампаніі што напісана у модлулі. модуль усіх падпісчыкаў адпісвае праз запыт да біпэйда.

па твайму пытанню накот картак і сяброўскіх унёскаў.
1. пакуль не думаем пра ануляваныя карткі. можна стварыць асобную ішшу і гэта прадумаць. 
2. так, магчыма ствараць тэрміновыя і безтэрміновы кампаніі. гэта добрая ідэя. рэалізуем яе.

іншыя рызыкі калі ласка сюды не уключай. бо гэта пашырэнне функцыянала і мы яго прадумаем па меры вырашэння больш базавых задач.

**Comment by alies-dev** [comment]
@rizomaa 
>Усе кампаніі на баку біпэйда безтэрміновыя (!!!)

Што ты меў на ўвазе тут -- падпіскі? Бо ў біпэйда няма кампаній.

>Калі наступае каноцўка кампаніі што напісана у модлулі. модуль усіх падпісчыкаў адпісвае праз запыт да біпэйда.

Па-добраму для гэтага тксама патрэбны крон ці чэргі, што будзе не толькі ў наступнай версіі.

**Comment by rizomaa** [comment]
@lptn 

1. Меў на увазе планы, па якім адбваюцца рэкурэнтныя плацяжы.
2. Так, гэта будзе пасля. Таму мы на гэтай версіі не парымся і робім безтэрміновыя падпіскі, бо важна запусціць іх наогул

**Comment by alies-dev** [comment]
@rizomaa 
>Так, гэта будзе пасля. Таму мы на гэтай версіі не парымся і робім безтэрміновыя падпіскі, бо важна запусціць іх наогул

Насамрэч я запарыўся некалькі месяцаў таму і дадаў вось гэта: https://github.com/diglabby/doika/blob/9aedabb2d50067314ea296c46f3d6a58b9359644/app/Services/PaymentGateways/BePaidPaymentGateway.php#L117

Тут падлічваецца колькі разоў падпіска можа быць выкарыстана да канца кампаніі (`billing_cycles`) і такім чынам пры змене дат кампаніі старыя падпіскі не мяняюцца. Што рабіць цяпер з гэтай логікай -- выдаляць? Ці пры `campaign.finish_at === null` ствараць такі безтэрміновую падпіску?

**Comment by rizomaa** [comment]
@lptn так, пакуль ствараць безтэрміновую.

у будучай ітэрацыі можна будзе дадаць фічу.

1. калі кампанія безтэрміновая - падпіска безтэрміновая.
2. калі кампанія тэрміновая - падпіска тэрміновая.

але не зараз, каб сканцэнтравацца на асноўным зараз
1. інсталятар
2. працуючы мэйлінг.

**Comment by alies-dev** [comment]
@rizomaa 
Чакай, я так і не зразумеў што рабіць ў маючай логікай і кодам (абмежаванне КОЛЬКАСЦІ аплат на падпіску): выдаляем ці пакідаем?

**Comment by rizomaa** [comment]
Трэба зрабіць падпіскі такім чынам каб зхмены дат кампаніі не ўздзенічалі на падпіскі. толькі калі сцякае дата падпіскі ануліруюцца. такая логіка патрэбна @lptn

**Comment by alies-dev** [comment]
@rizomaa 
Ну глядзі, зараз калі ствараецца падпіска на кампанію каторая скончыцца праз 70 дзен, то ахвярадаўца плаціць тройчы: зараз, праз месяц і праз два месяца, бо у нас падлічваецца колькасць аплат на момант падпіскі і дасылаецца на біпэйд (я пісаў пра гэта [тут](https://github.com/diglabby/doika/issues/333#issuecomment-500227853) і [тут](https://github.com/diglabby/doika/issues/333#issuecomment-506956659))

Плюс такога падыходу што адмін можа мяняць дату кампаніі у бок павелічэння, але гэта не ўплывае на існуючыя падпіскі (не мяняюцца правілы гульні пад час гульні).

Болей відавочны плюс: падпіскі не бясконцыя. Калі нам такі трэба бясконцыя падпіскі (да сканчэння карткі) -- можам здабіць поле campaign.finish_at не абавязковым і тады мы НЕ будзем адбяжоўваць колькасць аплат у межах падпіскі (`billing_cycles`). Гэта даволі проста хоць зараз рэалізаваць (на бэке)

**Comment by rizomaa** [comment]
@lptn 

1. так трэба прыбраць абмежаванне на падпіскі - напрыклад гэта для членскіх унёскаў
2. наогулкалі кампанія мае верхнюю мяжу падпіскі (планы) безтэрміновыя. Калі кампанія заканчваецца, крон апрацоўвае адпіскі. Карацей. Тут вымаўлёваецца крон які будзе адпісваць ад скончаных кампаній патрэбныя планы(падпіскі) кожнага ахвярадаўцы

@lptn

**Comment by rizomaa** [comment]
Ліст спынення (нумар 7):
https://docs.google.com/document/d/1CP19vpVUDnBsbQlVzZ0uP7CrpLjfZrCKk8Kw-6oKsY4/edit#
