### ISSUE TITLE
Выдаліць і схаваць функцыянал тэставых плацяжоў

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#335]
Праблема: тэставыя і "жывыя" дадзеныя (транзакцыі, падпіскі, ахвярадаўцы) могуць быць як тэставымі, так і "жывымі" што будзе уплываць на статыстыку ў дашбордзе

Праблема апісана вось тут https://github.com/diglabby/doika_1.2/issues/105

**Comment by lptn** [comment]
@nastyafrosty 
Вітаю Наста. Здаецца мне гэта UX задача, есьць думкі як будзем вырашаць?

**Comment by rizomaa** [comment]
@lptn як разумею у нас сінонімы - адмінка = дашбоард. у любым разе запішыце у слоўнік

**Comment by lptn** [comment]
@rizomaa 
у гэтым слоўніку ужо есць https://github.com/diglabby/doika/blob/develop/docs/glossary.md

Сама гэтая праблема значна шырэйшая за проста візуальную -- гэта архітэкступная праблема, там тэставыя плацяжы будуць замінаць пастаянна, калі мы робім запыты у БД, калі сумуем дадзеныя і гэтак далей

Есьць некалькі варыянтаў рашэння, прыйдзе час, будзем падбіраць лепшы

**Comment by rizomaa** [comment]
@lptn я да гэтага паста карыстаюся толькі слоўнікам што у трэла. 

Яны былі сінхранізаваныя?

**Comment by lptn** [comment]
@rizomaa 
прабач, я нічога ня ведаю пра слоўнік у трэла

Можа лепей бліжэй да коду слоўнік неранесці?

**Comment by rizomaa** [comment]
@lptn 

https://trello.com/c/SaP88sEG там цябе ўзгадваў мінімум 2 разы + ты ў гэтай карцы ёсць

Прапаную спачатку усё сінхранізаваць ў трэла, а пасля пераносіць ў іншыя месцы. І таксама абмеркоўваць з камандай новыя тэрміны або назвы. Дзякуй

**Comment by lptn** [comment]
@rizomaa 
>https://trello.com/c/SaP88sEG там цябе ўзгадваў мінімум 2 разы + ты ў гэтай карцы ёсць

гэта так, выбачаюся. ВЕЛЬМІ шмат шуму ідзе з трэлла, я яго проста ігнорю збольшага і праглядаю эпіздачын, я фізычны не валодаю такою колькасцю часу каю чытаць усе `@board` там і `@channel` у slack. Вельмі хацелася б мець меней паведамленняў

@rizomaa 
Праглядзі калі ласка мой ПР - там усе проста: выдаляем тэчку /docs каб яна болей не спакушала Remove docs dir: we use Trello and Wiki instead #338

**Comment by rizomaa** [comment]
@rizomaa зараз найбольш абнаўляецца гітхаб (часам да 50 паведамленняў на дзень). Трэла ў параўнанні вельмі мала 3-5 паведамленняў на дзень там. Тое самае па слэку.

**Comment by Olya147** [comment]
@fr0zen @lptn  вопрос решён? Можно закрывать?

**Comment by lptn** [comment]
@Olya147 
Не, не вырашына, гэта відаць будзе доўгаіграючая задача, па-ранейшаму чакаю @nastyafrosty :)

**Comment by nastyafrosty** [comment]
@lptn я,возможно,не очень поняла,что требуется от меня...Сейчас тестовые платежи помечены в админке?

**Comment by lptn** [comment]
@nastyafrosty 
>Сейчас тестовые платежи помечены в админке?

зараз яны ніяк не пазначаны (тэхнічна) але мы гэта хутка рэалізуем

Мне падабаецца ў Stipe як гэта рэалізавана -- View test data
![image](https://user-images.githubusercontent.com/5278175/56733873-05063d00-676a-11e9-9669-4078388f9770.png) . Пры переключэнні мяняюцца ўсе дадзеныя на старонцы

**Comment by nastyafrosty** [comment]
@lptn что именно тебе нравится?

**Comment by lptn** [comment]
@nastyafrosty 
что есць толькі адна переключалка, інтэрфейс пры гэтым зусім не ускладняецца, пры гэтым тогл пераключэння адлюстюстравання тэставага рэжыму навідавоку

**Comment by lptn** [comment]
@svetasemashko 
Можа ў цябе есьць бачанне таго як такую праблему вырашыць?

**Comment by nastyafrosty** [comment]
> @nastyafrosty
> что есць толькі адна переключалка, інтэрфейс пры гэтым зусім не ускладняецца, пры гэтым тогл пераключэння адлюстюстравання тэставага рэжыму навідавоку

т.е. ты возможно предлагаешь вариант с доп секцией в меню "Тестовые платежи".где будет отображены такая же табличка,как с информацие об обычных платежах,но только тестовые?

**Comment by lptn** [comment]
@nastyafrosty 
ну я пакуль што не прапаноўваю, а хутчэй зажу што есьць такая опцыя і яны зручная на сайце  Stripe. 

Але пры стварэнни кампании хутчэй за ўсе таксама трэба будзе выбіраць -- гэта тэставая кампанія ці не, а ячшэ кампанія не змажа быць адначасова тэставай ня тэставай, а яшчэ са з'явленнем новых Paymentgateway з'явяцца новыя праблемы кафігурацыі: у bePaid зараз канфіг тойжа для тэставых і жывых працяжоў (мяняецца толькі сцяг "live"), у другіх плацяжных сістэмах ключы звычайна разныя (clientId + secretKey/token). Карацей гемар ягчэ той, трэба думаю спачатку разабрацца як і для чаго звычайны карыстальнік выкарыстоўвае тэставыя плацяжы

**Comment by nastyafrosty** [comment]
> @nastyafrosty
> ну я пакуль што не прапаноўваю, а хутчэй зажу што есьць такая опцыя і яны зручная на сайце Stripe.
> 
> Але пры стварэнни кампании хутчэй за ўсе таксама трэба будзе выбіраць -- гэта тэставая кампанія ці не, а ячшэ кампанія не змажа быць адначасова тэставай ня тэставай, а яшчэ са з'явленнем новых Paymentgateway з'явяцца новыя праблемы кафігурацыі: у bePaid зараз канфіг тойжа для тэставых і жывых працяжоў (мяняецца толькі сцяг "live"), у другіх плацяжных сістэмах ключы звычайна разныя (clientId + secretKey/token). Карацей гемар ягчэ той, трэба думаю спачатку разабрацца як і для чаго звычайны карыстальнік выкарыстоўвае тэставыя плацяжы

ну я просто уточнила,правильно ли я поняла, что тебе нравится в примере и как это может быть использовано у нас.
предложи нашему бизнес-аналитику добавить вопрос про тестовые платежи в анкету для организаций

**Comment by rizomaa** [comment]
@nastyafrosty @lptn 

У нас ёсць агульны канфіг для біпэйда, які мы можам пераключаць
1. на тэставыя плацяжы 
2. на рэальныя плацяжы
больш тут не трэба нічога ускладняць, хай так і застанецца пакуль.

для рэалізацыі можна стварыць у базе поле, якое будзе запісваць статус 1 або 0 плацяжа,  і па яму выводзіць прагрэс і падлічваць рэальныя плацяжы

калі пройдзены тэставы плацёж ён трапляе у табліцу транзакцый, але не падлічваецца у прогрэс бары

ці так відавочней?

**Comment by lptn** [comment]
@rizomaa 

>калі пройдзены тэставы плацёж ён трапляе у табліцу транзакцый, але не падлічваецца у прогрэс бары

а ў адмінцы ў статыстацы паказваем тэставыя? А калі карыстальнік прняў рэальныя плацяжы, переключыў у тэставы і прыняў тэставыя -- якія лічбы паказваем у статыстацы?

Кантрол тэставы/жывы -- на ўсе шлюзы ці асобна на кожны? Калі на ўсе -- складана будзе тэсціцб шлюзы па-асобку. Калі па-асобку -- складана паказваць статыстыку (як зразумець -- паказваем тэставыя дадзеныя ці жывыя калі bePaid -- live, а БелАграПромБанк -- тэставы?). Я думаю логіку адлюстравання статыстыкі live/test і налады шлюзаў трэба размежаваць -- гэта розныя штукі

**Comment by nastyafrosty** [comment]
а если в табличке,где название кампании, в начале писать [Тэставы]?

**Comment by lptn** [comment]
так, можна вырашыць праблему тым, што зрабіць Кампанію тэставай ці жывой, але  пры гэтым статус мяняць забараніць, гэта будзе найпрасцешы варыянт думаю

**Comment by fr0zen** [comment]
@lptn 1. Кантрол тэставы/жывы -- на ўсе шлюзы ці асобна на кожны? - Бачу са свайго боку так: зараз у нас 1 кампанія - 1 шлюз, таму тэставы/рэальны плацеж - павінна ўказвацца ў кампаніі. Магчыма я жадаю тэсціць толькі адну кампанію з усіх. Калі на кампанію будзе выбар шлюза - тады тэстуюцца адразу усе шлюзы.
Наконт як адлюстроўваць - магчыма проста шыльдачку "тэставы" адмаляваць побач з назвай кампаніі

**Comment by lptn** [comment]
@fr0zen 
Пытанне "што у нас можа быць тэставым" я так разумею па-ранейшаму адкрытае:
 1. Кампаніі (то бок кампанія можа быць ЦІ жывой ЦІ тэставай і мяняць яе статус нельга)
 2. Плацяжы (любая кампанія можа прымаць і жывыя і тэставыя плацяжы)

У залежнасці ад адказу трэба пісаць розны код. Асабіста мне падабаецца варыянт 2 бо можна рабіць тэставыя плацяжы ў любы момант, але ен ставіць перад намі іншыя задачы, але і першы варыянт не так просты ў рэалізаціі праз тое што пакуль што мы можам мяняць статус адкрытай кампаніі (тэставая ці жывыя)

**Comment by rizomaa** [comment]
@lptn @fr0zen @nastyafrosty 

прачытаў. думаю. у бліжэйшы час напішу свае заўвагі.

**Comment by rizomaa** [comment]
@fr0zen @lptn @nastyafrosty 

Наогул пікча такая:
1. Модуль дае магчымасць падключаць некалькі агрэгатараў.
2. Адначасова працуе толькі адзін агрэгатар (гэта дакладна да ітэрацыі 6-7 мінімум). Бо арганізацыі не будуць ставіць сабе па 2-3 агрэгатара і камбініраваць кампаніі з адначасовай працай. такога запыта ад іх ніколі не чуў.
3. Таму робім агульную наладку. Тэставы рэжым у канфігурацыі агрэгатара (гэта распаўсюджваецца на ўсе кампаніі)
4. Арганізацыя хоча пратэсіць кампані. Заходзіць у канфігурацыю агрэгатара, ставіць яго ў тэставы рэжым і робіць аплату у любой кампаніі. І гэта аплата запісваецца як тэставая.

Зы 
Важна адзначыць: 
1. Агрэгатар мае тры станы: 
1.1. выключаны, 
1.2. уключаны, 
1.3. тэставы. 
калі адзін аргэгатар уключаны, або тэставы астатнія агрэгатары адключаны (наладка знаходзіцца на старонцы канфігурацыі агрэгатара).

ВАЖНА
1. Усе кампаніі або ўключаны, або адключаны. Іх тэставы рэжым не трэба задаваць.

2. Як адлюстроўваць тэставы плацёж ёсць некалькі думак:

2.1. памяшчаць яго ў адмінцы у спісе з усімі плацяжамі кампаніі, але не залічваць у прогрэс бары кампаніі. 
2.2. проста выводзіць у кліенскай часцы, што модуль працуе у рэжыме тэставага плацяжу і нікуды не запісваць праведзены тэставы плацёд наогул.

Зызы
Па харошаму пратэсціць можна 1 рублём і працуючую кампанію, калі арганізацыя будзе іх некалькі запускаць... таму тут ідзем па прасцеўшаму па рэалізацыі шляху.

**Comment by nastyafrosty** [comment]
@fr0zen @lptn @rizomaa ну что,к чему пріходім?)

**Comment by rizomaa** [comment]
так, тут перачытаў перапіску. так. я наогул думаю магчыма тэставы функцыянал на сёння не замарачвацца. можна тэставаць 1 рублём. Бо тэсты патэрбны больш для распрацошгчыкаў.

Наогул тэставае функцыянаванне непатрэбна, калі яна дадае шмат болі.

Задача непрыярытэтная

**Comment by rizomaa** [comment]
Падобная картка тут https://github.com/diglabby/doika/issues/549. Яе зачыняю

**Comment by rizomaa** [comment]
+1
