### ISSUE TITLE
Рэалізаваць лакалізацыю (наноў) [выкарыстоўваем старыя пераклады]

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#336]
Яна была, але выдалілі праз праблемы з роўтамі

Перад реалізацыяй трэба абмеркаваць дзе будзем захоўваць інфармацыю па бягучай лакалі -- кукі ці URI ці сесія ці яшчэ якія вырыянты

**Comment by rizomaa** [comment]
@lptn ці застаўся сам масіў перакладу такім жа?

**Comment by lptn** [comment]
@rizomaa 
пераклады я не чапаў і не буду, проста пакуль што нельга мяняць мову
