### ISSUE TITLE
Реализовать cookies для хранения введенных данных до отсылки их на сервер.

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#34]

**Comment by Tyuba4** [comment]
@fr0zen @falanster @Tyuba4 @lptn Надо разобраться нужен ли нам этот функционал.

**Comment by lptn** [comment]
@Tyuba4 
па назве іш'ю я нават здагадацца не магу што "автор хотел сказать" :)

Я патрабую ўнятнага апісання!

**Comment by Olya147** [comment]
@Tyuba4 @lptn  карточка ещё актуальна?

**Comment by fr0zen** [comment]
Нічога не зразумеў і не памятаю, аб чым шла гаворка. Зачыняю.
