### ISSUE TITLE
Трэба перадаць такен узнаўлення пароля ў login view.

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#340]
Сфарміраваць такен каб далучыць на старонку https://github.com/diglabby/doika/pull/339/files#diff-fb982ab34b5bef50b61be6d1b5eb8749R38

**Comment by lptn** [comment]
WAT? Трэба нейкая дапамога?

**Comment by lptn** [comment]
@fr0zen ?

**Comment by fr0zen** [comment]
@lptn не актуальна
