### ISSUE TITLE
Змяніць URL, каб пазбавіцца ад залішняй секцыі (/doika/doika vs /doika)

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#341]
Зараз маем шлях /doika/doika/dashboard -> неабходна выдаліць адну секцыю так, каб той жа самы роут працаваў праз шлях /doika/dashboard

Зараз усе запыты накіроўваюцца правілам https://github.com/diglabby/doika/blob/cb21687e2c6e94584b29844ef90c6829b2aecbd4/.htaccess#L20
ў https://github.com/diglabby/doika/blob/cb21687e2c6e94584b29844ef90c6829b2aecbd4/index.php#L52
Можа ёсць думкі на гэты конт?

**Comment by rizomaa** [comment]
@lptn ці тут яшчэ насамрэч гарачае нешта засталося?

**Comment by alies-dev** [comment]
@rizomaa 
так, праблема засталася не вырашана

**Comment by rizomaa** [comment]
@lptn у чым яе складанасць на твой погляд. бо разумею гэта игуа цягнецца з минулай версіі

**Comment by alies-dev** [comment]
@rizomaa 
мы можам з гэтым жыць я думаю, яно здаецца дыскамфорт дадае толькі для распрацоўшчыкаў, вырашым у далейшым, не думаю што гэта блочыць рэліз 2.0

Першая /doika дадаецца ад таго што мы заліваем дойку ў тэчку з такім імем, другая doika дадаецца на ўрозне Laravel для таго каб роўты спасылкі маглі генерыцца правільныя і унікальныя

**Comment by rizomaa** [comment]
акей тады я зжамаю гэту ішшу ў свабоднае плаванне
