### ISSUE TITLE
Login page session expired

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#343]
Адразу пасля таго як лагінімся, выдаецца паведамленне 419 "page expired". Тэставаў праз докер. 
У саміх формах csrf token уключаны, у сессіі есць таксама. 
@lptn @Tyuba4 можа есць якія думкі ў вас?

**Comment by lptn** [comment]
@fr0zen 
Fixed by https://github.com/diglabby/doika/commit/3a106ea1327863664e44d3014c09df8abdf7b289
