### ISSUE TITLE
Бэкэнд. Рэалiзаваць клас, які запісвае дадзеныя для адмінкі (збор статыстыкі) з дзеянняў данэйцера

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#35]

**Comment by fr0zen** [comment]
- [ ] Сабраць спіс задач, для якіх ствараецца класс
- [ ] Стварыць спіс метадаў і палей класа
- [ ] Рэалізаваць кожны метад
- [ ] Напісаць тэсты
- [ ] Праверыць стылі кода

**Comment by rizomaa** [comment]
Тут макет: https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346287487153

**Comment by Tyuba4** [comment]
@Tyuba4 Сделать класс который будет собирать данные плательщика и подписки в базу данных

**Comment by lptn** [comment]
@Tyuba4 
распішы калі ласка якога кшталту статыстыку мы збіраемся збіраць

**Comment by rizomaa** [comment]
@Tyuba4 @lptn 

спіс дадайце, калі, бачыце нешта зможам дадаць:

1. Дата ахвяравання
2. Назва кампаніі
3. Сума ахвяравання
4. Імя ахвярадаўцы
5. Імэйл ахвярадаўцы
6. Тэлефон
7. Статус падпіскі
8. Статус аплаты

**Comment by fr0zen** [comment]
Дадзеныя збіраюцца. зачыняю.
