### ISSUE TITLE
Дызайн. Стварыць акенца лагіна у адмiнку (дызайн)

### ISSUE THREAD

**Issue by nastyafrosty** [diglabby/doika#37]

**Comment by nastyafrosty** [comment]
- [ ] Узнать о нужном функционале

- [ ] Изобразить

**Comment by nastyafrosty** [comment]
https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346284941445

**Comment by falanster** [comment]
дзякуй зачыняем задачу @nastyafrosty
