### ISSUE TITLE
Кривые заголовки в Спіс кампаній

### ISSUE THREAD

**Issue by KahjuksEi** [diglabby/doika#371]
Кривые заголовки в Спіс кампаній

**Comment by ghost** [comment]
@KahjuksEi Поясни, что ты имел в виду.

**Comment by KahjuksEi** [comment]
@Olya147  Смещение верстки заголовков при открытии навбара

**Comment by fr0zen** [comment]
@KahjuksEi возьмешся паправіць?

**Comment by KahjuksEi** [comment]
@fr0zen ok
