### ISSUE TITLE
Изменить текст в кнопке Помоги команде

### ISSUE THREAD

**Issue by KahjuksEi** [diglabby/doika#372]
Изменить текст в кнопке Помоги команде

**Comment by Olya147** [comment]
@KahjuksEi Сейчас в названии кнопки опечатка. 
Должно быть "Дапамажы".

**Comment by Olya147** [comment]
@KahjuksEi  +после нажатия на кнопку _ничего не происходит_.

**Comment by KahjuksEi** [comment]
@Olya147 пока что существует проблема, мешающая редактировать текстовые данные. 
@fr0zen а куда должна вести кнопка?

**Comment by Gordonshik** [comment]
Делаю это
Pull request сделаю тогда, когда пойму как он делается. (видимо скоро)

**Comment by rizomaa** [comment]
@Gordonshik зачыняйце гэту картку

**Comment by Gordonshik** [comment]
closes #372

**Comment by rizomaa** [comment]
@Gordonshik ці маеш такую кнопку?

![Selection_002](https://user-images.githubusercontent.com/9870374/75259787-a1212a80-57f9-11ea-9319-faf35bd87775.png)

**Comment by Gordonshik** [comment]
@rizomaa  не
![изображение](https://user-images.githubusercontent.com/51483246/75330637-7636e500-5892-11ea-88b4-3cf354ded3f2.png)
в других issues вроде было
