### ISSUE TITLE
Стварыць гайд па сінхранізацыі форка з асноўным рэпазіторыем

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#375]
Стварыць гайд, як забіраць апошнія змены, калі форкаемся ад рэпазіторыя.

**Comment by lptn** [comment]
Мо проста знайсці і даць спасылку на існуючыя?

**Comment by fr0zen** [comment]
Вось просты гайд https://medium.com/@shanhaichik/%D1%81%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-fork-a-%D0%BD%D0%B0-github-%D1%81-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%BC-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B5%D0%BC-47565bd37385

**Comment by lptn** [comment]
і вось простыя 
https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser
https://gist.github.com/CristinaSolana/1885435


а тут відые https://www.youtube.com/watch?v=o-2fvj7GsOQ

**Comment by fr0zen** [comment]
@lptn мне падаецца вось з такога і добра фарміраваць вікі. Зачыню issue і дам на яе спасылку у wiki. Гэта для тых, хто робіць пулы праз форк.

**Comment by lptn** [comment]
@fr0zen 
@rizomaa 
гэта увогуле мае агульнае бачанне некаторых праблемз доками -- ужо амаль усе напісана, ня трэба перавынаходзіць ровар, дастаткова выкарыстоўваць спасылкі на маючуюся дакументацыю. Перевагу лепей аддаваць докам офіцыйным ці якія падтрымліваюццаа кам'юніці (репы на тым жа GitHub). Вядома для кастамных докаў гэта не падыходзіць, але такія агульныя як форкі -- дастаткова спасылкі

А всоь цяпер пытанне: ці норм спасылкі на english докі?

**Comment by fr0zen** [comment]
@lptn мне падаецца па english доках ўвогуле не павінна пытанне ўзнікаць, бо шмат чаго не перакладзена зусім, гэта не повад не выкарыстоўваць інфу)
