### ISSUE TITLE
Стварыць feature test на працэс данэйта (аднаразовы і падпіску) 

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#378]
Выдзелена з Абмеркаваць інтэграцыю аўтатэставання #204

**Comment by rizomaa** [comment]
@lptn хочаш нейкім аўтатэстам пакрываць? 

што такое "feature test"?

**Comment by alies-dev** [comment]
feature test - https://laravel.com/docs/master/http-tests


але я думаю для гэтага ня трэба issue тут: закрываю
