### ISSUE TITLE
Старонка адпіскі ад кампаніі (проста дадаць надпіс што вы паспяхова адпісаны)

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#383]
@nastyafrosty падумай, калі ласка, над дызайнам старонкі, якая паказвае, што чалавек паспяхова адпісаўся ад плацяжоў.

**Comment by rizomaa** [comment]
@fr0zen гэта не гарачая задача. я нават думаю, што тут не тэрба маляваць проста кликаеш па старонцы и белая старонак з надпісам і ўсё.

**Comment by rizomaa** [comment]
Дублюе задачу https://github.com/diglabby/doika/issues/218
