### ISSUE TITLE
Пропало текстовое поле с описанием кампании

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#384]
**Дзеянні каб паўтарыць памылку**
1. Открыть раздел "Список кампаний"
2. Нажать кнопку "Создать кампанию"

**Фактический результат:** исчезло поле для описания цели проводимой кампании.
**Ожидаемый результат:** поле есть.

Было:
![1](https://user-images.githubusercontent.com/46268205/56861526-500e9300-69aa-11e9-86d3-ed6cb27424a0.jpg)

Стало: 
![Без Описания](https://user-images.githubusercontent.com/46268205/56861432-59e3c680-69a9-11e9-9d5d-d92f3db0ac8c.png)

**Тэставыя ўмовы**
- Версія Doika: 1.3
- Платформа і версія: Windows10
- Браўзер і версія: Chrome/Opera

**Comment by ghost** [comment]
Исправлено.
