### ISSUE TITLE
Нельзя завершить сеанс, нажав на кнопку "Выйсці"

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#385]
**Шаги воспроизведения:**
1. Открыть модуль;
2. нажать на кнопку Admin;
3. нажать на кнопку Выйсці

**Фактический результат:** ничего не изменилось, пользователь остался на странице модуля.
**Ожидаемый результат:** сеанс завершён.

Версия Doika: 1.3
Платформа и версия: Windows10
Браузер и версия: Chrome 73.0.3683.103/Opera 58.0.3135.132

**Comment by ghost** [comment]
исправлено.
