### ISSUE TITLE
После нажатия на кнопку "Забыліся пароль" открывается страница с ошибками

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#386]
**Шаги воспроизведения:**
1. Перейти по ссылке http://doika/doika/doika/dashboard/login
2. нажать "Забыліся пароль?".

**Фактический результат:** перенаправление на страницу с ошибками.

**Ожидаемый результат:** открыта страница Восстановления пароля.
![3](https://user-images.githubusercontent.com/46268205/56862234-62d89600-69b1-11e9-8cba-19637de1350d.png)

**Окружение:**
Версия Doika: 1.3
Платформа и версия: Windows10
Браузер и версия: Chrome 73.0.3683.103/Opera 58.0.3135.132

**Comment by lptn** [comment]
@Olya147 
Дзякуй за рэпорт, гэты функцыянал яшчэ не рэализаваны, я дадаў пустую старонку замест, а ягчэ я стварыў задачу каб рэалізаваць гэты функцыянал : "Рэалізаваць функцыянал для "Забыліся пароль" (forget password) #396"
