### ISSUE TITLE
Ошибка 404 при повторном открытии сайта

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#393]
**Шаги для воспроизведения:**
1. открыть модуль;
2. залогиниться;
3. закрыть вкладку сайта;
4. открыть сайт ещё раз.

**Фактический результат:** открывается страница 404. Зайти на сайт можно после удаления истории браузера.
**Ожидаемый результат:** открывается страница модуля.
**Окружение:**
Версия Doika: 1.3
Платформа и версия: Windows10
Браузер и версия: Chrome 73.0.3683.103/Opera 58.0.3135.132

**Приложение:** [1.zip](https://github.com/diglabby/doika/files/3132029/1.zip)

**Comment by alies-dev** [comment]
@Olya147 
 Дзякуй за відыё -- рэальна дапамогло

Праблема была ў тым куды рэдзірэкціць залашіненага карыстальніка калі ен хоча зайсці на старонку /doika/dashboard/login . Я паправіў -- цяпер рэдзірэкціць на хатнюю старонку dashboard

Які flow цяпер: ты тэсціш наноў і закрываеш ці я магу закрыць?

**Comment by ghost** [comment]
@lptn Проверила, всё исправлено.
Закрываю.
