### ISSUE TITLE
Перевести название поля в разделе Payment systems на белорусский язык

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#394]
**Шаги для воспроизведения:**
1. Открыть модуль;
2. перейти в раздел "Payment systems"

**Фактический результат:** название поля "Текст условий сервиса сбора пожертвований" написано на русском языке (см. вкладки Bepaid и Artpay).
**Ожидаемый результат:** поле называется "Тэкст умоў сэрвісу збору ахвяраванняў".

![1](https://user-images.githubusercontent.com/46268205/56978061-56a23380-6b7f-11e9-88d1-4596893185a3.png)

Окружение:
Версия Doika: 1.3
Платформа и версия: Windows10
Браузер и версия: Chrome 73.0.3683.103/Opera 58.0.3135.132

**Comment by Olya147** [comment]
Предлагаю также перевести названия разделов Payment systems, Layout, Notificatons, т.к. после их открытия справа (на белом фоне) отображается аналогичная запись на бел. языке (Злучэнне з плацежнай сістэмай, Параметры макета, Наладка паведамленняў). 
@rizomaa @fr0zen @lptn @KsenjaV  как вы считаете?

**Comment by lptn** [comment]
так, варта перекласці

**Comment by ghost** [comment]
@fr0zen Осталось перевести "Текст условий сервиса сбора пожертвований" как в приложении.

**Comment by fr0zen** [comment]
@Olya147 👍 прапусціў, што яна на рускай мове
