### ISSUE TITLE
Добавить текстовые поля в разделах "Payment systems" и"Notificatons"

### ISSUE THREAD

**Issue by Olya147** [diglabby/doika#395]
**Шаги для воспроизведения:**
1. Открыть модуль

**Фактический результат**: в разделах "Payment systems" и "Notificatons" отсутствуют текстовые поля.

**Ожидаемый результат:** поля есть.
![3](https://user-images.githubusercontent.com/46268205/56980594-6c1a5c00-6b85-11e9-8de9-f09ab1943249.png)
![4](https://user-images.githubusercontent.com/46268205/56980600-6f154c80-6b85-11e9-9196-6175b4cdfce1.png)

**Comment by KahjuksEi** [comment]
@fr0zen что за поля должны быть?

**Comment by ghost** [comment]
исправлено.
