### ISSUE TITLE
Рэалізаваць функцыянал для "Забыліся пароль" (forget password)

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#396]
http://127.0.0.1/doika/doika/dashboard/password/reset/token

Болей інфы тут
 Фронтэнд. Вокны лагіна і ўзнаўлення пароля #50

**Comment by rizomaa** [comment]
@lptn твая спасылка ідзе на лакальны сэрвер

**Comment by alies-dev** [comment]
@rizomaa 
я ведаю, болей жа пакуль няма ніякіх сайтаў дзе круціцца дойка апошняя з develop, так?

**Comment by rizomaa** [comment]
@lptn @fr0zen учора планаваў наладзіць тэставы варыянт з develop

@fr0zen ёсць тут навіны?
