### ISSUE TITLE
Канфлікт роўтараў Laravel і Vue

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#398]
Трэба зрабіць фільтр, каб роут /campaigns/{campaign} ->  dashboard.campaigns.update спрацоўваў толькі калі параметр {campaign} лічбавы. Фармат [0-9]+

**Comment by lptn** [comment]
@fr0zen 
Якая мэта? Якую праблему хочаш вырашыць?

**Comment by fr0zen** [comment]
@lptn зараз такая сітуацыя, што пры звароце да роута напрыклад  /campaigns/{campaign}/edit (яго няма у laravel routes ) laravel наўпрост адказвае 404.  Але мне патрэбна, каб роуты фармата /campaigns/<number>/edit апрацоўваліся праз https://github.com/diglabby/doika/blob/2e2a56e759f785999422487a9dc52e8fa7150980/routes/dashboard.php#L28, бо потым яны апрацуюцца дадаткова роутэрам vue. Валідацыя павінна дапамагчы у гэтай справе.

**Comment by lptn** [comment]
@fr0zen 
Дзякуй, сення ці заўтра займуся

**Comment by alies-dev** [comment]
зроблена, закрываю
