### ISSUE TITLE
Бэкэнд. Рэалізаваць апрацоўку дадзеных данэйцера. 

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#40]
когда плательщик будет делать платеж он будет оставлять нам свои данные.
Необходимо реализовать php класс наследующий дефолтный класс Request laravelа для валидации данных. Более подробно: https://laravel.ru/docs/v5/validation

**Comment by rizomaa** [comment]
Двайная праверка уведзеных дадзеных

**Comment by lptn** [comment]
@Tyuba4 
З якою мэтаю будзе валідзіраваць? Ад PG прыходзяць памылкі валідацыі ўсе адно, так?

**Comment by fr0zen** [comment]
@lptn не ўяўляю каштоўнасць гэтай issue, зачыняю
