### ISSUE TITLE
Тэх пытанне: Як захоўваем налады плацежных шлюзаў у ДБ

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#401]
Зараз у нас маюцца табы для наладак некалькіх агрэгатараў. Трэба вырашыць, як іх захоўваем. Ці пакуль проста як key:value у табліцы settings, або ствараем асобную табліцу, Але тады прыйдзецца рабіць звязку Кампания -> агрэгатар (адзін к аднаму). Што думаеце на гэты конт  @lptn @Tyuba4 ?

**Comment by lptn** [comment]
@fr0zen 
> агрэгатар 

гэта што такое, плацежны шлюз?

**Comment by fr0zen** [comment]
@lptn так, дакладна

**Comment by lptn** [comment]
> Але тады прыйдзецца рабіць звязку Кампания -> агрэгатар (адзін к аднаму). Што думаеце на гэты конт

Так, я думаю гэта лепшае рашэнне, але на дадзены момант я б не чапаў гэта -- новыя шлюзы будуць у лепшым выпадку ў v1.4 толькі

**Comment by fr0zen** [comment]
@lptn @Tyuba4 тады я буду захоўваць іх наўпрост у табліцу, ок. На мой погляд таксама найлепшы варыянт зараз. @lptn дзякуй за ўдакладненне

**Comment by rizomaa** [comment]
@fr0zen 

Вельмі мала верагодна, што адна арганізацыя будзе карыстацца адначасова двума агрэгатарамі, таму ўсе кампаніі маюць адзін шлюз у агрэгатара. 

Калі ласка не пладзіце шмат наладак, бо яны будуць з большага не патрэбныя. 

@lptn @Tyuba4

**Comment by rizomaa** [comment]
@lptn https://trello.com/c/SaP88sEG/
