### ISSUE TITLE
Спрасціць (аўтаматызаваць) міграцыю з Doika v1 => v2

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#408]
У нас ёсць пытанне, 

1. На сёння каля 15 арганізацый устанаўліваюць або ужо карыстаюцца Doika.
2. Ім рана ці позна захочацца абнавіцца. 

Што будзем рабіць у дадзеным выпадку?

1. Ствараем мігратар для аднаўлення версій ужо зараз (не прама зараз, на ітэрацыі 1.4)
2. Дапамагаем арганізацыям ручкамі зрабіць абнаўленне з 1.2 на 1.3 і прадумваем мігратар з 1.3. на 1.4

Вашы думкі? @fr0zen @lptn @KahjuksEi @cema93 @Tyuba4

**Comment by lptn** [comment]
@rizomaa 
так, можна зрабіць мігратар (магчыма з нейкімі абмежаваннямі, але хутчэй за ўсе паўнавартасны)

Вядома ж рабіць яго не зараз а як будзе ўвесь галоўны функцыянал рэалізаваны

> ітэрацыі 1.4

калі каротка, то мне здаецца што гэты ітэрацыйны падыход у яго багучым выкананні -- не вельмі добрая штука: мне здаецца версіі дойкі лепей адвязаць ад спрынтоў, выкарыстоўваць semver 2.0 (MAJOR.MINOR.PATCH схема, новая фіча фіча можа быць пасярэдзіне спрынта) -- будзем рэлізіцца часцей і ў распрацоўшчыкаў з'явіцца ментальная легкасць у дачыненні рэлізаў і фіч. Асабліва важна рэлізіць PATCH релізы часта каб усе маглі па-хуткаму абнавіцца 


>Дапамагаем арганізацыям ручкамі зрабіць абнаўленне з 1.2 на 1.3 і прадумваем мігратар з 1.3. на 1.4

Такі варыянт таксама падыходзіць! Калі арганізацыі гатовы згубіць старую статыстыку -- гэта крыта, мы можам свой рэсурс пісціцб на болей карысныя справы чым напісанне міграцый

**Comment by rizomaa** [comment]
Тут удзельнікі накідалі ідэі 

"Мозговой штурм по поводу миграции дойки.
1 Сделать понятный инсталлятор
2. Выбор функциональности
3. Перенос таблиц с конверсией данных
4. Добавить гайд "Как сделать все ручками"
5. Помощь с тех. помощью
6. Vip-версия с расширенными функциями
7.Простой для пользователя
8. SQL запрос
9. Ручной перенос информации (используя труд школьников , практикантов)
10. Обновление путем наложения версий
11. Создать инсталлятор для v1.3 с возможностью обновления 1.2
12. Создать json-файл для экспорта / импорта данных
13. API
14. Клиент-серверное взаимодействие
15. Откат версий
16. Создать файл Дистрибутив exe для скачки"

https://trello.com/c/hXxgmMAa/#comment-5cd05c7516397267d467df59

https://trello-attachments.s3.amazonaws.com/5afee29cdc7e2f274f42491b/5ccadd1da1f8312fbe959380/4658be4e53b59f5115129ee8db609f55/IMG_20190504_222758.jpg

**Comment by alies-dev** [comment]
@rizomaa 
мы можам апытаць арганізацыі ці рэальна ім патрэбна старая інфармацыя з дойкі 1.2? Можа проста хай яны дачакаюцца закрыцця кампаній і пасля усталюць новую версію? Мне падаецца ня варта гбляць час зараз (ці нават увосень) на міграцію. Я думаю называемся "doika 2.0" і не даем магчымасці міграцый. Калі камусці РЭАЛЬНА патрэбна -- хай намаюць за грошы кагосці з каманды а мы гэтыя напрацоўкі выкарыстаем для іншых арганізацый :)

Ну а усе наступныя версіі дойкі будуць з нармальнай міграцыяй, тут пытанняў не будзе

PS: а для doika 1.2 трэба выпусціць security update дзе прыбраць існуючыя бэкдоры -- там жа рэпутацыя важна, так?

**Comment by cema93** [comment]
Этот вопрос поднимался ещё в тот момент, когда  мы поняли, что структура базы изменится.

Личный опыт:
Я представитель одной из инициатив, которая пользуется doika(правда, я пользуюсь как ИП и на nginx). Мне было бы очень обидно потерять данные о платежах, которые есть на данный момент.


Я считаю, что стоит сделать отдельный php файл, который обновляет базу до состояния doika 1.3.
Не думаю, что стоит делать это частью инсталятора, потому что он надо только 10-ти организациям, которые используют данное решение. Причем, им это надо только 1 раз. Если встроим в инсталятор, то через месяц этот код будет болтаться как якорь.

**Comment by rizomaa** [comment]
@lptn 
так, думаю апытаем, калі зробім больш менш устойлівую кампаненту.

па шэтаму адчыняй новую картку, бо я упэўнены, што у нас добры код у 1.2 =)
"PS: а для doika 1.2 трэба выпусціць security update дзе прыбраць існуючыя бэкдоры -- там жа рэпутацыя важна, так?"

**Comment by rizomaa** [comment]
Пакуль закрываю картку, таму што большасць, хто карыстаецца  Дойка стваралі 1-2 кампаніі. Ім прасцей будзе яе перастарыць, чым на пісаць міграцыі версій 1.2 на 2. 

На старонцы адмінкі бачу толькі вельмі агульная інфа. Ні інфы па асобны данатам ці данацерам няма. Назва кампаніі, колькасць ахвяраванняў, вылічыня ахвяравання.  

Амагчыма актуальна прадумац гэты функцыянал для наступных версій з 2 на 3. Зараз не трэба парыцца дакладна. Згодны - лепей у належны час. 

@cema93 скажы калі ласка якую інфу нельга будзе скапіраваць напамяць са старона адмінкі. 
карацей гэта пакуль вельмі дарагая фіча, хто за яе будзе плаціць.
