### ISSUE TITLE
Вместо названий полей и подсказок стоит надпись  «labels.admin….»

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#415]
**ФР:** Вместо названий полей и плейсхолдеров стоит запись "labels.admin. ...". 

![1](https://user-images.githubusercontent.com/46268205/57200444-d58ad800-6f94-11e9-833e-de727d1d3eaf.png)
![2](https://user-images.githubusercontent.com/46268205/57200445-d58ad800-6f94-11e9-8806-0b78df465ead.png)
![3](https://user-images.githubusercontent.com/46268205/57200446-d58ad800-6f94-11e9-9793-42492b91d45e.png)
![4](https://user-images.githubusercontent.com/46268205/57200447-d6236e80-6f94-11e9-8cfe-c47c74438042.png)

**Comment by rizomaa** [comment]
@fr0zen можаш апісаць задачу на гэтыя багі, імі перапоўнена адмінка. адчуваю, што задача не складаная, як проаста трэба аформіць і перадаць іншаму чалавеку

**Comment by ghost** [comment]
@fr0zen После очистки целевой суммы сборов в поле "Колькасць" появляется плейсхолдер labels.admin...

![2](https://user-images.githubusercontent.com/46268205/57647392-83b50400-75cb-11e9-8b6d-53ac53b0a61a.png)

**Comment by ghost** [comment]
@fr0zen в форме редактирования кампании появляется поле с надписью "<iframe width='750' height='550' frameborder='0' src='/doika/doika/widget":

![1](https://user-images.githubusercontent.com/46268205/57923793-fe23a380-78ab-11e9-94ed-363d57eebebb.png)
