### ISSUE TITLE
Прыняць стандарт найменавання версій рэлізаў

### ISSUE THREAD

**Issue by alies-dev** [diglabby/doika#416]
Вырашыў перанесці гэтае пытанне ў асобную issue

Мы удо краналіся гэтага пытання https://github.com/diglabby/doika/issues/408#issuecomment-489330895 і https://github.com/diglabby/doika/issues/84#issuecomment-489715727

Мая прапанова:
## Semver

Выкарыстоўваем semver 2.0, што значыць па схеме MAJOR.MINOR.PATCH

- MAJOR: Ламанне адваротнай сумяшчальнасці  (напрыклад 2.0.0)
- MINOR: любая болей меней важкая новая фіча (напрыклад 2.15.0)
- PATCH: тут усе зразумела -- выпраўленне існуючага вункцыянала (напрыклад 2.0.14)

Умовы для doika 3.0:
 - пераход на новую мінімальную версію PHP
 - змена патрабавання для кліентскай часткі (да пабачэння IE)
 - нейкія каардынальныя змены ў архітэктуры
 - хапнуць хайп)

На выхадзе плануем:
 - [ ] Мець агульнапрынятае дакументаванае рашэнне (ЯКАЯ схема/прынцып нумерацыі)
 - [ ] Тэхнічную дакументацыю ЯК мы прастаўляем новую версію (чэкліст)

________
## Смежнае

- Аўтаматычнае стварэнне архіва-істалятара для рэлізаў #160
- Рэалізаваць аўта-дэплоймент на тэставыя асяродкі #319

**Comment by alies-dev** [comment]
@rizomaa 
@cema93 
@fr0zen 
Хацелася б пачуць вашы меркаванні

**Comment by alies-dev** [comment]
# Альтэрнатывы
## Хаос
Вы ведаеце прыклады :)

## Календарны падыход
мажорная версія кожныя X тыдняў ці месяцаў

Хто выкарыстоўвае: Angular, Chrome, Firefox

Кожныя X тыдняў ці месяцаў згодна плану выпускаеюцца новыя версіі з breaking changes. Гэта робіцца не раптоўна: звычайна 2+ версіі таму стары API пазначаецца як deprecated

Такі падыход добры для праектаў з public API і добрай прадказальнасцю выкаткі версій (не мы)

## EPIC+semver

некаторыя праекты выкарыстоўваюць такі падыход: EPIC + semver. Прыклады: Laravel, Yii


Болей тут https://en.wikipedia.org/wiki/Software_versioning#Change_significance

## Цонта-няцотны

- Цотныя - для LTS рэлізаў
- Няцотныя - для не-LTS рэлізаў

Добра ўжываецца з semver

**Comment by fr0zen** [comment]
@rizomaa @lptn на мой погляд Semver 2.0 даволі просты і падыходзіць добра пад нашыя патрэбы. Астатнія пакінем карпарэйтам)

**Comment by cema93** [comment]
> Хацелася б пачуць вашы меркаванні

Я только за :)

**Comment by rizomaa** [comment]
@lptn 

"Выкарыстоўваем semver 2.0, што значыць па схеме MAJOR.MINOR.PATCH

MAJOR: Ламанне адваротнай сумяшчальнасці (напрыклад 2.0.0)
MINOR: любая болей меней важкая новая фіча (напрыклад 2.15.0)
PATCH: тут усе зразумела -- выпраўленне існуючага вункцыянала (напрыклад 2.0.14)"

можна прыняць такі падыход. прапаную тады запісаць дзесці у вікі, бкаб больш не падымалася гэта пытанне.

**Comment by alies-dev** [comment]
добра. здаецца усе хто хацеў выказаліся за semver 2.0 , прымаем і закрываем, вікі я абнавіў: https://github.com/diglabby/doika/wiki/%D0%92%D0%B5%D1%80%D1%81%D1%96%D1%8F%D0%BD%D0%B0%D0%B2%D0%B0%D0%BD%D0%BD%D0%B5
