### ISSUE TITLE
Зрабiць FAQ па працы з PTR запісамі в DNS

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#42]

**Comment by svetasemashko** [comment]
@Tyuba4 што такое PTR?

**Comment by cema93** [comment]
http://g.zeos.in/?q=PTR%20%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D1%8C

**Comment by falanster** [comment]
@ilyaaki гэта картка трохі пазней будзе... але можа паціху яе абсіжваць =)

**Comment by ilyaaki** [comment]
PTR-запісы, як правіла, кіруюцца ў правайдэра (оўнэра IP-адраса).

**Comment by falanster** [comment]
@ilyaaki 
Так мы зараз абдумваем, якия кроки павінна зрабіць арганізацыя каб націфікейшны з doika не шлі ў спам.

Ці маеш нейкае бачанне 
1. як гэта можа быць арганізавана на шарэхостынгу
2. якія дзеянні могуць зрабіць арганізацыя для гэтага
?

**Comment by fr0zen** [comment]
На мой погляд гэта оффтоп у кантэксце распрацоўкі модуля, калі паўстане востра, запішам на вікі
