### ISSUE TITLE
Дадаць абавязковы чэкбокс "я згодны з правіламі" на віджэт

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#420]
Зараз можна правесці данэйт без згоды з правіламі - пафіксіць

**Comment by fr0zen** [comment]
@rizomaa @nastyafrosty што робім калі чалавек не праставіў птушачку на згоду па terms of use. Выводзім popup паведамленне, альбо пішам знізу, можа яшчэ якія варыянты есць?

**Comment by rizomaa** [comment]
@fr0zen вакно-папярэджанне дастаткова. @nastyafrosty ?
