### ISSUE TITLE
Памылка пры атрыманні redirect_url aд bepaid

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#422]
Пры спробе зрабіць запыт да Bepaid атрымаў памылку аб тым, што немагчыма атрымаць дадзеныя з неіснуючага аб'екта. Наступная страка: https://github.com/diglabby/doika/blob/bdfe0a9cfbc928de24f33f8efcb0c9875415d19a/app/Services/PaymentGateways/BePaidPaymentGateway.php#L89
https://github.com/diglabby/doika/blob/bdfe0a9cfbc928de24f33f8efcb0c9875415d19a/app/Services/PaymentGateways/BePaidPaymentGateway.php#L91
Чаму мы спрабуем выцягнуць redirect_url з поля сheckout->token? Вельмі гарачая штучка)

**Comment by alies-dev** [comment]
fixed by 5cc0d40e709cd14e22414be92bbd1c179e557f29

**Comment by fr0zen** [comment]
@lptn 👍

**Comment by alies-dev** [comment]
@fr0zen 
Працуе? Бо я не мог праверыць пад час фіксу

**Comment by fr0zen** [comment]
@lptn так, зараз усе добра
