### ISSUE TITLE
После переустановки пропала админка модуля

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#423]
**Шаги для воспроизведения:**
1. Переустановить Doika 1.3 по инструкции (Win + Openserver);
2. запустить модуль;
3. заполнить e-mail и пароль на странице авторизации;
4. нажать Логин.

**Фактический результат**: все поля на странице авторизации сместились в левую сторону. При входе в админку открывается _пустая страница_ с неработающими ссылками.

Версия Doika: 1.3
Платформа и версия: Windows10
Браузер и версия: Chrome 73.0.3683.103/Opera 58.0.3135.132

**Приложения:**
![3](https://user-images.githubusercontent.com/46268205/57391786-db1c3400-71c7-11e9-96c8-33dd2aff65ab.png)
![4](https://user-images.githubusercontent.com/46268205/57391799-e40d0580-71c7-11e9-8c5d-a80359204bcf.png)
![1](https://user-images.githubusercontent.com/46268205/57391815-ea02e680-71c7-11e9-807d-01625c8f3acf.png)
![2](https://user-images.githubusercontent.com/46268205/57391816-ea9b7d00-71c7-11e9-8a58-645d14bbc18e.png)
![5](https://user-images.githubusercontent.com/46268205/57392040-71505a00-71c8-11e9-89c0-430e6cc680a3.png)

**Comment by alies-dev** [comment]
@Olya147 
Правер калі ласка ці існуе ў цябе файл `.env`

А калі існуе - якое значэнне у пераменнай `APP_ENV`? (значэнне мусіць быць `local`)

**Comment by alies-dev** [comment]
@Olya147 
наконт npm -- я паправіў докі, трэба запускаць `npm run dev`

**Comment by ghost** [comment]
@lptn Теперь работает. Спасибо.

**Comment by alies-dev** [comment]
@Olya147 дык у чым была праблема? Нам трэба ведаць тыповыя праблемы якія узнікаюць у стафа і інтэгратараў

**Comment by ghost** [comment]
@lptn В том случае у переменной APP_ENV тоже было значение local. 
Видимо, проблема возникла из-за исправленной команды.
