### ISSUE TITLE
Интуитивно непонятный интерфейс при валидации поля Email на странице авторизации

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#424]
**Шаги для воспроизведения:**
1. открыть страницу авторизации;
2. ввести произвольный эл. адрес в поле e-mail; 
3.  ввести произвольный пароль;
4. нажать Логин;
5. нажать "Х" в поле e-mail. 

**Фактический результат**: кнопка некликабельна. Введённое значение не удалено.

![11](https://user-images.githubusercontent.com/46268205/57465428-40832a00-7287-11e9-820f-b9540688f201.png)

**Тестовые условия:**
Версия Doika: 1.3
Платформа и версия: Windows10
Браузер и версия: Chrome 73.0.3683.103/ Opera 58.0.3135.132/ Firefox 60.6.3esr

**Comment by KahjuksEi** [comment]
Это не кнопка, просто фон, если надо сделать кнопку, то @fr0zen подскажи где редактить

**Comment by ghost** [comment]
Нерабочие кнопки в форме создания новой кампании":

![1](https://user-images.githubusercontent.com/46268205/57646084-6df20f80-75c8-11e9-94a4-e53ffa90ff39.png)

**Comment by fr0zen** [comment]
@Olya147 па сэнсу гэта паказчыкі валіднасці/неваліднасці поля, але калі ты не зразумела адразу, значыць UX зроблены не вельмі)
