### ISSUE TITLE
Рэалізаваць адпраўку-прыем дадзеных аб наладках плацежных сістэм

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#425]
Захаваць і рабіць выбарку дадзеных па наступных наладках:

- [x]  Bepaid Market Id
- [x]  Bepaid Market Key
- [x]  Terms Of Use text
- [x]  Min payment
- [x]  Max payment

**Comment by fr0zen** [comment]
#426 тут фікс

@lptn крута было б зрабіць, каб наладкі пры плацяжах цянуліся з БД, а не з .env

**Comment by alies-dev** [comment]
@fr0zen 
добра, зраблю
