### ISSUE TITLE
 Фронтэнд пераключэнне плацёжных сістэмаў ў канфігурацыі модуля

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#43]

**Comment by falanster** [comment]
прапарцуем бліжэй да другой паловы ітэрацыі 1.3

**Comment by fr0zen** [comment]
@fr0zen Рэалізацыя опцый плацежных сістэм праз табы.

**Comment by Alexey-Chechukov** [comment]
@fr0zen  удакладни калиласка што тэставаць

**Comment by rizomaa** [comment]
Зрабіць працуючы таб  з назвай "Artpay"

- [ ] 1. Скапіраваць элементы з існуючай тады, якая адчыяецца па змоўчанню.
- [ ] 2. І уставіць ў табу "Artpay"
