### ISSUE TITLE
Рэалізаваць API endpoint каб сцягваць дадзеныя пра падпіскі для dashboard

### ISSUE THREAD

**Issue by alies-dev** [diglabby/doika#433]
@fr0zen 
нам жа трэба такі функцыянал ці не? Я пакуль на франце гэтага не бачу, на РТБ я такога не знайшоў

@nastyafrosty 
@rizomaa 
Я думаю у адмінаў дойкі будзе зрэдку узнікаць патрэба выдаліць некаторыя падпіскі самастойна (будуць скардзіцца карыстальнікі ці проста ў межах тэставання). Што думаеце?

**Comment by alies-dev** [comment]
@fr0zen 
Трэба такі endpoint?

**Comment by fr0zen** [comment]
@lptn так, было б крута

**Comment by alies-dev** [comment]
@rizomaa 
@fr0zen 
тут устае пытанне: пры выдаленні падпіскі з адмікі ці выдалем падпіску на шлюзе?

Я думаю -- так! Але трэба каб гэта было відачона з інтэрфейсу (modal dialog?)

**Comment by fr0zen** [comment]
@lptn так, с шлюза таксама, так, прыйдзецца рабіць мадаль без варыянтаў

**Comment by alies-dev** [comment]
@fr0zen 
зараз толькі шбачыў што я гэта ужо прадугледзіў і рэалізаваў)

дарэчы delete реквэст прымае параметр "reason": можам у мадальцы апцыянальна пытаць прычыну адпіскі

**Comment by fr0zen** [comment]
@lptn ты прапанаваў класную фічу, трэба будзе яе ў бэклог занесці)

**Comment by nastyafrosty** [comment]
@lptn уточню. фича, которая поможет админу отписать донэйтера от кампании?

**Comment by alies-dev** [comment]
@nastyafrosty 
так. Было б класна для гісторыі мець прычыну адпіскі (насамрэч я гэта ужо рэалізаваў і мы піўам дэфолтавы тэкст, але модам і кастамны)

**Comment by rizomaa** [comment]
> @rizomaa
> @fr0zen
> тут устае пытанне: пры выдаленні падпіскі з адмікі ці выдалем падпіску на шлюзе?
> 
> Я думаю -- так! Але трэба каб гэта было відачона з інтэрфейсу (modal dialog?)

чаму карыстальнику цікавы такія тэзнічныя дэталі? проста выдаляей адюсюль з падпіспі. пакідаем толькі статыстыку карыстальніка ў базе модуля. @lptn
