### ISSUE TITLE
Баг перанакіравання

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#436]
@lptn Пры заходзе на старонку dashboard/login калі ўжо залагінены, перанакіроўвае на /api/campaigns
Чакаемыя паводзіны: павінна перанакіроўваць на /campaigns

**Comment by alies-dev** [comment]
Я гэта пафіксіў пару гадзін таму, абнавіся і пераправер калі ласка

**Comment by fr0zen** [comment]
👍 Працуе!
