### ISSUE TITLE
Перанакіраванне на старонку вынікаў данэйта

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#437]
@lptn ці можам зрабіць, каб пасля праводкі транзакцыі вяртала на старонку кшталту
```php
final class CampaignDonationResultController extends Controller
{
    public function show(Campaign $campaign, Request $request)
    {
        if($request->get('status') == 'successful')
            return redirect('/doika/widget/campaigns/1/donation-result/successful');
       if($request->get('status') == 'failed')
            return redirect('/doika/widget/campaigns/1/donation-result/failed');
    }
}
```
Паводле https://docs.bepaid.by/ru/gateway/statuses

**Comment by alies-dev** [comment]
@fr0zen 
То бо проста хочаш зусім розныя старонкі а не проста розныя GET параметры адной, так? Чаму?

**Comment by alies-dev** [comment]
@fr0zen 
і ці патрэбна {campaign} ва URI ці проста проста /doika/widget/donations/success (зараз гэта /doika/widget/campaigns/{campaign}/donation-result) ці мо нават `/doika/widget/donations/{donation}` ? Што табе на гэтай старонцы патрэбна? Ты будзеш HTML збіраць праз JS ці можам SSR выкарыстаць?

**Comment by fr0zen** [comment]
@lptn на старонцы мне патрэбны толькі сам статус, каб адмалеўваць малюнкі і id кампаніі, каб ведаць, куды вяртаць карыстальніка. Гэта ў ідэале. Праз свой роутэр я забяру id і status, а потым выкарыстаю іх як трэба

**Comment by alies-dev** [comment]
@fr0zen 
дык зараз жы вяртае на `/campaigns/{campaign}/donation-result?status={status}` дзе усе есьць:
 - campaign id
 - status

Такі варыянт не падыходзіць? Я нечага не разумею?

**Comment by fr0zen** [comment]
@lptn зараз вяртаецца view
```
 return view('widget.pages.campaigns.donation-result', [
            'campaign' => $campaign,
            'status' => $request->get('status'),
        ]);
```

мне было б лепш, каб быў проста рэдырэкт на старонку кшталту /campaigns/{campaign}/donation-result/successful

**Comment by alies-dev** [comment]
@fr0zen 
>мне было б лепш, каб быў проста рэдырэкт на старонку кшталту >/campaigns/{campaign}/donation-result/successful

дык табе прынцыпова каб статус быў не GET падаметрам а часткаю base URL?

напрыклад мы рэдзірэкцім з біпэйда адразу на `/campaigns/{campaign}/donation-result/successful`, што мы тут мусім вяртаць: в'юху ці json?

**Comment by fr0zen** [comment]
@lptn так, часткай base-url.
Можна проста перакінуць карыстальніка па гэтаму шляху? Роуты widget ssr зробяць сваю справу

**Comment by alies-dev** [comment]
@fr0zen 
Амаль усе можна, але ж я хачу зразумець прыроду такіх патрабаванняў)

**Comment by rizomaa** [comment]
@lptn @fr0zen тут размова пра кліентскуя частку?

**Comment by fr0zen** [comment]
@rizomaa так, @lptn менавіта частка url, таму што мне будзе даволі зручна апрацоўваць тады vue-роутэрам.

**Comment by rizomaa** [comment]
@fr0zen можна зрабіць каб пры атрыманні выніка вакно браўзера перамяшчалася у тую ж воласць па якару. Ці гэта ў іншую таску лепей закінуць?

**Comment by fr0zen** [comment]
@rizomaa не, тут трохі іншае зараз, якары ўжо не патрэбны)

**Comment by rizomaa** [comment]
@fr0zen што іншае, патлумач?

**Comment by fr0zen** [comment]
@rizomaa у папярэдняй версіі после правядзення данэйта старонка перагружалася, таму трэба было якарыцца, каб перакінуць карыстальніка к секцыі модуля. Зараз ужо такі механізм не патрэбны, бо старонка не перагружаецца.

**Comment by rizomaa** [comment]
@fr0zen дзякуй

**Comment by alies-dev** [comment]
@fr0zen 
Гатова
