### ISSUE TITLE
Клас, які будзе пераключаць паміж плацёжнымі сістэмамі

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#44]

**Comment by rizomaa** [comment]
@Tyuba4 @lptn @fr0zen тут нам важна, які патэрн праектавання лепей далучыць, каб пакінуць сабе магчмасць маштабаваць плацёжны шлюзы

**Comment by lptn** [comment]
@Tyuba4 
можаш апісаць што трэба, а то нічога не ясна ЧАМУ і НАВОШТА трэба нешта переключаць
