### ISSUE TITLE
Пользователь не авторизован после ввода верных логина и пароля

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#446]
**Шаги для воспроизведения:**
1. открыть сайт;
2. в поле "E-mail адрас" ввести **demo@example.com** 
3. в поле "Пароль" ввести password;
4. нажать "Лагин"

**Фактический результат:** сообщение  "E-mail и пароль не існуюць."
**Ожидаемый результат:** пользователь авторизован.

**Тестовые условия:**
Версия Doika: 1.3
Платформа и версия: Windows10
Браузер и версия: Chrome 73.0.3683.103/ Opera 58.0.3135.132/ Firefox 60.6.3esr

**Comment by ghost** [comment]
@lptn @fr0zen логин и пароль, указанные в инструкции, не менялись?

**Comment by alies-dev** [comment]
@Olya147 
Прабач, гэта тым у 20:30 без абвяшчэння вайны памянілі на `demo@example.com` + `demo`

**Comment by alies-dev** [comment]
PS: Абнавіў інфу ў wiki
