### ISSUE TITLE
Рэалізаваць вывад дадзеных пра admin'аў як асобную старонку dashboard

### ISSUE THREAD

**Issue by alies-dev** [diglabby/doika#448]
каб паказваць на старонцы doika/dashboard/admins

**Comment by alies-dev** [comment]
@fr0zen 
бэкэнд зроблены, як зробіш фронт -- закрый калі ласка issue

**Comment by fr0zen** [comment]
#498 тут есць пытанне, глянь калі ласка

**Comment by alies-dev** [comment]
@fr0zen 
>#498 тут есць пытанне, глянь калі ласка

адказаў, але думаю тое пытанне не блочыць гэтую issue. "Рэалізаваць функцыянал аднаўлення пароляў адміністратара #498" гэта проста апцыянальны дадатак да бягучай issue

**Comment by rizomaa** [comment]
@lptn @fr0zen калі ласка не парцеся па гэтай ішшус. вельмі чакаем рэліз таго, што зараз ужо працуе.

**Comment by rizomaa** [comment]
арганізацыям на сёння не патрэбны асобныя адміны, 
калі ласка абмяжуйцеся простай старонкай уводу новага пароля для аднаго карыстальніка.
@lptn @fr0zen 

магчыма вернемся да суммы адмінаў зімой 2020
