### ISSUE TITLE
Наладзіць тэставыя асяродак

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#45]
- [x] Куды зліваем код з dev branch
- [x] Якія доступы да адмінкі
- [ ]

**Comment by falanster** [comment]
@fr0zen распавядзі, які зараз алгартым тут, магчыма янешта наладжу...

**Comment by fr0zen** [comment]
- [ ] Наладзиць .htaccess для разгортвання на дамене.
- [ ] Падправіць роуты laravel.
- [ ] Падправиць роуты на vue @fr0zen 
- [ ] Наладзиць задачы у jenkins для разгортвання непасрэдна на дамен

**Comment by rizomaa** [comment]
@fr0zen тут неяк шмат чэкбоксаў патлумаш, што з гэтага яшчэ варта зрабіць

таксама апішы наогул дзесці як функцыянуе тэставы асяродак, каб удзельнікі ведалі як ім наладжваць яго таксама. 

ці зачыняем ішу?
