### ISSUE TITLE
Ці робім версію 1.3 - > 2.0 ?

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#456]
у сувязі з прыняццем новага падыхода версіравання https://github.com/diglabby/doika/issues/416
цалкам падтрымліваю ідэю зрабіць гэту версію пасля адладкі 2.0

зараз можна выпускаць 2.0.0alpha пакуль вы не давялі да розума =)

@lptn @fr0zen @Tyuba4 @cema93 @KahjuksEi @Olya147 @maxmatoha

**Comment by alies-dev** [comment]
@diglabby/core 
# Галасавалка 1.3 vs 2.0
😕 ня ведаю
👎 1.3
👍 2.0

**Comment by alies-dev** [comment]
@rizomaa 
>зараз можна выпускаць 2.0.0alpha пакуль вы не давялі да розума =)

А навошта, калі не сякрэт?)

**Comment by rizomaa** [comment]
> @rizomaa
> 
> > зараз можна выпускаць 2.0.0alpha пакуль вы не давялі да розума =)
> 
> А навошта, калі не сякрэт?)

@lptn папярэдзіць карыстальнікаў і устаноўшчыкай, каб строга не судзілі, калі там будзе шмат багаў. маеш сваё бачанне?

**Comment by alies-dev** [comment]
@rizomaa 
амаль згодны, не ясна што такое "зараз"

Мне падаецца на паліраванне рэлізу дзесьці тыдзень трэба, тады і можна тэгаваць як (напрыклад) `2.0.0 RC1`

А пакуль што мы  і так ведаем што рэліз сыраваты, лепей не тэгаваць мне падаецца

**Comment by rizomaa** [comment]
@lptn 
пад зараз я маю на ўвазе, калі вось ужо фіча гатова, але не адтэшчана талкова. трэба яе уключаць у рэліз і даваць супольнасці і юзаць і тым самым тэставаць. ну карацей рабіць як мага хуткія рэлізы з папярэджаннем пра іх якасць, так з гэтам добра спраўляюцца alpha, beta і rc. 

вообшэм гэта прапанова. калі лічыш. што занадта складана, можна не парыцца. проста рабіце рэліз з лічбамі як мы дамовіліся

**Comment by alexap13** [comment]
Прашу прасціць: Лепей тая сістэма, якая стандартызавана (апісана) і панятна, як камандзе,так і карыстальнікам.

**Comment by alies-dev** [comment]
@rizomaa 
усе за 2.0 з тых хто хацеў выказацца, прынята, закрываем?

**Comment by rizomaa** [comment]
@lptn так, прынята рашэнне)
