### ISSUE TITLE
Возможно создание двух идентичных кампаний

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#458]
**Шаги для воспроизведения:**
1. создать две одинаковые кампании.

**Фактический результат:** обе кампании успешно сохранены.
**Ожидаемый результат:** вторая кампания не сохранена, появляется сообщение об ошибке (напр. "Название не уникально"). 

![1](https://user-images.githubusercontent.com/46268205/57957551-58048780-7905-11e9-823b-481d83fe58f3.png)

**Тестовые условия:**
Версия Doika: 1.3
Платформа и версия: Windows10
Браузер и версия: Chrome 73.0.3683.103/ Opera 58.0.3135.132/ Firefox 60.6.3

**Comment by rizomaa** [comment]
@Olya147 тут не парся. гэта правяраць няўдзячная штука, пакідаем гэту фічу на роздум самім арганізацыям. Яны самі прымуць рашэнне, ці патрэбна ім дзве кампаніі.
