### ISSUE TITLE
При закрытии формы кампании сбрасываются настройки переключателей

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#459]
**Шаги для воспроизведения:**
1. Открыть форму создания кампании;
2. заполнить все поля;
3. перевести в активный режим все переключатели;
4. нажать "Захаваць";
5. открыть только что созданную кампанию.

**ФР:** переключатели "Верхни банэр" и "Паласа прагрэсу" неактивны.
**ОР:** все переключатели активны.

**Тестовые условия:**
Версия Doika: 1.3
Платформа и версия: Windows10
Браузер и версия: Chrome 73.0.3683.103/ Opera 58.0.3135.132/ Firefox 60.6.3

**Comment by darth-tesla** [comment]
Сегодня хотел поработать над этой задачей и обратил внимание, что ни один из переключателей не делает ровным счётом ничего, т.е. они просто висят как "декорации". Хоть они и имеют директиву v-model, но при переключении состояние не меняется на true или false. И первым делом, как я понял, мне нужно "научить" эти переключатели менять состояние полей, прописанных в этом самом v-model.

Однако куда отправляется форма после сабмита и откуда я могу вытянуть информацию об уже созданной компании? Ведь именно там, как я понимаю и храниться актуальное состояние тумблеров.

**Comment by rizomaa** [comment]
Прывітанне @darth-tesla ,

Гэта задача можа быць звязана з бэкам трохі, трэба праверыць код... Наогул зацані свае сілы перад пачаткам. Кали нешта пакуль заскладана, я магу узяць частку на сябе.

Бачу такі алгарытм:
1. Правяраем ці ёсць апрацоўшчыкі для гэтых фішак на бэку.
2. Калі ёсць дапісваем у адпаведных кампанентах запіс і чытанне на франце.
3. Калі няма 
3.1. дапісваем адпаведныя апрацоўшчыкі на бэку.
3.2. дадаем апрацоўшчыкі на франце па вобразу і і падобію іншых*
4. Адпаведна ствараем дзве новыя ішус: для рэалізацыі першага тумблера - бачнасці кампаніі. і другога - гэта бачнасці  верхняй гарызантальнай панэлі.
![Selection_059](https://user-images.githubusercontent.com/9870374/85296482-236ce300-b4aa-11ea-99a9-85c892a1efb3.png)

Каб працавалася прасцей, тлумачу
1. Першае поле - гэта тумблер бачнасці. іншамі словамі калі поле актызна, кампанія не павінна выводзіцца, хаця айфрэйм яе можа быць на старонцы. Гэта поле павінна уключацца аўтаматычна, калі тэрмін кампаніі сцёк.
2. Другое поле - гэта тумблер верхняй гарызантальнай панэлі. Як гэта зараз працуе на doika 1.2 прыклад тут https://doika.falanster.by/

**Comment by darth-tesla** [comment]
@rizomaa Я попробую найти обработчики на бэке, но править ничего не буду, т.к. обязательно что-нибудь поломаю (опыта на бэке мне недостаточно). Если до завтра найду что-нибудь, то дам знать.
