### ISSUE TITLE
Стварыць табліцы у БД (карыстальнік, план падпіскі. падпіска)

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#46]

**Comment by Tyuba4** [comment]
Для тестирования задачи необходимо сделать команду по выполнению миграций(php artisan migrate). Проследить нету ли ошибку при выполнении миграций, и проверить наличие необходимых таблиц столбцов (список будет в пулл реквесте #162)

**Comment by rizomaa** [comment]
@Tyuba4 як тут у цябе ідзе справа?

**Comment by Tyuba4** [comment]
@rizomaa Это issue как-то ненавязчиво мигрировало в #217

**Comment by rizomaa** [comment]
@Tyuba4 лепей тут усё вядзі. Бо я бачу, што @pro2s павольна адзкавае на лісты. таму гэта задача нікуды не дзяваецца да цябе. тым больш у #217 няма ні табліцы 
1. транзацкцый
2. план падпіскі. 
3. падпіска
таму тут апісвай. калі мы зробім раней табліцу данэйцераў тут проста там адпішамся. 

ці ў цябе іншае бачанне?

**Comment by rizomaa** [comment]
@Tyuba4  па выніках размовы сёння
мы цябе падтрімліваем у любых тваіх пачынаннях.
магчыма на
Сушы думкі дапамогуць табе
1. Ствараем табліцы donators, transactions, subscriptions (plans умяшчаем у subscriptions)
2. Данатар можа мець некалькі падпісак (табліца subscriptions)
3. transactions мае поле  subscription_id (можа мець знаxэнне NULL для аднаразовых плацяжэй)
4. Усе астатняе як мы прагаворвалі.
5. transactions - уключае created, donator_id, [updated - для асинхронных], paymentgateway_id, paymentgateway_transaction_id
6. suиcriptions уключае deleted_at (для статыстыкі)

Сумесная творчасць ад @fr0zen @lptn @rizomaa

**Comment by lptn** [comment]
@Tyuba4 
@fr0zen 
@rizomaa 

# Сэт пытанняў  №1

1. Закрываем кампанію (уручную  ці аўтаматычна) -- спыняем ці выдаляем усе subsriptions?
2. Ці можа адмін змяніць дату зканчэння кампаніі? Калі так -- што будзе з падпіскамі на яе?
