### ISSUE TITLE
Макет афармлення модуля не захоўваецца

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#460]
**Шаги для воспроизведения:**
1. создать кампанию;
2. в разделе "Знешні выгляд" изменить цвет фона.
3. нажать "Прыстасаваць".

**ФР:** появляется сообщение "exceptions.general".
**ОР:** выбранные цвета сохранены. Макет применён к странице сайта http://doika/doika/doika/widget/campaigns/   .

**Тестовые условия:**
Версия Doika: 1.3
Платформа и версия: Windows10
Браузер и версия: Chrome 73.0.3683.103/ Opera 58.0.3135.132/ Firefox 60.6.3

**Comment by ghost** [comment]
[doika-1560870138272.log](https://github.com/diglabby/doika/files/3302137/doika-1560870138272.log)

**Comment by rizomaa** [comment]
гэта задача не гарачая, наогу выходзіць за скоўп і нідзе неабмяркоўвалася загаддзя

**Comment by darth-tesla** [comment]
Смею предроложить, что этот баг так же исплавлен и неактуален, т.к. цвет меняется и ошибок не возникает.

**Comment by rizomaa** [comment]
@darth-tesla дзякуй за тэставанне. пакуль перамесцім у рэў'ю гэту картку.
