### ISSUE TITLE
Зрабіць падпіскі гнуткімі для працы з любымі разумнымі інтэрваламі

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#462]
Z Services/PaymentGateways/BePaidPaymentGateway.php vynesti statychnye dadzenye u techku config. Stvaryc' dlja getaga kanfig fajl.

**Comment by alies-dev** [comment]
@Tyuba4 
1. Якую праблему вырашаеш?
2. Што за статычныя дадзеныя?
3. Чаму ў канфіг файл?


Глядзі, без адказу на першае пытанне ў такой фурмаліроўцы гэтые issue не магчыма дэлегаваць каму-небудзь, трэба писаць лепей аписанне задач

**Comment by alies-dev** [comment]
ping @Tyuba4

**Comment by fr0zen** [comment]
@lptn мелася на ўвазе магчымасць захоўваць інтэрвал данэйту у базе ці ў канфігурацыонным файле і змяняць гэта значэнне праз інтэрфейс на фронце.

**Comment by alies-dev** [comment]
@fr0zen 
Прапаную захардкодзіць тыповыя інтэрвалы на франце (пакуль няма дызайну). Магчыма нікому і не будзе патрэбны (апроч тэсцераў) нейкі іншы варыянт чым `1 month`, а мы тут ускладнім усе і наварацім. Зараз backend цалкам гатовы да любых валідных інтэрвалаў (падчынаючы ад кантроллера, далей інтэграцыя з bepaid і далей webhook хэндлер)

Болей за тое, кантроллер на бэкэндзе патрабуе валідны параметр (гэта абавязковы параметр), але ж гэта не значыць што мы абавязаны паказваць гэтую опцыю карыстальнікам, так? 

Прапаную хардкодзіць і забыць на нейкі час (а issue закрыць, штурхануць апцыянальна дызайнера)


Ад цябе патрэбна зараз паправіць тут https://github.com/diglabby/doika/commit/ba5bd4fe4129175a3d703d73512317fbfb320a20#r33711114

**Comment by fr0zen** [comment]
@lptn згодны, што асноўныя пакуль трэба захардкодзіць. Падкажы калі ласка, я зараз перадаю інтэрвалы ў фармаце "P1H", але мне кажа, што фармат не валідны, як трэба перадаваць?

**Comment by alies-dev** [comment]
@fr0zen 
Глядзі тут https://en.wikipedia.org/wiki/ISO_8601#Durations

Для часу (а не дата-часу) трэба яшчэ дадаваць `T` (time): `PT1H`

Больш складаны вападак (які не падтымліваецца bepaid але агульную ідэю ты зразумеееш):
 - `P1YT1H`: 1 год + 1 гадзіна
 - `P1MT1M`: 1 месяц + 1 хвіліна
