### ISSUE TITLE
Напісаць тэкст імэйлаў па рэкурэнтным плацяжам

### ISSUE THREAD

**Issue by alies-dev** [diglabby/doika#464]
Файлы для рэдагавання
 - Паспяховае стварэнне падпіскі (зарам з першым плацяжом): ці патрэбны там такі імэйл?
 - Няўдалае стварэнне падпіскі https://github.com/diglabby/doika/blob/develop/resources/views/emails/subscriptions/charge--failed.blade.php
 - Удалая транзакцыя па падпісцы https://github.com/diglabby/doika/blob/develop/resources/views/emails/subscriptions/charge--success.blade.php

**Comment by alies-dev** [comment]
ping @rizomaa 
вось у межах гэтай issue трэба скласці тэкст, дапамажы калі ласка скаардынаваць людзей

**Comment by ghost** [comment]
Примеры писем можно найти по ссылке ниже. Пожалуйста, изучите их и (при необходимости) оставьте комментарии. 
https://docs.google.com/document/d/1CP19vpVUDnBsbQlVzZ0uP7CrpLjfZrCKk8Kw-6oKsY4/edit

**Comment by alies-dev** [comment]
@Olya147 
Дзякуй за добрую працу, я пакінуў нескалькі сваіх камэнтроў, галоўны з якіх самы верхні -- пра тэмы лістоў

**Comment by svetit** [comment]
Таксама пакінула некалькі каментароў, @Olya147

**Comment by ghost** [comment]
@lptn @svetit @fr0zen @rizomaa @alexap13 @nastyafrosty @KsenjaV Спасибо, я прочитала все замечания. Но нужно прояснить несколько моментов:
1) сообщения «Паспяховы платёж», «Падзяка за выраблены плацёж», «Аплата не прайшла»  - это, скорее, не письмо на электронную почту, а текст для модального окна при разовой оплате. 
Письмо с благодарностью обязательно  отправлять на эл. почту при каждом платеже?
2) Название общ. организации и данные о кампании: я исходила из того, что в модуль встроен макет письма, где по умолчанию будет указан наш текст сообщения, но каждая организация будет иметь возможность изменить его по своему усмотрению. В таком случае, им не составит труда самостоятельно вписать своё название и дать ссылку на свой сайт. Я права?

**Comment by svetit** [comment]
@Olya147 
1. Тады лепш асобную табличку зраби для надписаў для вакна пры разавых плацяжах. (У тым жа доку)
І яшчэ раз гляну там.

**Comment by ghost** [comment]
@lptn @svetit @fr0zen @rizomaa @alexap13 @nastyafrosty @KsenjaV  Попытка № 2. Сбрасываю ссылку на новый документ с текстами сообщений. Пожалуйста, прочтите его и оставьте замечания. https://docs.google.com/spreadsheets/d/1rOQv1g7skB_77JRRn6BSyyFLo5V9I5RfpCAQG0sIpr4/edit?usp=sharing

**Comment by rizomaa** [comment]
@Olya147 

па першаму лісту
з большага даволі афіцыйна (можа так  і трэба для шаблона).
трэба дадаць 
1. ці гэта разовы ці гэта рэгулярны плацёж 
2. і дадаць дзе чалавек зможа адпісацца.

**Comment by nastyafrosty** [comment]
@rizomaa @lptn @fr0zen 
1)если у человека оформлена подписка и в день снятия средств у него их недостаточно, будет ли списана эта сумма позже, когда деньги на карте появятся? 
2) "карта заблакаваная або скончыўся тэрмін яе дзеяння." если срок действия карты закончен,то человеку нужно заново подписаться? он же не может как-то поменять карту? (нет интерфейса донейтера)

**Comment by nastyafrosty** [comment]
@Olya147  док откоментила

**Comment by alies-dev** [comment]
@nastyafrosty 
>1)если у человека оформлена подписка и в день снятия средств у него их недостаточно, будет ли списана эта сумма позже, когда деньги на карте появятся?

Так, 5 будзе зроблена 5 спробаў. З якой часціней -- дакументацыя bePaid [маўчыць](https://docs.bepaid.by/ru/subscriptions/plans) ("Количество неудачных попыток оплаты прежде чем отменить подписку. По умолчанию 3")

>"карта заблакаваная або скончыўся тэрмін яе дзеяння." если срок действия карты закончен,то человеку нужно заново подписаться? он же не может как-то поменять карту? (нет интерфейса донейтера)

Так, вядома няма, трэба па-новай будзе падпісвацца

**Comment by ghost** [comment]
@lptn  [Тексты сообщений](https://docs.google.com/spreadsheets/d/1rOQv1g7skB_77JRRn6BSyyFLo5V9I5RfpCAQG0sIpr4/edit#gid=0) готовы.

**Comment by alies-dev** [comment]
@Olya147

дзякуй, рэалізацыю будзе ўмежах новай issue "Абнавіць кантэнт імэйлаў па рэкурэнтным плацяжам #583"
