### ISSUE TITLE
 Стварыць класы для карыстальнікаў, плану падпіскі, падпіскі

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#47]

**Comment by Tyuba4** [comment]
@falanster Сделан тестовый класс по созданию плана. #159 #151

**Comment by Tyuba4** [comment]
Для тестирования необходимо сделать код ревью. После этого проверить работу классов через командную строку (в пулл реквесте будет инструкции). По завершению сделать рабочие классы обрабатывающие создание плана, пользователя и подписки.

**Comment by Olya147** [comment]
@Tyuba4 Пожалуйста, опишите более подробно:
1. суть вносимых изменений;
2. где пользователь сможет увидеть окончательный вариант;
3. критерии приёмки.

**Comment by Tyuba4** [comment]
@Olya147 
1. Создается код по интеграции в плагин функции рекуррентных платежей на bePaid.
2. Здесь я работаю над разработкой этой интеграции, так что окончательного варианта на этом этапе не будет.
3. "в пулл реквесте будут инструкции"

**Comment by Tyuba4** [comment]
@falanster Сделан тестовый класс по созданию пользователя на бипэйд. Изменения будут в скорости в пулл реквесте.
