### ISSUE TITLE
Дадаць статычныя дадзеныя адміна модуля пры тэставым сідаванні

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#481]
Есць праблема, што зараз фабрыка фарміруе поўнасцю рандомныя дадзеныя адмінаў на тэставым сідэры, трэба адзін статычны, каб было зручней тэставаць

**Comment by alies-dev** [comment]
@fr0zen 
ты пра якія дадзеныя? Адмінаў? Якой камандай карыстаешся?

**Comment by fr0zen** [comment]
@lptn раблю пры разгортванні 
```
php artisan migrate:fresh
php artisan db:seed --class=TestingSeeder
```
крута было б каб адзін з карыстальнікаў быў статычным (аднолькавым пры кожным разгортванні). Так лягчэй будзе працаваць тэсцерам

**Comment by alies-dev** [comment]
`php artisan db:seed --class=AdminSeeder`  жа стварае `demo@example.com`/`demo` адміна, выкарыстоўвай яго, ці есьць нейкія праблемы з ім?

```sh
php artisan migrate:fresh
php artisan db:seed --class=TestingSeeder
php artisan db:seed --class=AdminSeeder
```

PS: Закрывай issue калі праблемаў няма

**Comment by fr0zen** [comment]
@lptn Так, дзякуй, зачыняю
