### ISSUE TITLE
Фармат адказу не супадае з чакаемым

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#482]
Калі сідуем базу праз тэставы сідер, то пры запыте да дадзенных кампаніі праз кантроллер атрымліваем наступны адказ:
```
visual_settings: "{"buttons":["5","10","25","50"],"progressBar":"1","colors":{"widgetBackground":null,"buttonBackground":null,"progressBarColor":null,"fontColor":null,"termsOfUse":null}}"
```

на фронце замест стракі чакаецца аб'ект

```
visual_settings: {buttons: ["5", "10", "25", "50"], progressBar: "1",…}
buttons: ["5", "10", "25", "50"]
colors: {widgetBackground: null, buttonBackground: null, progressBarColor: null, fontColor: null,…}
progressBar: "1"
```

Памылка ўзнікае толькі пры сідынге, калі пішам у базу праз кантроллер - усе добра.

**Comment by alies-dev** [comment]
@fr0zen 
>на фронце замест стракі чакаецца аб'ект
```
visual_settings: {buttons: ["5", "10", "25", "50"], progressBar: "1",…}
buttons: ["5", "10", "25", "50"]
colors: {widgetBackground: null, buttonBackground: null, progressBarColor: null, fontColor: null,…}
progressBar: "1"
```
buttons, colors, progressBar: гэта ўсе мусіць быць часткаю visual_settings, у тваим прыкладзе невалидный json,  можаш удакладніць што ты чакаеш?

вось як ен мусіць выглядаць на маю думку:
```json
{
    "visual_settings": {
        "buttons": [
            "5",
            "10",
            "25",
            "50"
        ],
        "colors": {
            "widgetBackground": null,
            "buttonBackground": null,
            "progressBarColor": null,
            "fontColor": null
        }
        "progressBar": true
    }
}
```

**Comment by fr0zen** [comment]
@lptn так, ты ўсе дакладна зразумеў. Зараз праблема ў тым, што сідер залівае у базу строку замест JSON аб'екта. Калі захоўваем праз кантроллер visual_settings - усе добра

**Comment by alies-dev** [comment]
@fr0zen 
гатова
![image](https://user-images.githubusercontent.com/5278175/58515407-64160200-81ad-11e9-9d69-0520fc71a290.png)


але я ўсе адно не да канца упэўнены ці гэтага ты хацеў)

Калі гэтага -- закрывай issue :)

**Comment by fr0zen** [comment]
👍
