### ISSUE TITLE
Схаваць усе узгадванні рэгістрацыі модуля

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#483]
**Шаги для воспроизведения:**
1. Перейти в раздел "Спіс карыстальнікаў"; 
2. нажать на кнопку "Стварыць новага карыстальніка";
3. в поле "Пароль" внести 12345;
4. в поле "Паўтарыце пароль" внести 11111.

**ФР:** отсутствует сообщение об ошибке.
**ОР:** появляется всплывающая подсказка (напр. "Введённые пароли не совпадают").

**Тестовые условия:**
Версия Doika: 2.0

**Comment by rizomaa** [comment]
карыстальніка ствараць наогул непатрэбна. выходзім паза скоўп. пераіменоўваю тэму

**Comment by rizomaa** [comment]
Дублюе https://github.com/diglabby/doika/issues/490 Зачыняю
