### ISSUE TITLE
Нельга выдаліць кампанію са спіса

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#487]
**Предусловие:** создать кампанию.
**Шаги для воспроизведения:**
1. Открыть раздел "Спіс кампаній";
2. нажать на кнопку "Выдаліць"

**ФР:** кнопка не кликабельна, кампания не удалена.
**ОР:** появляется диалоговое окно с подтверждением удаления.

**Тестовые условия:**
Версия Doika: 2.0
Платформа и версия: Win10
Браузер и версия: Chrome 73.0.3683.103/ Opera 58.0.3135.132/ Firefox 60.6.3esr

**Comment by alies-dev** [comment]
@Olya147 
а давай мы цяпер з табой пяройдзем на іншы ўзровень і...  будзем прасіць у цябе логі з кансолі браўзера

Кансоль звычайна адчыняецца па F11 ці яшчэ лепей Cmd + Shift + J

Вось тут артукул https://support.airtable.com/hc/en-us/articles/232313848-How-to-open-the-developer-console

Памылкі з кансолі вельмі дапамогуць распрацоўшчыкам і дапамогуць табе быць яшчэ болей крутым тэсціроўшчыкам 🦄 

Як табе ідэя?

Праз месяц-другі зможам цябе навучыць чытаць "Network" таб з devTool браўзера калі табе цікава

**Comment by ghost** [comment]
@lptn  хорошая идея. я "за")
Файл с логами во вложении.
[doika-1559117390035.log](https://github.com/diglabby/doika/files/3231392/doika-1559117390035.log)

**Comment by alies-dev** [comment]
@Olya147 
Класна!
Тут дарэчы яшчэ адзін бенефіт будзе: калі ў кансолі есьць памылкі -- то гэта як мінімум frontend bug, а значыць мяне можна не асайніць не issue  (і іншых бэкэндзераў)

**Comment by rizomaa** [comment]
Вітаю, 

Ішус карэлюе з маёй папярэдняй #684 . Што мы бачым: 
![Selection_001](https://user-images.githubusercontent.com/9870374/77159584-b155be00-6ab6-11ea-878f-9899e48203eb.png)

Гэта кнопка павінна быць стартавым механізмам выдалення.

Што зрабіць: 
- [x] Знайсці эндпоінт для выдалення кампаніі php artisan route:list
- [ ] Вызначыць спосаб, якім будзе выдаляцца. Функцыя ў methods , паразважаць ці патрэбны custom events?
- [x] Зрабіць зручны вывад id кампаніі ў форме, для таго каб было зразумела, што выдаляць.
- [ ] Напісаць або знайсці паведамленне якое будзе вяртаць бэкэнд пры выдаленні. Мяркую Тут https://github.com/diglabby/doika/blob/develop/app/Http/Controllers/Dashboard/CampaignController.php функцыя delete
- [ ] Напісаць апрацоўшчык у кампаненце Campaigns.vue (axios delete)
- [x] Дадаць пацверджанне выдалення. (izitoast ?)


Карысныя спасылкі:
- Бібліятэка для папапаў https://www.npmjs.com/package/vue-izitoast
- Тут запісаць апрацоўшчык ў карэктнай форме https://github.com/diglabby/doika/blob/develop/app/Http/Controllers/Dashboard/CampaignController.php
-

**Comment by rizomaa** [comment]
1. Хаця ў кампаненце стаіць   let { data } = await axios.post(this.$app.route(this.actionRoute)
Буду рабіць праз прамы доступ да эндпоінта па яго шляху.   | DELETE   | doika/dashboard/api/campaigns/{campaign}                   | dashboard.campaigns.delete

2. Выкарыстоўваюць ужо бібліятэку тады магчыма не буду мучаць ізітостам. Пагляджу як гэта працуе. window.swal .... паглядзеў. не ведаю, як яго інсталілі npm пусты таму паставіў праз npm запрацавала. Усе функцыі swal трэба пераписваць, бо нейкія яны deprecated па усяму праекту.

3. Апрацоўшчык знаходзіцца ў DataTable... карацей ён палены. Трэба перапісваць, пакуль не разумею працы роўтаў там. Наогул выглядае weird, калі не пакаціць у сераду будзем прымаць генеральнае рашэнне.

4. Выдаленне наладзіў (перапісаў deleteRow у DataTable.Vue), але пакуль у тэставым выглядзе. Не каммічу, бо трэба яшчэ пару апрацоўшчыкаў пісаць, я магу, але адчуваю, што тады ўся бягучая архітэктура франта валіцца....

зы
Пакуль ураджанне: тона непатрэбных функцый і пантовых апрацоўшчыкаў, якія не працуюць. засмечваюць код, заблытваюць. Навошта іх наогул пачыналі пісаць... эх

**Comment by rizomaa** [comment]
Нарэшце дазрэў:

Вось пулрэквэст https://github.com/diglabby/doika/pull/695

Якія ўрокі з рашэння задачы:
1. Пастаяннае вывучэнне дапаможнай бібліятэкі https://bootstrap-vue.js.org/. Яна вельмі магутная, але не апісана ў стэку (дадаў старонку ў вікі, можна там [паціху запаўняць](https://github.com/diglabby/doika/wiki/%5BDevelopment%5D-Frontend)). Наогул галячок з апісаннем часта выкарыстоўваемых бібліятэк. Канешне можна праз код, але гэта займае час.

2. Пакуль цёмны бок праекта вось такія канструкты `**this.$app.route(this.deleteRoute)**`. Яны паказваюць імёны роўтаў, але як іх прымяняць загадка. Папаўла макароніна. Магчыма, як у функцыі `**loadData(sortBy, sortDesc) {**` але нейкі каментар на кодам дапамог бы.

3. З папярэдняга паста другі пункт актуальны. Шмат састарэлага кода. Гэта канешне цікава разбірацца ў чарговай бібліятэцы) хех

@Gordonshik @Tyuba4 правярайце калі ласка змены, ці працуе у вас выдаленне? Калі так буду зачыныць картку

**Comment by rizomaa** [comment]
Калі няма заўваг, зачыняю. Калі ласка адчыняйце і каментуйце, калі заўвыжыце нешта.
