### ISSUE TITLE
Неверно рассчитано количество дней до окончания кампании

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#488]
_**Предусловие:** создать кампанию._
**Шаги для воспроизведения:**
1. Открыть раздел "Спіс кампаній";
2. нажать "Рэдагаваць";
3. изменить поля "Дата пачатку" и "Дата заканчэння" на 01.06.19 и 05.06.19 соответственно;
4. нажать "Захаваць".

**ФР:**  из общего числа "дней до окончания" исключается последний день проведения кампании.

![Период](https://user-images.githubusercontent.com/46268205/58512588-2792d800-81a6-11e9-9a25-78d3a1015dbf.png)
![Кол-во дн](https://user-images.githubusercontent.com/46268205/58512595-2a8dc880-81a6-11e9-91c1-b647b29a57f1.png)

**Тестовые условия:**
Версия Doika: 2.0
Платформа и версия: Win10
Браузер и версия: Chrome 73.0.3683.103/ Opera 58.0.3135.132/ Firefox 60.6.3esr

**Comment by Gordonshik** [comment]
@rizomaa почему-то у меня список компаний после создания не отображается, соответственно сколько дней осталось на странице я посмотреть не могу.
При чем ссылка редактирования компании работает.
![изображение](https://user-images.githubusercontent.com/51483246/75440702-4f99ac80-596d-11ea-93b2-ee444621ab7a.png)
![изображение](https://user-images.githubusercontent.com/51483246/75440752-63451300-596d-11ea-9b33-f2174613f207.png)

**Comment by Gordonshik** [comment]
@rizomaa при добавлении компании список, как можно увидеть, расширяется, но это не приводит к отображению
![изображение](https://user-images.githubusercontent.com/51483246/75456935-3c4a0980-598c-11ea-9f2d-eac60989957c.png)

**Comment by rizomaa** [comment]
> @rizomaa почему-то у меня список компаний после создания не отображается, соответственно сколько дней осталось на странице я посмотреть не могу.
> При чем ссылка редактирования компании работает.
> ![изображение](https://user-images.githubusercontent.com/51483246/75440702-4f99ac80-596d-11ea-93b2-ee444621ab7a.png)
> ![изображение](https://user-images.githubusercontent.com/51483246/75440752-63451300-596d-11ea-9b33-f2174613f207.png)

@Gordonshik так гэта асобны баг. можаш яго вынесці ў асобную issue?

**Comment by Gordonshik** [comment]
@rizomaa не вопрос, сделаю, только сейчас гляну как эти issue делаются.

**Comment by Gordonshik** [comment]
@rizomaa сделал

**Comment by rizomaa** [comment]
@Gordonshik можаш падказаць, які гэта быў ПР?

**Comment by Gordonshik** [comment]
@rizomaa привет, что значит какой? Честно говоря я что-то не помню.

**Comment by rizomaa** [comment]
@Gordonshik тады я маркирую гэту картку як "неабходна зрабіць"

**Comment by darth-tesla** [comment]
Этот баг всё ещё актуален? Просто у меня всё верно отображается. Или подобная ошибка происходит только при выборе определённых дат?

https://ibb.co/VCVqgX2
https://ibb.co/vPB829M

**Comment by rizomaa** [comment]
@darth-tesla прывітанне,
пакуль яе не правяраў:
але патрэбна праверыць на 
1. Адным месяцы. кампанія не пачалася, але пачнецца.
2. Некалькіх месяцах. кампанія не пачалася, але пачнецца.
3. Кампаніі, якая ідзе з аднаго года ў іншы. кампанія не пачалася, але пачнецца. і кампанія пачалася.
4. На кампаніі, якая пачалася у мінулым, але скончыцца ў будучым (напрыклад праз 2 дні)

**Comment by darth-tesla** [comment]
@rizomaa сделал небольшое "ручное тестирование" согласно описанному тобой алгоритму. Ошибку так и не удалось воспроизвести. Сравнивал рассчитанное количество дней с вот этим калькулятором - https://planetcalc.ru/273. 

Может баг можно воспроизвести только в очень специфичных условиях? В таком случае я даже не знаю, с какой стороны подойти, чтобы его отловить.

**Comment by rizomaa** [comment]
@darth-tesla дзякуй за тэставанне, гэта таксама вельми важна. Будзем больш пильна сачыць за каммітамі.

Я тады зачыняю гэту картку.
