### ISSUE TITLE
Рэалізаваць спасылку на адключэнне ад падпicкi

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#49]
- [x] Логіку амеркаваць
- [x] Намаляваць клас
- [x] Зрабіць апрацоўшчыкі
- [ ] Пратэставаць

**Comment by falanster** [comment]
дадаў крытэры прыёмкі

**Comment by rizomaa** [comment]
Трэба даследваць, якія дадзеныя неабходныя каб адключыць падпіску?

Можна выкарыстаць хэш, якія фарміруецца падчас падпіскі у табліцы Данэйцера. У табліцы проста мяняем статус з 1 на 0 у табліцы.

**Comment by lptn** [comment]
>Трэба даследваць, якія дадзеныя неабходныя каб адключыць падпіску? Можна выкарыстаць хэш, якія фарміруецца падчас падпіскі у табліцы Данэйцера. 

Гэта мусіць быць рандомны радок, не абавязкова хэш, яго генерыць пры стварэнні падпіскі. Патрэбна будзе яшчэ старонка не заканфірміць адпіску трэба

>Пры выдаленнi у табліцы проста мяняем статус з 1 на 0 у табліцы.

Можна і `deleted_at` поле выкарыстоўваць: прасцей і болей інфы будзе

**Comment by rizomaa** [comment]
@lptn 

1. старонку  мы ўжо абмяркоўвалі... для ітэрацыі 1.3 робім проста спасылка выклікае функцыю адпіска. для 1.4 або 1.5 зробім канфірмэйшн. я ствару ішу для адмаўлёкі і наогул абмеркавання.
Наконт хэша або рандома, калі ласка, можаце самі вырашыць. проста мне падаецца хэш больш якасна і яго рабіць асля канкатэнацыі патрэбнай інфы не складана. тым больш яго можна праверыць заўсёды.
2. Тут патлумач "Можна і `deleted_at` поле выкарыстоўваць: прасцей і болей інфы будзе" ?

**Comment by lptn** [comment]
>1. старонку  мы ўжо абмяркоўвалі... для ітэрацыі 1.3 робім проста спасылка выклікае функцыю адпіска. для 1.4 або 1.5 зробім канфірмэйшн. я ствару ішу для адмаўлёкі і наогул абмеркавання.

Добра, проста нагадаю: прайсці па спасыльцы -- гэта GET request. Get request не мусіць мяняць стэйт, пагэтаму лепей каб спасылка вяла на старонку дзе карыстальнік можа зрабіць POST request

>1. Наконт хэша або рандома, калі ласка, можаце самі вырашыць. проста мне падаецца хэш больш якасна і яго рабіць асля канкатэнацыі патрэбнай інфы не складана. тым больш яго можна праверыць заўсёды.

вось вось, хэш трэба кабіць калі мы зацікаўлены ў праверцы дадзеных якія не будуць мяняцца. На дадзены момант у нас вылікая нявызначанасць з дадзенымі


>2\. Тут патлумач "Можна і `deleted_at` поле выкарыстоўваць: прасцей і болей інфы будзе" ?

https://laravel.com/docs/master/eloquent#soft-deleting

status [0|1] нясе інфу ТОЛЬКІ пра стутус, у той да час поле `deleted_at` нясе інфу пра стутус і пра час калі падпіска выдалена (што магчыма спатрэбіцца для статыстыкі)

**Comment by alies-dev** [comment]
@rizomaa 
Як і калі будзем дасылаць спасылкі на адпіску ад падпіскі?

**Comment by rizomaa** [comment]
@lptn 

1. У лісце пераз зняццём грошай (3 дні да зняцця)
2. У лісце пасля зняцця грошай (адразу пасля зняцця)

**Comment by alies-dev** [comment]
@rizomaa 
@fr0zen 
>У лісце пераз зняццём грошай (3 дні да зняцця)

Гэта значыць нам патрэбны крон ці хак (пры кожным реквэсце правяраць ці есьць што адправіць), ці пацнуць крон арганізацыі?

**Comment by fr0zen** [comment]
@rizomaa @lptn пакуль мы можам нармальна рэалізаваць варыянт толькі з пісьмом пасля плацяжу.
Алгарытм наступны.
1. Чалавек свядома падпісваецца на данэйт.
2. Тут жа грошы здымаюцца. 
3. Прыходзіць пісьмо с падзякай, указаннем колькасці плацяжу і спасылкай на адпіску з датай, калі грошы здымуцца наступны раз. Калі чалавек памыліўся/не жадае данэйціць у наступны раз - ен проста адпісваецца. 

На мой погляд гэта даволі лагічна і максімальна проста рэалізуецца ў параўнанні з іншымі варыянтамі, бо дадатковыя наладкі крона на хостынгах - не наш кейс.

**Comment by rizomaa** [comment]
@lptn Так, магчыма для гэтай ітэрацыі дастаткова аднаго паведамлення пасля аплаты, як піша @fr0zen , але для будучай варта папярэджваць.

Наконт запуска праверкі  для адсылкі думаю, варта лепей карыстацца проста праверкай умоваў адпраўкі па спісу пры ўваходзе любога карыстальніка на сайт. Можна даследваць ці ёсць магчымаць на шарэхостынгах правіць канфіг крона.

> @rizomaa @lptn пакуль мы можам нармальна рэалізаваць варыянт толькі з пісьмом пасля плацяжу.
> Алгарытм наступны.
> 
> 1. Чалавек свядома падпісваецца на данэйт.
> 2. Тут жа грошы здымаюцца.
> 3. Прыходзіць пісьмо с падзякай, указаннем колькасці плацяжу і спасылкай на адпіску з датай, калі грошы здымуцца наступны раз. Калі чалавек памыліўся/не жадае данэйціць у наступны раз - ен проста адпісваецца.
> 
> На мой погляд гэта даволі лагічна і максімальна проста рэалізуецца ў параўнанні з іншымі варыянтамі, бо дадатковыя наладкі крона на хостынгах - не наш кейс.
