### ISSUE TITLE
Прыбаць з бачнасці любы функцыянал па стварэнню новых юзэраў (рэгістрацыя. узнаўленне пасвардаў)

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#490]
**Шаги для воспроизведения:**
1. перейти в раздел "Спіс карыстальнікаў";
2. нажать "Стварыць новага карыстальніка";
3. заполнить поля;
4. нажать "Стварыць".

**ФР:**  Пользователь не создан. Форма остаётся открытой, кнопка стала некликабельной.
**ОР:** форма закрывается; в системе создан новый пользователь.

**Тестовые условия:**
Версия Doika: 2.0
Платформа и версия: Win10
Браузер и версия: Chrome 73.0.3683.103/ Opera 58.0.3135.132

**Приложение:** [doika-1559125438825.log](https://github.com/diglabby/doika/files/3231975/doika-1559125438825.log)

**Comment by rizomaa** [comment]
@lptn гэта задача не гарачая. кали ласка закіньце яе падалей.

**Comment by rizomaa** [comment]
З гэтых трох месцаў:

![Selection_008](https://user-images.githubusercontent.com/9870374/77830194-ece82c00-7137-11ea-99c7-4df3a14d948c.png)
![Selection_009](https://user-images.githubusercontent.com/9870374/77830237-44869780-7138-11ea-9411-380e36b8baa0.png)
![Selection_010](https://user-images.githubusercontent.com/9870374/77830239-46505b00-7138-11ea-84c0-6cbf011f0e8c.png)

**Comment by Gordonshik** [comment]
Вопрос такой, это все тут я так понимаю как временной мерой подается, так? Типа пока не разобрались надо это прикрыть? То есть надо сделать так, чтобы их просто не было видно?
Еще вопрос отдельно по гитхабу, я ни в инете не нашел, ни сам додуматься не могу. Как в in progress это все дело перенести?

**Comment by rizomaa** [comment]
@Gordonshik як толькі пратэстую, зачыню. або нехта іншы раней паспее.

**Comment by rizomaa** [comment]
> @Gordonshik як толькі пратэстую, зачыню. або нехта іншы раней паспее.

тэставаў?

**Comment by Gordonshik** [comment]
@rizomaa ну у меня наботает конечно.
