### ISSUE TITLE
Паменшыць кнопкі "Плацёж" і "Падпіска"

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#492]
**Шаги для воспроизведения:**
1. открыть страницу http://it3donate-joomla.falanster.by/
2. поочерёдно нажимать на кнопки "Плацеж" и "Падпіска".

**ФР:** кнопки наслаиваются друг на друга.

![Кнопки](https://user-images.githubusercontent.com/46268205/58554294-43869000-821f-11e9-9277-296566a3a412.png)

**Тестовые условия:**
Версия Doika: 2.0
Платформа и версия: Win10
Браузер и версия: Chrome 73.0.3683.103/ Opera 58.0.3135.132/

**Comment by Gordonshik** [comment]
@rizomaa при открытии ссылки http://it3donate-joomla.falanster.by/ ничего нет,
![изображение](https://user-images.githubusercontent.com/51483246/75371713-49a5bc00-58d8-11ea-855c-b6397795a7ee.png)
в самом виджете кнопки нормально работают
![изображение](https://user-images.githubusercontent.com/51483246/75371752-5cb88c00-58d8-11ea-9bc5-565217700fa4.png)

**Comment by rizomaa** [comment]
@Gordonshik схіляешся на тое, што джумла псавала стылі?

**Comment by Gordonshik** [comment]
@rizomaa что-то минимально подобное происходит на долю секунды в Кіраванне/Знешні выгляд в примере компании, но это не совсем то все же, можешь анимацию глянуть сам, если интересно, просто кнопки в результате переключения (наведения) как бы меняют свой план на другой (с переднего на задний и наоборот), но вроде все смотрится вполне презентабельно, совсем не как на скрине.
Джумла или нет не могу сказать, т.к. не компетентен в этим вопросе
![изображение](https://user-images.githubusercontent.com/51483246/75376118-8bd2fb80-58e0-11ea-88b4-8e3574fb68f9.png)

**Comment by rizomaa** [comment]
@Gordonshik звярні увагу як тут https://www.figma.com/file/RlVbECuyzs25TCVHZ1Sls87E/Doika-module-%D0%BA%D0%BBi%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%B0%D1%8F-%D1%87%D0%B0%D1%81%D1%82%D0%BA%D0%B0?node-id=0%3A1
(гэта пакінула @nastyafrosty арыентуемся як на шаблон для праўкі) 

Трэба падправіць 
1. Стылі межаў і падсветкі, дзе кнопкі сустракаюцца.
2. Таксама паглядзець магчыма замяніць самі кампаненты на больш зручныя (тут рашэнне з табой)

![Selection_011](https://user-images.githubusercontent.com/9870374/75520787-6b598d00-5a17-11ea-84d8-11767e0fa8ae.png)

**Comment by Gordonshik** [comment]
@rizomaa я на фигме такое нашел, теперь мне не понятно, окей я нашел уже что и где, но что от меня ожидается? вот на моем скрине я сдвинул в виджете кнопки
![изображение](https://user-images.githubusercontent.com/51483246/75558713-47b43800-5a53-11ea-8889-7af6500ffdb4.png)
 но что делать с border, мне сделать так, чтобы они выглядели с розовыми border и он был всегда так виден
![изображение](https://user-images.githubusercontent.com/51483246/75558825-77fbd680-5a53-11ea-8fcf-cd3575d54a2f.png)
или
![изображение](https://user-images.githubusercontent.com/51483246/75558910-8f3ac400-5a53-11ea-8297-790ff0bdd7e9.png)
так мне кажется более органично, потому что от кнопок остальных стилем не отличается. Понятно, что в этом случае при не active состоянии они будут просто цвета background без всяких розовых border.
Просто я например не вижу принципиальной разницы между тем как я сейчас сделал (на первом скрине) и как у frosty на последнем. И тогда требуется ли делать эти розовые рамки?
Прошу пояснить, желательно со скрином к каждому случаю.
Потому что скрин с этими двумя выделениями не дает мне понять, какой стиль из этих двух использовать, ведь в одном розового бордера нет, а в другом есть. А сделать это уже будет не вопрос.
Или быть может розовый бордер должен быть в случае, если вариант еще не выбран, а в случае active он исчезает и становится как на 3 скрине. Что-то сейчас такая мысль меня после анализа посетила.

**Comment by rizomaa** [comment]
@Gordonshik колеры павінны наладжвацца праз адмінку. у тым ліку і межы.

Так з большаўа маеш рацыю, аналіз дапамог):

1. Калі ласка зрабі, як на макеце межы кнопак.
1.1. Калі нічога не абрана межы застаюцца. Кнопкі белыя.
1.2. Калі абраны адзін з варыянтаў межы знікаюць і выдзеленая клавіша чёмнага колеру.
2. Колеры межаў будуць такія ж як і колеры прыціска "Ахвяруй" (Іншымі словамі яны павінны падхопліваць тыя ж стылі, што і прыціск).

ps
@nastyafrosty напішы калі я у нечым адыйшоў ад твайго канцэпта.

**Comment by Gordonshik** [comment]
Пока со стилями кнопок разобрался. Сделал вроде как по красоте, но в настоящее время разбираюсь с этим кожны месяц или разава, розовый бордер сделал, при clicked он исчезает, вопрос в том, что надо сделать, чтобы и у второго исчез этот бордер. Я так понимаю, что надо js написать что-то типа:
if(я нажимаю на кнопку а){
кнопка б теряет бордер
}
Ну и наоборот. Пока не могу найти где такую функцию писать. Пытался найти по объявлению класса, но ничего дельного не нашел. Буду, видимо, искать дальше.
В фигме я посмотрел у кнопок в углах, которыми они соприкасаются углы не закруглены должны быть, а сейчас закругленные. Планирую каждой кнопке присвоить свой уникальный класс и у каждой с нужной стороны закруглить углы.
И еще одно, раз клавиша становится темного цвета, все же считаю правильным не делать шрифт черным, считаю нужным сделать его розовым в дизайне сайта в случае класса picked.

**Comment by rizomaa** [comment]
@Gordonshik 
Мо ты ўжо глядзеў у джээсе гэта eventListener у Vue 
https://vuejs.org/v2/guide/events.html  (v-on)
Я яшчэ  тут нарошчаюц веды таксама

зы
Наконт як рабіць: па дызайну (мы паважаем яе працу, таму тут важна быць пасля доўным),
Як зробіш асноўнае заданне і вельмі хочацца паказаць свой варыянт, тады стварай брэнчы для A/B тэста =)

**Comment by Gordonshik** [comment]
@rizomaa да, про v-on читал, как в реакте условном onClick, это я понимаю, просто пока не всегда помню и по-прежнему часто думается категориями ванильного js, так скажем.
Проблема как обычно не в том, что я не знаю, что надо сделать. Я представляю все эти ивентлисенеры и т.д. Я не могу найти компонент нужный куда его вписать и как это соединить все, у меня с этим проблема скорее.
По поводу дизайна понял, я там просмотрел, что написал про оранжевый цвет, хотя его нет в дизайне, хотя думал, что про розовый написал, который есть в кнопках на дизайне, но запроса на изменение цвета в issue нет, поэтому я и подумал, что быть может сделать эти две клавиши с color: розовый.
А так конечно, дизайнеру видней)

**Comment by nastyafrosty** [comment]
@Gordonshik @rizomaa привет! Розовым бордером кнопки подсвечиваются, когда юзер ничего не выбирает и выскакивает ошибка. другое дело,что можно дизэйблить кнопку Ахваруй, пока не выбраны значения. Темный bg это active, т.е выбранное значение

**Comment by Gordonshik** [comment]
@nastyafrosty привет, понял. Переделаю.
@rizomaa Ура, я понял, что все же это MainWindow, спасибо Vue Devtools за это, буду змагацца.

**Comment by Gordonshik** [comment]
@rizomaa 
![изображение](https://user-images.githubusercontent.com/51483246/76020560-b3574300-5f34-11ea-9b99-455c68b36c3b.png)
![изображение](https://user-images.githubusercontent.com/51483246/76020638-d3870200-5f34-11ea-93f3-24ccc2a0e73a.png)
Вроде все по дизайну. Кнопки в btn-group засунул, края острые теперь между ними. color розовым у кнопок платеж и подписка сделал. Плюс эти кнопки на скрине сделал bg белый. Все так вроде, по дизайну.

**Comment by nastyafrosty** [comment]
@Gordonshik вижу нюанс, о котором мне тоже сказали в свое время: у инпута, куда вводится желаемая кастомная сумма, не должно быть такой тени,как у кнопок, потому что это не кнопка. на макете у меня легкая внутренняя тень. посмотри,пожалуйста

**Comment by Gordonshik** [comment]
@nastyafrosty this? У меня уже с глазами что-то
![изображение](https://user-images.githubusercontent.com/51483246/76024590-6d9e7880-5f3c-11ea-84f2-6bd6a74a90cd.png)

**Comment by nastyafrosty** [comment]
@Gordonshik угу, и может сделать закругление,как и у всех элементов?

**Comment by Gordonshik** [comment]
@nastyafrosty ну, смотри сама. Правда интересно почему тогда тени не должно быть как у других элементов? Я просто пытаюсь понять алгоритм, мне казалось, что все должно быть выдержано в одном стиле или как это делается, я не знаю просто)
![изображение](https://user-images.githubusercontent.com/51483246/76117649-3e037500-5ffd-11ea-8b50-c38ab67253da.png)

**Comment by nastyafrosty** [comment]
@Gordonshik тень не нужна ,потому что это поле ввода, оно,конечно,может якобы выступать, но не совсем логично. кнопки же это тот элемент, который в реальном мире выпуклый,имеет тень.

**Comment by Gordonshik** [comment]
@nastyafrosty имеет смысл. Ну, я так понял с виду все окей?

**Comment by Gordonshik** [comment]
@rizomaa Вопрос такой, я менял кое-что в widget.css, но мой github desktop не фиксирует изменения в этом файле. Как мне эти изменения передать по реквесту в таком случае? В интернете внятного не нашел вроде

**Comment by rizomaa** [comment]
@Gordonshik наогул для пачатку раю карыстацца git bash :
1. будзеш бачыць усё, як адбываецца.
2. зможаш хутчэй знаходзіць багі ў тым ліку адказы па ім.
3. калі ўся матчастка па гіту будзе засвоена на практыцы (1 год + ) можа пераходзіць на юай розныя=)

наогул мне дапамагае `git add *` ці `git add .` амаль заўсёды)

**Comment by rizomaa** [comment]
@Gordonshik хачу пратэсціць вылез залежны таск https://github.com/diglabby/doika/issues/680 як яго улагодзім зможам чэкнуць і зачынік ішу.

Дзякуй за працу)
