### ISSUE TITLE
Рэалізаваць функцыянал аднаўлення пароляў адміністратара

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#498]
Зрабіць магчымасць аднаўлення адміністратарскіх пароляў праз адмінку, вызначыць, як перадаем і захоўваем паролі ў базу каб было бяспечна.

**Comment by fr0zen** [comment]
@lptn у нас раней паўставала такое пытанне, давай вырашым як будзем дзейнічаць. 
Мне падаецца дастаткова проста хэшануць паролі сродкамі ларавеля і ўсе, твае думкі?

**Comment by alies-dev** [comment]
>Мне падаецца дастаткова проста хэшануць паролі сродкамі ларавеля і ўсе, твае думкі?


так, ніякіх праблемаў у лававэля з гэтым няма, усе проста, яго і будзем выкарыстоўваць

**Comment by alies-dev** [comment]
Duplicate of #396
