### ISSUE TITLE
Зрабіць сідер для дадавання тэставых дадзеных аб наладках модуля.

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#499]
Крута было б зрабіць сідер наладак, які б запаўняў палі idMarket, keyMarket на тэставых даменах. Але паўстае пытанне бяспечнасці такой штукі. @lptn @Tyuba4 вашы думкі?

**Comment by alies-dev** [comment]
@fr0zen 
Якімі дадзенымі будем запаўняць? Есьць нефкія агульнавядомыя тэставыя дадзеныя афіцыйныя ад bepaid ікія мы можам выкарыстоваць? Калі не, то ад Settings можам рабіць фалбэк на config а ад яго фалбэк на env, то бок груба кажучы цягнуць налады з env файла калі іх няма ў Settings/DB

Гэта вырашыць праблему як не шарыць адчувальную іфамармацыю праз git. Для гэтага трэба напісаць сваю рэалізацыю Settings, але:
 - гэта даволі проста
 - гэта дазволіць нам вярнуцца да дот-натацыю якая мне падабаецца значна болей чым _-натацыя

**Comment by alies-dev** [comment]
>Крута было б зрабіць сідер наладак, які б запаўняў палі idMarket, keyMarket на тэставых даменах. 

а якая мэта? Каб што?

**Comment by rizomaa** [comment]
@fr0zen так, я думаю тут няварта парыцца. проста трэба дадаць у гайд такия звесткі, хай арганізацыі самі вучацца уводзіць дадзеныя, бо пасля шмат блытаніны можа быць

**Comment by fr0zen** [comment]
@lptn @fr0zen мне падаецца так шмат зручней мануальна тэставаць мелкія issue, зараз каб паглядзець напрыклад што там не так з нейкай кнопкай на віджэте, тэсцерам пасля кожнага каміта будзе трэба пераствараць кампаніі і прапісваць дадзенныя. Кожны ж раз робіцца новы білд.

**Comment by alies-dev** [comment]
@fr0zen 
Што каркрэтна сідаваць апроч  bepaid?

Можаш сам дадаць, вось прыклад https://github.com/diglabby/doika/commit/ae445020428813b830c11a65736e6f575199b9ce

Закрый калі ласка issue калі гэтага дастаткова
