### ISSUE TITLE
Фронтэнд. Вокны лагіна і ўзнаўлення пароля

### ISSUE THREAD

**Issue by falanster** [diglabby/doika#50]
- [x] Спачатку сварыць макеты https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346278654036
- [x] Намаляваць і далучыць спасылкі на дызайны
- [x] Звярстаць з улікам выкарыстоўваемага фрэймварка
- [ ] Пратэставаць на дамене

**Comment by nastyafrosty** [comment]
https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346284941445

**Comment by fr0zen** [comment]
@nastyafrosty крута, дзякуй! @falanster зачынім пасля тэставання на жывым дамене.

**Comment by nastyafrosty** [comment]
how about adding button "show password" ?

**Comment by rizomaa** [comment]
прыбраў са спрынта, бо гэта не так важна зараз, будзем пазней працаваць з ёй

**Comment by ursar** [comment]
**Ссылка Forget password на странице входа в систему розового цвета.**

**Environment:** Google Chrome 71.0.3578.98 (32 бит).

**Steps of reproduce:** Открыть страницу входа в систему URL (http://it3donate-landing.falanster.by/doika/admin/campaigns).

**Actual result:** Цвет ссылки Forget password розового цвета.
![img1](https://user-images.githubusercontent.com/17195571/50724295-3516cb00-10fc-11e9-86a8-4da9541b06fe.jpg)

**Expected result:** Цвет ссылки Forget password черный. (https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346284941445)
 ![img1_1](https://user-images.githubusercontent.com/17195571/50724298-3cd66f80-10fc-11e9-8b53-b512513e15a7.jpg)

**Comment by ursar** [comment]
**Неактивный чек-бокс на странице входа в систему серого цвета.**

**Environment:** Google Chrome 71.0.3578.98 (32 бит).

**Steps of reproduce:** Открыть страницу входа в систему URL (http://it3donate-landing.falanster.by/doika/admin/campaigns).

**Actual result:** Неактивный чек-бокс серого цвета.
![img2](https://user-images.githubusercontent.com/17195571/50724363-3eecfe00-10fd-11e9-84c5-67fa5da71486.jpg)



**Expected result:**  Неактивный чек-бокс белого цвета в черной рамке.(https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346284941445)
![img2_1](https://user-images.githubusercontent.com/17195571/50724362-398fb380-10fd-11e9-9c41-374c4fcee56f.jpg)

**Comment by ursar** [comment]
**Отсутствует логотип на странице восстановления пароля.**

**Environment:** Google Chrome 71.0.3578.98 (32 бит).

**Steps of reproduce:** 
1. Открыть страницу входа в систему URL (http://it3donate-landing.falanster.by/doika/admin/campaigns).
2. Нажать на ссылку Forget password?

**Actual result:** Логотипа нет.
![img4](https://user-images.githubusercontent.com/17195571/50724444-ae172200-10fe-11e9-8475-fc7bb37d677c.jpg)

**Expected result:**  Логотип есть.
(https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346284941445)
![img4_1](https://user-images.githubusercontent.com/17195571/50724445-b2433f80-10fe-11e9-8c50-310fc08b7087.jpg)

**Comment by ursar** [comment]
**Неверное название элемента на странице восстановления пароля.**

**Environment:** Google Chrome 71.0.3578.98 (32 бит).

**Steps of reproduce:** 
1. Открыть страницу входа в систему URL (http://it3donate-landing.falanster.by/doika/admin/campaigns).
2. Нажать на ссылку Forget password?

**Actual result:** Элемент называется Login.
![img5](https://user-images.githubusercontent.com/17195571/50724527-c50a4400-10ff-11e9-90d3-f0c17571473d.jpg)

**Expected result:** Элемент называется Password recovery.
(https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346284941445)
![img5_1](https://user-images.githubusercontent.com/17195571/50724532-e10de580-10ff-11e9-971c-e3a31f8c28df.jpg)

**Comment by maxmatoha** [comment]
Можно добавить повторный(проверочный) ввод пароля.
И войти с помощью google+ facebook

**Comment by rizomaa** [comment]
Тут была падобная картка 
https://github.com/diglabby/doika/issues/51

**Comment by rizomaa** [comment]
@fr0zen @lptn  вы ўключалі у гэту ітэрацыю дадзены функцыянала?

**Comment by alies-dev** [comment]
@rizomaa 
аднаўленне паролю не зрібім да прэзентацыі хутчэй за ўсе, а лагін вядома ж удо працуе

Аднаўленне паролю тут:
Рэалізаваць функцыянал для "Забыліся пароль" (forget password) #396

**Comment by alies-dev** [comment]
Закрываю, бо для нерэалізаванай часткі есць "Забыліся пароль" (forget password) #396
