### ISSUE TITLE
Добавить в разделе "Знешні выгляд" кнопку для сворачивания цветовой палитры

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#500]
**Описание:** 
Я как администратор сайта, хочу при выборе оформления макета видеть кнопку для подтверждения выбранного мной цвета (фона, шрифта и т.д.) или иметь возможность скрыть палитру, щёлкнув за её пределы. Так мне было бы удобней.

**Comment by InaFK** [comment]
@rizomaa 
Бяру задачу на сябе.
Планую рэалізаваць заданне праз мажлівасць скрываць палітру (пасля выбару колера) праз клік па-за яе межамі.

**Comment by rizomaa** [comment]
@InaFK перад пачаткам, усё пытанні пішыце, каб у нас было дакладнае тлумачэнне задачы

**Comment by rizomaa** [comment]
@InaFK абнавіце калі ласка тут інфармацыю? як ідзе праца з задачай?

**Comment by darth-tesla** [comment]
Начну стажировку с этой задачи. Реализую закрытие палитры при клике за её границами.

**Comment by rizomaa** [comment]
@darth-tesla паспрабуй спачатку ўзнавіць гэту багу, каб яна была чотка паўтараема і пасля апішы, што будзе яе рашэннем. лепей у скрынах

**Comment by darth-tesla** [comment]
> @darth-tesla паспрабуй спачатку ўзнавіць гэту багу, каб яна была чотка паўтараема і пасля апішы, што будзе яе рашэннем. лепей у скрынах

Я для себя обозначил следующие проблемы. 

1. Возможность открыть сразу несколько палитр. Интуитивно непонятно, как их закрыть. Предлагаю сделать возможность закрытия палитры при клике за её пределами, а так же добавить кнопку закрытия для ещё более понятного интерфейса. https://ibb.co/tQVp2qm 

2. Предлагаю сделать поля с хекс / ргба кодом пошире (чтобы код помещался полностью), а так же сделать одинаковую ширину для полей с описанием. https://ibb.co/473RW0g

**Comment by rizomaa** [comment]
@darth-tesla дзякуй, слушныя думкі. як зразумеў:
1. клік па-за межамі для закрыцця.
2. крыжык-кнопка для закрыцця.

Твой пункт 2 пераношу у новы іш'ю. Хаця яна па аднаму і таму ж кампаненту. Лепей (асабліва пакуль толькі пранікаешся ў праект) асобнай карткай.

**Comment by rizomaa** [comment]
@darth-tesla глядзі тут https://github.com/diglabby/doika/issues/734

**Comment by rizomaa** [comment]
@darth-tesla перанес пакуль у бэклог. але апішы тут на чым спыніўся, пасля табе будзе прасцей вяртацца да карткі
