### ISSUE TITLE
Пафіксіць валідацыю плацежных інтэрвалаў

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#504]
@lptn Спрабую перадаваць розныя фарматы кшталту "P1H", "P1M" cюды https://github.com/diglabby/doika/blob/706943ca34ae78a54bea4f8707e3b64d35fecf8e/app/Http/Controllers/Widget/CampaignSubscriptionIntendController.php#L24
але валідацыя не праходзіць.

Вось тут таксама баг з канверсіей 
https://github.com/diglabby/doika/blob/706943ca34ae78a54bea4f8707e3b64d35fecf8e/app/Services/PaymentGateways/BePaidPaymentGateway.php#L156
Пры ўваходным параметры "P1M"
```
$intervalUnit == '1'
```

**Comment by alies-dev** [comment]
`P1H ` -- не валідны інпут, трэба `PT1H` (прабач калі я напісаў няправільны прыклад)

З `P1M` мусіць быць усе ок -- я толькі што тэст напісаў


>Вось тут таксама баг з канверсіей

Дзякуй, гэта пафіксіў

**Comment by fr0zen** [comment]
👍
