### ISSUE TITLE
Хлопцы, вельмі актуальны рэліз версіі 2.0.0

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#508]
Тут мы хочам паставіць на першыя пилотныя сайты рэкурэнтныя плацяжы... ці можаце прадаставіць саммы ранні рэліз? @lptn

**Comment by alies-dev** [comment]
@rizomaa 
Прабач, я не зразумещ што ад нас падтабуцца: архіў?

**Comment by rizomaa** [comment]
@lptn патрабуецца мець рэліз з усімі бібліятэкамі, каб можна было ставіць распакаваўшы на віруткальным хостунгу (без кампозараў і іншых пакетных мэнэджэраў)

**Comment by alies-dev** [comment]
@rizomaa 
Ну хуткую руку зрабіў стварэнне архіваў пры рэлізах https://github.com/diglabby/doika/releases (але трэба адпаліраваць рашэнне)
![image](https://user-images.githubusercontent.com/5278175/58951689-6aead900-879a-11e9-825a-970c80286e05.png)


Як будзе адпалізавана, закрыю "Аўтаматычна стварэць архіў-істалятар для рэлізаў #160"

**Comment by rizomaa** [comment]
дзякуй @lptn
