### ISSUE TITLE
Аднаўленне пароля не працуе

### ISSUE THREAD

**Issue by svetasemashko** [diglabby/doika#51]
http://doika.falanster.by/doika/password/reset

**Comment by falanster** [comment]
@svetasemashko пакуль мы такое не планавалі, але я запішу ў бэклог. таму тут трэба пакуль асцярожна

**Comment by svetasemashko** [comment]
@falanster  добра, калі што я ўжо ведаю спосаб як аднавіць пароль рукамі...

**Comment by falanster** [comment]
@svetasemashko напішы калі ласка як ты гэта робіш у трэле (або тут у вікі), каб мы маглі хуткапыдамаць, калі раптам каму спатрэбіцца.

**Comment by svetasemashko** [comment]
https://trello.com/c/Lki1Z3tn/286-%D0%B4%D0%B0%D0%B4%D0%B0%D1%86%D1%8C-%D0%BC%D0%B0%D0%B3%D1%87%D1%8B%D0%BC%D0%B0%D1%81%D1%86%D1%8C-%D0%B0%D0%B4%D0%BD%D0%B0%D0%B2%D1%96%D1%86%D1%8C-%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D1%8C-%D0%B7%D0%B0%D0%B1%D1%8B%D0%BB%D1%96-%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D1%8C  @falanster
