### ISSUE TITLE
BePiad: Пытаць email для аднаразровых плацяжоў разам з дадзенымі карткі (а не перад карткаю)

### ISSUE THREAD

**Issue by alies-dev** [diglabby/doika#512]
Чаму: каб адпавядаць дызайну

@fr0zen 
есьць што дадаць да гэтай задачы?

**Comment by alies-dev** [comment]
@fr0zen 
Я падправіў каб bepaid пытаў на імэйл
![image](https://user-images.githubusercontent.com/5278175/58991794-d2804300-87f1-11e9-9cdd-d125d67a7d84.png)

**Comment by alies-dev** [comment]
@fr0zen 
Гатова!

**Comment by rizomaa** [comment]
Я не ведаю, адкуль вы узялі гэту задачу у стэк наогул)? @fr0zen @lptn

**Comment by fr0zen** [comment]
@rizomaa выцекла з абмеркаванняў з @lptn. Зараз логіка руху дадзенных данэйцера даволі кастыльная.

**Comment by rizomaa** [comment]
ага, дзякуй

**Comment by alies-dev** [comment]
@rizomaa 
@fr0zen 
>@rizomaa выцекла з абмеркаванняў з @lptn. Зараз логіка руху дадзенных данэйцера даволі кастыльная

Выцекла з дызайна наколькі я разумею, вось https://miro.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346272483621
![image](https://user-images.githubusercontent.com/5278175/59165424-0f1aaa00-8b24-11e9-95e6-6a2e7722f70e.png)
