### ISSUE TITLE
Дадаць тэкст на старонцы дадзенных карыстальніка. Няма падказак

### ISSUE THREAD

**Issue by svetasemashko** [diglabby/doika#52]
https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346272465599

Чакаемы вынік: 

- [ ] 1. апісаны ўсе палі
- [ ] 2. у тым ліку памылкі
- [ ] 3. а таксама падказкі

**Comment by svetasemashko** [comment]
@KsenjaV

**Comment by falanster** [comment]
дарэчы тут толькі пачынаецца эпік з тэкстамі... яшчэ прадумваю. але адчуваю, што шмат тэкстаў не ўлічана.

@nastyafrosty калі ласка можаш на усіх новых макетах пазначыць, дзе былі тлумачальныя тэксты на першых

**Comment by nastyafrosty** [comment]
@falanster  какие тексты?в коментах?

**Comment by falanster** [comment]
1. першым крокам важна раставіць кропкі, дзе павінны быць самі тэксты. 
2. пасля будзем разам пісаць тэксты. але толькі пасля першага кроку.
@nastyafrosty
