### ISSUE TITLE
Вырашыць багі перанакіравання пры аплаце на розных CMS

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#522]
@fr0zen @lptn 

1. Які ён?
2. Ці працуе ён па апошняму камміту з develop?

**Comment by rizomaa** [comment]
http://it3donate-landing.falanster.by/
http://it3donate-landing.falanster.by/doika/admin/campaigns

**Comment by fr0zen** [comment]
@fr0zen 
http://it3donate-landing.falanster.by/ - не грузіцца, трэба фікс.
http://it3donate-joomla.falanster.by/ - працуе
http://it3donate-wordpress.falanster.by/ - 403, трэба фікс

**Comment by fr0zen** [comment]
https://github.com/diglabby/doika/issues/319

**Comment by fr0zen** [comment]
@Olya147 можаш прайсціся па даменах?
http://it3donate-landing.falanster.by/
http://it3donate-joomla.falanster.by/
http://it3donate-wordpress.falanster.by/
http://it3donate-drupal.falanster.by/

Калі модуль усюды выглядае карэктна - у гатова картку

**Comment by rizomaa** [comment]
@fr0zen гэта усталёўка ідзе з рэліза, або з develop галіны?

**Comment by fr0zen** [comment]
@rizomaa dev галіна.

**Comment by rizomaa** [comment]
Ага, дзякуй. 
Тады я стварыў дадатковую таску для дэма дамена #595

**Comment by ghost** [comment]
@fr0zen  
**1. Веб-версия:** 
- при переходе на страницу оплаты в виджете появляется вертикальный скролл (не вмещается строка Powered by Doika)
- после совершении оплаты через сайт http://it3donate-landing.falanster.by/ происходит переадресация на страницу http://it3donate-landing.falanster.by/doika/doika/widget/campaigns/1 

**2. Моб. версия** (см. приложение в разрезе сайтов): 
- отсутствует кнопка, чтобы закрыть "Правила донейта";
- кнопки наслаиваются друг на друга;
- виджет не вмещается на странице.
[Моб. версия.zip](https://github.com/diglabby/doika/files/3423104/default.zip)

**Comment by rizomaa** [comment]
дамены пакуль вычышчаем таму картку зачыняем, калі будзем ладзіць адмысловыя тэсты, магчыма спатрэбіцца.
