### ISSUE TITLE
Дадаць скрыны для актуалізацыі масіва перакладаў

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#53]

**Comment by falanster** [comment]
@fr0zen ці акутальная гэта картка?

**Comment by fr0zen** [comment]
@falanster @KsenjaV актуальна, зараз у працэсе, будзе тут https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346292135916

**Comment by falanster** [comment]
@fr0zen калі ласка сінхранізуй усё таксама з макетамі на rtb, каб там усё было актуальна таксама
