### ISSUE TITLE
Памылкі пры спробе усталяваць Doika

### ISSUE THREAD

**Issue by svetit** [diglabby/doika#533]
Я спрабую паставиць дойку.
Пакуль я валюсь на п. 10. (для Лінукса)
"Разгортваем базу дадзеных камандай php artisan migrate."

1. Скажыце, інфа ўсюды актуальная тут
https://github.com/diglabby/doika/wiki/Устаноўка-для-Распрацоўшчыкаў ?

2. Я не ведаю як усталяваць ext-pdo, ext-curl, ext-json, ext-mbstring для пхп.
Падкажыце, калі ласка. Ці могуць быць праблемы з-за гэтага?

3. І версія нпм у мяне:
npm -v
3.5.2
Ці важна больш новая версія?

![image](https://user-images.githubusercontent.com/1722996/59567488-2bb06800-9077-11e9-945d-7bf342162552.png)

**Comment by alies-dev** [comment]
@svetit 
не прайшла папярэдняя каманда:  `composer install` (ці не была запушчана ці завяршылася з памылкай), запусці яшчэ раз калі ласка з тэчкі дойкі і пакажы вывад яе

**Comment by alies-dev** [comment]
@svetit

Як справы ў цябе з усталеўкаю? Прайшла далей?

**Comment by svetit** [comment]
@lptn  Вітаю. Дзякуй вялікі за адказ!
Я з тых часоў не спрабавала працягнуць. Але буду. І скіну што там далей.

**Comment by svetit** [comment]
`Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-curl * is missing from your system. Install or enable PHP's curl extension.
  Problem 2
    - The requested PHP extension ext-mbstring * is missing from your system. Install or enable PHP's mbstring extension.
  Problem 3
    - Installation request for erusev/parsedown 1.7.3 -> satisfiable by erusev/parsedown[1.7.3].
    - erusev/parsedown 1.7.3 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 4
    - Installation request for laravel/framework v5.8.23 -> satisfiable by laravel/framework[v5.8.23].
    - laravel/framework v5.8.23 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 5
    - Installation request for facebook/webdriver 1.6.0 -> satisfiable by facebook/webdriver[1.6.0].
    - facebook/webdriver 1.6.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 6
    - Installation request for phar-io/manifest 1.0.3 -> satisfiable by phar-io/manifest[1.0.3].
    - phar-io/manifest 1.0.3 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 7
    - Installation request for phpunit/php-code-coverage 6.1.4 -> satisfiable by phpunit/php-code-coverage[6.1.4].
    - phpunit/php-code-coverage 6.1.4 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 8
    - Installation request for phpunit/phpunit 7.5.12 -> satisfiable by phpunit/phpunit[7.5.12].
    - phpunit/phpunit 7.5.12 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 9
    - Installation request for theseer/tokenizer 1.1.2 -> satisfiable by theseer/tokenizer[1.1.2].
    - theseer/tokenizer 1.1.2 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 10
    - laravel/framework v5.8.23 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/dusk v5.1.0 requires illuminate/console ~5.7.0|~5.8.0|~5.9.0 -> satisfiable by laravel/framework[v5.8.23].
    - Installation request for laravel/dusk v5.1.0 -> satisfiable by laravel/dusk[v5.1.0].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-sockets.ini
    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.2/cli/conf.d/20-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
`
Вынік каманды "composer install" @lptn 

"Я не ведаю як усталяваць ext-pdo, ext-curl, ext-json, ext-mbstring для пхп.
Падкажыце, калі ласка. Ці могуць быць праблемы з-за гэтага?" Гэта звязана?

**Comment by alies-dev** [comment]
@svetit 
>Падкажыце, калі ласка. Ці могуць быць праблемы з-за гэтага?" Гэта звязана?

так, у цябе ў сістэме не хапае PHP экстэншынаў (яны ж і модулямі завуцца):
 - ext-curl
 - ext-mbstring
 - ext-dom

 Для ubuntu паспрабуй
```sh
sudo apt-get install php7.2-curl php7.2-mbstring php7.2-dom
```

**Comment by svetit** [comment]
@fr0zen  Мне дапамог гэта вырашыць!

**Comment by alies-dev** [comment]
@svetit Файна!
Калі паставілі табе дойку - закрывай issue калі ласка ;)

**Comment by svetit** [comment]
![image](https://user-images.githubusercontent.com/1722996/60385336-c43fe280-9a90-11e9-97fc-75899cdf74df.png)
Атрымалася, ура! :)

**Comment by svetit** [comment]
Трэба было ўсталяваць усе залежнасці да php.

Напрыклад, "sudo apt install php7.2-pdo" ...

**Comment by rizomaa** [comment]
@svetit у гайдзе як разумею гэта патрабаванне прапушчана?

@fr0zen @lptn @cema93

**Comment by alies-dev** [comment]
@rizomaa 
У гайдзе гэта есьць :P
