### ISSUE TITLE
Указать пропорции загружаемого рисунка в поле "Выява кампаніі"

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#536]
**Предусловие:** открыть модуль (админ), создать кампанию.
**Шаги воспроизведения:**
1.  нажать на "Рэдагаваць";
2. загрузить в поле "Выява кампаніі" изображение (!портретная ориентация);
3. нажать "Захаваць";
4. открыть страницу кампании на сайте
**Фактический результат:** рисунок обрезан по вертикали.

![1](https://user-images.githubusercontent.com/46268205/59693363-7228d280-91ef-11e9-8cf2-1e6551400133.png)

**Comment by alies-dev** [comment]
@fr0zen @nastyafrosty 
Якія патрабаванні да выявы? Магу дадаць валідацыю на бэкэндзе, але трэба ведаць абмежаванні

**Comment by KuhniaDruggist** [comment]
Я так понимаю здесь необходимо масштабирование загружаемых картинок под размер поля с учетом их пропорций? Ничего обрезаться не должно

**Comment by rizomaa** [comment]
@KuhniaDruggist прывітанне,

1. Варта зрабіць допіс, каб людзі ведалі пра прапорцыі.
2. Таксама каб рабіўся не кропінг, а звыйназ смена памеру.

**Comment by alies-dev** [comment]
@rizomaa 
@KuhniaDruggist 
прашу заўважыць, што браўзеры не аптымальна мчянябць памеры выяваў -- на выхадзе будзе файл вялікага памеру. У ідэыяле лепей рабіць гэта на бэкэндзе (але не паўсюль стаяць наабходныя бінарнікі і php-модулі) ці 3-баковых API/сэрвісаў (што стварае складанасці пры гэгістрацыі)

Найпрасцей напісаць невялікі інлайн хэлпдля адміна і дэлігаваць гэта яму, а на бэке зрабіць валідацыю і прапускаць толькі неабходны памер выявы (піксель у піксель);

https://squoosh.app/ - лепшы сэрвіс дзе адмін рукамі можа аптымізаваць выяву (але не кропнуць ці паменшыць)

**Comment by rizomaa** [comment]
@lptn 

"чаму не аптымальна" на франце змяніць памер выявы?

ЗЫ
Дзякуй за лінк на цікавы сэрвіс.

**Comment by alies-dev** [comment]
Браўзеры рэсайзяць выявы выкарыстоўваючы неаптымальныя алгатырмы, у выніку
выява будзе на 20%-80% болей чым калі гэта рабіць праз MozJpeg, PNGOptim і
іншыя алгарытмы, якія выкарыстоўваюцца тым жа сэрвісам што я даў лінк. Але
гэта калі запарывацца аптымізацыяй.

З іншага боку перакласці гэтую праблему на адміна -- гэта нават спрасціць
дойку, што для фокуса над болей важнымі задачамі

**Comment by rizomaa** [comment]
@lptn так вось гэта

> З іншага боку перакласці гэтую праблему на адміна -- гэта нават спрасціць
дойку, што для фокуса над болей важнымі задачамі

Зараз найбольш значна. Важна прыбраць задачы, якія непатрэбны на дадзеным этапе.

**Comment by alies-dev** [comment]
Ну так давайце проста валідзіраваць памеры (з улікам рэціна дысплэяў) і не
кропаць ці гэсайзіць :)

**Comment by KuhniaDruggist** [comment]
@rizomaa @lptn 
Сделал в лоб как и требовалось в issue. (Указал оптимальные пропорции). Однако, проблему это не решило.
Покопавшись обнаружил в стилях фиксированную высоту контейнера в который вложено изображение, из-за чего собственно говоря и происходит резка.
![Screenshot_124](https://user-images.githubusercontent.com/48412681/84423822-bf375d00-ac27-11ea-9a84-dae9fb2dc519.png)
![Screenshot_125](https://user-images.githubusercontent.com/48412681/84423825-bfcff380-ac27-11ea-92bb-9892ddd7e085.png)

Предлагаю:
А. Вариант попроще:
    1. установить максимальную ширину изображения max-width (под каждое медиа выражение)
    2. задать height: auto
   (Однако при соотношении 2:1, если изображение вертикальное то появляется вертикальная 
    полоса прокрутки)
![Screenshot_126](https://user-images.githubusercontent.com/48412681/84429088-44bf0b00-ac30-11ea-967c-2b26d279d824.png)
Б. Сложнее:
    Сделать как в VK - Выбирать зону, которая будет отображаться в превью.(Но это скорее всего на БЭКЕ)
![Screenshot_111](https://user-images.githubusercontent.com/48412681/84428926-fd387f00-ac2f-11ea-8b6d-94b07c33e091.png)

Что вы об этом думаете?

**Comment by rizomaa** [comment]
@KuhniaDruggist другі варыянт цікавей. 
1. глянь калі ёсць нейкая простая бібліятэка, можна паспрабаваць. калі за 2-3 гадзіны нічога варта не знойдзеш (бегла бачу, што нешта ёсць https://vuejsexamples.com/tag/crop/)
2. проста напісаць на лэйбе да поля запампоўкі выявы патрабуемую прапорцыю тэкстам і ўсё.

**Comment by alies-dev** [comment]
@rizomaa 
а навошта нам гэтыя складанасці зараз? Можа проста будзем пабрабаваць патрэбны памер, а адмін можа яго падрыхтаваць у адмысловых праграмах

**Comment by rizomaa** [comment]
@lptn можна і так, гэта пункт 2 змайго каментара вышэй. =)

**Comment by KuhniaDruggist** [comment]
@rizomaa Привет. В общем ситуация на данный момент такая. Я потратил время глубже разобрался во vue, понял как работают компоненты. Удалось создать vue компонент для кропинга и подключить его, однако не могу его правильно применить, чтобы им пользоваться именно в момент выбора файла(не достаточно знания, пока). Так как время все-таки идет буду двигаться дальше и поэтому прибегну ко второму варианту решения проблемы.
На данный момент в открытом ПР реализовано следующее:
1. Добавил span для соотношения сторон. (так это выглядит)
![Screenshot_127](https://user-images.githubusercontent.com/48412681/85332103-f9ceae80-b4df-11ea-8dec-f88f0b7f294d.png)
Однако, опять таки повторюсь фиксированная высота в стилях не позволяет полноценно решить данную проблему для вертикальных изображений.

Можем созвониться я покажу в чем суть проблемы и мой вариант её решения.
Потому что с теми стилями что есть сейчас необходимо требовать только горизонтальное изображение.

**Comment by rizomaa** [comment]
@KuhniaDruggist можам стэлефанавацца. напішу у асабістыя. калі ласка пакінь тут нейкі код, што спрабаваў рабіць

**Comment by rizomaa** [comment]
@KuhniaDruggist прыняў ПР па гэтай задачы. калі трэба будзе нешта навярнуць зробім дадатковы. Дзякуй за працу тут)
Па тваіх заўвагах пагутарым
