### ISSUE TITLE
Ці разбіваць наладкі па падпунктах?

### ISSUE THREAD

**Issue by falanster** [diglabby/doika#54]
@nastyafrosty гэта пытанне задаў @fr0zen што скажаш на гэты конт?

**Comment by nastyafrosty** [comment]
> @nastyafrosty гэта пытанне задаў @fr0zen што скажаш на гэты конт?

а на какие пункты?

**Comment by falanster** [comment]
@nastyafrosty ага, затэгуй яго на пытанні, тады ён атрымае уведамленне на пошты сабе

**Comment by fr0zen** [comment]
@nastyafrosty @falanster што мелася на ўвазе: зараз усе наладкі модуля знаходзяцца на адной старонке, на мой погляд гэта можа перагружаць інтэрфейс у перспектыве. Таму адразу можна разбіць наладкі па падтэмах, кшталту (Знешні выгляд, Плацежная інфа, Наладкі паведамленнняў і т.д.). Калі закіну скрыны, глянеш сваім вокам і па ітогу вырашым. Я яшчэ не ўпэўнены на конт патрэбы гэтага.

**Comment by falanster** [comment]
ага, у нас быў макет які больш зручна раганізоўваў наладкі ў #21 ?

@fr0zen @nastyafrosty аб'ядноўваем задачу?

**Comment by rizomaa** [comment]
@fr0zen @nastyafrosty пінг

**Comment by fr0zen** [comment]
@rizomaa тут ужо наладкі разбітыя, зачыняю
