### ISSUE TITLE
Зрабіць сбор дадзеных аб тым, чаму чалавек адпісваецца. 

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#541]
Зрабіць сбор дадзеных аб тым, чаму чалавек адпісваецца. 
Рэалізаваць наступны алгарытм. Націсківаем лінк - з'яўляецца апроснік аб тым, чаму адпісваемся - па выніках з'яўляецца лінк на адпіску. 
Прамыя спасылкі на адпіску забаронены.

**Comment by rizomaa** [comment]
не гарачая. @fr0zen
