### ISSUE TITLE
Калі не прайшла плата, карыстальнік атрымлівае паведамленне на пошту

### ISSUE THREAD

**Issue by cema93** [diglabby/doika#542]
## Апісанне
Я хочу, чтобы пользователь, чей платеж не прошел получал письмо с просьбой попробовать оплатить ещё раз
Пример:
я попробовал оплатить, оплата не прошла. Я обиделся и ушел.
Через час система проверяет, был ли удачный платеж. Если нет то высылать письмо с информацией о не прошедшем платеже и предлагать оплатить ещё раз

**Comment by rizomaa** [comment]
@cema93 глядзі тут тэксты ўсіх мэйлаў збіраем, якія могуць дачылацца данэйцеру:

https://github.com/diglabby/doika/issues/464#issuecomment-504439832

**Comment by rizomaa** [comment]
https://github.com/diglabby/doika/issues/541

**Comment by rizomaa** [comment]
дадаў, бо выглядае функцыя даволі значнай

**Comment by rizomaa** [comment]
Зачянем гэту картку. працяг тут https://github.com/diglabby/doika/issues/565
