### ISSUE TITLE
Фикс названия поля суммы

### ISSUE THREAD

**Issue by nastyafrosty** [diglabby/doika#543]
Сейчас название поля ввода суммы, которая нужна для сбора, обозначена как "колькасць", это не очень понятно. предагаю "патрэбная сума"

**Comment by KuhniaDruggist** [comment]
Сделал все в одном PR в issue #711

**Comment by rizomaa** [comment]
@KuhniaDruggist 

Добра, але ёсць пытанні па ПР (прычытаў прув https://github.com/diglabby/doika/pull/728#issuecomment-629697173)

Я магу гэты раз прыняць такі ПР (бо тэмы блізкія) ў якасці выключэння (!). Але варта адсылаць асобныя (хаця і падобныя ішшус). Прынцып: адна ішус = адзін ПР.

Тут гайд працы з галінамі. Раю прачытаць:
https://github.com/diglabby/doika/wiki/Распрацоўшчыку.-Git.-Праца-з-рэпазіторыем
Калі маеш каментары, пакідай іх тут.
