### ISSUE TITLE
В виджете оплаты кнопка подтвердить смещается вниз при вставке текста

### ISSUE THREAD

**Issue by cema93** [diglabby/doika#545]
В виджете оплаты кнопка подтвердить смещается вниз при вставке текста.

Если текста очень много, кнопка кажется отдельно от всей формы.

Кнопка "подтвердить" должна быть сразу за выбором разово\подписка

**Comment by rizomaa** [comment]
@Gordonshik ці можаш паўтарыць гэты баг?

**Comment by Gordonshik** [comment]
![изображение](https://user-images.githubusercontent.com/51483246/75373356-347e5c80-58db-11ea-9c1b-8e3782df1be1.png)
@rizomaa ничего никуда не смещается, или быть я чего-то не понимаю?

**Comment by rizomaa** [comment]
@cema93 на чым тэставаў?

@Gordonshik на якіх браўзераз правяраеш?

**Comment by Gordonshik** [comment]
@rizomaa 
![изображение](https://user-images.githubusercontent.com/51483246/75373815-19f8b300-58dc-11ea-9c73-62be75549579.png)

**Comment by rizomaa** [comment]
@Gordonshik карыстаешся? 

https://www.browserstack.com/?campaignid=359715590&adgroupid=1279831768347842&adid=&msclkid=e1ce91299c7011c550b2cf7f28ee2d7f

яшчэ некальки бразуераў які мімнімум зром + нешта_)

**Comment by Gordonshik** [comment]
@rizomaa 
нет, не пользуюсь
На хроме у меня та же история

**Comment by Gordonshik** [comment]
@rizomaa на Brave тоже ничего

**Comment by rizomaa** [comment]
> @rizomaa
> нет, не пользуюсь

@Gordonshik паспрабуй, для фронтэдндзера гэта вельми добра штука. Калі спатрэбіцца больш браузераў кажы, у нас ёсць поўны акаўнт.

**Comment by Gordonshik** [comment]
@rizomaa мне дальше как действовать если на моих браузерах нет этого?
Если аккаунт есть и мне он потенциально понадобится в стажировке- предлагаю расшарить, потому что там на каждый браузер 1 минута, а мне еще разобраться с этим надо будет как и что работает. Если это действительно время сэкономит.

**Comment by rizomaa** [comment]
@Gordonshik акей. расшару.
пакуль гэту картку адкладваем. трэба каб пацвердзіўся баг, або дэталізаваны @cema93 са скрынамі.

дзякуй, што тут парыўся
