### ISSUE TITLE
Поле ўводу "іншая сума" зрабіць пастаяннай да моманту пакуль туды не пачалі ўводзіць суму

### ISSUE THREAD

**Issue by nastyafrosty** [diglabby/doika#548]
В виджете в поле. где донэйтер может ввести свою сумму вместо 0  лучше написать "іншая сума" і не менять фразу на выбранную сумму із предоставленных, пусть пользователь всегда відіт,что он может впісать свою

**Comment by KuhniaDruggist** [comment]
Сделал. Изменил плейсхолдеры в поле ввода суммы в трех вариантах (be, ru, en)

**Comment by rizomaa** [comment]
@KuhniaDruggist прыняў ПР. Напішу вам мэйл. Добрага дня
