### ISSUE TITLE
Прыбраць функцыянал тэставыя плацяжы.

### ISSUE THREAD

**Issue by cema93** [diglabby/doika#549]
На странице " Плацежныя сістэмы" отображается надпись "Адключыць тэставыя плацяжы". С первого взгляда не понятно, что будет происходить при включении\отключении этой функции.

Предлагаю переименовать этот пункт на "Тэставыя плацяжы". При включении этого пункта включаются тестовые платежи. при отключении - отключаются.

И сделать этот пункт по дефолту включенным.

**Comment by cema93** [comment]
@diglabby/core прошу вас высказать свое мнение

**Comment by rizomaa** [comment]
@cema93 так, можна па дэфолку уключаным. 
ёсць яшчэ думака

каб у кліенскай частцы было паведамленне побач з аплатай, на першым вакне віджэта. 
гэта дасць магчымасць і карыстальнікам і адміну модуля своечасова перключыцца у рэальны рэжым.

**Comment by rizomaa** [comment]
пакуль думкі ідуць прыбраць наогул тэставыя плацяы, бо бачу дэвелаперы разгубіліся

**Comment by rizomaa** [comment]
Трэба наогул прыбраць рэжым тэставых плацяжоў

**Comment by rizomaa** [comment]
Зачыняю гэту картку. бо выдаляем функцыі тэставых плацяжоў
