### ISSUE TITLE
Не захоўваюцца наладкі плацёжнай сістэмы

### ISSUE THREAD

**Issue by cema93** [diglabby/doika#550]
При заполнении всех полей на странице настройки платежной системы не сохраняются данные.
В консоли;
exception: "Symfony\Component\Debug\Exception\FatalThrowableError"
file: "C:\xampp\htdocs\doika\app\Http\Controllers\Dashboard\SettingsController.php"
line: 34
message: "Argument 1 passed to Diglabby\Doika\Http\Controllers\Dashboard\SettingsController::Diglabby\Doika\Http\Controllers\Dashboard\{closure}() must be of the type string, null given, called in C:\xampp\htdocs\doika\vendor\laravel\framework\src\Illuminate\Support\Collection.php on line 1197"

**Comment by rizomaa** [comment]
Адчуваю, што гэта гарачы піражок становіцца.

**Comment by rizomaa** [comment]
@cema93 

У мяне візуальна пры запаўненні нічога не мяняецца наогул. Цікава 

У мяне ў кансолі (Network->XHR->Response) даволі цікавы вынік: 
`{"settings":{"gateway_bePaid_idMarket":"123","gateway_bePaid_keyMarket":"2342134123412341234","termsOfUse":"<p>\u0413\u044d\u0442\u0430 \u0443\u043c\u043e\u0432\u044b \u043a\u0430\u0440\u044b\u0441\u0442\u0430\u043d\u043d\u044f \u043f\u0440\u0430\u0432\u0430\u0439\u0434\u044d\u0440\u0430\u043c !!!!<\/p>","disableLivePayments":[],"minPayment":"1","maxPayment":"100","paymentInteval":[]}}`

Наконт фронтэнда, бачу там усё развалена, толькі іншае:

```
Vue warn]: Property or method "pending" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

-
--> <PaymentSystems> at resources/js/dashboard/views/PaymentSystems.vue
       <Full> at resources/js/dashboard/containers/Full.vue
         <App> at resources/js/dashboard/App.vue
           <Root>

dashboard.js:122992 [Vue warn]: Invalid prop: type check failed for prop "checked". Expected Boolean, got String with value "test".

found in

---> <CSwitch> at resources/js/dashboard/components/Plugins/Switch.vue
       <BTab>
         <BTabs>
           <BCollapse>
             <PaymentSystems> at resources/js/dashboard/views/PaymentSystems.vue
               <Full> at resources/js/dashboard/containers/Full.vue
                 <App> at resources/js/dashboard/App.vue
                   <Root>
```

**Comment by rizomaa** [comment]
План рэалізацыі:

- [x] 1. Знайсці апрацоўшчкі на бэкэндзе.
- [x] 2. Знайсці апрацоўшчыкі на франце.
- [x] 3. Праглядзець як справы ў базе.
- [x] 4. Паглядзець метад pending і props -> checked.
- [x] 5. Падумаць, якія паведамленні зрабіць пры паспяховым запісу або непаспяховым можна дадаць (ці ёсць ўжо пастаўленыя бібліятэкі, або самаму паставіць)
- [x] 6. Пратэставаць

**Comment by rizomaa** [comment]
@cema93 праглядзеў гэту ішус, 
з кансолі прыбраў памылкі.
пакуль тут не магчыма паўтарыць тваю памылку.

Але ёсць канешне іншыя заўвагі:
1. Як і дзе захоўваецца рэжым тэставых плацяжоў (у табліцы settings няма)
2. Даволі блытаная логіка ў switcher, магчыма там прыёдзецца перапісаць кампаненту і прыбраць кучу непатрэбных залежнасцяў.

Гэта на асобныя задачы.

зы
Світчэр трэба будзе раскурваць. Бо без каментавання яго складана разумець.

Пул https://github.com/diglabby/doika/pull/699
