### ISSUE TITLE
Частота рекурентності платежа в адмінке: пакінуць толькі 1месяц

### ISSUE THREAD

**Issue by nastyafrosty** [diglabby/doika#551]
убрать в частоте рекурентності 1 час, возможно 1 день
і вообще оставляем ли этот функционал, в начале у нас было ежемесячно

**Comment by rizomaa** [comment]
@fr0zen @lptn так, у нас зараз толькІ штомесяцовая рэкурнтнасць. @nastyafrosty

**Comment by alies-dev** [comment]
Я думаю пакінем падтрымку любых інтэрвалаў на backend а вось на франце трэба толькі 1месяц пакінуць

**Comment by rizomaa** [comment]
@lptn удаклдані калі ласка дзе у нас зараз запісваецца інтэрвал, праз які адбываецца рэкурнэтнаяспісанне грошай?

**Comment by alies-dev** [comment]
@rizomaa 
У БД subscriptions.payment_interval:
![image](https://user-images.githubusercontent.com/5278175/60387279-4dfbaa00-9aa9-11e9-8823-3782f3373151.png)

Мы гэты інтэрвал абавязаны перадаваць на bePaid пры стварэнні падпіскі, раней ен быў захардкоджаны на `1 month` але я зрабіў яго гнуткім перад прэзентацыяй

На франце як гэта будзе (налады кампаніі, налады дойкі, захардкоджана) -- ня ведаю, думаю дастаткова захардкодзіць пакуль што

**Comment by rizomaa** [comment]
@lptn захардкодзіць маеш на ўвазе і пакінуць у табліцы базы. так?

**Comment by alies-dev** [comment]
@rizomaa маю на ўвазе каб фронт заўседы дасылаў на бэк інфу пра адзін месяц -- гэта самае простае што можам зрабіць

**Comment by rizomaa** [comment]
@lptn так, я не прачытащ надпіс да базы. меў на увазе, што зараз увесь канфіг ляжыць у базе.. гэта крута!

**Comment by fr0zen** [comment]
- [ ]  Прыбраць элемент выбару інтэрвала часу з адмінкі.
- [ ] Назначыць кожнай новай кампаніі інтэрвал у адзін месяц

**Comment by rizomaa** [comment]
зачыняю картку яна нерэлевантная патрэбам. пасля дададзім гэта калі будзе такая патрэба
