### ISSUE TITLE
Кнопка рекурентности в виджете

### ISSUE THREAD

**Issue by nastyafrosty** [diglabby/doika#552]
Если у нас есть разные виды рукурентности (месяц, неделя, день), то пользователю неоходимо видеть, на что же он подписывается. есть предложение в кнопке рекурентности писать не "подписка", а "ежемесячно", "еженедельно"

**Comment by rizomaa** [comment]
@nastyafrosty пакуль толькІ штомесяцовая падпіска, усё астатнія варта прыбраць (схаваць). будзем думаць над імі пасля.
