### ISSUE TITLE
Подготовка релиза к публикации

### ISSUE THREAD

**Issue by cema93** [diglabby/doika#553]
Удаляются ли перед публикацией релиза кнопки и поля, которые не работают?

**Comment by cema93** [comment]
Мы предоставляем пользователям продукт, который работает с деньгами. Всё, что работает с деньгами должно быть качественным и безопасным.

Если есть не рабочие кнопки это показывает, что продукт не качественный.

Если в админке есть кнопки, которые не работают, то думаю, что их стоит из релиза убирать, чтобы не объяснять, что кнопка есть, но пользоваться ей пока что нельзя.

**Comment by cema93** [comment]
@diglabby/core поделитесь своим мнением

**Comment by alies-dev** [comment]
Згодны, функцыянал які плануецца ажывіць мусіць быць выдалены ці схаваны

**Comment by rizomaa** [comment]
@cema93 @lptn @fr0zen 
так калі ласка не мудрыце тое, чаго няма на макетах і колькасць рухаз зменшым і не будзе дохлых прыціскаў

**Comment by rizomaa** [comment]
@cema93 апішы калі ласка палі, якія на твой погляд не працуюць... зацяб 3 штукі

**Comment by cema93** [comment]
Кнопка нового пользователя, кнопка отключения компании, Возможно раздел уведомлений

**Comment by rizomaa** [comment]
> Кнопка нового пользователя, кнопка отключения компании, Возможно раздел уведомлений

@cema93 дзякуй. 

1. Кнопка нового пользователя,  - прыбіраем яна не патрэбна.
2. кнопка отключения компании, - дапрацуем.
3. Возможно раздел уведомлений - правярай

**Comment by rizomaa** [comment]
Картку зачыняю, бо схаванне непрацощнага функцыянала і непатрэбных элементаў інтерфейса паклалі у іншыя карткі па тэмам.
