### ISSUE TITLE
warning в консоли

### ISSUE THREAD

**Issue by cema93** [diglabby/doika#554]
при работе с админкой и виджетом в консоли разработчика появляется масса warning-ов
![image](https://user-images.githubusercontent.com/1865012/59980769-071e3800-9603-11e9-8253-8896d36d6db9.png)
Я понимаю, что это не ошибки, но, если они есть, значит мы что-то делаем не правильно

Их надо либо исправить, либо скрыть. @diglabby/core что думаете на этот счет?

**Comment by rizomaa** [comment]
на якіх старонках гэта з'яўляецца?

@Olya147 у цябе тое самае?

**Comment by ghost** [comment]
@rizomaa Таких сообщений много, и они появляются при:
1) переходах между разделами, за исключением "Агульная інфа" и "Зваротная сувязь";
2) создании пользователя и кампании. 
Логи ниже:
[Внешний вид.log](https://github.com/diglabby/doika/files/3364787/default.log)
[Изменение цветов в виджете.log](https://github.com/diglabby/doika/files/3364788/default.log)
[Платёжные системы.log](https://github.com/diglabby/doika/files/3364789/default.log)
[Создание кампании.log](https://github.com/diglabby/doika/files/3364790/default.log)
[Создание нового пользователя.log](https://github.com/diglabby/doika/files/3364791/default.log)
[Список кампаний.log](https://github.com/diglabby/doika/files/3364792/default.log)
[Список пожертвований.log](https://github.com/diglabby/doika/files/3364793/default.log)
[Список пользователей.log](https://github.com/diglabby/doika/files/3364794/default.log)
[Уведомления.log](https://github.com/diglabby/doika/files/3364795/default.log)

**Comment by rizomaa** [comment]
@Olya147 дзякуй будзем глядзець

**Comment by rizomaa** [comment]
#690 гатова. гэту карку зачыняю. калі будзе што паўтарацца калі ласка адчыняйце новую картку.
