### ISSUE TITLE
Фронтэнд. Рэалізаваць вывад памылак пры захаванні кампаніі. Адмінка

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#564]
Адмінка

- [x] 1. пустая назва кампаніі.
- [x] 2. не пазначана дата пачатку і сканчэння
- [x] 3. няма апісання
- [x] 4. Непазначана сума кампаніі
- [x] 5. Выява - не абавязкова

**Comment by alies-dev** [comment]
Праверыў бэк: усе апісанныя праверкі ужо рэалізаваны, справа за франтом (адпісваюся)

**Comment by rizomaa** [comment]
@lptn дзякуй

**Comment by rizomaa** [comment]
Пакуль думкі
Чэнкуць усё праз swal

**Comment by rizomaa** [comment]
Гатова =) Што атрымалася.

1. Поле picture_url
1.1. Асноўны затык быў на тым, што кампанія не стваралася, калі не было выявы да яе. Усе перарыў у франце, але адказ аказаўся на бэку.  Пакуль паставіў (праз дадатковую міграцыю*) NULL на поле picture_url табліцы campaign, магчыма ў будучым дададзім фічу выява па змоўчанні, але зараз не трэба. 
1.2. На франце ў віджэце пакуль зрабіў праверку на запоўненасць поля picture_url для вываду. Асноўныя змены ў файле resources/js/widget/views/MainWindow.vue
3. Яшчэ праўкі на франце па іншым палям у файле resources/js/dashboard/views/CampaignForm.vue

Гайды, якія дапамаглі:
1. https://www.techiediaries.com/laravel/laravel-7-6-migrations-tutorial-admin-role-example/
2. https://laravel.com/docs/7.x/migrations#running-migrations
3. https://vuejs.org/v2/guide/computed.html#Computed-Properties

*Для прымянення міграцыі пасля заліўкі абнаўленняў з апстрыма, калі ласка зрабіце
`sudo php artisan migrate`

** Патэнцыйна можна зрабіць змены ў асноўнай міграцыі для табліцы campaign 
https://github.com/diglabby/doika/blob/develop/database/migrations/2019_01_01_000010_create_campaigns_table.php цікава тваё меркаванне, дзе лепей у асобнай міграцыі, або ў асноўнай адносна будучай распрацоўкі @lptn

**Comment by rizomaa** [comment]
https://github.com/diglabby/doika/pull/722

**Comment by Alexeyvk** [comment]
Up: QA при адаптации Doika4UA обнаружен фронт-енд баг при сохранении кампании: 
Ошибки при неправильных датах

Summary
--
Any errors aren't shown for invalid dates 

Steps to Reproduce
--
1. Login to Admin page https://dbai.zeleniy-list.od.ua/doika/doika/dashboard/login 
2. Click/Tap on "Додати" > "Нова кампанія".
3. Fill all mandatory fields and set the same 'Дата початку' and 'Дата закінчення' (or End date is earlier than Start date).
4. Click/Tap on 'Зберегти' button.

Actual Result
--
Nothing happened. The same screen is displayed, new campaign isn't saved but any errors aren't shown for invalid date.

Expected Result
--
Corresponding error about invalid dates is shown.


Screenshot
--
https://prntscr.com/10bnc7w

**Comment by Alexeyvk** [comment]
Up: QA при адаптации Doika4UA обнаружен фронт-енд баг при сохранении кампании: 
Не сохраняется  сумма float сумма пожертвы, не выдается ошибка

Summary
--
Any errors aren't shown for not integer required amount 

Steps to Reproduce
--
1. Login to Admin page https://dbai.zeleniy-list.od.ua/doika/doika/dashboard/login 
2. Click/Tap on "Додати" > "Нова кампанія".
3. Fill valid mandatory fields and set some double number in 'Необхідна сума' field.
4. Click/Tap on 'Зберегти' button.

Actual Result
--
Nothing happened. The same screen is displayed, new campaign isn't saved but any errors aren't shown for invalid required amount.

Expected Result
--
Corresponding error about invalid amount is shown.


Screenshot
--
https://prntscr.com/10boklc

**Comment by Alexeyvk** [comment]
Up: QA при адаптации Doika4UA обнаружен фронт-енд баг при сохранении кампании: 
Ошибка не показана при пустых датах, обязательных полях. Кнопка "Сохранить" доступна

Summary
--
Errors aren't shown for empty date fields and 'Зберегти' button is enabled

Steps to Reproduce
--
1. Login to Admin page https://dbai.zeleniy-list.od.ua/doika/doika/dashboard/login 
2. Click/Tap on "Додати" > "Нова кампанія".
3. Fill all mandatory fields with valid values.
4. Clear dates.
5. Click/Tap on 'Зберегти' button.

Actual Result
--
Errors aren't shown for empty date fields and 'Зберегти' button is enabled

Expected Result
--
Corresponding errors about empty date fields are shown. 'Зберегти' button is disabled.


Screenshot
--
https://prntscr.com/10bop6r
