### ISSUE TITLE
Фіча. Наладзіць паведамленні, калі не адбылася аплата: няма сродкаў, скончыўся тэрмін карты. 

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#565]
Нужно обсудить, как поведёт себя система (в т.ч. механизм списания средств и аннулирования подписки) в следующих случаях:

- [ ] няма сродкаў
- [ ] скончыўся тэрмін карткі

**Comment by rizomaa** [comment]
@Olya147 дзякуй што дадала тэму.

Пакуль я думаю, што 
1. Напрацягу тыдня адбываецца 3 спробы праз 2 дні.
2. Калі не атрымліваецца робіцца спроба праз месяц (згодна падпісцы).

@diglabby/core @lptn @fr0zen @cema93 вашы думкі?

**Comment by alies-dev** [comment]
>если на карте плательщика недостаточно средств;

робіцца 5 спробаў, але інтэрвал паміж імі мне не вядомы (@rizomaa відаць ведае болей, сапраўды [3 спробы па дэфолту, але мы праставілі 5](https://github.com/diglabby/doika/blob/9aedabb2d50067314ea296c46f3d6a58b9359644/app/Services/PaymentGateways/BePaidPaymentGateway.php#L131) [вярнуць 3?])

>организация полностью удалила модуль.

Выдаленне модуля нічога не мяняе. Трэба выдаляць кампаніі перад выдаленнем модуля

**Comment by rizomaa** [comment]
@lptn 

тры разы на мой погляд дастаткова, але я не буду вельмі можна настойваць на іх, хаця адзін і той жа ліст можа трапіць у спам. 

хачу падкрэсліць, што гэтыя спрабы не павінны адключыць ад падпіскі наогул. простамодуль разумее, што у чэла няма сродкаў і "прапусціць" гэта месяц, запытае наступны усё як па плану. разумееш ідэю?

Ці згодны з агарытмам
1.3-5 папярэджэнняў.
2. паўтор запыта на наступны месяц (пакуль сам падпісчык не адпішацца праз лінк)
?

офтоп
накнот выдалення кампаній. я разумею @Olya147 заўвагу. бо арганізацыя можа 1. не аплаціць хостынг. 2. або пасадзіць адміна, які выпадкова выдаліць модуль з базай, калі будзе "чысціць". 
на будучыню можна падумаць пра аўтаматычны дэінсталятар. але зараз пакідаем безтэрміновыя планы у падпісках.

**Comment by alies-dev** [comment]
@rizomaa 
>Ці згодны з агарытмам

так, менавіта так гэта і працуе (ну ці мы чакаем што яна так працуе :) )

**Comment by rizomaa** [comment]
@lptn тады дзякуй за тлумачэнне

**Comment by rizomaa** [comment]
https://github.com/diglabby/doika/issues/541

**Comment by rizomaa** [comment]
падобная картка https://github.com/diglabby/doika/issues/542

**Comment by rizomaa** [comment]
Паступіла ад @cema93 

Мне падаецца, што ідэя з'яўляецца падвыпадкам для гэтай

"Апісанне
Я хочу, чтобы пользователь, чей платеж не прошел получал письмо с просьбой попробовать оплатить ещё раз
Пример:
я попробовал оплатить, оплата не прошла. Я обиделся и ушел.
Через час система проверяет, был ли удачный платеж. Если нет то высылать письмо с информацией о не прошедшем платеже и предлагать оплатить ещё раз"

Таму зачыняю картку: https://github.com/diglabby/doika/issues/542

Тут працягваем

**Comment by rizomaa** [comment]
Дадаў толькі две опцыя якія неабходна запіліць:

- [ ]  няма сродкаў
- [ ]  скончыўся тэрмін карткі

**Comment by rizomaa** [comment]
Закрываю, яна вырашана
