### ISSUE TITLE
Фіча. Як адміністратар модуля, жадаю мець магчымасць дадаваць тэрміновыя і безтэрміновыя кампаніі (+ на бязмежную суму) для таго, каб лепей абаптаваць іх вывад для прыхільнікаў і палепшыць кіраванне падпіскамі

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#567]
Функцыянал:
1. калі кампанія безтэрміновая - падпіска безтэрміновая.
2. калі кампанія тэрміновая - падпіска тэрміновая.

**Comment by cema93** [comment]
Думаю, что данный функционал  избыточен, усложняет администрирование(дополнительное поле при создании компании), и решается созданием компании  у которой дата окончания будет стоять через 10 лет...

**Comment by rizomaa** [comment]
з большага можна і так @cema93 тут важна ўзважыць як гэта узаемадзенічае з апі бягучага агрэгатара і наступных
