### ISSUE TITLE
работа doika на nginx

### ISSUE THREAD

**Issue by cema93** [diglabby/doika#573]
приветствую.
Я планирую использовать Doika  на своем сервере, но у меня нет apache  и не будет.

Будет ли работать doika на nginx, нет ли каких-нибудь особенностей?

**Comment by rizomaa** [comment]
@cema93 прывітанне, гэта адкрытае пытанне

**Comment by rizomaa** [comment]
@cema93 дакладна зараз не плануем адаптаваць. гэта залежыць у аснощным ад цябе. ці гатовы закантрыбіць у гэту фічу, значыць будзе. калі не, значыць не. Тут яшчэ важна улічваць папулярнасць на шарных хостынгах.

але я бы асабіста вітаў такі функцыянал.

Пакуль картку пакіну=) Можа быць яшчэ у каго такая ідэя ўзнікне
