### ISSUE TITLE
Cфарміраваць шаблоны email-аў паводле #464

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#577]
Перанесці тэкста шаблонаў з гугл-дока ў шаблоны email, якія выкарыстоўваюцца Ларавелем.

**Comment by rizomaa** [comment]
@fr0zen а дзе той гугл док... 
шукаю нешта не трапляецца https://github.com/diglabby/doika/issues/222

**Comment by rizomaa** [comment]
https://github.com/diglabby/doika/issues/217

**Comment by rizomaa** [comment]
наогул, асабліва парыцца з шаблонамі не трэба. проста тэксты. будзе плэйн рабіць.
або патлумач, што трэба змяніць @fr0zen

**Comment by rizomaa** [comment]
Дублюе задачу https://github.com/diglabby/doika/issues/583. Зачыняю гэту картку
