### ISSUE TITLE
Рэкурэнтныя плацяжы скончваюцца 500-ай памылкай. Пафіксіць

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#578]
- [ ] Ці працуюць разавыя
- [ ] Ці працуюць рэкурэнтныя

Зараз правядзенне рэкурэнтных плацяжоў скончваецца 500-ай памылкай. Пасля аплаты не перанакіроўваецца на старонку падзякі.

**Comment by rizomaa** [comment]
дзякуй. я тады стаўлю гэту задачу, як прыярытэтную.

@lptn ці было ў цябе нешта такое. бо ты кажаш рэкурнтныя працуюць з бэка, але 500 памылка гэта сэрверная памылка. патлумач, мо я нешта не лаўлю тут

**Comment by alies-dev** [comment]
@fr0zen 
@rizomaa 
Хлопцы, пакуль не магу праверыць (проста тупа стаміўся ад працы апошні месяц і не хачу брацца за оўпэн-сорс), але калі скініце тэкст памылкі -- магу пафіксіць нават без тэстаў (хутчэй за ўсе).

Гэта нават абавязковае патрабаванне ва ўсіх OSS праектах  - даваць як магу болей інфы па багу для дэбага, а тое што я тут паль што бачу - так сабе інфармацыйна

Любая 500 памылка логіцца ў `storage/logs/laravel.log` файл, проста пры стварэнні цікета пішыце ўвесь стэк-трэйст адтуль, і будзе усем значна прыемней, дзякуй

**Comment by Tyuba4** [comment]
@lptn @rizomaa Платеж вроде происходит нормально, но почему-то нет перенаправления на страницу благодарности, когда виджет находится в iframe, в обычном режиме все ок. Также не отбиваются webhooks, но это скорее всего из-за того, что я на локалке

**Comment by alies-dev** [comment]
@Tyuba4 
так, на лакалку веб-хукі не прыйдуць, трэба юзаць Ngrok ці падобныя тулы

што за памылка дакладней - трэба глядзець у логах

**Comment by Tyuba4** [comment]
@lptn Дак серверной ошибки нет, есть факт отказа браузера перенаправлять пользователя на страницу успеха операции.

**Comment by Tyuba4** [comment]
Закрываю, решено.

**Comment by Tyuba4** [comment]
Все работает, главное, ввести правильные тестовые данные магазина(id, key)
