### ISSUE TITLE
Стварыць тэставы сідэр для выкарыстанна падчас уталёўкі модуля

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#579]
- [ ] Зрабіць тэставы сідер базы, з якога ў базу будзе пісацца значэнне інтэрвалу ў 1 гадзіну. (На прадакшэне 1 месяц.)
- [ ] Карыстальнік вызывае сідэр пры усталёўцы модуля (праверыць рыдмі)

**Comment by rizomaa** [comment]
Сама ідэя сідэра добрая асабліва для распрацошчыкаў, каб не ствараць напрыклад 3 кампаніі з розным функцыяналам. 

Але пакуль бачу, што разыходзіцц назва карткі і падпункты у ім. Я зачыню картку, калі узнікне падобная ідэя яшчэ у каго з гатоўнасцю яе зрабіць будзем пачынасць.

Дзякуй
