### ISSUE TITLE
Дадаць прогрэс-бар у выглядзе стакана малака ў ўсталёўшчык

### ISSUE THREAD

**Issue by nastyafrosty** [diglabby/doika#58]
1- пустой стакан,5 - наполненіе, 7-ая - напоўнены малаком

**Comment by cema93** [comment]
В установщике 6 страниц.
и надо страница с опрокинутым стаканом, тогда установка не удалась

**Comment by rizomaa** [comment]
@nastyafrosty @cema93 выношу гэту картку са спрынта, бо пакуль яе ніхто не робіць + яна не прыярытэтна менавіта для гэтага спрынта. магчыма улучыць у наступныя
