### ISSUE TITLE
Абнавіць кантэнт імэйлаў па разавым і рэкурэнтным плацяжам (агульны спіс для усіх выпадкаў)

### ISSUE THREAD

**Issue by alies-dev** [diglabby/doika#583]
Паводле Напісаць тэкст імэйлаў па рэкурэнтным плацяжам #464

Асноўны спіс мэйлаў: https://docs.google.com/document/d/1CP19vpVUDnBsbQlVzZ0uP7CrpLjfZrCKk8Kw-6oKsY4/edit#

**Comment by rizomaa** [comment]
Актуальныя лісты 1-4. 

5-6, спатрэбяцца для павелічэння функцыянала

**Comment by rizomaa** [comment]
тут гатова, узяў інфу для сідаў. таму гэту карту зачыняю.
