### ISSUE TITLE
Реализовать установщик 

### ISSUE THREAD

**Issue by cema93** [diglabby/doika#59]
- [x] Описать логику нового установщика
- [ ] Перенести установщик с версии 1.2
- [ ] Обновить оформление
- [ ] Подготовить тексты для перевода
- [ ] Перевести на английский
- [ ] Перевести на белорусский

**Comment by cema93** [comment]
![1](https://user-images.githubusercontent.com/1865012/48671608-16547900-eb3c-11e8-9ba7-2f9881ec1a92.png)

**Comment by cema93** [comment]
![2](https://user-images.githubusercontent.com/1865012/48676329-59334280-eb76-11e8-830b-290218a39bce.jpg)

**Comment by falanster** [comment]
@cema93 ці ёсць у цябе такі ж масіў як выкарыстоўвае @fr0zen для перакладу?

**Comment by rizomaa** [comment]
адключаю ад спрынта. прычына тая ж ніхто не рэалізуе яе у межах спрынта.
наступны раз варта агаварыць, як мы працуем з такімі вялікімі карткамі. @cema93

**Comment by Olya147** [comment]
@cema93 @rizomaa  Можем закрывать?

**Comment by rizomaa** [comment]
@Olya147 дзякуй? што напісала. гэта задача становіцца вельмі актуальнай 

зачыняю дублюючую #380

**Comment by rizomaa** [comment]
Актуальныя пытанни на мой погляд 

1. Як паводзім з базай (праз код або дампам?).
2. Як паводзім з кодам (праз архіў, або скачваем і распакоўваем).
3. Як паводзім з канфігам ларавэль (што там пакідаем, што даем карыстачу?).
4. Ці будзе сумяшчальнасць з версіяй 1.2? (гэта вельмі актуальна асабліва з улікам таго, што ужо больш за 10к інсталяцый)
@cema93 @Tyuba4

**Comment by rizomaa** [comment]
Блізкія задачы https://github.com/diglabby/doika/issues/580
