### ISSUE TITLE
Пасля падпіскі bepaid робіць 5 запытаў на веб-хук

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#591]
@lptn ведаеш, чаму Bepaid робіць 5 запытаў пры стварэнні падпіскі?
![image](https://user-images.githubusercontent.com/19183277/61432575-90423980-a939-11e9-9684-f2b20a01f7b7.png)

Дамп ngrok 
![image](https://user-images.githubusercontent.com/19183277/61432911-8d941400-a93a-11e9-8555-d0a09dade065.png)

**Comment by alies-dev** [comment]
@fr0zen 
так, ен робиць пакуль не атрымае 2XX адказ, а у цябе 5XX

**Comment by fr0zen** [comment]
@lptn магчыма спачатку зрабіць рассылку мэйла, а потым ужо запіс ў базу? Тады зможам адлавіць 500-ую пакуль транзакцыя не зайшла ў базу

**Comment by alies-dev** [comment]
@fr0zen 
можаш і так але гэта ня правільна

у тваім выпадку трэба пафіксіць мэйлінг проста)
