### ISSUE TITLE
Исправить размер целевой суммы в разделе "Спіс кампаній"

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#593]
**Шаги для воспроизведения:**
1) создать кампанию, используя корректные данные;
2) перейти в раздел "Спіс кампаній".

**ФР:** целевая сумма уменьшена в 100 раз  (напр., 80 руб. => 0.80)
**ОР:** сумма сборов в карточке кампании и в общем списке кампаний совпадают.
![19-07](https://user-images.githubusercontent.com/46268205/61495488-d2af5900-a9c1-11e9-9ada-44bdc5deeb40.png)

**Тестовые условия:**
Версия Doika: 2.0
Платформа и версия: Win10
Браузер и версия: Chrome 73.0.3683.103/ Opera 58.0.3135.132/ Firefox 60.6.3esr

**Comment by Gordonshik** [comment]
Залез в vuetools, вижу что значение все нормально принимается, но действительно при изменении или создании новой компании сумма уменьшается, надо посмотреть всю цепочку.
![изображение](https://user-images.githubusercontent.com/51483246/78763528-ef475300-798d-11ea-96cf-b4805bd7cbda.png)
попробовал увеличить target amount, но результата не дало
![изображение](https://user-images.githubusercontent.com/51483246/78767002-b5c51680-7992-11ea-848a-74dbea3f6e87.png)
решил, что все же надо искать в methods
Нашел это `amountState() {
            return (this.model.target_amount > 0) ? true : false
        },`
но по факту это просто проверка, поэтому пошел дальше. Появилась мысль, что быть может посмотреть именно в сторону страницы, на которой выводится сумма

**Comment by Gordonshik** [comment]
Решил пойти намеченным путем, в итоге зашел в campaigns.vue, сначала увидел метод, который мог иметь к задаче отношение, но в результате тестов пришел к выводу об отсутствии связи.
Далее я поднялся вверх и увидел этот код, который меня заинтересовал:
```
<template v-slot:cell(received)="data">
            <span v-text="`${(data.item.amount_collected/100).toFixed(2)}/${(data.item.target_amount/100).toFixed(2)}`"></span>
          </template>
```
По сути он являлся клеткой таблицы, которая отвечала за собранную сумму. Из этого кода стало понятно, что одна его часть отвечает за сумму, которую уже собрали, а вторая за ту, которую необходимо собрать. Видно было, что tofixed отвечает, за кол-во символов после точки, но деление на 100 меня смущало изначально. Было решено проверить теории о том, что именно деление на сто имело влияние. В результате махинаций с ходом мое предположение подтвердилось.
Но, тут еще одно, в сумму уже собранной есть то же самое деление на 100, а значит я считаю правильным изменить и его.
Таким образом ожидаю принятия моих пр и заливаю.

**Comment by Gordonshik** [comment]
Кстати, последнее касается и упомянутого метода

  ```
  average(count, summ) {
        let result = (summ / count / 100).toFixed(2);
        if(!isNaN(result)) return result;
        else return 0;
    },
```
Тут тоже это деление, кажется, присутствует

**Comment by rizomaa** [comment]
@Gordonshik лінкуй свой PR. цікава глянуць, што ў цябе атрымалася

**Comment by rizomaa** [comment]
@Gordonshik прыняў твой ПР, дзякуй=)

Прагляджу ўжо, як буду забіраць змены перад сваім ПР.
