### ISSUE TITLE
Праца модуля з 3-D secure

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#594]
Як будзе працаваць модуль на баку плацельшчыка, калі для яго карты ўсталявана дадатковая абарона 3-D Secure?

**Comment by rizomaa** [comment]
@fr0zen яно будзем працаваць гэтак жа, бо мы ж выкарыстаощваем афсайт плацяжы.
чаму такое пытанне?

**Comment by fr0zen** [comment]
@rizomaa не тэсціў сам, там дадаў, каб не запамятаваць

**Comment by rizomaa** [comment]
@fr0zen тэсціш зараз нешта з 3дэсекюрэ?

**Comment by rizomaa** [comment]
няма ходу картцы, таму зачяняю. будзе пытанне больш актуальным адкрыем нанова
