### ISSUE TITLE
Добавить в виджете сообщение об ошибке в случае если пользователь не выбрал сумму платежа

### ISSUE THREAD

**Issue by ghost** [diglabby/doika#597]
**Шаги для воспроизведения**:
1. открыть сайт http://it3donate-landing.falanster.by/ ;
2. нажать кнопку "Платёж";
3. включить чек-бокс "Я згаджаюся з правіламі";
4. не заполняя сумму платежа, нажать кнопку "Пацвердзіць"

**ФР:** открывается пустая страница.
**ОР:** появляется сообщение "Калі ласка, увядзіце суму плацяжу"; пользователь остаётся на прежней странице.

![1](https://user-images.githubusercontent.com/46268205/61722204-8887f800-ad72-11e9-9742-e0ca6700e634.png)

**Comment by rizomaa** [comment]
@KuhniaDruggist 
Таксама вырашыць:
Пры націсканні поля уводу "іншая сумма", здымаем фокус з кнопак з лічбамі.
