### ISSUE TITLE
Даследванне і абмеркаванне: Перанос версіі doika_1.2 на doika з улікам VUE.JS

### ISSUE THREAD

**Issue by svetasemashko** [diglabby/doika#6]

**Comment by lptn** [comment]
хм. Вы зьбіраецеся цягнуць js framework на сайт карстыльнікаў для таго каб працаваў невялікі могуль? Я бачу гэтае рашэньне неаптымальным з кроплі гледжвання performance. Гатовы дапамагчы напісаць frontend код на vanilla js

**Comment by falanster** [comment]
@fr0zen табе пытанне

**Comment by falanster** [comment]
@fr0zen таксама у мяне пытанне, калі ласка абгрунтуй выкарыстанне vue.js на адмінцы, мы папярэдне гутарылі пра самы просты варыянт з bootstrap, а пасля паварот.
@Tyuba4 можа ты нешта напишаш на гэты конт?

**Comment by fr0zen** [comment]
@falanster Vue пад адмінку дае даволі добрыя інструменты для таго каб зрабіць адмінку больш зручнай. Пад кліентскую частку - бОльшыя затрымкі будзе даваць загрузка iframe-аў, на іх фоне затрымкі загрузкі Vue не такія істотныя. Але калі будуць моцныя праблемы з рэсурсамі, я перагляжу падыход.
