### ISSUE TITLE
Наладзіць адпраўку мэйлаў пры разавых і рэкурэнтных плацяжах

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#622]
Развагі
1. Выкарыстоўваем свой мэйлер (https://github.com/diglabby/doika/issues/710)
2. Калі-небудзь дададзім функцыю знешніх мэйлераў. Але спачатку абкатаем на сваім.
3. Усе паведамленні апісаны тут: doika/doika/dashboard/notifications
4. Ці патрэбна табліца мэйлінга (кшталту лога аб паспяховасці адпраўкі) - можа быць карысна для аналізасітуацыі.

Астатняе яшчэ даследую

**Comment by fr0zen** [comment]
Асяродак: apache2 + php 7.1 + mysql 5.6 + sendmail

- [ ] Разабрацца, якія наладкі мэйл сэрвера патрэбны для працы рассылак зараз.
- [ ] Пратэставаць ці адпраўляюцца мэйлы пасля адзіночнага плацяжу .
- [ ] Пратэставаць ці адпраўляюцца мэйлы пасля стварэння падпіскі.
- [ ] Пратэставаць ці адпраўляюцца мэйлы пасля таго як біпэйд робіць зняцце грошаў па плану падпіскі.
- [ ] Пратэставаць, ці адпраўляецца лінк на адпіску у лістах рэкурэнтных плацяжоў і ці працуе адпіска.

**Comment by fr0zen** [comment]
Тэсціць можна тут http://it3donate-joomla.falanster.by/

**Comment by rizomaa** [comment]
![Selection_004](https://user-images.githubusercontent.com/9870374/69649149-a4334000-107d-11ea-98b4-79b2a4e15e2c.png)
што тэсціць @fr0zen

**Comment by rizomaa** [comment]
Развагі:

- [ ] 1. Выкарыстоўваем свой мэйлер (https://github.com/diglabby/doika/issues/710)
- [ ] 2. Калі-небудзь дададзім функцыю знешніх мэйлераў. Але спачатку абкатаем на сваім.
- [ ] 3. Усе паведамленні апісаны тут: doika/doika/dashboard/notifications
- [ ] 4. Ці патрэбна табліца мэйлінга (кшталту лога аб паспяховасці адпраўкі) - можа быць карысна для аналізасітуацыі.
- [ ] 

Астатняе яшчэ даследую
