### ISSUE TITLE
Дакументацыя. Зрабіць апісанне працы з гітом і галінамі

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#63]
- [ ] Стварыць старонку ў вікі
- [ ] Размясціць выяву зправа. https://user-images.githubusercontent.com/9870374/50741147-5d8ceb00-120a-11e9-9b91-d0f6ae130fbb.jpg
- [ ] Апісаць выяву зправа тэкстам.

**Comment by falanster** [comment]
@Tyuba4 а дзе гэта аписанне зараз можна глянуць?

**Comment by rizomaa** [comment]
Падобная картка https://github.com/diglabby/doika/issues/84

**Comment by lptn** [comment]
@Tyuba4 
@falanster 

>Сделать описание работы с гитом (composer и папка vendor) #63

Увогуле гэтае ішью якую праблему вырашае? Задачу лепей будуваць так каю было ясна НАВОШТА а не толькі ШТО рабіць. Магчыма сама пастаноўка праблемы ня правільная і адпаведна прананова па вырашэнню. Ці Нават калі пастаноўка правільная то салюшн можа быць ня правільным

**Comment by Tyuba4** [comment]
@lptn Тут ишью изначально был создан для создания инструкции по работе, но трансформировался в размышления вообще как поступить? @falanster Что думаешь по поводу хранить релиз где-то во вне гитхаба?

**Comment by lptn** [comment]
@Tyuba4 
Так, справа ў тым што такое апісанне работы з гітом не патрэбна калі рэалізаваць маю прапанову, пагэтаму і важна акцэнт рабіць на матывах стварэння задачы

**Comment by rizomaa** [comment]
@romanromanenko @Olya147 вам задача, да 01.02 чакаем чарнавога афармлення дока па працы з гітам.

**Comment by rizomaa** [comment]
@Olya147 закінь калі ласка сюды спасылку на старонку, з якой працуеш?

**Comment by Olya147** [comment]
@rizomaa  https://github.com/diglabby/doika/wiki/Git:-%D0%9F%D1%80%D0%B0%D1%86%D0%B0-%D0%B7-%D1%80%D1%8D%D0%BF%D0%B0%D0%B7%D1%96%D1%82%D0%B0%D1%80%D0%BE%D0%BC-(%D0%B4%D0%BB%D1%8F-%D1%80%D0%B0%D1%81%D0%BF%D1%80%D0%B0%D1%86%D0%BE%D1%9E%D1%88%D1%87%D1%8B%D0%BA%D0%B0%D1%9E)

**Comment by rizomaa** [comment]
@Olya147 калі @lptn запапрвіў я давяраю.

магчыма запытай у каго менш фопытнага як @KahjuksEi @maxmatoha @ursar  ці усё ім там відавочна.

**Comment by lptn** [comment]
@rizomaa 
я структуру дакумента не правіў, толькі сінтаксіс

Структрай каб займацца трэба ведаць якія праблемы маюць навабранцы каб ведаць што там апісваць, гэта такс на некалькі гадзін, якія я лепей накірую на што небудзь болей карыснае

**Comment by Olya147** [comment]
@KahjuksEi @maxmatoha @ursar  ознакомьтесь все с приведённой инструкцией. Всё ли доступно и корректно описано (этапы работы, выполняемые в терминале команды). Сообщите, если появятся замечания.

**Comment by rizomaa** [comment]
@Olya147 ага, крута што затэгіла.  калі не будзе рэакцыі пацаноў, напішы кожнаму у лічку=)

**Comment by ursar** [comment]
@Olya147 возможно, будет не лишним, добавить каким образом сделать локальную копию удаленной ветки. А также каким образом синхронизировать форк с оригинальной репой.

**Comment by KahjuksEi** [comment]
Ок. Главное что основа положена, по ходу дела уже будем корректировать.

**Comment by rizomaa** [comment]
@ursar дапоўні сваім каммітам
