### ISSUE TITLE
Просмотр кампаний на тестовом сайте

### ISSUE THREAD

**Issue by samarieta** [diglabby/doika#643]
## Апісанне
Как [админ тестового сайта], я хочу [изменять кампанию и видеть, как она выглядит при публикации], для того чтобы [представлять внешний вид своей конкретной кампании].
<!--
Example 1: `Як адмінстратар сайта, я хачу бачыць графік паступлення працяжоў, каб лепей прадказаць быдучыя працяжы`.
Example 2: `Як карыстальнік дойкі, я хачу мець магчымасць увесці любую суму плацяжа, як данэйціць вялікія сумы`.
--!>

**Comment by rizomaa** [comment]
падобная картка https://github.com/diglabby/doika/issues/460

**Comment by rizomaa** [comment]
пакуль пазначу сумежныя карткі:
1. https://github.com/diglabby/doika/issues/460
2. https://github.com/diglabby/doika/issues/544

Пасля, магчыма, іх склеім
