### ISSUE TITLE
Дадаць у канец мэйлаў з лістом аб рэкурэнтных плацяжах спасылку з магчымасцю адпісацца

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#647]
Сумежная картка тут:
https://github.com/diglabby/doika/issues/217

**Comment by Tyuba4** [comment]
неабходна пераправерыць код на наяўнасць функцыі генерацыі старонкі для адпіскі

**Comment by Tyuba4** [comment]
Паглядзець франтовую частку адмінкі якая змяшчая гэтыя наладкі: https://github.com/diglabby/doika/issues/710
