### ISSUE TITLE
Напісаць гайд па ўсталёўцы модуля для распрацоўшчыкаў

### ISSUE THREAD

**Issue by falanster** [diglabby/doika#65]

**Comment by falanster** [comment]
@lptn 

мэтавая аўдыторыя = распрацоўшчыкі, якія жадаюць далучыцца да стварэння коду, тэставання таго, што накоділі.

**Comment by falanster** [comment]
@fr0zen пінгпінг

гэта гарачая, штука. 
мы хочам шукаць тэсціроўшчыкаў. 
заўтра будзем рассылаць тэставыя задачы. без алгартма устаноўкі, прыйдзецца даваць інсталяваць версію 1.2.

чакаем твайго каментару.

скажы чым трэба тут дапамагчы?

**Comment by falanster** [comment]
сённяшняя версія ўсталёўшчыка тут:
https://github.com/diglabby/doika#распрацоўшчыку---як-запусціць-праект

**Comment by ilyaaki** [comment]
Можна дадаць, што калі па шляху /doika/admin/login уваход у адмінку не адкрываецца, праверыць rewrite для хаста/каталога сайта

**Comment by falanster** [comment]
@ilyaaki дадавай, калі ў цябе быў гэты нюанс

**Comment by rizomaa** [comment]
дублюючая задача
