### ISSUE TITLE
Не лагініцца на сайт пад тэставым адмінам

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#655]
Зайшоў у базу бачу, што ёсць нейкія левыя карыстальнікі а адміна няма 
![Selection_023](https://user-images.githubusercontent.com/9870374/70513998-c16b1280-1b43-11ea-9c9e-65bc8003ea69.png)

але у сідах нібы стаіць адмін нічога не пазначана, як гэта мяняецца падчас дэплоймэнта
https://github.com/diglabby/doika/blob/develop/database/seeds/AdminSeeder.php#L12

@fr0zen @lptn 

Пакуль буду сам разбірацца, але удзячны любой дапамозе. Дзякуй

**Comment by rizomaa** [comment]
1. Стварыў дадатковы сід з тыпавым пасвардам, прымяніў яго (`php artisan db:seed --class=AdminSeeder2`)
2. Вычысціў старыя запісы з базы засталася адна.
3. Тэстую тут http://it3donate-landing.falanster.by/doika/doika/dashboard/login
4. Працуе.

Карысныя спасылкі:
https://laravel.com/docs/5.8/seeding
+
https://stackoverflow.com/a/26144180

Пытанне, усё ж застаецца чаму заліваюцца нейкія незразумелыя дадзеныя, але намальны тэставы сід не?!

**Comment by rizomaa** [comment]
Задача была блакуючай, бо немагчыма было перадаць дызайнерам на праверку юзабіліці адмінкі

**Comment by rizomaa** [comment]
@lptn @fr0zen памылка зноў узнікла. падазраю, што неяк няякасна спрацоўваюць сіды пры аўтаматычным удбналенні. калі перазапускаю сіды заходзіць.

ці можаце часова адключыць аўтаматычныя скрыпты, бо яны зараз запавольваюць тэставанне і распрацоўку?

**Comment by alies-dev** [comment]
@rizomaa 
Дэфолтавы логін і пасворд які ствараецца сідэрамі тут: https://github.com/diglabby/doika/blob/e0c8be76d5cbf6ed42f2d4a5255b31f2d5c8d2aa/database/seeds/AdminSeeder.php#L11-L12 і нязменныя (не дынамічныя)

усе астатнія карыстальнікі ствары ці старой дойкай ці чыімсці дзеяннямі

**Comment by rizomaa** [comment]
@lptn так, я гэта усё бачыў і спрабаваў рабіць.

1. калі адбываюцца нейкія аўтаматычня дзеянні з рэпам (праверкі, тэсты?), 
2. на сервак перазаліваюцца дадзеныя і праект нанова. 
3. гэта блакуе магчымасць зайсці (па тым пасвардам якія у сідзеры, які паказваеш).

дапамагло толькі стварэнне новага карыстальніка праз сід. пісаў рашэнне вышэй. але яно не устойлівае, бо прымушае пастаянна бегаць на сервер і перапісваць гэта ручкамі. кавыраючыся у шэле. дызайнеры і тэсцеры юікс гэта наўрад ці могуць зрабіць. як вынік, запавольваюцца працэсы.

**Comment by alies-dev** [comment]
>калі адбываюцца нейкія аўтаматычня дзеянні з рэпам (праверкі, тэсты?),

пры любым каміце запускаюцца праверкі код-стайла і ганяюцца тэсты

>на сервак перазаліваюцца дадзеныя і праект нанова.

ня ведаю (я тут нічога не рабіў)

>та блакуе магчымасць зайсці (па тым пасвардам якія у сідзеры, які паказваеш).

тое ж самае як і папярэдні пункт

**Comment by rizomaa** [comment]
@lptn дзякуй за адповяд. паставіў некалькі разоў яшчэ. бага знікла. проста буду мець на ўвазе, бо гэта паўтаралася і ў @Tyuba4 

пакуль зачыня. ішус
