### ISSUE TITLE
Прапанова па разбіццю дакументацыі

### ISSUE THREAD

**Issue by lptn** [diglabby/doika#66]
Гэта частка маіх прапановаў для паляпгэння работы з патэнцыйнымі кантрібютарамі ці кам'юніці. Добрую устур для гэтага можна знайсці тут: https://opensource.guide/building-community/

# Праблема
На бягучы момант у нас есць некаторая дублікацыя інфармацыі ў розных крыніцах: wiki, repository, можа яшчэ дзе-небдузь.

## Прапанова 1: Малыя файлы + спасылкі на іх

Замест таго каб дубляваць, лепей выдзеліць інфармацыю ў невялікі файлы і проста даваць спасылку на яго.

Прыклад
![image](https://user-images.githubusercontent.com/5278175/49329950-32263900-f598-11e8-8774-343eba6fc20e.png)
![image](https://user-images.githubusercontent.com/5278175/49329966-90531c00-f598-11e8-9901-8e35c92d072a.png)

PS: Думаю трэба вынесці ўсе інфармацыю для распрацоўгчыкаў з README у іншыя файлы каб разгрузіць яго і зрабіць прыязней для тых хто хоча пастаіць яго сабе на праект, для распрацоўшчыкаў дастаткова толькі спасылкі на іншы дакумент

## Прапанова 2: Шырэй выкарыстоўваць стандартныя магчымасці github

Есьць пэўныя файлы, якія гітхаб апрацоўвае спецыяльным чынам:
 - README - мы ужо выкарыстоўваем, думаю усе ведаюць што гэта. Можна выкарыстоўваць файл з такой назвай часцей і дадаваць яго у іншыя дырэкторыі. Прыклад -- гэты рэпазіторый https://github.com/InteractionDesignFoundation/handbook/tree/master/guides
 - CODE_OF_CONDUCT - нормы паводзінаў на праекце, для нас апцыянальна
 - LICENSE - інфа пра ліцэнзію, дарэчы думаю варта [дадаць](https://opensource.guide/legal/)
 - [CONTRIBUTING.md](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)

Часта людзі яшчэ выкарыстоўваюць іншыя файлы, якія пакуль што не маюць спецыяльнай апрацоўкі з боку guthub:
 - AUTHORS
 - CHANGELOG
 - ROADMAP
 - файлы тэмлэйтаў для issue і pull request (па-за межамі гэтай прапановы)

**Comment by falanster** [comment]
@lptn патэнцыйна можна. Паспрабуй стварыць старонкі, якія макімальна зручны для распрацоўшчыкам, пасля зачысцім рыдміэмдэ.

**Comment by falanster** [comment]
@lptn як толькі адкажаш на мой камент у пулрэквэсце, змагу склеіць

**Comment by lptn** [comment]
@falanster не магу знайсці ніякіх каментароў да PR

**Comment by Al-Shaytan-Al-Akbar** [comment]
@falanster @ilyaaki @lptn 
Тэхнічная дакументацыя з'яўляецца часткай прадукта і павінна білдзіцца і версіянавацца разам з ім.
Адпаведна, яе месца - у рэпазіторыі, а не ў вікі.

**Comment by lptn** [comment]
@Al-Shaytan-Al-Akbar 
>Тэхнічная дакументацыя з'яўляецца часткай прадукта і павінна білдзіцца і версіянавацца разам з ім.
>Адпаведна, яе месца - у рэпазіторыі, а не ў вікі.

Цалкам згодны, прычым я гэта ужо агучваў на офісе

**Comment by lptn** [comment]
@Olya147 

А чаму закрываем?

**Comment by lptn** [comment]
@Olya147 
не зыбываем пра https://github.com/diglabby/doika/pull/317

**Comment by lptn** [comment]
@rizomaa 
ну што, ці гатовы мы вырнуцца да гэтага пытання? Калі не -- адпішы калі ласка калі зможам (даты ці ўмовы), было б файла навесці парадак і не дубляваць адно і тое ж у розных месцах

**Comment by Al-Shaytan-Al-Akbar** [comment]
Заадно я мог бы паказаць, як я арганізую дакументацыю на працы. Можа, што
прыдалося б як шаблон.

**Comment by rizomaa** [comment]
@lptn @Al-Shaytan-Al-Akbar так можна вярнуцца да гэтага пытання. Я гатовы у суботу выдаткаваць час. Або тут асвяжыце свае думкі

**Comment by alies-dev** [comment]
@falanster 
@Al-Shaytan-Al-Akbar 

Я ў суботу (сення) не буду, пагэтаму выкажу думкі тут

1. Дакументацыя мусіць версіянавацца разам з кодам: абнаўляем і то і другае РАЗАМ. Гэта ВЕЛЬМІ важна для выпадкаў калі нехта выкарыстоўвае старую версію праекта да якога новая дакументацыя не падыходзіць. Гэта значыць докі мусяць быць у рэпазіторыі дойкі.
1. Докі мусяць быць даступнымі (быць на бачным месцы + быць зразумелымі). GitHub мае github pages -- гэта калі можна апублікаваць змесціва тэчкі `/docs` рэпазіторыя як асобны сайт, вось наша змесціва https://diglabby.github.io/doika/ (тэмы можна мяняць) (есьць абмежванне -- лінкуецца `master` брэнч толькі)
1. Некаторыя докі мусяць праходзіць стадыю рев'ю як гэта мы робім з кодам
1. Докі мусяць быць малымі, адрасанаванымі і зразумелымі. Ня трэба міксаваць інфармацыю для распрацоўгчыкаў і арганізацый і адным файле, лепей проста пералінкаваць іх калі трэба ці проста мець добры Table of content у галоўным README.md ці docs/README.md


Ак можаце зразумець -- я за докі ў гэтай рэпе у тэчцы `/docs`, а замест вікі можам выкарыстоўваць стандартны UI GitHub (https://github.com/diglabby/doika/blob/master/docs/README.md) ці GitHub pages (https://diglabby.github.io/doika/)

**Comment by alies-dev** [comment]
А што з ВІКІ? -- Выдаляем усе і выключаем у наладах рэпазіторыя :)

**Comment by KahjuksEi** [comment]
Оптимально будет разделение документации для разработчиков и людей, не связанных с этим, которым будет достаточно гайда по установке.

**Comment by svetit** [comment]
Мая прапанова:
- прыбраць рыдмі мд.
- Усю дакументацыю размяшчаць у вікі рэпазіторыя.
На галоўнай старонцы вікі - самы вышэйшы ўзровень абстракцыі.

**Comment by alexap13** [comment]
Я прапаную крытэрыи - 1.  удобства карыстання карыстальниками 2. Удобства абнаулення инфы нами

**Comment by alies-dev** [comment]
Якое б рашэнне не прынялі, я ўпэўнены што дакументацыя для распрацоўшчыкаў мусіць быць ў рэпазіторыі -- хотя б для офлайнавай працы і версіянавання докаў разам з кодам

README.md -- гэта стандарт дэ-факта ў усім кам'юніці (не толькі на GitHub), яго выдаляць недапушчальна

**Comment by ghost** [comment]
Я бы предложила оставить и то и другое, удалив при этом дублирующую информацию из вики. Каждый из вариантов имеет свои преимущества:
1) вики удобна в плане навигации (проще искать по заголовкам) + проще в редактировании;
2) readme  содержит необходимую информацию по установке. 
Думаю, будет лишним всё, опубликованное в вики, размещать в readme, т.к. этот же документ будет скопирован на компьютер, и будет содержать избыточную информацию.

**Comment by fr0zen** [comment]
@lptn на мой погляд зараз набор .md файлаў пад дакументацыю - overkill. Бо зараз пытанее па версіянаванню не стаіць вельмі востра. Можа нам зрабіць на .md - шках сугуба інфу па коду, кшталту тэставых спецыфікацый. Мне падаецца такія будуць аднаўляцца хутчэй за ўсе і выконваць нейкую функцыю гісторыі.

**Comment by alies-dev** [comment]
Пытанне: ці патрэбна нам рабіць наш репазіторый (README.md) презентабільным для арганізацый ? Калі не -- то можам выкарыстоўваць докі для распрацоўшчыкаў у рупазіторыі, докі для арганізацый -- у вікі . Докі па усталеўцы -- гэта для арганізацый ці для распрацоўшчыкаў?)

**Comment by maxmatoha** [comment]
Вся общая информация в вики. Конфигурация,установка-README.

**Comment by alies-dev** [comment]
дарэчы у опцыы докаў у тэчцы `/docs` есьць вядікая перавага -- неабмежаваныя ўзроўні гіерархіі. 


@fr0zen 
>а мой погляд зараз набор .md файлаў пад дакументацыю - overkill

тэхнічга вікі -- гэта гіт-репазіторый з md файламі  `https://github.com/diglabby/doika.wiki.git`-- можаш склоніць :)
____________________

Так, GitHub дае магчымасьць легка рэдагаваць вікі файлы, але ж амаль той да інтефейс есьць у .md файлах:
1. Клікаем 
![image](https://user-images.githubusercontent.com/5278175/57183124-fb3eb100-6eb0-11e9-8bb9-183f50f4f3c8.png)
1. Рэдагуем 
![image](https://user-images.githubusercontent.com/5278175/57183127-101b4480-6eb1-11e9-85b6-376bf0cab560.png)

Профіты:
 - версіянаванне докаў і кода разам
 - прыгожыя докі (via github pages)
 - любая структура докаў (укладзенасць)
 - офлайнавыя докі для тых хто склоніў рэпазіторвый

**Comment by b-shchuko** [comment]
Тэхнічная дакументацыя - гэта частка самога прадукта. Не прышлёпка збоку, а
частка прадукта.
Таму яна павінна версіянавацца разам з прадуктам. І гісторыя зменаў павінна
адсочвацца.
То бок, такую дакументацыю трэба трымаць у рэпе, разам з кодам.

КАРЫСТАЛЬНІКІ тэхнічнай дакументацыі:
* праграмісты,
* дэвопс-чувакі (ці сісадміны, "дэплоеры"),
* магчыма, людзі тэхпадтрымкі,
* магчыма, тэставальнікі (малаверагодна).
ЗАЎВАГА:
Тэхнічная дакументацыя НЕ прызначаная для бізнэс-чувакоў (мэнаджараў,
старшыняў арганізацый і г.д.). Хадзіць і чытаць рэпазіторый - гэта не іх
справа, яны НЕ будуць гэта рабіць, і марна ад іх гэтага чакаць.
ЗАЎВАГА:
Бізнэс-патрабаванні і тэхнічныя патрабаванні (спецыфікацыі) да прадукта не
з'яўляюцца тэхнічнай дакументацыяй. Іх не трэба трымаць у рэпе.

=======
ПРЫКЛАДЫ ТЭМАЎ тэхнічнай дакументацыі:

1) Для ўсіх чытачоў дакументацыі:
* агульнае апісанне сэнсу прадукта (пара-тройка абзацаў);
* changelog (лепш па стандартнай форме https://keepachangelog.com/en/1.0.0/)
* спіс людзей, тэхнічна адказных за прадукт, з іх кантактамі

2) Для праграмістаў:
* апісанне API;
* як інтэграваць прадукт з праграмамі на іншых фрэймворках;
* як дадаваць новы код у прадукт;
* апісанне архітэктуры (магчыма, у выглядзе схемы);
* architectural decision record.

3) Для дэвопсаў / адмінаў:
* як задэплоіць (усталяваць) прадукт;
* як уключыць (задзейнічаць) прадукт, калі ён усталяваны;
* якія вядомыя глюкі/багі ёсць і як іх абыходзіць на дадзены момант;
* якія ў прадукта залежнасці;
* што будзе, калі прадукт "упаў" (якія наступствы для Сусвету);
* за якімі параметрамі трэба сачыць падчас працы прадукта ў штатным рэжыме.

Уся гэтая інфармацыя размяшчаецца ў рэпе, пажадана ў тэчцы "docs". Разбіццё
на md-файлы - як вам зручна. Але ёсць пэўная логіка, пазней распішу яе.

**Comment by b-shchuko** [comment]
Цяпер наконт **разбіцця дакументацыі на розныя файлы**.
Логіка разбіцця прыкладна наступная.

**1)** Раздзел змесціва, які з часам будзе разрастацца ў аб'ёме, выносім у асобны дакумент. Напрыклад:
* changelog
* architectural decision record (ADR)
* апісанне known issues і іх workarounds

Гэта ўсё асобныя дакументы. (Праўда, ADR можа ўвогуле быць цэлай тэчкай, у якой для кожнага новага архітэктурнага рашэння будзе асобны дакумент.)

**2)** Раздзел змесціва, які адразу мае вялікі аб'ём, выносім у асобны дакумент.
Напрыклад, гэта можа быць:
* аб'ёмная інструкцыя па ўсталяванні / дэплойменце
* аб'ёмная інструкцыя па інтэграцыі
* апісанне апёў (API)

**3)** Раздзелы змесціва, прызначаныя для **розных** чытачоў/роляў, **НЕ** змяшчаем у адзін дакумент.
Напрыклад, калі дэвопс адкрывае дакумент, ён/яна **не** павінен там бачыць тое, што не патрэбна дэвопсу.

**4)** Раздзелы змесціва, якія маюць невялікі аб'ём і прызначаныя для адной і той жа аўдыторыі, можна аб'ядноўваць у адзін дакумент.
Напрыклад, у межах аднаго дакумента я пішу:
* агульнае апісанне прадукта/праекта/сервіса (пара абзацаў)
* пералік людзей, тэхнічна адказных за прадукт, і іх кантактаў

Іншы прыклад. У адзін дакумент аб'ядноўваю такое:
* апісанне залежнасцяў прадукта;
* апісанне наступстваў, якія будуць, калі прадукт "ляжа" на продзе.

**5)** Асаблівыя, спецыфічныя раздзелы змесціва, якія трэба пісаць менавіта для **гэтага** прадукта, а ў іншых сістэмах падобнае не сустрэнеш (або рэдка), можна выносіць у асобны дакумент.
Напрыклад:
* інструкцыя ў наладцы злучэння прадукта са знешнімі правайдарамі аўтэнтыфікацыі;
* інструкцыя ў квашанні макаронаў у падліве з чайнага грыбу і тушанага малака і г.д.

===
Уся гэтая логіка дазваляе нам пазбавіцца ад вялізных дакументаў, у якіх згружана ўсё і якія цяжка рэдагаваць (у рэдактары маркдаўну) і можа быць цяжка ўспрымаць. Таксама яна пазбаўляе чытачоў ад не патрэбнай ім інфармацыі.

У шапцы кожнага дакумента варта даваць **МЕТАЗВЕСТКІ**:
* як называецца дакумент;
* пра што ён (адным сказам);
* для **каго** ён.

Для ўсёй дакументацыі ствараецца нейкі index - то бок, старонка "Змест" са спісам спасылак на ўсе дакументы. Гэты index можа быць асобным дакументам (/docs/index.md) ці ўнутры цэнтральнай рыдмішкі.
У гэтым індэксе спасылкі разбіваюцца паводле аўдыторыі. Блок спасылак на дакументы для ўсіх, блок спасылак на дакументы для праграмістаў, блок спасылак на дакументы для адмінаў і г.д.
Вось прыклад (спасылкі пустыя):
# Documentation Index

## 1. General
* 1.1. [General Info](https://dummy.of.by)
* 1.2. [Changelog](https://dummy.of.by)

## 2. Dev
* 2.1. [ADR](https://dummy.of.by)
* 2.2. [Integration Instructions](https://dummy.of.by)
* 2.3. [Contributing Rules](https://dummy.of.by)

## 3. Ops
* 3.1. [Deployment Instructions](https://dummy.of.by)
* 3.2. [Alert Handling](https://dummy.of.by)
* 3.3. [Dependencies & Impact](https://dummy.of.by)
* 3.4. [Known Issues & Solutions](https://dummy.of.by)

====
І я яшчэ раз хачу падкрэсліць, што нармальныя бізнэс-чувакі, не адмарозкі, не палезуць у гітхаб. Гітхаб для тэхнічных людзей. Каштоўнасць Дойкі для арганізацый і прававыя асаблівасці яе выкарыстання трэба распісваць недзе на лэндынгу, а не на рэсурсе для тэхнароў.

**Comment by alies-dev** [comment]
@Al-Shaytan-Al-Akbar 
згодны і падпісваюся пад кожным словам, за болей чым 3 гады самі прышлі да такога ж бачання у сябе на праекце (я пра маю асноўную працу)

**Comment by rizomaa** [comment]
@lptn 

вікі можа правіца як рэпазіторый.

мне цікава, якую структуру докаў ты зараз бачыш?

**Comment by rizomaa** [comment]
@Al-Shaytan-Al-Akbar дзякуй за прапанаваную структуру. прывяжы яе калі ласка к сённяшнім рэаліям і пакажы, як бы ты рабіў перанос напрыклад пункта 3.4, 3.2. 2.1.

Наогул на мой погляд, мы структуру арганізуем, але тут важна, каб каманда максімальна проста магла арыентавацца у такой дакументацыі і абнаўляць яе. 

Мне імпануе звязка адзін просты readme.md і астатняя дакументацыя ў вікі*. З рыдмі будуць спасылкі на вікі. Таму, каб не цягнуць час. Прымаю адказнасць за гэта рашэнне.

*
1. Вікі таксама можа быць рэпам з версіямі, таму калі у нас часта пайдуць змяняцца версіі перанясем файлы у астноўны рэп у вашу любімую тэчку.
2. Вікі проста і зручна абнаўляць. 

Калі нехта з вас @lptn @Al-Shaytan-Al-Akbar  возьмецца за задачу структуравання сённяшняй дакументацыі, як вы прапанавалі вышэй, я буду дапамагаць.

**Comment by b-shchuko** [comment]
@rizomaa Не разумею першае пытанне-просьбу. Прывязаць у якім выглядзе? Рабіць перанос - чаго, куды і адкуль? 

Вікі мае версіянаванне, але ці прывязаныя яе версіі да версій прадукта? Па-мойму, не. У вікі асобны кантроль версій. А лепш, каб кожнаму білду прадукта адпавядаў свой "злепак" дакументацыі.

Структураваць дакументацыю павінен той, хто знаходзіцца добра ў яе кантэксце і працуе з ёй. Я не знаходжуся ў кантэксце, і каб увайсці ў кантэкст, спатрэбяцца тыдні ці месяцы; а без гэтага рабіць праўкі - неадэкватна. 
І любая змена/ператасоўка павінна ўзгадняцца з тымі, хто пісаў дакументы і хто карыстаецца імі. Таму гэта павінны рабіць людзі ўнутры праекта.
Нарэшце, вельмі важна, каб структураванне было сапраўды ПАТРЭБНА. Калі ў вас няма ў ім рэальнай патрэбы, то лепш займацца чымсьці больш прыярытэтным.
Мая справа - падзяліцца "методыкай". Яна, дарэчы, можа канкрэтна вам і не падыходзіць (!).

**Comment by alies-dev** [comment]
@rizomaa 
я пакуль крыху навеў парадак з маючай дакументацыя (паправіў інфу, спасылкы, выладіў дублікаты і некаторыя пустыя старонкі, перейменаваў файлы), асноўную працу можна убачыць тут https://github.com/diglabby/doika/wiki

Спадзяюся будзе карыстным для таго каю інсці далей па паляпшэнню

>мне цікава, якую структуру докаў ты зараз бачыш?

`/README.md` - толькі для распрацоўшчыкаў, утрымлівае апісанне праекта, галоўныя каманды для штодзеннай працы распрацоўшчыка + спасылкі на іншыя важныя дакументы (FAQ, Wiki, усталеўка)
`/docs/` - дакументацыя для распрацоўшчыкаў і інтэгратараў. На першым этапе проста пераносім з вікі вось гэта: 
![image](https://user-images.githubusercontent.com/5278175/57243106-f22f1a80-703d-11e9-8b55-c3697f08f9c7.png)

Дзе і як захоўваем докі для арганізацый? -- Тут я не гатовы адказаць што ім зручней: магчыма Wiki, магчыма google docs, наш лэндынг ці нават асобны сайт згерераваны з markdown-файлаў (гэта вельмі проста). Можна нават асобную репу для докаў зрабіць і на яе павесіць github pages (а для github pages можна выкарыстоўваць кастымны паддамэн, напрыклад docs.doika.by).

**Comment by rizomaa** [comment]
ДОкі прыведзены у гармонію тут https://github.com/diglabby/doika/wiki
астатнія паляпшэнні пасля запуска функцыянала
