### ISSUE TITLE
Усталяванне праэкта Doika

### ISSUE THREAD

**Issue by AlekseyKrivitskiy** [diglabby/doika#664]
Паспрабавау усталявать новую версию праэкта Doika. Зрабиу усё па мануалу https://github.com/diglabby/doika/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BB%D1%91%D1%9E%D0%BA%D0%B0-%D0%B4%D0%BB%D1%8F-%D0%A0%D0%B0%D1%81%D0%BF%D1%80%D0%B0%D1%86%D0%BE%D1%9E%D1%88%D1%87%D1%8B%D0%BA%D0%B0%D1%9E
Але зноу жа не работаюць стыли и не адлюстроуваецца кантэнт. 
![image](https://user-images.githubusercontent.com/59744681/72667494-5f000e80-3a2d-11ea-8fed-ebf0a1db09e9.png)
![image](https://user-images.githubusercontent.com/59744681/72667499-6a533a00-3a2d-11ea-902b-0aac4f368138.png)
Працую на Windows 10, можа з ей якия праблемы?

**Comment by KahjuksEi** [comment]
@AlekseyKrivitskiy, все должно работать на 10 винде, проверь версии
apache-php-7.2
php-7.2
mysql-5.7
Laravel Framework 5.8.36
Composer version 1.8.5
node v10.15.3
перепроверь путь в адресной строке, у меня например работает doika/doika
![image](https://user-images.githubusercontent.com/39082880/72705827-852cc800-3b6d-11ea-83db-59d1d14c2160.png)
@fr0zen  тут странные вещи при установке композера происходят, но не мешают
![QIP Shot - Screen 049](https://user-images.githubusercontent.com/39082880/72705948-c91fcd00-3b6d-11ea-9272-621cb67614e8.png)

**Comment by AlekseyKrivitskiy** [comment]
@KahjuksEi У вас проект в папке D, у меня же в domains, в пути не должно быть ошибок.
![image](https://user-images.githubusercontent.com/59744681/72728380-47946300-3b9e-11ea-8299-afdaa25572d5.png)
![image](https://user-images.githubusercontent.com/59744681/72728399-54b15200-3b9e-11ea-8253-84306bcbca4e.png)
А вот при написании команды composer update ошибка вылетает. Гуглил, но так и не понял как пофиксить.
![image](https://user-images.githubusercontent.com/59744681/72730067-a8716a80-3ba1-11ea-8ba7-6a824441637a.png)

**Comment by KahjuksEi** [comment]
Там как раз прикол с путями, например у меня работает так:
![image](https://user-images.githubusercontent.com/39082880/72732341-89c1a280-3ba6-11ea-975e-fe83936ff3c6.png)
И попробуй такую версию apache выставить
![image](https://user-images.githubusercontent.com/39082880/72732492-e1600e00-3ba6-11ea-97c9-f8c62758ee82.png)

**Comment by AlekseyKrivitskiy** [comment]
@KahjuksEi у меня вот такая стоит, просто 7,2 нету
![image](https://user-images.githubusercontent.com/59744681/72732890-ce017280-3ba7-11ea-8a35-50466e4f0fb7.png)
Да, заработало, причина была в правильном расположении папок и проекта, а почему так? почему нужно в domains создавать еще одну папку "D", туда клонировать проект, и домен настраивать на ту папку "D", ну и путь прописывать уже в url? Это специфика фреймворка?
просто я работал с yii2, все проекты просто в domains ставил домен на файлы в самих проектах был настроен, проблем не было

**Comment by KahjuksEi** [comment]
Логика вложенности в том, что в доменах мы создаем папку для проекта, в котором мы впишем при желании верстку, модули (как например дойку) и прочий контент,  а не создаем проект тупо ради модуля))

**Comment by AlekseyKrivitskiy** [comment]
@KahjuksEi звучит логично) спасибо большое за помощь)

**Comment by AlekseyKrivitskiy** [comment]
Проблема решилась правильным расположением файлов и папок. Необходимо создавать папку проекта, и в нее уже устанавливать модуль. Домен настраивать на папку проекта, а не модуля.

**Comment by rizomaa** [comment]
@AlekseyKrivitskiy зачынайце картку, калі усё атрымалася!
