### ISSUE TITLE
Лакальнае разгортванне праекту (натыўнае) пад mac (якар Linux).

### ISSUE THREAD

**Issue by InaFK** [diglabby/doika#676]
@rizomaa
Пасля запуску composer атрымала памылку http://prntscr.com/qx2fek
Прыйшлося спачатку выканаць п. 7 мануала і нанава запусціць composer
Далей усё пайшло добра - да п.8.
Тут пытанні па стварэнню БД http://prntscr.com/qyajzs.

**Comment by SashaKalinin** [comment]
Введите sudo mysql

**Comment by InaFK** [comment]
@SashaKalinin, дзякую за дапамогу

@rizomaa, пасля выканання інструкцыі ў п.10
![image](https://user-images.githubusercontent.com/3469516/74092720-fe6a6b80-4ad8-11ea-8521-fa7e7ae4ef3d.png)

выпаў эксэпшн:
![image](https://user-images.githubusercontent.com/3469516/74092718-f4e10380-4ad8-11ea-966a-dc7772206575.png)
дапамагла sql-каманда (from stackoverflow.com):
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '123';

![image](https://user-images.githubusercontent.com/3469516/74092859-1216d180-4adb-11ea-808f-7eabc46f70fa.png)

пасля генерацыі ключа (п.12) усталяваная версія запусцілася:
![image](https://user-images.githubusercontent.com/3469516/74092918-ed6f2980-4adb-11ea-84e1-ad37a0ecb28e.png)

праект дасяжны:
![image](https://user-images.githubusercontent.com/3469516/74093002-31166300-4add-11ea-8944-2d4dea4387ef.png)

**Comment by SashaKalinin** [comment]
У меня такая-же проблема.

вс, 9 февр. 2020 г., 1:23 Ina <notifications@github.com>:

**Comment by SashaKalinin** [comment]
Вы просто ввели это в mysql?
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY
'123';

вс, 9 февр. 2020 г., 9:31 Alexander Kalinin <sashakalininweb@gmail.com>:

**Comment by InaFK** [comment]
@SashaKalinin
так:

![image](https://user-images.githubusercontent.com/3469516/74101439-ca2f9300-4b4a-11ea-8b9b-88fd68ad2c7c.png)

вось тут (https://stackoverflow.com/questions/52364415/php-with-mysql-8-0-error-the-server-requested-authentication-method-unknown-to/53881212#53881212) апісаны больш агульны выпадак з password:

![image](https://user-images.githubusercontent.com/3469516/74101464-314d4780-4b4b-11ea-84ac-62bb8e5ef1b3.png)

**Comment by rizomaa** [comment]
@InaFK віншую з усталёўкай.

закрывайце гэту картку, напішу прадалейшыя крокі.
