### ISSUE TITLE
Нативная установка проекта Doika

### ISSUE THREAD

**Issue by SashaKalinin** [diglabby/doika#677]
Дошел до пункта 10, выдает ошибку
![Снимок экрана от 2020-02-07 14-54-41](https://user-images.githubusercontent.com/60601773/74028161-c240e900-49ba-11ea-9213-e09768c4f34b.png)

**Comment by SashaKalinin** [comment]
что бы я не ввел : 
"Разгортваем базу дадзеных камандай php artisan migrate.
Пасля дадаем зыходныя дадзеныя камандай php artisan db:seed
Генерым ключ для laravel: зайсцi у папку doika праз i выканаць php artisan key:generate"
ошибка одинаковая.

**Comment by SashaKalinin** [comment]
и вот такая ошибка
![Снимок экрана от 2020-02-07 15-18-13](https://user-images.githubusercontent.com/60601773/74029147-19e05400-49bd-11ea-8ec6-ca1d9325e748.png)

**Comment by SashaKalinin** [comment]
https://github.com/diglabby/doika/issues/165

уже у кого-то была такая ошибка, но я не понимаю как ее решили

**Comment by SashaKalinin** [comment]
![Снимок экрана от 2020-02-07 15-20-45](https://user-images.githubusercontent.com/60601773/74029305-76437380-49bd-11ea-8813-856711d59d0a.png)

**Comment by SashaKalinin** [comment]
получилось
![Снимок экрана от 2020-02-07 15-44-28](https://user-images.githubusercontent.com/60601773/74030757-e1db1000-49c0-11ea-9bae-2ac3134531f4.png)

**Comment by SashaKalinin** [comment]
но после ввода пароля таже ошибка что и выше
![Снимок экрана от 2020-02-07 15-45-19](https://user-images.githubusercontent.com/60601773/74030793-f7503a00-49c0-11ea-8b36-13a0e6a06f0f.png)

**Comment by SashaKalinin** [comment]
Переустановил все заново.
Делал все 100% по шагам,каждое действие.
и всё равно ошибка.
![Снимок экрана от 2020-02-07 17-55-09](https://user-images.githubusercontent.com/60601773/74039624-37b8b380-49d3-11ea-8593-b019ef0777fe.png)

**Comment by SashaKalinin** [comment]
попытался найти решение в интернете, ввел выделенную команду,выдало новую ошибку
![Снимок экрана от 2020-02-07 18-14-42](https://user-images.githubusercontent.com/60601773/74041058-fd9ce100-49d5-11ea-9ef1-3ce96ce9d815.png)
![Снимок экрана от 2020-02-07 18-14-49](https://user-images.githubusercontent.com/60601773/74041059-fe357780-49d5-11ea-9aa8-2b112b6ab305.png)

**Comment by SashaKalinin** [comment]
![Снимок экрана от 2020-02-09 18-27-52](https://user-images.githubusercontent.com/60601773/74104897-57361480-4b6a-11ea-845c-8490ca9294b1.png)

**Comment by rizomaa** [comment]
@SashaKalinin калі ласка зачыняйце гэту картку, калі вырашылі ўсё, па ёй
