### ISSUE TITLE
Адмаляваць усе паведамленні

### ISSUE THREAD

**Issue by falanster** [diglabby/doika#68]
Намаляваць або вырашыць як будзе выводзіцца

першы спіс
- [ ] Паспяховасць адпраўлення паведамлення распрацоўгчыкам у адмінцы.
- [ ] паспяховае старэнне камапніі.

другі спіс
- [ ] Не правільна запоўненае поле ў адмінцы 
- [ ] Няправільна заопўненае поле ў кліентскай часцы.

**Comment by nastyafrosty** [comment]
https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346355317394  примеры

**Comment by rizomaa** [comment]
@lptn @fr0zen ці адмалёўваецца у нас паспяховасць ці не паспяховасць дзеяння у адмінцы ці кліенскай часцы?

**Comment by alies-dev** [comment]
@rizomaa 
я пакуль на франце нічога не рабіў (не толькі для гэай issue) --  я ЗУСІМ нічога не рабіў, не магу адказаць

**Comment by fr0zen** [comment]
Зроблена, зачыняю
