### ISSUE TITLE
Дадаць апісанне ў гайд, як ставіць віджэт (кліентскую частку) Doika

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#680]
1. Зрабіць гайд са скрынамі
2. Размясціць на вікі праекта.
3. Злінкаваць з гайдамі ўсталёўкі.

Што атрымалася знайсці:
Гэты айфрэйм, калі ставіш на старонку і ужо створана першая кампанія, можна выкарыстоўваць:
<iframe width="750" height="500" src="/doika/doika/widget/campaigns/1" frameborder="0"></iframe>

**Comment by Gordonshik** [comment]
То есть по сути нужно визуализировать статью Усталёўка для Распрацоўшчыкаў?
Што атрымалася знайсці:
Гэты айфрэйм, калі ставіш на старонку і ужо створана першая кампанія, можна выкарыстоўваць:
Эта информация где и как должна быть использована?

**Comment by rizomaa** [comment]
@Gordonshik напісать тэкстам, толькі тыя пункты якія неабхоны для кліентскай часткі.

Вось тут можна прачытаць, што такое "кліенсткая частка" (віджэт)
https://github.com/diglabby/doika/wiki/Слоўнік-праекта

"Інфа" можа быць выкарыстана на старонцы, якую трэба стварыць.

**Comment by Gordonshik** [comment]
@rizomaa то есть я работаю с open server 5.3.5 и нужно написать условно так:
1) Качаем os 5.3.5 отсюда
2) Ставим сюда
3) Открываем это
4) Настраиваем так
5) Запускаем так
6)???
7)PROFIT
Я так понимаю, что это не то, ведь ставится и админка, а вопрос не о ней. Не понимаю, что нужно. С какого шага? Быть может пример?
Потому что я понимаю, что за клиентская часть, и прочитал, но пока я ее установку для себя не могу отделить от установки админки и т.д.

**Comment by rizomaa** [comment]
@Gordonshik тут ужо пра сэрвер ничога не трэб пісаць.

магчыма задача сфармулавана не вельмі відавочна.

перафармулёўваю.

1. Спачатку паставіць сабе віджэт кліентскай часткі (сама дойка ўжо стаіць)
2. Падшыць сюды скрыншот.
3. Пасля напісаць як гэта зрабілі ў вікі.

Пачынайце пункты 1 і 2. Трэці калі будзе усё зроблена па першым двум.

**Comment by Gordonshik** [comment]
@rizomaa окей, я понял что имелось ввиду, разобрался.
Тогда такой вопрос, а где этот виджет должен быть?
То есть я уже его вставлял, он появляется, все окей, но он наверное должен быть где-то конкретно? Я под этим подразумеваю то, что я вставил его в app.blade.php, например, и он у меня выше хедера, это же не дело, так?
Или важен сам факт, показать, мол вот я вставил код определенным образом и вот виджет появился?
![изображение](https://user-images.githubusercontent.com/51483246/74964224-1f5d8580-5424-11ea-8d8b-1fa42ded5c98.png)

**Comment by rizomaa** [comment]
@Gordonshik так, важны толькі сам факт паказаць, як выводзіць віджэт на любой старонцы.

**Comment by Gordonshik** [comment]
@rizomaa 
Сам гайд:
https://github.com/diglabby/doika/wiki/%D0%AF%D0%BA-%D1%81%D1%82%D0%B0%D0%B2%D1%96%D1%86%D1%8C-%D0%B2%D1%96%D0%B4%D0%B6%D1%8D%D1%82-(%D0%BA%D0%BB%D1%96%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D1%83%D1%8E-%D1%87%D0%B0%D1%81%D1%82%D0%BA%D1%83)-Doika
![изображение](https://user-images.githubusercontent.com/51483246/75097233-57e29800-55b9-11ea-8ffe-c95f9b1b584e.png)
Я так понял это имелось ввиду (добавил снизу ссылку на гайд).

**Comment by Gordonshik** [comment]
@rizomaa добавил в home wiki для разработчиков в конце:
https://github.com/diglabby/doika/wiki

**Comment by rizomaa** [comment]
@Gordonshik прывітанне, ці можаш даслаць дакладную спасылку?

**Comment by rizomaa** [comment]
@Gordonshik заўважыў тут https://github.com/diglabby/doika/wiki/Даданне-Doika-на-сайт

Асноўны каментар, ці магчыма зрабіць гайд па-беларуску? Дастаткова лаканічнага адказу, так ці не.

**Comment by Gordonshik** [comment]
@rizomaa да, сейчас сделаю

**Comment by Gordonshik** [comment]
@rizomaa перевел, но  на всякий лучше проверить

**Comment by rizomaa** [comment]
@Gordonshik зачыняй картку, дзякуй!

**Comment by rizomaa** [comment]
@Gordonshik прывітанне,

Пачаў ставіць па [твайму гайду](https://github.com/diglabby/doika/wiki/%D0%94%D0%B0%D0%B4%D0%B0%D0%BD%D0%BD%D0%B5-Doika-%D0%BD%D0%B0-%D1%81%D0%B0%D0%B9%D1%82) віджэт узнікла некалькі пытанняў:

1. Чаму трэба капіраваць код айфрэйма ў хэдэр html файла. Наколькі я ведаю гэта служовая частка разметкі для падключэння стыляў, бібліятэк, розных шруфтоў, кадыровак ці метатэгаў. Але не бачыў айфрэймаў там. Патумач мне, бо без аўтарытэтных прываў трэба перапрацаваць і засунуць код у body тэг.

2. Па якому роўту ты выклікаеш app.blade.php Буду вельмі удзячны, калі зарыентуеш шлях адносна виртуальнага хаста

**Comment by Gordonshik** [comment]
@rizomaa да, в body тег, я чет просто не заметил походу. Потому что читал, что в body, но не туда вставил. изменю скрин.
Не совсем понимаю вопрос, 
![изображение](https://user-images.githubusercontent.com/51483246/78374992-d842e280-75d4-11ea-84fa-eb65ff299b0d.png)
вот путь к файлу. А виджет сам появляется, когда я страницу запускаю, никаких действий больше не произвожу

**Comment by Gordonshik** [comment]
гайд по поводу body тега дополнил, если что

**Comment by rizomaa** [comment]
@Gordonshik як ты адчыняеш старонку на трэцим кроку? па якому адрасе?

**Comment by Gordonshik** [comment]
@rizomaa сразу после авторизации на компании, на ней. Но оно в любом случае видно будет, если там размещать, где я это сделал

**Comment by rizomaa** [comment]
@Gordonshik так, там можна узяць тэг з айфрэймам. 
!!!
мне цікава, якая спасылка павінна быць на старонку, дзе ты ўстаўляеш гэты айфрэйм.

**Comment by Gordonshik** [comment]
@rizomaa то есть? Ну та, которая ведет на эту страницу, где и стоит виджет? А какая еще может туда направлять? Или я не понимаю что-то?
Ну то есть если на странице А, есть этот плагин, то ссылка такой и будет: https://A
Вопрос в этом? сейчас проверю конечно

**Comment by Gordonshik** [comment]
@rizomaa проверил, при интеграции на страницу входа там и появился, тогда какая ссылка еще нужна?

**Comment by rizomaa** [comment]
@Gordonshik 
Напрыклад. Я паставіў модуль. 
Ведаю шлях да адмінкі, а дзе будзе шлях да старонкі віджэта?
Пазнач, каб чэл ведаў, з якой старонкі запусціць сам віджэт.  
Іншымі словамі, што напісаць у камандны радок браўзера.
Важна апісаць макімальна дакладна, бо гэту аперацыю могуць рабіць не дэвелаперы, а адміны сайтаў.

**Comment by Gordonshik** [comment]
@rizomaa так, окей, понял и разобрался. Но хочу уточнить как оформить
http://localhost/doika/doika/widget/campaigns/1 то есть путь условно у меня получился такой, но как он будет выглядеть в рамках реального сайта? я так понимаю там же локалхоста не будет и первая дойка наверное будет названием того сайта? просто я сам это ссылку определил, но как ее в примере лучше обозначить?

**Comment by Gordonshik** [comment]
@rizomaa или наверное все же вместо локалхоста будет название сайта, а одну дойку мы уберем из ссылки или как это лучше оформить?

**Comment by rizomaa** [comment]
@Gordonshik так можаш замест локалхаста написаць файлкарту кшталту: <адрас_сайта>

**Comment by Gordonshik** [comment]
@rizomaa в пути doika один раз указывать? или так и указывать doika/doika?

**Comment by rizomaa** [comment]
@rizomaa другі варыянт

**Comment by Gordonshik** [comment]
@rizomaa проверяй

**Comment by rizomaa** [comment]
@Gordonshik у мяне асноўнае пытанне,

навошта закідваць спасылку ў app.blade.php калі ў гайдзе прапануеццаа прамая спасылка доступа да віджэта
?

паспрабуй апусціць другі крокі. ці зменіцца ад гэтага вынік?

**Comment by Gordonshik** [comment]
@rizomaa изначально не так понял, исправлю

**Comment by rizomaa** [comment]
@Gordonshik пакуль гэту задачу пакідаем, як неабходную зрабіць. Бо па сутнасці гайд не адказвае на пытанне, як паставіць Doika віджэт на сайт (старонку сайта) = Даданне Doika на сайт
Папанаваенае рашэнне можа падыходзіць, калі ў арганізацыі няма сайта, а ёсць дамен і ставім дойка на голы дамен. Але такую усталёку хутчэй за усё не прапусціць агрэгатар, бо не усё усовы старонкі вытрыманы.

**Comment by andrei-roh** [comment]
@rizomaa добрый день! Хочу уточнить:
Я смог внедрить в свой сайт модуль Doika, но я использовал Open Server, где в localhost сначала установил модуль Doika по руководству для разработчиков, а потом положил в localhost свой сайт. После в модуле создал кампанию по сбору средств и разместил эту кампанию у себя на сайте:
![Модуль на сайте](https://user-images.githubusercontent.com/65450338/83408989-38f76b80-a41c-11ea-9f88-8f54e14edfec.jpg)
Это правильный подход к руководству либо мне нужно разместить сайт c модулем на хостинге типа github pages и так составить руководство?

**Comment by andrei-roh** [comment]
@rizomaa 
[Установка клиентской части Doika.docx](https://github.com/diglabby/doika/files/4717011/Doika.docx)

**Comment by rizomaa** [comment]
@andrei-roh прывітанне, выглядае цікава.

1. Пара заўваг. Можна тэксты пісаць адразу ў вікі праекта. На будучае, імкнемся рабіць чарнавікі у праектнай прасторы. Гэта ўжо ўзгаданая вікі.
2. Таксама знаёмся з папярэдняй размовай або працай над задачай, бо частка там карысныя спасылкі або інфа.

Вось старонка, дапоўні яе калі ласка 
https://github.com/diglabby/doika/wiki/Даданне-Doika-на-сайт
беларускім тэкстам (калі складана беларускім. Проста карыстайся аўта перакладам, пасля хто-небудзь з каманды вычытае на арфаграфію).

**Comment by andrei-roh** [comment]
@rizomaa https://github.com/diglabby/doika/wiki/Даданне-Doika-на-сайт

**Comment by rizomaa** [comment]
@andrei-roh вітаю,

Дзякуй, добрая праца.

Адзін каментар:

Вось тут https://github.com/diglabby/doika/wiki/Даданне-Doika-на-сайт#Крок-трэцi-Размяшчэнне-
віджэту--модуля-doika-на-сайце

Удакладні тэкст: 
"адкрыць для рэдагавання сайт"

Уяві, што ты рэдактар, які ўмее размяшчаць навіны, але не распрцоўшчык.

**Comment by andrei-roh** [comment]
Понял, попытался уточнить последний этап https://github.com/diglabby/doika/wiki/Даданне-Doika-на-сайт
