### ISSUE TITLE
Поле ввода,открытие виджета

### ISSUE THREAD

**Issue by SashaKalinin** [diglabby/doika#682]
В виджете в поле. где донэйтер может ввести свою сумму вместо 0 лучше написать "іншая сума" і не менять фразу на выбранную сумму із предоставленных, пусть пользователь всегда відіт,что он может впісать свою

**Comment by rizomaa** [comment]
@SashaKalinin ваша картка дублюе больш раннюю, таму гэту зачыняю. Калі ласка працягвайце тут працаваць https://github.com/diglabby/doika/issues/548
