### ISSUE TITLE
Не могу установить на open server

### ISSUE THREAD

**Issue by Timatiklive** [diglabby/doika#685]
Во время установки Doika на open server windows по инструкции столкнулся с ошибкой. После команды php artisan migrate - ошибка (на фото)  Еще смущает.ENV в котором, мне кажется, тоже может быть нюанс, больше смущает его имя. (Фото) 

<img width="334" alt="2" src="https://user-images.githubusercontent.com/60982663/75855439-60ca3980-5e03-11ea-8df8-e6c72c4dfb80.PNG">
<img width="358" alt="1" src="https://user-images.githubusercontent.com/60982663/75855442-61fb6680-5e03-11ea-936d-ed389120127b.PNG">

**Comment by rizomaa** [comment]
@Timatiklive 
якое дакладна імя щ файла канфігарацыі і дзё ён ляжыць?

наконт паведамлення, што вы маеце шмат адказаў можа быць пытанне. а шт овы спрабавалі? 
напрыклад:
https://laracasts.com/discuss/channels/forge/it-is-unsafe-to-run-dusk-in-production-error-when-trying-to-deploy?page=1#reply=367103

**Comment by Timatiklive** [comment]
Добрый день! 
1. имя файла .env.example (пробовал test.env) лежит тут: D:\OSPanel\domains\localhost\doika
2. перечитал кучу форумов и русскоязычных и англоязычных, толком решения не нашёл, хоть эта проблема не только у меня. Пробовал с самого начала composer install, но все остается (думал, что ошибка при установке произошла, так как ненадолго потерял соединение) Сейчас буду ещё гуглить

**Comment by Timatiklive** [comment]
попробовал composer install еще раз. такая же ошибка 
<img width="658" alt="Снимок" src="https://user-images.githubusercontent.com/60982663/76159664-dd2a8880-6133-11ea-9757-6f1842b6cc22.PNG">

**Comment by Timatiklive** [comment]
Эффекта нет...
<img width="533" alt="2" src="https://user-images.githubusercontent.com/60982663/76159973-00a30280-6137-11ea-982b-1f58f79c0752.PNG">

**Comment by rizomaa** [comment]
> Добрый день!
> 
> 1. имя файла .env.example (пробовал test.env) лежит тут: D:\OSPanel\domains\localhost\doika
> 2. перечитал кучу форумов и русскоязычных и англоязычных, толком решения не нашёл, хоть эта проблема не только у меня. Пробовал с самого начала composer install, но все остается (думал, что ошибка при установке произошла, так как ненадолго потерял соединение) Сейчас буду ещё гуглить

@Timatiklive ці скапіравалі файл .env.example у .env ?

**Comment by Timatiklive** [comment]
Доброе утро! Попробую ещё раз! Полное имя файла с расширением должно быть таким: ".env" или ".env.env" спасибо!

**Comment by Timatiklive** [comment]
Все получилось! Спасибо! Начудил с именами файлов .env
Готов к дальнейшим подвигам! :)
<img width="491" alt="4" src="https://user-images.githubusercontent.com/60982663/76356507-1a0aa100-6327-11ea-92d6-68a562d4824d.PNG">


> > Добрый день!
> > 
> > 1. имя файла .env.example (пробовал test.env) лежит тут: D:\OSPanel\domains\localhost\doika
> > 2. перечитал кучу форумов и русскоязычных и англоязычных, толком решения не нашёл, хоть эта проблема не только у меня. Пробовал с самого начала composer install, но все остается (думал, что ошибка при установке произошла, так как ненадолго потерял соединение) Сейчас буду ещё гуглить
> 
> @Timatiklive ці скапіравалі файл .env.example у .env ?

**Comment by rizomaa** [comment]
@Timatiklive супер. Тады я зачыняю гэту карту. Можаце праглядзець спіс адкрытых ішус. 
https://github.com/diglabby/doika/issues

працягнем перапіску поштай.
