### ISSUE TITLE
У рэпе перазахоўваюцца выявы пры тэставанні стварэння кампаній storage/public/uploads

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#689]
Трэба дадаць гэту тэчку storage/public/uploads у гіт ігнорэ

**Comment by rizomaa** [comment]
https://github.com/diglabby/doika/pull/688

**Comment by rizomaa** [comment]
@lptn як лічыш, гэту тэчку storage/public/uploads нейкім чынам адпраўляць у .gitignore ці гэта норм пакінуць так?

**Comment by alies-dev** [comment]
@rizomaa 
https://github.com/diglabby/doika/blob/develop/.gitignore#L20 :)

PS: так, трэба
