### ISSUE TITLE
Пытанні па архітэктуры і інфраструктуры праекта (бэкэнд)

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#692]
1. Якую функцыю зараз выконвае тэчка: https://github.com/diglabby/doika/tree/develop/resources/views ? Можам яе закрыць?

2. Ці гатовы докер для карыстання? https://github.com/diglabby/doika/tree/develop/docker Я удмаю памясціць мэйк файлы ў тэску з докерам, каб яны не поўзалі у корні, гэта не апшкодзіць логіку працы з імі?

3. Хацелася б тэставаць API падчас працы з франтом. Калі мы пачнем новы фронт, хутчэй за усё нам спатрэбіцца ісці па усіх роўтах. Падкажы калі ласка, як яго наладзіць (як ты генерыш токены і робіш аўтарызацыю: на постмэне, або свагеры, або твой інструмент?
https://github.com/diglabby/doika/blob/develop/routes/dashboard_api.php  Ці гэта звычайныя эндпоінты і да іх даступацца напрост па шляхах роўтаў?

4. Навошта патрэбна гэта тэчка для праекта https://github.com/diglabby/doika/tree/develop/bootstrap ?

**Comment by alies-dev** [comment]
@rizomaa 
1. У https://github.com/diglabby/doika/tree/develop/resources/views  ж ляжаць віюхі якія рэнрэрыць Лапавел (не vue). Выдаляць катэгарычна нельга - там ляжыць каркас прыкладання і некаторыя старонкі якія рэндэрыць Лапавэль (напрыклад аўтарызацыя)
1. Па докеру- пытанне да Лешы, ен яго ствараў. Наколькі памятаю былі праблемы на шляхам для рэсурсаў і URL старонак (кшталту /doika/doika )
1. Аўтарызацыя класічна і спрошчана зроблена праз кукі, пагэтаму трэба старонка аўтарызацыя Ларавэль (калі справа ідзе пра адмінку). 
1. Гэта службовая тэчка Ларавэля, дзе ён захоўвае файлы для запуска (bootstrap)

**Comment by rizomaa** [comment]
@lptn дзякуй за хуткі адповяд. доступы да гэтага каркаса такія ж як і для дэмкі на франце?

**Comment by alies-dev** [comment]
@rizomaa 
не зусім разумею пра што ты, але думаю адказ станоўчы, бо доступы паўсюль аднолькавыя

**Comment by rizomaa** [comment]
@lptn я пра гэта "У https://github.com/diglabby/doika/tree/develop/resources/views ж ляжаць віюхі якія рэнрэрыць Лапавел (не vue). Выдаляць катэгарычна нельга - там ляжыць каркас прыкладання і некаторыя старонкі якія рэндэрыць Лапавэль (напрыклад аўтарызацыя)"

Там тая самая (лагін, пароль) аўтарызацыя як на адмінку толькі натыўная для ларавэль, так?

**Comment by alies-dev** [comment]
@rizomaa 
аўтэнціфікацыя у нас пра форму якую рэндэрыць Ларавэль (і толькі так).  + каркас для Vue 
такжа там тэмплэйты імэйлаў ляжаць

такжа там ляжыць каркас для Vue для нашага віджэта

**Comment by rizomaa** [comment]
@lptn дзякуй, па аўтэтыфікацыі праз гуі пакуль пытанні скочыліся)

знайшоў кампаненты для Vue па часцы паведамленняў
https://gthub.com/diglabby/doika/blob/develop/resources/js/dashboard/views/Notifications.vue у бліжэйшы час працую над функцыянальнасцю кастанымных паведамленняў.

Пакуль да кампанентаў виджэта не лез,магчыма трохі пазней, калі нейкая аплата там запрацуе.

**Comment by rizomaa** [comment]
@lptn гэта сінанімічныя запісы: 

Diglabby\Doika\Models і
App\Models
Калі падключаеш прасторы мадэляў?

**Comment by alies-dev** [comment]
@rizomaa 
не, мапінг тут:
https://github.com/diglabby/doika/blob/500dad18920a8efd5c2fbe6f0efd7ddc814ec4cb/composer.json#L55-L57

**Comment by rizomaa** [comment]
бачу нейкая прамежкавая сітуацыя зараз паміж унутранай апрацоўка эндпоінтаў і АПІ. 

Масівы дадзеных вяртаюцца ў  джэйсон фармаце як бы гатовыя для знешняй апрацоўкі, але прыём адбываецца наўпрост, ці я пакуль не знайшоў мідлварэ, якое правярае карыстачоў, якія могуць слаць запыты ў базу. 

@lptn Можаш пракаментаваць частку па мідлварэ, дзе яны ляжыць, калі ёсць, бо ўжо думаю пісаць у Notification адпаведны функцыянал. Дзякуй

**Comment by rizomaa** [comment]
> @rizomaa
> не, мапінг тут:
> https://github.com/diglabby/doika/blob/500dad18920a8efd5c2fbe6f0efd7ddc814ec4cb/composer.json#L55-L57

@lptn дзякуй, пачынаю раскурываць гэту частку.

**Comment by alies-dev** [comment]
Глядзі тут камэнтар https://github.com/diglabby/doika/blob/b81c6c5412fc67b5b9ab8fe44792d2ceae27d28e/routes/dashboard_api.php#L3-L5

 вось тут рэўіструем розныя файлы роўтаў і дадаем middleware узроўня файлаў

https://github.com/diglabby/doika/blob/96b9bf9e8993a70183ec6febc1d52da14df042f4/app/Providers/RouteServiceProvider.php#L24-L63


а тут можаш глянуць што middleware api насамрэч гэта группа іншых middleware  якія мы мусім ужывацб да  усіх api запытаў
https://github.com/diglabby/doika/blob/96b9bf9e8993a70183ec6febc1d52da14df042f4/app/Http/Kernel.php#L29-L49

**Comment by rizomaa** [comment]
@lptn ага, дзякуй за тлумачэнне

**Comment by rizomaa** [comment]
@lptn зараз падабраліся да двух значных функцый.
- [ ] 1. Мэйлінг 
- [ ] 2. Старонка адпіскі ад рэкурэнтных плацяжоў.
Буду ўдзячны калі падкажаш, які код у нас ужо ёсць і можна выкарыстоўваць для гэтых задач.

**Comment by rizomaa** [comment]
Па докер інсталяцыі. Паціху вывучаю матчастку докера. Паглядзеў, што ў нас ёсць па гэтаму пытанню.

1. Файлы прысвечаныя докеру ў розных частках праекта ў тым ліку ў тэчцы docker
2. Так у нас ёсць гайд для лінукс. І віндовы, яго ў асноўным спрабуюць навічкі, пакуль не было выпадку, калі ён прынес плён.

Маю некалькі пытанняў @lptn па працы з разгорнутым докер асяродкам:

1. Дзе захоўваецца база дадзеных распрацоўкі? У кантэйнеры? Як арганізаваць нейкую гісторыю базы для наступных задач, калі выключыць кантэйнер. Гэта пытанне важнае, бо щ нас пакуль няма сідаў для тэставых дадзеных і, шчыра, перапісваць тэставыя дадзеныя пасля кожных зменаў, можа быць даволі раскошна для нас. проста написанне сідаў таксамаможа не вырашаць пытанне.
2. Дзе трэба перазапускаць npm асяродак (ці уключаць яго ў рэжым watch), гэта часта трэба для распрацоўкі фронтэнд. У тым ліку патэнцыйнай дастаўкай нейкіх модуляў іг.д.
3.  Ці магчыма без згубы якасці ўсё, што тычыцца докера, закінуць у адну тэчку, бо розныя файлы засмечваюць праект і не відавочныя адразу.

Чакаю тваіх каментароў.

**Comment by alies-dev** [comment]
>Файлы прысвечаныя докеру ў розных частках праекта ў тым ліку ў тэчцы docker

не зусім (наколькі паматаю). Толькі тэчка  docker + пара файлаў у корні


> 1. Дзе захоўваецца база дадзеных распрацоўкі? У кантэйнеры?

Наколькі я бачу (і нажаль) у кантэйнеры

>проста написанне сідаў таксамаможа не вырашаць пытанне.

у чым праблема з сідамі? І што за тэставыя дадзеныя і як вы іх зюіраецеся выкарыстоўваць?

>2. Дзе трэба перазапускаць npm асяродак (ці уключаць яго ў рэжым watch), гэта часта трэба для распрацоўкі фронтэнд. У тым ліку патэнцыйнай дастаўкай нейкіх модуляў іг.д.

думаю лакальна могуць запускаць watch (не тэсціў на існуючым сетапе), але ж гэта залежыць ад архітэкстуры праекта (SPA і "наколькі" SPA). Ведаю  што на пытанне не адказаў, але тут "depeds on"


> 3.  магчыма без згубы якасці ўсё, што тычыцца докера, закінуць у адну тэчку, бо розныя файлы засмечваюць праект і не відавочныя адразу.

чым ясасней праект, тым болей розных бібліятэк і пакетаў для асяродздзья і канктроля якасці, нэта непазбежна ў 2020, не думаю што гэта рэальна праблема. Але думаю перанесці можна кожным нецялікага ускладнення карфігаў. Але дасведанаму распрацоўшчыку будзе прасцей калі ўсе ў корне (як на іншых праектах -- гэта амаль industry standard)




PS: усе гэтыя пытанні (строга чажучы) не архітэктурныя а інфраструктурныя :)

**Comment by rizomaa** [comment]
@lptn дзякуй за каментар, яшчэ напішу па гэтаму пытанню. так слушна тут больш інфраструктуры.
