### ISSUE TITLE
Скараціць назвы палёў табліцы Кампаніі

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#696]
Назва кампаніі  -> Назва
Статус кампаніі -> Статус
Ахвярадаўцы -> Ахвярадаўцы
Падпіска -> Падпіска
Сярэдні чэк -> Сяр. чэк
Сабраная сума -> Сабр. сума
Колькасць дзён да заканчэння -> Дзён да заканчэння
Дзеянні ->

**Comment by Gordonshik** [comment]
Делаю

**Comment by Gordonshik** [comment]
По факту сделал, я так понял надо подождать пока примут мой предыдущий пулреквест

**Comment by rizomaa** [comment]
@Gordonshik можаш пуліць)

**Comment by Gordonshik** [comment]
@rizomaa Прыбау з бачнасці любы функцыянал па стварэнню новых юзэраў (рэгістрацыя. узнаўленне пасвардаў) #700
в этот pr изменения подкреились по укорачиванию полей таблицы, я не специально, пул реквест создавал без них, но закомитил изменения и оказалось, что они присосались к этому пулреквесту. Я понятия не имел, что такое может произойти. Протестируй, и тогда сразу закроем, или как?

**Comment by rizomaa** [comment]
@Gordonshik я суботу вядзелю на тэставанне, зробленага табой.
дзякуй, што пракаментаваў, пакуль працягвай іншыя задачы, зараз важна #680
