### ISSUE TITLE
Занесці ў масіў перакладу некалькі радкоў з DataTable.vue або ўзяць гатовыя радкі іпадставіць пераменныя

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#697]
title: this.$t('labels.admin.common.confirmation'),
        text: "Выдаленая кампанія больш не ўзновіцца. Усе падпіскі прыпыняцца!",
        icon: "warning",
        buttons: ["Адмена", "Выдаліць!"
        ]

**Comment by KuhniaDruggist** [comment]
Привет. Правильно ли я понял, что необходимо добавить фразу "Выдаленая кампанія больш не ўзновіцца. Усе падпіскі прыпыняцца!" и название кнопок "Адмена", "Выдаліць!" в словари (be en ru) + в файле DataTable.vue добавить на них ссылки?

**Comment by rizomaa** [comment]
@KuhniaDruggist дакладна

**Comment by KuhniaDruggist** [comment]
Как мне можно будет проверить результат? Дело в том, что в демо версии у меня в разделе список компаний отсутствуют компании и создать компанию я не могу, соответственно удалить тоже)

**Comment by rizomaa** [comment]
@KuhniaDruggist 
Чаму вы не можаце стварыць кампанію?
Пакажыце скрын, або памылку калі такая маецца. Будзем глядзец)

**Comment by KuhniaDruggist** [comment]
Заполняю поля, нажимаю "Захавать" и ничего не происходит. В разделе списки компаний пусто. (Перед тем как нажать кнопку "Захавать" очистил консоль. После нажатия посыпались ошибки) Прилагаю скрин.
![Screenshot_107](https://user-images.githubusercontent.com/48412681/81598153-878e8880-93cf-11ea-87c2-eb43ec991ae6.png)

**Comment by rizomaa** [comment]
@KuhniaDruggist Цікава што там у POST запыце першая памялка з кансолі.

На якой галіне git вы працуеце?

**Comment by KuhniaDruggist** [comment]
develop

**Comment by rizomaa** [comment]
Яшчэ
1. Ці пазнчалі апісанне?
2. Ці абіралі даты пачатку і даты канца?

**Comment by KuhniaDruggist** [comment]
Только что попробовал - все вышло. Это приятно. Однако с точки зрения пользователя при заполнении обязательных полей(название, выбрать файл и количество) активируется кнопка "Захавать" означающая что появилась возможность сохранения. Но при клике на нее ничего не происходит и пользователь ничего не понимает, как это было со мной. Мне кажется с точки зрения доступности это не совсем правильно и с этим необходимо что-то сделать. Либо сделать все поля обязательными, либо выводить сообщение подсказку, дескать заполните "эти" поля что по сути и означает их обязательность. Что вы думаете по этому поводу?

**Comment by rizomaa** [comment]
@KuhniaDruggist 
калі гатова, рабіце ПР _) + залінкуйце яго да гэтай карткі

я зараз працую над гэтай ішу: https://github.com/diglabby/doika/issues/564
пакуль думаю, што варта рабіць

па-першае, натыфікейшны па кожнаму полю, калі 
1. яно абавязковае
2. але не запоўненае.

па-другое, 
1. рабіць падсветку абавязковых
2. незапоўеныных палеў.

па-трэцяе,
1. пазначыць самі незапоўненыя абавязковыя палі, напрыклад зорачкай, як людзі прывыклі разумець абавязковасць =) 

зы 
што было перашкодаў асноўнай?

**Comment by KuhniaDruggist** [comment]
Сделеал PR https://github.com/diglabby/doika/pull/721

**Comment by rizomaa** [comment]
@KuhniaDruggist дзякуй, прыняў ПР =)

у бліжэйшы час абазначу наступную задачу
