### ISSUE TITLE
Дзе запісваецца рэжым тэставага плацяжу?

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#698]
Гляджу тут на старонцы наладак ёсць гэта поле. Але ў табліцы ня бачна. 

@lptn падкажаш, як зараз арганизавана гэта частка?

**Comment by alies-dev** [comment]
@rizomaa 
прабач, не памятаю

**Comment by rizomaa** [comment]
вось тут бачу пуста тут 
![Selection_014](https://user-images.githubusercontent.com/9870374/77894964-b963e980-727e-11ea-99ef-4ec6f957625e.png)
і тут
![Selection_015](https://user-images.githubusercontent.com/9870374/77895740-e49b0880-727f-11ea-9bc1-d19f555711cf.png)

пакуль гэту карту пакідаю на падумаць і да часу калі у нас наогул пойдуць хоць нейкія плацяжы.

зы
Ёсць думка 
1. Вывесці тэставыя плацяжы у табліцу агульных наладак doika_settings (поле testmode: true/ 
 па змощчанні false)
2. У транзакцыях дадаць поле test-payments (true/false)
3. Калі калі тэставыя плацяжы выключаюцца тады выдаляюцца ўсё транзакцыі з поля test-payments: true

**Comment by alies-dev** [comment]
@rizomaa 
у нас апроч базы юзаецца яшчэ вось гэты файл https://github.com/diglabby/doika/blob/develop/config/settings.php#L26 у яго усе сецінгсы задумывалася пісаць

**Comment by rizomaa** [comment]
@lptn Якога характару налады? Тыя што для падключння агрэгатара, або нейкія сістэмныя? бо як разумею ёсць за яшчэ .env

Дарэчы, тут гэтага файлу settings.json пакуль няма https://github.com/diglabby/doika/tree/develop/storage

**Comment by alies-dev** [comment]
@rizomaa 
>Якога характару налады? Тыя што для падключння агрэгатара, або нейкія сістэмныя? бо як разумею ёсць за яшчэ .env

налады праекту, якія складана прывязаць да нейкіх тыпаў у рэляцыйных БД.
.env - гэта для таго зто будзе разгортваць. для .env у нас няма GUI і ен можа быць закэшаваны. settings.json для наладаў праекту даступных з UI

>Дарэчы, тут гэтага файлу settings.json пакуль няма

ен ствараецца аўтаматам пры першым запісу (патрэбныя правы на запіс)

**Comment by rizomaa** [comment]
@lptn Да апісанага табой тыпу, адносяцца наладкі знешняга выгляду віджэта?

**Comment by alies-dev** [comment]
@rizomaa 
думаю так. Няма нияких чотких межаў і правілаў што дзе заховаць. Думаю з улікам бягучай сітуацыі лепей захоўваць так, каб прасцей было распрацоўшчыкам (я так разумею задача стаіць максімальна спрасціць працэс распрацоўкі)

**Comment by rizomaa** [comment]
картку зачыняю бо функцыя тэставых плацяжоў непатрэбна. гэта можна зрабіць стварыўшы тэстаувю кампанію.. 

Ці як варыянт стварыць проста сідам нейкую кампанію па дэфолту аўтаматам, на якой будуць правяраць тэставы рэжым.
