### ISSUE TITLE
Дадаць laravel migrations, адпаведныя бягучай структуры БД версіі 1.2

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#7]
- [ ]  1. Вырашыць структуру базы дадзеных (20 снежня).
- [ ]  2. Зрабіць мадэлі і іх сувязі (20 снежня)
- [ ]  3. Зрабіць класс reccurentPaymentHandler (связан с маделямі, працуючымі з табліцай рэкурэнтных плацяжоў) (27 снежня)
- [ ]  4. Зрабіць мадэль віджэта і мадэлі старонак адмінкі (3 студзень)
- [ ]  5. DoikaMailHandler (абпрацоўшчык паведамленняў (працуе з інтэрфейсам ларавэля)) (адмена адпіскі прадумаць, сістэма рэгістрацыі прадумаць)

**Comment by lptn** [comment]
калі раптам трэба згенераваць маграцыі аўтаматычна з БД - вось есьць пакет для гэтага https://github.com/Xethron/migrations-generator

**Comment by falanster** [comment]
@lptn дзякуй,

мы ўчора гутарылі наконт стварэння новай структуры БД #17 
як толькі мы створым бачанне новай БД, далей мы будзем актыўна выкарыстоўстваць для падубовы міграцый

**Comment by lptn** [comment]
@falanster 
Размова відаць ішла пра https://github.com/Xethron/migrations-generator

**Comment by falanster** [comment]
@Tyuba4 @fr0zen гэта штука можа нам дапамагчы? https://github.com/Xethron/migrations-generator

**Comment by fr0zen** [comment]
@falanster @lptn так, дзякуй, добрая тулза

**Comment by fr0zen** [comment]
[] 1. Вырашыць структуру базы дадзеных (20 снежня).
[] 2. Зрабіць мадэлі і іх сувязі (20 снежня)
[] 3. Зрабіць класс reccurentPaymentHandler (связан с маделямі, працуючымі з табліцай рэкурэнтных плацяжоў) (27 снежня)
[] 4. Зрабіць мадэль віджэта і мадэлі старонак адмінкі (3 студзень)
[] 5. DoikaMailHandler (абпрацоўшчык паведамленняў (працуе з інтэрфейсам ларавэля)) (адмена адпіскі прадумаць, сістэма рэгістрацыі прадумаць)
[] 6.

**Comment by Tyuba4** [comment]
API bepaid(begateway) PHP https://github.com/begateway/begateway-api-php

**Comment by falanster** [comment]
@Tyuba4 магчэма гэту спасылку варта дадаць у карысны на трэла?

@fr0zen падправіў твой спіс актыўнасцяў па гэтай картцы, але у мяне патанне да абодвух

ці гэта  спіс тычыцца непасрэдна гэтай задачы? @Tyuba4 @fr0zen ?

**Comment by Tyuba4** [comment]
@falanster Я добавлял, перенес из пункта GitHub в bepaid.

**Comment by rizomaa** [comment]
@Tyuba4 скажы калі ласка, што трэба у гэтай задачы патэсціць? бо яна ужо тры тыдні гэтага чакае, карта разруліцца
