### ISSUE TITLE
Проблема с перенаправлением виджета на страницу успеха.

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#703]
Платеж вроде происходит нормально, но почему-то нет перенаправления на страницу благодарности, когда виджет находится в iframe, в обычном режиме все ок. Также не отбиваются webhooks, но это скорее всего из-за того, что я на локалке

**Comment by rizomaa** [comment]
@Tyuba4 чаму уводзіш залежнаць перанкіраванне з "не отбиваются webhooks" ? ці бачыш тут найкія зувязі, або гэта незалежная таска?

**Comment by Tyuba4** [comment]
> @Tyuba4 чаму уводзіш залежнаць перанкіраванне з "не отбиваются webhooks" ? ці бачыш тут найкія зувязі, або гэта незалежная таска?

@rizomaa Нет, это даже не ошибка, так как она появляется только на локале.

**Comment by rizomaa** [comment]
@Tyuba4 калі я магу нечым тут дапамагчы пазнач, якую частку мне можна узяць. Бо пасля размовы я зразумеў: што ты бачыш прабелму ў vue і маршруцізацыях (роўтах) там.
Пакуль я магу паглядзець як арганізаваны віджэт.

Дарэчы Атрымліваецца ў нас двайная ўкладзенасць айфрэймаў:
1. Гэта айфрэйм віджэта дойкі.
2. Другі айфрэйм - агрэгатар. які укладзены ў першы.

Агрэгатар павінен вяртаць адказ з плацяжа айфрэйму віджэта. Але гэтага не адбываецца? правільна?

**Comment by Tyuba4** [comment]
Пока игрался с платежами на локалке заметил, что на сервер приходит адрес платежной страницы такого формата: "https://checkout.bepaid.by/v2/checkout?token=...", но в айфрейме виджета адрес другого формата "https://checkout.bepaid.by/v2/checkout?token=...&iframe=inline". После я создал html страницу с афреймом и поместил туда по очереди платежные страницы с разными форматами адреса, чтобы проверить перенаправление. Во втором случае перенаправления не было. Так что, возможно, проблема в форматах платежных страниц. Сейчас я собираюсь поискать код, который формирует адрес с параметром "iframe=inline" на серверной части. Если мои поиски не увенчаются успехом, то передам эстафету тебе @rizomaa. Может данный код скрывается во Vue.

**Comment by Tyuba4** [comment]
Буду опробовать работу с webhooks. Если ответы о совершении платежей от bepaid будут приходить быстро, то предлагаю смотреть в сторону websockets как инструмента для измения платежной страницы в виджета на страницу статуса платежа, то есть о перенаправлении и информировании донатеров.

**Comment by Tyuba4** [comment]
@rizomaa Для проверки webhooks
1) установить xdebug
2) установить и настроить ngrok
3) проверить webhook, для этого:
 a) найти файл app/Http/Controllers/Webhooks/PaymentGateways/BePaidPaymentWebhookHandler.php
 b) найти в нем метод donated и поставить поинт для дебагера
 c) ввести адрес localhost/doika/bepaid/donated/{campaignId} и убедится в том, что при этом сервер приходит в эту часть кода, потом проделать ту же операцию через ngrok
 d) повторить тоже самое через ngrok, сделав оплату через виджет

**Comment by rizomaa** [comment]
Я тут стварыў асобную картку пакуль https://github.com/diglabby/doika/issues/714

калі задачы 100% перасякаюцца можам працягнуць у гэтай. @Tyuba4  ?

**Comment by Tyuba4** [comment]
@rizomaa Тест ngrok показал, что отправка webhook происходит в течении 3-4 секунд. Следовательно можно работать с перенаправлением на страницу успеха внутри виджета с помощью websocket. Websocket будет работать на линии server-frontend.

**Comment by Tyuba4** [comment]
@rizomaa Я начинаю заниматься настройкой websockets на сервере.

**Comment by rizomaa** [comment]
@Tyuba4 Скажы, як мы будзем тэставаць на лакале усе цуды юды. Асабліва цікава частка франта
