### ISSUE TITLE
Дадаць у масіў перакладу радкі са старонкі рэдагавання паведамленняў 

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#711]
Для уводнай задачкі: 

http://<url-хаста>/doika/doika/dashboard/notifications

Усё што не кранаецца саміх паведамленняў і іх назваў.

Падказка:
Амаль усё ляжыць у NotificationsForm.vue і Notifications.vue

![Selection_035](https://user-images.githubusercontent.com/9870374/80598642-55c20d00-8a32-11ea-87ab-1911f319a90d.png)

**Comment by rizomaa** [comment]
@KuhniaDruggist наступная картка. Яна падобна на папярэднюю з перакладамі.

**Comment by KuhniaDruggist** [comment]
@rizomaa  Правильно ли я понял: необходимо также внести все в словарь и сделать ссылки?

**Comment by rizomaa** [comment]
@KuhniaDruggist менавіта так. Уносце ва ўсе моўныя слоўнікі.
