### ISSUE TITLE
Адладзіць прыём паведамленняў з сэрвера агрэгатара - Сварыць тэставы сэрвер

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#714]
- [x] 1.1. Усталяваць php-дэбагер на atom рэдактар
- [x] 1.2. Усталяваць праброс віртуальнага хаста праз ngrok
- [x] 2.1. Знайсці патрэбны файл (BePaidPaymentWebhookHandler.php) і паставіць брэйк пойін на метадзе donated.
- [ ] 2.2. Пратэставаць яго GET запыт
- [ ] 3. Адправіць запыт з віджэта.
- [ ] 4. Пасля аплаты павінен прыйсці адказ ад сэрвера. 
- [ ] 

Трэба:

- [ ] 1. Засеч час адказу.
- [ ] 2.  Калі час прымальны (да 10 сек) бярэм варянт
- [ ] 3. Інакш абмяркоўваем, што робім

**Comment by rizomaa** [comment]
Камент адсюль:

1. установить xdebug
2. установить и настроить ngrok
3. проверить webhook, для этого:
a) найти файл app/Http/Controllers/Webhooks/PaymentGateways/BePaidPaymentWebhookHandler.php
b) найти в нем метод donated и поставить поинт для дебагера
c) ввести адрес localhost/doika/bepaid/donated/{campaignId} и убедится в том, что при этом сервер приходит в эту часть кода
d) повторить тоже самое, сделав оплату через виджет

адсюль
https://github.com/diglabby/doika/issues/703#issuecomment-621806866

**Comment by rizomaa** [comment]
Тут докі для запуска https://ngrok.com/docs#getting-started-stable

**Comment by rizomaa** [comment]
Наладзіў праз ngrok (https://ngrok.com/docs#virtual-hosts) віртуальны хост.

Адчыняецца мая лакальаня інсталяцыя:
http://e04438d1.ngrok.io/doika/doika/dashboard/login

![Selection_037](https://user-images.githubusercontent.com/9870374/80963596-f1c78c00-8e17-11ea-88f6-c0b65cbc162f.png)

Пры лагіне выдае 
"
Symfony \ Component \ HttpKernel \ Exception \ HttpException
CSRF token mismatch.
Previous exceptions
CSRF token mismatch. (0)
"
Калі перагружаю шлях, ён залагіньваецца і перанакіроўвае на лакальны хост:
http://doika2/doika/doika/dashboard/campaigns

@lptn сустракаўся з такім момантаў.

**Comment by alies-dev** [comment]
@rizomaa 
тут усе распісана што да чаго https://laravel.com/docs/master/csrf

калі не ясна што гэта такое - ЧАСОВА адключайце VerifyCsrfToken middleware

**Comment by rizomaa** [comment]
@lptn добрай раніцы,
дзякуй, чытаю артыкул)

**Comment by rizomaa** [comment]
Пранікся) Знайшоў файл 
https://github.com/diglabby/doika/blob/develop/app/Http/Middleware/VerifyCsrfToken.php
Па ходу гэты мідлварэ.

@lptn Маеш на ўвазе тут:
https://github.com/diglabby/doika/blob/develop/app/Http/Kernel.php
закаменціць гэты радок:
`36            \Diglabby\Doika\Http\Middleware\VerifyCsrfToken::class,`
?


Зы яшчэ паспрабую 
```
protected $except = [
        'stripe/*',
        'http://example.com/foo/bar',
        'http://example.com/foo/*',
    ];
```

зы @Tyuba4 табе таксама гэта можа быць цикава=)

**Comment by rizomaa** [comment]
уваход зараз адбываецца без csrf паведамлення аб памылцы, але пераходзіць на лакальны хост з дыстанцыйнага.
мяркую
1. канфігі (.env не пракаціў)
2. .... думаю

**Comment by rizomaa** [comment]
Падзадача:

Усталяваць лібу і праверыць яе працу з віджэта 
https://www.npmjs.com/package/vue-native-websocket

**Comment by alies-dev** [comment]
А што ў нас ёсць сервер з вэбсокетамі? Ці трэццебаковыя сэрвісы плануецца
выкарыстаць? Чым апраўдана такое ўскладненне?

**Comment by rizomaa** [comment]
@lptn займаюся прадумваннем гэтай часткі рашэння з боку франта.
бачыш прасцей рашэнне?

**Comment by Tyuba4** [comment]
А в чем будет заключаться усложнение? Добавим библиотеку по типу такой https://packagist.org/packages/hoa/websocket и вперед.))) А вебсокеты позволят нам редиректится на страницу статуса платежа внутри виджета, не перезагружая всю страницу.

**Comment by Tyuba4** [comment]
@lptn @rizomaa На локалке вэбсокет почекал, все работает. Проверить бы на хостинге каком

**Comment by alies-dev** [comment]
@Tyuba4 
 які вэб-сэкет сервер ставіў? працуе з рэжыме дэмана?

**Comment by rizomaa** [comment]
@Tyuba4 добра, што пайшло.
Табе трэба шарынг хостынг, або проста нешта анлайн (можам наш сэрвер выкарыстаць)?

**Comment by Tyuba4** [comment]
@lptn Этот пакет поставил - https://packagist.org/packages/hoa/websocket  И все, через него работает
> які вэб-сэкет сервер ставіў? працуе з рэжыме дэмана?

**Comment by Tyuba4** [comment]
@rizomaa Лучше сразу какую-нить шару попробовать. Может у Семы что-то есть?
> добра, што пайшло.
> Табе трэба шарынг хостынг, або проста нешта анлайн (можам наш сэрвер выкарыстаць)?

**Comment by Tyuba4** [comment]
@rizomaa @lptn Проверил, на shared-хостингах закрывают все порты, кроме сконфигурированных по умолчанию. Короче websockets отпадают.( Так что, думаю, надо  останавливаться на варианте с проверкой статуса транзакции через AJAX.

**Comment by rizomaa** [comment]
@Tyuba4 добра, што зараз пряныли за ўвагі. Мінімізавалі працу.
Скажы якія далей крокі?

**Comment by Tyuba4** [comment]
@rizomaa Берем схему с проверкой статуса платежа AJAXом. Я делаю на бэкенде проверку с запросом на bepaid. Ты делаешь на vue периодическую отправку AJAX на бэкенд и перенаправление на страницу статуса при его изменении.

**Comment by rizomaa** [comment]
@Tyuba4 

Значыць у нас на франце будзе кампанент, які кожную хвіліну (так?)
1. адпраўляе запыт на сэрвэр і 
2. правярае ці прыйшло, што-небудзь.
3. калі прыйшло паказвае наступнае ваконо віджэта.

Акей, тады чакаю ад цябе эндпоінтаў і магчымыя варыянты статусаў.

**Comment by Tyuba4** [comment]
> 
> Значыць у нас на франце будзе кампанент, які кожную хвіліну (так?)
> 
> 1. адпраўляе запыт на сэрвэр і
> 2. правярае ці прыйшло, што-небудзь.
> 3. калі прыйшло паказвае наступнае ваконо віджэта.
> 
> Акей, тады чакаю ад цябе эндпоінтаў і магчымыя варыянты статусаў.

@rizomaa 
Да, все правильно. Работаю над бэком и эндпоинтами

**Comment by Tyuba4** [comment]
> > Значыць у нас на франце будзе кампанент, які кожную хвіліну (так?)
> > 
> > 1. адпраўляе запыт на сэрвэр і
> > 2. правярае ці прыйшло, што-небудзь.
> > 3. калі прыйшло паказвае наступнае ваконо віджэта.
> > 
> > Акей, тады чакаю ад цябе эндпоінтаў і магчымыя варыянты статусаў.
 
@rizomaa 
Да, все правильно, только не каждую минуту, а чаще, через каждые 5-10 секунд. Работаю над бэком и эндпоинтами

**Comment by alies-dev** [comment]
@Tyuba4 
@rizomaa 
во-во-во хлопцы

>@rizomaa Берем схему с проверкой статуса платежа AJAXом. Я делаю на бэкенде проверку с запросом на bepaid. Ты делаешь на vue периодическую отправку AJAX на бэкенд и перенаправление на страницу статуса при его изменении.

не зразумеў, якую праблему вы вырашаеце полінгам кожную хвіліну? Чуйка мне падзвае што тут штосьці не так

**Comment by rizomaa** [comment]
@lptn паглядзі калі ласка назву задачы, там апісана праблема. Калі ведаеш нешта больш за нас прапануй рашэнне, фронт працы. Я дапамагу рабіць па франтовай часцы любы працоўны варыянт.  Сэканоміш кучу нашага часу.)

**Comment by alies-dev** [comment]
@rizomaa 
>паглядзі калі ласка назву задачы, там апісана праблема.

>Адладзіць прыём паведамледнняў з сэрвера агрэгатара

А чаму яе трэба адладзіць? Яна ж працавала. Ужо не прыходзяць вэбхукі ці што? Дарэчы 'stripe/*' выключаць з CSRF ня трэба, бо мы не выкарыстоўваем VerifyCsrfToken для вэбхукаў:

 
https://github.com/diglabby/doika/blob/96b9bf9e8993a70183ec6febc1d52da14df042f4/app/Providers/RouteServiceProvider.php#L31-L37

\Diglabby\Doika\Http\Kernel::class 
![image](https://user-images.githubusercontent.com/5278175/82482355-66205180-9adf-11ea-9927-da057ec806c6.png)


> Калі ведаеш нешта больш за нас прапануй рашэнне, фронт працы. Я дапамагу рабіць па франтовай часцы любы працоўны варыянт. Сэканоміш кучу нашага часу.)

я ж ня ведаю праблему, хлопцы! Мала таго што тут ўмат паведамленняў, я ўсе прачытаў але праблемы так і не знайшоў, толькі варыянты яе рашэння. Калі хочам эканоміць час -- трэба добрае апісанне праблем (гэта галоўнае у баг-рэпорце а не магчымыя варыянты рашэння)

**Comment by alies-dev** [comment]
Калі праблема ў тым што не прыгоходзяць вэбхукі, то  праверце куды МЫ УКАЗВАЕМ каб яны прыходзілі. У нашым выпадку гэта адбываецца тут https://github.com/diglabby/doika/blob/9aedabb2d50067314ea296c46f3d6a58b9359644/app/Services/PaymentGateways/BePaidPaymentGateway.php#L67

Толькі калі ў вашым `.env` стаіць `APP_URL=http://localhost` ці што-небудзь лакальнае, то вэбхук не прыйдзе (бо адрас лакальны [surprise?])

Буду рады дапамагчы. Калі я ня правільна угадаў вашу праблему - калі ласка апішыце яе а лепей абнавіце title і descriotion гэтай issue а я перачытаю

**Comment by rizomaa** [comment]
> я ж ня ведаю праблему, хлопцы! Мала таго што тут ўмат паведамленняў, я ўсе прачытаў але праблемы так і не знайшоў, толькі варыянты яе рашэння. Калі хочам эканоміць час -- трэба добрае апісанне праблем (гэта галоўнае у баг-рэпорце а не магчымыя варыянты рашэння)

@lptn звярні ўвагу на сумежную картку тут пазначаную https://github.com/diglabby/doika/issues/714#ref-issue-591115650
гэта картка менавіта для адладкі створана

**Comment by rizomaa** [comment]
> Калі праблема ў тым што не прыгоходзяць вэбхукі, то праверце куды МЫ УКАЗВАЕМ каб яны прыходзілі. У нашым выпадку гэта адбываецца тут
> 
> https://github.com/diglabby/doika/blob/9aedabb2d50067314ea296c46f3d6a58b9359644/app/Services/PaymentGateways/BePaidPaymentGateway.php#L67
> 
> Толькі калі ў вашым `.env` стаіць `APP_URL=http://localhost` ці што-небудзь лакальнае, то вэбхук не прыйдзе (бо адрас лакальны [surprise?])
> 
> Буду рады дапамагчы. Калі я ня правільна угадаў вашу праблему - калі ласка апішыце яе а лепей абнавіце title і descriotion гэтай issue а я перачытаю

@lptn Дзякуй за камент. Мы разважалі з пазіцыі тэставання на лакальным асяродку. Як разумею, калі мы падключаем ngrok мы павінны закапіраваць гэты часовы урл у .env і ўсё будзе ціптоп? Паспрабую сёння гэта пратэставаць. 

@Tyuba4 ці улічваў ты гэты момант?

**Comment by alies-dev** [comment]
@rizomaa 
> Як разумею, калі мы падключаем ngrok мы павінны закапіраваць гэты часовы урл у .env і ўсё будзе ціптоп?

так (але я да сяго часу ня ўпэўнены што у вас запраблемы - рэдырэкт айфрэйма ці вэбхукі)

**Comment by Tyuba4** [comment]
@lptn проблема в редиректе айфрэйма

**Comment by Tyuba4** [comment]
@lptn @rizomaa Короче надо новый ишью делать или переходить в старый с багом редиректа. Алесь прав, все захламили.

**Comment by rizomaa** [comment]
Пры вывадзе віджэта...
Карацей нжрок тут не дапамога, бо CORS яшчэ пракідваць трэба.
`Access to XMLHttpRequest at 'http://doika2/doika/doika/widget/api/campaigns/10' from origin 'http://ac6a9dc0.ngrok.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by alies-dev** [comment]
Адкуль узяўся лакальны Дамэн doika2 у гэтым ерор мэссаджы?

**Comment by rizomaa** [comment]
@lptn 
1. Запусціў лакальны інстанс дойкі на сваім кампе. Яе віртуальны хост знаходзіцца http://doika2
2. Пасля запусціў ngrok па гэтаму ж віртуальнаму хасту
3. Пасля узяў згенераваны адрас і паставіў у .env замест localhost

Мэта усяго гэтага двіжа: зрабіць магчымым праводзіць тэставыя аплаты з лакальнай усталёўкі.

**Comment by alies-dev** [comment]
Гэта правільны алгарытм, вэбхукі будуць прыходзіць. А вось рэдырэкт гэта не
пафіксіць

**Comment by rizomaa** [comment]
магчыма на иншай галіне... патэнцыйна.

ці пашукаць pipeline continiuos integration як Bitbucket

**Comment by alies-dev** [comment]
Міхась, не зразумеў, да чаго тут pipeline continiuos integration як Bitbucket ?

**Comment by rizomaa** [comment]
> Міхась, не зразумеў, да чаго тут pipeline continiuos integration як Bitbucket ?

гэта канспект з нащай сёння размовы з @Tyuba4 , не звяртай увагі=)
мы хочам люты месяц трохі больш часу прысвяціць праекту, тым больш каманда украінцаў будзе для сябе адаптоўвацца таксама.
