### ISSUE TITLE
Пратэсціраваць заліўку фота кампаніі і змяніць правы на тэчкі для медыя кантэнта і кэша

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#717]
- [ ] 1. Праверыць ці дастаткова правоў пры стандартнай усталёўцы на лінукс сістэмах 
- [ ] 2. Калі недастаткова выканаць каманду `sudo chmod -R ug+rwx storage bootstrap/cache`
- [ ] 3. Дапоўніць усталёвачны гайд для распрацоўшчыкаў.

PS
Заўважыў узгадванне `sudo chmod 777 -R storage/` для докер усталёўкі... https://github.com/diglabby/doika/wiki/Усталёўка-для-Распрацоўшчыкаў

**Comment by andrei-roh** [comment]
@rizomaa Не могу установить на виртуальной ubuntu doika. Проблема возникает команде npm run dev/npm run watch. Прошу помочь с установкой
![Аннотация 2020-06-15 115257](https://user-images.githubusercontent.com/65450338/84637799-cba90780-aefe-11ea-861d-0f2bc8144c3e.jpg)

**Comment by rizomaa** [comment]
@andrei-roh ці выкарыстоўваеш sudo у камандзе з npm?

зы
дарэчы, калі падымеш свой скрын трохі вышэй будзе бачна больш дакладная памылка запуску npm каманды

**Comment by andrei-roh** [comment]
sudo использовал, а также прописывал перед composer install:
sudo chown -R www-data:www-data /var/www/doika/
sudo chmod -R 755 /var/www/doika/
sudo chmod -R 777 /var/www/doika/storage
![Аннотация 2020-06-18 181805](https://user-images.githubusercontent.com/65450338/85039304-3f157800-b190-11ea-9413-c1eb711ae42d.jpg)

**Comment by rizomaa** [comment]
@andrei-roh 4 пункт з гайда па ўсталёўцы. ці клікаў па спасылцы часта узнікаемая праблема
?

**Comment by andrei-roh** [comment]
@rizomaa да, кликал. Сделал, как в гайде, npm install прошло без ошибок, но при sudo npm run dev или sudo npm run watch ошибки появляются. Я пробовал игнорировать и ставить базу данных и запускать модуль, но возникает ошибка 404

**Comment by rizomaa** [comment]
@andrei-roh відавочна памылка правоў доступа да node-modules.

Якія гіпотэзы:
1. Сэрвер запушчаны пад адным карыстальнікам, а файлы пад іншымі закачаны. Напрыклад адзін субо карыстальнік друге - не.
2. Таксама такое можа быць што частка файлаў загружана пад аднам карыстальніка частка пад другім.
3. Варта праверыць якія правы доступа у самой тэчкі?

выбачай я памыліўся дзе варта засяродзіў увагу. Гэта 5 пункт. ТАм спасылка на стэкавэрфло, дзе апісана форс усталёўка. Спрабаваў яе?
