### ISSUE TITLE
Карыстальнікі сайта не бачаць даты пачатку і сканчэння збораў

### ISSUE THREAD

**Issue by ilyaaki** [diglabby/doika#72]
Карыстальнікі сайта, на якім размяшчаецца модуль doika (патэнцыйныя ахвяруючыя) не бачаць даты пачатку і сканчэння збораў (толькі калі гэта асобна напісаць у назве кампаніі ці апісанні кампаніі)

**Comment by ilyaaki** [comment]
Калі дата сканчэння збораў ужо прайшла (напрыклад,у наладках усталявана дата сканчэння 1 снежня 2018 года), модуль усё роўна працуе, і карыстальнікі далей могуць ахвяраваць грошы

**Comment by falanster** [comment]
@ilyaaki так, харошая, заўвага, 
варта будзе улічыць гэта на 1.3

@Tyuba4 @fr0zen трэба улічыць гэта....

**Comment by falanster** [comment]
@ilyaaki вось дарэчы падобная ішу
https://github.com/diglabby/doika_1.2/issues/41

@KsenjaV што думаеш наконт паставіць https://github.com/diglabby/doika_1.2/issues/41 як дадатковую задачу. ?
