### ISSUE TITLE
Дадаць тэксты падказкі ў вакне стварэння кампаніі (з перакладамі)

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#720]
Як адмін модуля хачу, каб была магчымасць бачыць неявілікі падкаскі побач з кожным полем 
1. Поле назва. Тэкст "Калі ласка апішыве ў назве асноўны сэнс кампаніі і яе мэту. Напрыклад, Спыніць апустыньванне Палесся. Шукаем сродкі на здымак фільма пра праблему"
2. Поле "Апісанне". Тэкст: "Пакіньце 2-4 сказы з асноўным сэнсам і некаторымі дэталямі кампаніі. Сродкі пойдуць на падарожжы па найбольш апустыненым месцам для здымання матэрыялаў, мантажу фільам"
3. Поле "Выява". Тэкст: Фота не абавязковае, але дае магчымасць больш зразумець што вы хочаце дасягнуць у вашай кампаніі. Даступныя фарматы. png, gif, jpg, jpeg
4. Поле "Дата пачатку и дата канца": Тэкст: "Калі ласка пазначце даты калі будзе бачна кампанія на вашым сайце. Дата сканчэння павінна быць пазней чым дата пачатку"
5. Поле "Колькасць (Сума)": Тэкст: "Любую суму, якую вы лічыце раэлістычна дасягнуць у вашай кампаніі"
6. Поле "Паласа прагрэсу". Тэкст: "Гэта поле будзе паказваць на старонцы дзе вы размесціце модуль колькасць сабраных на дадзены час сродкаў. Калі у вас тэрміновая кампанія такі функцыянала можа быць вельмі дарэчы."
7. .... іншыя палі, рэкурэнтнай кампаніі, верхні банер - пакуль нябачныя. таму ім тэкст будзе у іншай ішу.

зы магчыма выкарыстоўваць vue bootstrap элемент v-b-tooltip.hover

**Comment by KuhniaDruggist** [comment]
@rizomaa Привет. Давно меня не было, в связи с репрессиями в нашей стране. Сейчас приступил к реализации. Выглядит это так.
![Screenshot_132](https://user-images.githubusercontent.com/48412681/91040207-80a22380-e616-11ea-8121-7604b7ba66a4.png)
Единственное в поле "Апiсанне" решил сделать через placeholder, так мне кажется логичнее

**Comment by KuhniaDruggist** [comment]
@rizomaa Еще нашел один баг 
![Screenshot_131](https://user-images.githubusercontent.com/48412681/91040368-c6f78280-e616-11ea-9273-45e73632614b.png)
В поле сумма кракозябры, необходима новая issue. Знаю в чем проблема смогу исправить. Можно мне ее тогда to do забросить
