### ISSUE TITLE
Прыбраць надпіс Supported by the European Union

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#724]
![Selection_046](https://user-images.githubusercontent.com/9870374/81725902-3645ce00-948f-11ea-87f5-46e94a31cf96.png)

**Comment by KuhniaDruggist** [comment]
Эта фраза вообще где-нибудь используется? Или её вообще необходимо убрать из словаря?

**Comment by rizomaa** [comment]
@KuhniaDruggist 
1. Спачатку выдаліць з кампанента (футэр)
2.  Пасля прыбраць са слоўніка.

**Comment by rizomaa** [comment]
@KuhniaDruggist дзякуй. прыняў ПР
зараз прыярытэт гэта картка https://github.com/diglabby/doika/issues/711

**Comment by Alexeyvk** [comment]
@rizomaa  доречі в рамках реплікаціі мені у нас на українському лендінгу потрібно буде ярко та помітно цю надпис вернути ))) На 12 місяцев найменш, но то тільки на лендінгу )

**Comment by rizomaa** [comment]
> @rizomaa  доречі в рамках реплікаціі мені у нас на українському лендінгу потрібно буде ярко та помітно цю надпис вернути ))) На 12 місяцев найменш, но то тільки на лендінгу )

=))) 
Нас столькі людзей засупорціла, таму мы проста створым тут нейкую старонку з крыдэншлсамі)
