### ISSUE TITLE
Прапанова для сяброўскіх узнёскаў арганізацыі

### ISSUE THREAD

**Issue by ilyaaki** [diglabby/doika#73]
Прапанова:

Зрабіць магчымасць не задаваць даты пачатку і сканчэння збораў, а таксама прыбраць для карыстальніка магчымасць выбару сумы (пакінуць толькі патрэбную арганізацыі).

Тады арганізацыі зручна будзе праз doika збіраць сяброўскія ўзнёскі (напрыклад, узнёсак фіксаваны 23 BYN і няма абмежавання па даце аплаты).

**Comment by falanster** [comment]
@ilyaaki дзякуй, будзем трымаць у бэклогу

**Comment by rizomaa** [comment]
дзякуй гэта функцыя ёсць у іншай задачы. @ilyaaki
