### ISSUE TITLE
Уточнение гайда "Усталёўка для Распрацоўшчыкаў" для Win OpenServer

### ISSUE THREAD

**Issue by andrei-roh** [diglabby/doika#730]
Предлагаю уточнить гайд "Тэхнічныя патрабаванні да распрацоўкі" в некоторых моментах касательно установки:
1. Пункт 5 - для работы Git на Open Server Panel (Premium Edition не обнаружил) нужно зайти в Настройки Open Server-Закладки и добавить закладку git, в которой путь указать к git.exe (у меня это c:\program files\git\git-bash.exe). После этого в закладках Open Server появляется Git. 
2. При установке composer нужно указывать место нахождения php.exe в папке Open Server (у было меня C:\OpenServer\modules\php\PHP_7.2). Получается устанавливать сначала нужно Open Server, а потом уже composer. 
Поэтому предлагаю в Пункт 3,5 гайда добавить: 
установить composer, указав место нахождения php.exe в папке modules Open Server;
установить Laravel и Node.js;

**Comment by rizomaa** [comment]
@andrei-roh наколькі разумею гэты заваўвагі больш тычацца наладку самога асяродку.
я далёкі ад віндаўз усталёўкі, пакуль гэту картку патрымаем уверсе. калі нехта далучыцца з віндаўз яшчэ перагледзім гэтыч два пункты. дзякуй дэтальны разгляд.
