### ISSUE TITLE
Не перанакіроўвае нна наступны крок пасля выканання плацяжу

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#732]
Задача связана с #703

**Comment by Tyuba4** [comment]
Система состоит из двух составляющих: серверная(проверяет статус транзакции, посылая запрос на сервер bepaid, после отправляет ответ из bepaid фронтенду), фронтенд(после создания страницы платежа, фронтенд c периодичностью в несколько секунд посылает запросы о статусе транзакции на сервер с целью получения ответа)

**Comment by rizomaa** [comment]
@Tyuba4 дзякуй за апісанне. скінь калі ласка свае змены пул рэквэстам... чакаю з нецярпеннем)

**Comment by rizomaa** [comment]
@Tyuba4 у мяне тут гара памылак у кансолі... з некаторымі разабраўся, пакуль падвіс на гэтых

На старонцы загружаецца толькі свае кампаненты біпэйдаўская штука не дагружаецца:
http://<хост>/doika/doika/widget/campaigns/<нумар кампаніі>/donate

![Selection_052](https://user-images.githubusercontent.com/9870374/83119290-332a1f00-a0d8-11ea-9ef2-dda2cbb13775.png)

Можа яшчэ прыйдзе у галаву нешта. Сёння падчас размовы хачу таксама задзейнічаць твой разум на гэты конт, бо блакіруе далешы ход рашэння

**Comment by rizomaa** [comment]
Памылку вырашыў адключэннем плагіна да браўзера AdBlock

**Comment by rizomaa** [comment]
Учора размаўлялі з @Tyuba4 . Абмеркавалі, як рухаемя па картцы https://github.com/diglabby/doika/issues/732 Па пунктах
Long poling не так прост, асабліва для працы з шарэ хостынгамі (дзе тайм аўт сэрвера абмежаваны і фіксаваны).
Аждакс можа быць не такі кепскі, бо магчыма спатрэбіцца 1-2 максіму тры запыта каб атрымаць адказ.
Пакуль працягнем лонгполлінг, але калі да канца тыдня не вынайдзем простага рашэння прымаем ажакс рашэнне.
На франце алгарытм амаль аднолькавы застаецца, бо энд поінт тожа. Магчыма проста арганізавана рэкурсія.
@Tyuba4  папраў калі лаcка, калі нешта прапушчана.

**Comment by rizomaa** [comment]
![Selection_006](https://user-images.githubusercontent.com/9870374/86625973-af186080-bfce-11ea-83f0-44867724acd5.png)

Прайшоў праз працэдуры падпіскі сістэма вярнула наступны вынік. Фота вышэй. 
Вядомя не запісала гэты данат у табліцу. Стварыў асобны ішшу https://github.com/diglabby/doika/issues/762
Але з большага усё астатняе працуе. 

Проста калі посех вярнула, значыць, нейкі статус вярнула.

@Tyuba4 удакладні калі ласка тэкстам яшчэ раз задачу, каб я да серады паіграўся вакол гэтай задачы глыбей

**Comment by Tyuba4** [comment]
> ![Selection_006](https://user-images.githubusercontent.com/9870374/86625973-af186080-bfce-11ea-83f0-44867724acd5.png)
> 
> Прайшоў праз працэдуры падпіскі сістэма вярнула наступны вынік. Фота вышэй.
> Вядомя не запісала гэты данат у табліцу. Стварыў асобны ішшу #762
> Але з большага усё астатняе працуе.
> 
> Проста калі посех вярнула, значыць, нейкі статус вярнула.
> 
> @Tyuba4 удакладні калі ласка тэкстам яшчэ раз задачу, каб я да серады паіграўся вакол гэтай задачы глыбей

Скорее всего в БД ничего не записалось потому-что не отработал вебхук.

**Comment by rizomaa** [comment]
@Tyuba4 прывітанне,

Я думаў нейкі час, як гэта ўсё разруліць. Пасля нашага сэйшна падсумую, усё што абдумаў і мы зможам зрабіць, зараз напішу асоўны выклік.

1.1. campaigns/:id/donate - вакно, якое адмалёўвае форму ўводу сумы.
1.2. па змоўчанні пінгаванне эндпоінта `/bepaid-check-payment-status` будзе аддаваць памылку з тэстам `Gateway response not found.`
2.1. пасля націскання "Аплаціць" запыт адпраўляецца на эндпоінт і па выніку вяртаецца статус (поспех, або нейкая памылка і урл да іх).
2.2. Гэты урл і накіроўвае на stausWindow.vue - тое, што нам трэба, але...
3. Калі мы будзем проста пінгаваць эндпоінт `/bepaid-check-payment-status` на нейкі статус, які мае урл, мы будзем пастанна атрымліваць `Gateway response not found.`
4. А як толькі клікнем аплаціць, будзем перанакіраваны на бэк і ужо бэк нам дыктуе якая старонка статуса будзе адмалявана.

Зараз пытанне на падумаць. 
Дзе змяніць архітэктуру франта, каб пра націсканні запускаўся апрацоўшчык, які праверыць вернуты статус і тады падумае што рабіць...

**Comment by rizomaa** [comment]
@Tyuba4 
Атрымалася дайсці за рэкурсіўнай прапрацоўкі статусаў... =)

![Selection_072](https://user-images.githubusercontent.com/9870374/87147122-c304e080-c2b4-11ea-9a40-ac5e5a9a3ae1.png)

Яшчэ засталося дадаць 

- [ ] больш спорбаў...магчыма кожныя 10 секунд, +
- [ ] далучу апрацоўшчыкі для рэдырэкта 1. Поспеху і 2. Памылак

Застаецца бага, якую не вельмі зразумела, як выпраўляць. Калі націскеш клавішу "Аплаціць", нічога не адбываецца. Гэта "нічога не адбываецца" можа быць роўна выстаўленаму намі інтэрвалу запыту на эндпоінты ... я пакуль не маю рашэння для гэтага эфекту, але ён будзе, мы яго прымаем?

Цікавыя спасылкі:
1. https://github.com/axios/axios
2. https://stackoverflow.com/questions/45021907/vue-js-mounted
3. https://masteringjs.io/tutorials/vue/axios#with-server-side-rendering

**Comment by rizomaa** [comment]
Якія яшчэ ўмовы тэрба дапрацаваць у кодзе (запісваю сабе падзадачы):

- [x] 1. Рабіць першы інтэрвал 15 секунд, далей кожныя 1-2 секунды
- [x] 2. Калі форма не запоўнена пры сканчэнні ітнэрвала чакання запрасіць зрабіць паўторныя дзеянні па данату.
- [x] 3. Падумаць як паставіць на курсоры спінер, калі адправілі дадзеня карткі.
- [ ] 4. Разабрацца з франтом для падпісак і зрабіць тое самае.  Памылка 410 глядзець campaignsubscriptioIntendContoller.php (30-32 радкі)

**Comment by rizomaa** [comment]
Вырашыць яшчэ пытанне з унутраными роўтамі пасля атрымання статуса аперацыі (лепей праз router лібу)

Што праглядзець:
1. https://michaelnthiessen.com/redirect-in-vue
2. https://router.vuejs.org/guide/essentials/navigation.html
3. https://stackoverflow.com/questions/35664550/vue-js-redirection-to-another-page#35667628

**Comment by rizomaa** [comment]
Пазначыў, што [зроблена](https://github.com/diglabby/doika/issues/732#issuecomment-658060607). Засталося

- [x] 1. Аформіць код якасна для разавых плацяжоў (прыбраць непатрэбны код і дадаць чытальныя каменты)
- [x] 2  [REC] Наладзіць анлайн інстанс для зручнага тэставання на сэрверы (дамен doika2.falanster.by).
- [ ] 3. [REC] Паставіць інтэрвал 1 гадзіну для рэкурэнцыі (каб было зручна тэставаць).
- [x] 4. [REC] Пераслаць доступы на сэрвер @Tyuba4 (вышли мне калі ласка свой ssh ключ)
- [ ] 5. [REC] Паставіць код, які апрацоўваў аплату для разавых, на рэкурэнтныя. Прынцып працы тампадобны.
- [x] 6. Падумаць ці абмежавацца існуючым статусам fail_url ці ствараць асобны пры сканчэнні інтэрвала чакання пры уводзе дадзеных карткі?

**Comment by rizomaa** [comment]
Для таго, каб праверыць рэкурэнтныя плацяжы, трэба, 
1.1. каб ці ў нас у базе гэта неяк фіксавалася, 
1.2. і.ці на сэрверы 
2. Паставіць кароткі інтэрвал...

Наконт інтрэвала, што бачу на франце:

1. У секцыі data

```
 data() {
    return {
      campaign: [],
      redirect_url: null,
      placeholder: this.$t('buttons.widget.email'),
      model: {
        amount: sessionStorage.getItem('amount'),
        email: null,
        name: sessionStorage.getItem('name'),
        phone: sessionStorage.getItem('phone'),
        currency_code: 'BYN',
        payment_interval: 'P1M'
      }
    };
  },
```
Вось гэта нас цікавіць payment_interval: 'P1M'

Наконт дакументацыі на стуронцы: https://docs.bepaid.by/ru/subscriptions/plans

Бачна: 
`interval_unit | единица изменения интервала(hour - час, day - день или month  - месяц)`


зы
У рэшце пакуль шукаю яснасць дзе задаецца чоткі інтэрвал і як яго афармляць.

**Comment by rizomaa** [comment]
Тут зрабіў ПР для рэдурэкту разавых ахвяраванняў https://github.com/diglabby/doika/pull/775/files Гэту картку хутка зачыню, бо яны становяцца дублюючымі https://github.com/diglabby/doika/issues/703

Для сябе. Асноўны накірунак зараз пункты:
- [ ] [REC] Паставіць інтэрвал 1 гадзіну для рэкурэнцыі (каб было зручна тэставаць). Пашукаць у чым праблема.
- [ ] [REC] Паставіць код, які апрацоўваў аплату для разавых, на рэкурэнтныя. Прынцып працы тампадобны.

**Comment by Tyuba4** [comment]
Ад сеннешняга дня буду займацца працай над памылкамi запуску doiki на лакале.

**Comment by rizomaa** [comment]
1. Захаваць змены.
2. Пераставіць дойку.
3. Прынямінць змены і выкаціць ПР.
4. Скапіраваць змены у файл ReccurentWindows.vue

**Comment by rizomaa** [comment]
Які прагрэс пасля сёння:
1. У гэтым файле app/Services/PaymentGateways/BePaidPaymentGateway.php з боку бэка апрацоўваецца інтэрвал метадам parseDateInterval
2. Нібыта улічваецца: дзень, гадзіна, месяц - усё раскладаецца па кампанентам. Каб, як тут напісана https://docs.bepaid.by/ru/subscriptions/plans  Получение информации о плане... https://api.bepaid.by/plans/:plan_id праз гэты запыт. Трэба будзе тэстануць праз постмэн.

Наступныя крокі апісаны тут: https://github.com/diglabby/doika/issues/732#issuecomment-668481866

- [ ] 1. Спачатку інтэрвал для праверкі паспяховасці 1 плацяжу для рэкурэнта.
- [ ] 2. Калі гэта атрымаецца, пасля правяраем план, з якімі "interval" і "interval_unit" запісаліся на баку агрэгатара.
- [ ] 3. Пасля наладжваем запіс (не)паспяховых плацяжоў у базу (ці правяраем плацяжы нейкім скрыптом, які робіць запыты агэргатару... калі гэта магчыма). Лепей запіс у базу. 

На гэтым задачу варта будзе лічыць завершанай.

**Comment by Tyuba4** [comment]
Мы зачыняем дублюючую таску https://github.com/diglabby/doika/issues/703

**Comment by rizomaa** [comment]
@Tyuba4 ці перанакіроўвае у цябе юзэра. калі прауцем з анлайна?

**Comment by rizomaa** [comment]
>     1. У гэтым файле app/Services/PaymentGateways/BePaidPaymentGateway.php з боку бэка апрацоўваецца інтэрвал метадам parseDateInterval

@lptn вось гэты файл, дзе интэрвалы прапісаны

**Comment by Tyuba4** [comment]
@rizomaa зараз наладжу працу самога анлайна, тады гляну

**Comment by Tyuba4** [comment]
@rizomaa @lptn пераглядзеў яшчэ раз гэты кейс. Пры пацверджаннi плацяжу ажыцяўляецца пераход на пляцёжную старонку з карткай, але ж праз дзясятак секунд старонка перанакiроўвае на старонку з надпicам "Транзакция была обработана и отклонена шлюзом
![Снимок экрана 2021-04-03 в 23 05 04](https://user-images.githubusercontent.com/32882913/113490170-2254f180-94d1-11eb-928f-58f550b6ad9c.png)
"

**Comment by Tyuba4** [comment]
Карацей патрэбна дапамога vue-знаўцы, гэта значыць цябе @rizomaa  :)

**Comment by alies-dev** [comment]
Паглядзеў і я код - усё дрэнна на франце.  Крыху прыбраўся там, абнавіў залежнасці, выдаліх тое, штоне выкарыстоўваем у віджэце - стала крыху ляшчэй дыхаць. Пакуль жа узнікае жаданне увесь віджэт перапісаць але такі паспрабую пафіксіць.
