### ISSUE TITLE
Прапанова пашырыць шырыню ўводу колеру палітры для лепшага бачання коду

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#734]
Вось прапанова ад @darth-tesla

> Предлагаю сделать поля с хекс / ргба кодом пошире (чтобы код помещался полностью), а так же сделать одинаковую ширину для полей с описанием. https://ibb.co/473RW0g

Цікава гучыць...

**Comment by darth-tesla** [comment]
Прошу прощения. Выровнял поля по ходу работы над функционалом.

**Comment by rizomaa** [comment]
@darth-tesla добра тады прышэй сюды адпаведны камміт, калі там усё акей. будзем зачыняць картку

**Comment by rizomaa** [comment]
@darth-tesla апішы тут бягучыя выклікі для вырашэння карткі

**Comment by rizomaa** [comment]
@darth-tesla дзякуй за працу і адказы па каментарм., ПР прыняты
