### ISSUE TITLE
Абнавіць некаторыя кампаненты лэндынга Doika // https://doika.falanster.by/

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#735]
- [ ] 1. Прыбраць надпіс. На фота пазначаны
- [ ] 2. Дадаць Відэа.
- [ ] 3. Дадаць лагатыпы арганізацый, якія раыстаюцца дойка

![Selection_051](https://user-images.githubusercontent.com/9870374/82764074-eb27a580-9e14-11ea-96ed-60fcdc78e06c.png)

@svetit калі ласка дадай інфармацыю пра: 
1. Рэпазіторый, дзе працаваць з лэндынгам.
2. Спсылку на відэа
3. І лагатыпы для ўстаўкі.

**Comment by svetit** [comment]
@rizomaa  Сюды дадаваць задачы па дэндынгу? Ці асобнымі ішусамі?

**Comment by svetit** [comment]
Задача 2. Дадаць Відэа.

Спасылка на видэа https://www.youtube.com/watch?v=IYaf2GmB0q0&list=PLfDz_eqyn5f_zZkPcAbltV_QkIDHd_ekg&index=6&t=0s

Дадаць яго у блоку Што такое дойка. Расцягнуць гэты блок уніз, каб змясцілася відэа.
Пры гэтым водступы павінны быць такія ж. Шырыня відэа адпавядае шырыне тэкста.
(І для дэсктопа і для мабільнай версіі)
![doika_upgrade_1](https://user-images.githubusercontent.com/1722996/82813469-cc212600-9e9d-11ea-80fd-c1078572e6f5.png)

**Comment by svetit** [comment]
Сюды далучыць спасылку, каб я магла праверыць верстку.

**Comment by rizomaa** [comment]
@svetit пакуль усё сюды. Я аддзялю калі будзе патрэба.

=)

**Comment by rizomaa** [comment]
@svetit з якім рэпазіторыяем працаваць?

**Comment by svetit** [comment]
https://github.com/svetit/doika-landing - репазиторый. Я і забыла, што гэта мой..

**Comment by andrei-roh** [comment]
@rizomaa Добрый вечер! Вопрос по 3 пункту. Логотипы организаций, которые установили модуль займут место удаляемого контента в пункте 1?

**Comment by andrei-roh** [comment]
Добрый вечер! Ссылка на пункты 1 и 2:
https://github.com/andrei-roh/doika-landing
По 3 пока не понятно.
Также предлагаю пару замечаний:
1. Если уменьшать масштаб сайта, то все элементы отдаляются друг от друга, то есть на большом дисплее с высоким разрешением будет очень не удобно смотреть сайт. Я предлагаю после определенной ширины экрана "зафиксировать" верстку, чтобы элементы не расползались по экрану;
2. По мобильной версии. В css предусмотрено ограничение по ширине экрана (по сути окна) в пикселях. Но теперь экраны мобильных устройств имеют большие разрешения экранов и на экране смартфона сайт откроется как десктопный. Предлагаю учесть также плотность пикселей, которая у мобильных устройств в подавляющем большинстве будет выше, чем у обычных компьютеров и лэптопов, например @media only screen and (min-resolution: 300dpi) для мобильных устройств

**Comment by andrei-roh** [comment]
Добрый вечер! Ссылка на измененную верстку: https://github.com/andrei-roh/doika-landing
3 пункт не совсем понятно, где взять логотипы.
Кстати я заметил, что при уменьшении масштаба элементы сайта расползаются - предлагаю "зафиксировать" верстку для удерживания элементов друг рядом с другом при небольшом масштабе.

**Comment by rizomaa** [comment]
@svetit калі ласка адкажы на пытанне наконт лагатыпаў

**Comment by rizomaa** [comment]
@andrei-roh калі ласка пазначай нікі (імёны) з кім камунікуеш.

Па другому абзацу. Ствары асобную ішу (картку) і пакажы там, 1. як ёсць і 2. як ты хочаш, каб было: ці скрынамі ці схеамай. Калі будзе бачна слушнасць прапановы я схільны падтрымаць)

**Comment by andrei-roh** [comment]
@rizomaa Понял, исправляюсь https://github.com/diglabby/doika/issues/741

**Comment by svetit** [comment]
@andrei-roh  Вітаю.
Трэцяе заданне з лагатыпамі я яшчэ не сфармулявала, там частка даследчай працы з майго боку. У бліжэйшыя дні напішу.

Калі ласка, захосці сайт на гітхабе, мне будзе зручней праглядзець яго перад тым, як мерджыць.

Я не зразумела, што менавіта ты маеш на увазе, калі кажаш "Кстати я заметил, что при уменьшении масштаба элементы сайта расползаются - предлагаю "зафиксировать" верстку для удерживания элементов друг рядом с другом при небольшом масштабе.". Пакажы на нейкім скрыне, ці можам сазваніцца, і ты патлумачыць расшарыўшы экран.

**Comment by andrei-roh** [comment]
@svetit Добрый вечер! Отправляю ссылку на сайт: https://andrei-roh.github.io
Обсуждение по ширине верстки: https://github.com/diglabby/doika/issues/741
Прошу также глянуть очень важное (на мой взгляд, естественно) замечание и высказать своё мнение: https://github.com/diglabby/doika/issues/744

**Comment by svetit** [comment]
@andrei-roh Пра відэа - добра! Кідай мне пулрэквэст, я прыму.

**Comment by andrei-roh** [comment]
@svetit Жду информацию по 3 пункту

**Comment by svetit** [comment]
@andrei-roh 
3. У гэты блок тэксту трэба дадаць новыя лагатыпы са спасылками на сайты з дойкай, як ужо дададзеныя (на усіх мовах)
![image](https://user-images.githubusercontent.com/1722996/83664741-0e9bde80-a5d3-11ea-94a7-a16bf9fe9320.png)

Гэта арганізацыі:
Ахова птушак бацькаўшчыны https://ptushki.org/helpus/how_to_pay
Фонд развіцця брэсцкай крэпасці http://www.brestheritage.by/join/
Мамстарт http://mamstart.by/

Ніжэй далучу лагатыпы, ці выявы.

**Comment by svetit** [comment]
![ptushki](https://user-images.githubusercontent.com/1722996/83664961-689ca400-a5d3-11ea-8306-7c5ed8622c9b.jpg)

**Comment by svetit** [comment]
![br_krepost](https://user-images.githubusercontent.com/1722996/83664981-6e928500-a5d3-11ea-855f-7113942dd9b5.png)

**Comment by svetit** [comment]
![mamstart](https://user-images.githubusercontent.com/1722996/83664994-73573900-a5d3-11ea-9177-f7bc750db2e0.jpg)

**Comment by andrei-roh** [comment]
@svetit Отправляю ссылку на сайт с добавленными партнерами: https://andrei-roh.github.io/index.html

**Comment by rizomaa** [comment]
@svetit тут трэба твой апрув)

**Comment by svetit** [comment]
@andrei-roh Дзякуй, усе крута, рабі пул реквэст, заапруўлю.
@rizomaa Дзякуй, што пінгануў.
Выбачайце за затрымку.

**Comment by andrei-roh** [comment]
@svetit Готово! https://github.com/svetit/doika-landing/pull/35

**Comment by svetit** [comment]
@andrei-roh Змерджыла! :)

**Comment by andrei-roh** [comment]
@svetit Мне нужно что еще делать, чтобы завершить issue и добавить его в мой список достижений?

**Comment by svetit** [comment]
@andrei-roh  здаецца усе гатова, але трэба удакладніць.
@rizomaa  Вітаю. На лэндзінгу дойка раней працаваў джэнкінг і аўтаматычна забіраў аднаўленні.
https://doika.falanster.by/
Але гляджу сайт не адноўлены... Гэта, пэўна не уваходзіць у гэтую задачу, але гэта можа быць іншай задачай.

**Comment by rizomaa** [comment]
@svetit зараз не працуе джэнкінс. у бліжэйшы месяц дакладне не будзем запускаць. Таму калі ласка разграні яго ў ручным рэжыме

**Comment by svetit** [comment]
@rizomaa Ок.
@andrei-roh  Гэтая задача зроблена! Дзякуй:)
