### ISSUE TITLE
Фронтэнд. adding button "show password" in log in panel

### ISSUE THREAD

**Issue by nastyafrosty** [diglabby/doika#74]
http://it3donate-landing.falanster.by/doika/en/admin/login

**Comment by nastyafrosty** [comment]
https://github.com/diglabby/doika/issues/50

**Comment by Hellsingi** [comment]
ацэньваю на два тыдня

**Comment by Hellsingi** [comment]
Укажыце пуць па якім я магу знайсці файл для рэдагавання?

**Comment by rizomaa** [comment]
@Hellsingi атрымалася знайсці?

**Comment by Hellsingi** [comment]
@rizomaa не атрымалася знайсці, быў бы ўдзячны за дапамогу

**Comment by rizomaa** [comment]
@Hellsingi найпер шанпішы
1. Дзе шукаў
2. Па якіх ключавых словах шукаў?
Калі адкажаш, на іх тады змагу быць набольш эфектыўным

**Comment by Hellsingi** [comment]
@rizomaa я шукаў у тэчцы doika, па слова login ці якое падабаенная і каб у файлу было слова password

**Comment by fr0zen** [comment]
@Hellsingi 
[тут](https://github.com/diglabby/doika/blob/dev/resources/views/auth/login.blade.php) асноўны код шаблона
