### ISSUE TITLE
Зафиксировать максимальную ширину страницы Doika // https://doika.falanster.by/

### ISSUE THREAD

**Issue by andrei-roh** [diglabby/doika#741]
Предлагаю зафиксировать максимальную ширину страницы для больших экранов и/или экранов с большим разрешением. При текущей ширине страницы на таких экранах элементы страницы будут "отодвинуты" друг от друга. Это заметно при уменьшении масштаба страницы.
Как есть сейчас (масштаб 25%):
![Аннотация 2020-05-28 102557](https://user-images.githubusercontent.com/65450338/83113764-c1020c00-a0d0-11ea-85b0-3e1b1fe03375.jpg)

Я предлагаю сделать примерно так (масштаб 25%):
![Аннотация 2020-05-28 102558](https://user-images.githubusercontent.com/65450338/83113776-c4959300-a0d0-11ea-8ec0-8320b0240fba.jpg)

То есть на большом экране сайт перестанет растягиваться и будет занимать определенную часть окна браузера в середине. Пример: сайт Onliner.by

**Comment by rizomaa** [comment]
@andrei-roh які памер "большого экрана"?

@svetit што думаеш па гэтай прапанове?

**Comment by andrei-roh** [comment]
@rizomaa думаю что это экраны 27+ дюймов 4k, но это не точно. Я не имею столько опыта и мониторов

**Comment by darth-tesla** [comment]
@andrei-roh а что если увеличивать остальные элементы сайта на большой ширине?

**Comment by andrei-roh** [comment]
@darth-tesla да, если нужно, то можно увеличить масштаб шрифта и размеры картинок и логотипов для большого разрешения экрана. Например с помощью медиазапроса на плотность точек.

**Comment by darth-tesla** [comment]
> @darth-tesla да, если нужно, то можно увеличить масштаб шрифта и размеры картинок и логотипов для большого разрешения экрана. Например с помощью медиазапроса на плотность точек.

Вопрос в том, какой вариант лучше с точки зрения UX 🤔

**Comment by andrei-roh** [comment]
@darth-tesla моя логика такая - пользователь открыл сайт и видит мелкий шрифт и расползшиеся элементы, он берет и увеличивает масштаб в браузере и вот тут не известно, как элементы встанут между собой, не нарушится ли верстка. Поэтому, если ширина ограничена, то все элементы со всеми расстояниями между собой пропорционально увеличатся при масштабировании.

**Comment by svetit** [comment]
@andrei-roh Дзякуй за прапанову! Гэта вельми прыемна, калі ў чалавека з каманды узнікае жаданне палепшыць штосьці!

У мяне дазвол экрана 1920 на 1080 і ен мне падаецца агромны ужо.. :))))
Цяжка уявіць вячэзны экран на 27 цаляў.. і болей.

Ідэя ўладкаваць сайт, каб ен выглядаў лепш на вельмі вялікім экране - добрая.
Але прапанова, малюнак 2 мне не падабаецца. Бо ідэя была як раз у тым, каб фон з кароўкай на лузе расцягваўся на усю шырыню.
У нас у камандзе раней былі ідэі змяніць фон. падабраць іншую карову на лугу. (бо тэкст не вельмі добра чытаецца на гэтым фоне) і з гэтай ідэяй я магу згадзіцца, але так і не знайшлі фота пад свабоднай ліцэнзіяй на гэтую тэму, якое бы было лепш.

Прапанова такая - зрабіць апытанне і даведацца, ці рэальна гэта з'яўляецца праблемай.. - апытаць кожнаму з нас некалькі чалавек, у каго вялікі манітор. Калі праблема сапраўды існуе.. то можам працягнуць ідэі па яе вырашэнню, калі ж гэта не вельмі прынцыпова.. то можа пакуль лепей на іншае пераключыцца.

**Comment by rizomaa** [comment]
@andrei-roh на чым спыняемся?
