### ISSUE TITLE
Улучшить быстродействие сайта Doika // https://doika.falanster.by/

### ISSUE THREAD

**Issue by andrei-roh** [diglabby/doika#744]
В сss файле header.css я обнаружил, что изображение коровы на фоне травы закодировано в css файле в виде пары сотен строк кода. Сам css файл из-за этого занимает >1MБ, его загрузка проходит 382ms вместо 45ms у остальных css файлов, и это изображение не кэшируется, то есть оно загружается каждый раз при обновлении страницы заново.
В связи с этим предлагаю изображение коровы представить в .png и разместить также, как и остальные картинки.
![Аннотация 2020-05-28 214410](https://user-images.githubusercontent.com/65450338/83180748-92198380-a12c-11ea-9832-efbe091f9322.jpg)
![Аннотация 2020-05-28 214411](https://user-images.githubusercontent.com/65450338/83180766-95ad0a80-a12c-11ea-9654-9cb61d3ed9f5.jpg)

**Comment by rizomaa** [comment]
@andrei-roh 
1. ці будзе кэшыравацца выява?
2. а колькі яе загрузка асобная займае? 
гэта аднастаронкавы лэндынг, таму важна:: ці ёсць ээканомія пры першай загрузцы.

**Comment by andrei-roh** [comment]
@rizomaa 
1. Обычные изображения обычно кэшируются и остаются в дальнейшем для использования не только при обновлении страницы на F5, но и при закрытии/открытии браузера 
2. Грубо говоря: изображение в виде кода "весит" 1,2 МБ, а сжатым будет от 500 кБ до 150 кБ в зависимости от формата. Загрузится оно (изображение) в 2-3 раза быстрее. 

Для усиления масштаба трагедии укажу, что строка с изображением занимает примерно 1236278 символов css кода.

**Comment by rizomaa** [comment]
@svetit можаш пракаментаваць чаму ты закінулы выяву ў css?

**Comment by svetit** [comment]
@andrei-roh @rizomaa 
справа была такая. Адзин з валанцёраў - @KahjuksEi спрабаваў палепшыць верстку сайта.
І ен памяняў некаторыя выявы на нейкі код.
Я нічога у гэтым не разумею, і я першасна дадавала толькі png. І буду працягваць дадаваць пнг.
Зараз я не маю фоткі каровы, яна згубілася, і таму замяніць покул не магу. Я ужо хацела гэта зрабіць год назад, але не знайшла выяву. (Ці можна яе неяк преабразаваць карову з гэтага кода у пнг абратна?)
А якія іншыя выявы пераробленыя у код?

**Comment by KahjuksEi** [comment]
Спакойно, вот она))
![lostCow](https://user-images.githubusercontent.com/39082880/83284587-86d65e80-a1e5-11ea-9c1a-7b1adf09a044.png)

**Comment by KahjuksEi** [comment]
кстати чо то с сайтом в брейве и хроме 
![Annotation 2020-05-29 194325](https://user-images.githubusercontent.com/39082880/83284972-28f64680-a1e6-11ea-941e-067d1c1ae8e3.png)

**Comment by andrei-roh** [comment]
@KahjuksEi у меня на смартфоне в хроме ругалось на ненадежный сайт.
О, я попробую улучшить улучшенную верстку

**Comment by svetit** [comment]
@KahjuksEi дзякуй Андрэй, цудоўна! Карова знайшлася! Ура!

**Comment by rizomaa** [comment]
@andrei-roh @KahjuksEi дзякуй, што папярэдзілі, я зараз разбіраюся з гэтай задачай. Напішу, калі ўсё будзе ў страю.

**Comment by alies-dev** [comment]
Спадарства а давайце гэты рэпазіторый выкарытоўваць для дойкі толькі, а не для сайта дойкі, абяцаю што на доўгай дыстанцыі ніхто шкадаваць пра гэта не будзе :)

**Comment by rizomaa** [comment]
@lptn калі ласка не перашкаджай пакуль людзям працаваць у гэтай задачы. Я пакуль адмыслова не рассейваю нас па рэпам, бо 1. нас не шамт. 2. задача стаіць спрацавацца на простых тасках. 

Калі усе будуць арыентавацца добра ва усім, будзем разносіць па рэпам. Я прыйкрасна разумею, што блытаць не трэба. 

зы
Дарэчы, калі ты шукаеш ішу для ўдзелу ёсць для цябе.

**Comment by andrei-roh** [comment]
@svetit Доброе утро. Попробовал внести изменения в верстку сайта. Экспериментировал на своем github домене. Результат скорости загрузки с изображением, закодированным в header.css:
![Аннотация 2020-05-29 223105](https://user-images.githubusercontent.com/65450338/83319938-2f6ad980-a24b-11ea-9e0a-ec50e25a723c.jpg)
Результат с отдельным изображением, тег на которое я для большего приоритета в загрузке я поместил прямо в index.html с абсолютным позиционированием:
![Аннотация 2020-05-29 223104](https://user-images.githubusercontent.com/65450338/83319972-73f67500-a24b-11ea-916b-107d5cc7ae46.jpg)

Насчет кэширования я ошибся, не проверил актуальность информации, приношу извинения. Кэшируется и при закодированном в css изображении и при отдельном изображении. Разница для пользователей сайта кроме скорости загрузки в объеме данных для загрузки: 1,2 МБ при кодировке в css против 266 кБ для отдельного изображения

**Comment by svetit** [comment]
@andrei-roh  Шчыра кажучы, я не зусім зразумела у чым розница.
Ты параўноўваешь тое, што зараз - код на выяву, з варычнтам, калі выява сапраўдная у пнг?
І апошняее хутшэй, так?
А што значыць "абсалютнае пазіцыянаванне" ?

**Comment by andrei-roh** [comment]
Да, верно, просто изображение загрузится быстрее изображения в виде кода. Абсолютное позиционирование это когда элемент становится как бы невесомым и его можно перемещать как угодно, даже накладывать на другие элементы - он как-бы невидим для них. Я использовал это вместо css свойства background url, так как я вызвал изображение непосредственно в html файле буквально перед заголовками

**Comment by svetit** [comment]
@andrei-roh Ага, дзякуй.
Калі пры гэтым візуальна нічога не зменіцца на дэсктопе і  ў версіі шырыні планшэта і мабілкі, то можна зрабіць, як ты сказаў:)

**Comment by KahjuksEi** [comment]
Вроде быстрее чем в base64 не отрисуется ни каким способом.

ср, 3 июн. 2020 г., 21:36 Sviatlana Yermakovich <notifications@github.com>:

**Comment by andrei-roh** [comment]
@KahjuksEi я предварительно размещу сайт у себя в git pages и можно будет сравнить скорости

**Comment by KahjuksEi** [comment]
Год назад уже проверяли, где то скрины должны были висеть на эту тему

чт, 4 июн. 2020 г., 13:38 Andrei Roh <notifications@github.com>:

**Comment by rizomaa** [comment]
@andrei-roh як тут тэст хуткасцяў?

**Comment by andrei-roh** [comment]
https://github.com/diglabby/doika/issues/744#issuecomment-636279064
Вот мой тест времени отклика сервера и времени закачке при размещении сайта на git pages, если я правильно понял вопрос

**Comment by rizomaa** [comment]
@andrei-roh добра, тады ці вызначыліся тут, што рабіць?

**Comment by andrei-roh** [comment]
@rizomaa @svetit  Я выложил на git pages версию с обычным изображением https://andrei-roh.github.io для подтверждения
