### ISSUE TITLE
Фронт энд. Аформіць табы на старонцы "Паведамленняў"

### ISSUE THREAD

**Issue by falanster** [diglabby/doika#75]
Аформіць табы на старонцы "Паведамленняў" 

Стварыць:
- [x] - Таб для рэкурэнтных
- [x] - таб для адзіночных плацяжоў
- [x] - разнесці існуючыя элементы па табах (калі не відавочна ўто разносіць, запытай!).

Старонка на тэставым серваку:
http://it3donate-landing.falanster.by/doika/en/admin/notifications#

**Comment by falanster** [comment]
@fr0zen зрабіў картку па дабам. яна уаткульана на другі+ спрынты @nastyafrosty

**Comment by rizomaa** [comment]
@maxmatoha ці усё словы зразумелыя з назвы і апісання задачы?

**Comment by maxmatoha** [comment]
module configurations=>notificatons(гэта паведамлення)
выбар аператара не бачу

**Comment by rizomaa** [comment]
колькі часу ў цябе зойме для працы над гэтай задачай @maxmatoha

**Comment by maxmatoha** [comment]
Як ты казаў спачатку раблю #199 потым камунікую з @nastyafrosty наконт афармлення

**Comment by rizomaa** [comment]
можаш ацаніць колькасць гадзін, або дзён, тыдняў? @maxmatoha

**Comment by maxmatoha** [comment]
Напэўна тыдзень

пн, 11 февр. 2019 г., 23:59 Mister Cable notifications@github.com:

**Comment by nastyafrosty** [comment]
@nastyafrosty remade the prototype

**Comment by nastyafrosty** [comment]
@maxmatoha  https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346471444291   вот,переделала прототип. т.е. сейчас два таба будет: 1)к серверной части относится, 2й - к самим письмам

**Comment by fr0zen** [comment]
@KahjuksEi @maxmatoha што думаеце наконт гэтай issue? Сутнасць: На старонцы наладкі Паведамленняў разнесці існуючыя палі па трох табах:
1. Наладкі паштовага сэрвера.
2. Паведамленне пры рэкурэнтных плацяжах
3. Паведамленне пры адзіночных плацяжах

**Comment by maxmatoha** [comment]
@frOzen это как я делал bepay artpay?

**Comment by fr0zen** [comment]
@fr0zen зроблена, патэсціць

**Comment by rizomaa** [comment]
@Olya147 ці краналася гэта карткі?

**Comment by rizomaa** [comment]
Гатова,пакуль ляжаць у галіне 8-notifications

**Comment by rizomaa** [comment]
https://github.com/diglabby/doika/pull/709
