### ISSUE TITLE
Выправіць старонку вікі: Праца з гіт рэпазіторыем

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#752]
Асноўная праблема заўважана добра тут:
1. Адсутнасць стэйдж сэрвера. 
2. Занадта шмат увагі галіне master з якой ідзе толькі зборка рэліза.
3. Не прапиана чотка з якой галіны робіцца ПР у апстрым.

Слушныя каментары па сённяшняму стану гайда:
https://github.com/diglabby/doika/pull/747

Спасылка на старонку вікі: 
https://github.com/diglabby/doika/wiki/Распрацоўшчыку.-Git.-Праца-з-рэпазіторыем

**Comment by rizomaa** [comment]
@KuhniaDruggist калі ласка прачытай секцыю [Алгарытм працы з галінкамі](
https://github.com/diglabby/doika/wiki/Распрацоўшчыку.-Git.-Праца-з-рэпазіторыем#Алгарытм-працы-з-галінкамі)
, абнавіў як.

Напішы тут, што засталося няясным. Дапрацую

**Comment by KuhniaDruggist** [comment]
@rizomaa Не понял этого момента 
![Screenshot_128](https://user-images.githubusercontent.com/48412681/85432855-3ce65b80-b58c-11ea-80fa-4f0a3c26d6e2.png)

Зачем git pull?
Если имеется ввиду притянуть изменения, то, как мне кажется, лучше делать это предварительно, чтобы каждый раз работать с актуальным проектом.
В моем представлении это
1. переключаемся у себя на ветку разработки **git checkout develop**
2. тянем изменения с (upstream) **git pull upstream develop**.
3. пушим полученные изменения себе в форк **git push origin develop**

После этого можно создавать новую ветку под новый issue

**Comment by rizomaa** [comment]
Прывітанне, @KuhniaDruggist 

Дзякуй за каментары
1. "Зачем git pull?" З большага гэта звычка, перад пачаткам працы забіраць усе абнаўленні, калі працуеш у камандзе, каб мінімізаваць колькасць канфліктаў пры push. Тут магчыма будзе больш актуальным забраць абнаўленні з апстрыма. Думаю...
2. Так-так.... чытаю твой каментар ніжэй. Гэты кавалак можнасмела ўстаўляць.

**Comment by rizomaa** [comment]
@KuhniaDruggist адаптаваў тваю прапанову ў кроку 1 з пераходам на 3, а ў чацвёртым ёсць усё, што неабходна для пуша па твайму сцэнару. Чэкні яшчэ раз, каб захаваць зразумеласць

**Comment by rizomaa** [comment]
Улічыў рэкамендацыі. Адпраўляю у гатова. Калі знойдзем патэнцыйл для паляпшэння. створым новую картку
