### ISSUE TITLE
Прыбраць зялёны перакрываючы фон з прыціска (кнопкі) і падправіць стылі пад самім прыціскам

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#760]
Гл. скрыншот 
![Selection_005](https://user-images.githubusercontent.com/9870374/86625158-4e3c5880-bfcd-11ea-99d7-fc838c209d33.png)

Гэта на старонцы <хост>/doika/doika/widget/campaigns/<ID-кампаніі>/recurrent/donate

**Comment by andrei-roh** [comment]
@rizomaa не получается сделать тестовый платеж
![Аннотация 2020-07-31 185003](https://user-images.githubusercontent.com/65450338/89052683-bed15d80-d35e-11ea-8d8d-17114a76033e.jpg)

**Comment by rizomaa** [comment]
@andrei-roh паглядзі, ці набраны у цябе тэставыя дадзеныя на старонцы канфігурацыі аргэгатара.
?

**Comment by andrei-roh** [comment]
@rizomaa 
![Аннотация 2020-08-03 092139](https://user-images.githubusercontent.com/65450338/89152303-8f437080-d56b-11ea-8838-a4a780e0ed8a.jpg)
![Аннотация 2020-08-03 092140](https://user-images.githubusercontent.com/65450338/89152308-92d6f780-d56b-11ea-917e-b531e45e95e6.jpg)

**Comment by rizomaa** [comment]
@andrei-roh дадзеныя агрэгатара записваюцца тут /doika/doika/dashboard/paymentSystems

у вікі можна знайсці Тэставыя дадзеныя для праверкі аплаты пра Біпэйд https://github.com/diglabby/doika/wiki/
