### ISSUE TITLE
Зрабіць каб запісвала ў базу кожны праведзены плацёж.

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#762]
Бо пакуль галячок 
![Selection_008](https://user-images.githubusercontent.com/9870374/86626409-4ed5ee80-bfcf-11ea-90e7-28a52d743673.png)

Пратэставаць:
1. На рэкурэнтных
2. На разавых плацяжах

**Comment by rizomaa** [comment]
пачаў думаць як тут арганізаваць усё лепей)

**Comment by Alexeyvk** [comment]
Up issue )

**Comment by Alexeyvk** [comment]
"Статус оплати" - тут що саме, відповідь від єквайринга: "успіх", "відхиленно" та таке іньше?

**Comment by Tyuba4** [comment]
> "Статус оплати" - тут що саме, відповідь від єквайринга: "успіх", "відхиленно" та таке іньше?

Так

**Comment by Tyuba4** [comment]
Калі я паспрабаваў зрабіць токен і аплату праз эндпоiнт, то плацёж з'явіўся ў табліцы. Значыцца праблема можа быць на боку фронта?

**Comment by rizomaa** [comment]
@Tyuba4 на лакале рабіў ці на doika2.falanster.by ?

**Comment by Tyuba4** [comment]
> @Tyuba4 на лакале рабіў ці на doika2.falanster.by ?

На doika2.falanster.by

**Comment by alies-dev** [comment]
@Tyuba4 

мусіць жа запісваць праз вэб-хукі. Відаць лакальна ты проста не слухаў іх

https://github.com/diglabby/doika/blob/1d555cb30cb9cb0722f2b1123ed5606ce97c37bc/app/Http/Controllers/Webhooks/PaymentGateways/BePaidPaymentWebhookHandler.php#L16-L38
