### ISSUE TITLE
Чаму ў тэхналагічным стэку праекта нічога няма пра scss, які мы выкарыстоўваем?

### ISSUE THREAD

**Issue by falanster** [diglabby/doika#78]
@fr0zen можаш тут напісаць усе нюансы па фронтэнду. Каб удзельнікі ведалі якія патрабаванні да распрацоўкі фронтэнда. 

Пачаў чытаць:
http://www.thesassway.com/editorial/sass-vs-scss-which-syntax-is-better

**Comment by rizomaa** [comment]
vue.js + web pack + scss @fr0zen дадаць у тэхналагичны стэк

**Comment by fr0zen** [comment]
@rizomaa стэк у нас [тут](https://github.com/diglabby/doika_1.2/wiki/%D0%A2%D1%8D%D1%85%D0%BD%D0%B0%D0%BB%D0%B0%D0%B3%D1%96%D1%87%D0%BD%D1%8B-%D1%81%D1%82%D1%8D%D0%BA) 
Дадаў са спасылкамі

**Comment by rizomaa** [comment]
1. А што тады зараз у файле рыдмімд.
2. ТАксама чаму спасылка вядзе на версію 1.2 зараз 1.3+

**Comment by fr0zen** [comment]
@rizomaa у [бягучым](https://github.com/diglabby/doika/wiki/%D0%94%D0%BB%D1%8F-%D1%80%D0%B0%D1%81%D0%BF%D1%80%D0%B0%D1%86%D0%BE%D1%9E%D1%88%D1%87%D1%8B%D0%BA%D0%B0%D1%9E:-%D0%BA%D0%BE%D0%B4%D1%8B%D0%BD%D0%B3-%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82,-%D0%B2%D0%B5%D1%80%D1%81%D1%96%D0%B9%D0%BD%D0%B0%D1%81%D1%86%D1%8C,-%D1%82%D1%8D%D1%85%D0%BD%D0%B0%D0%BB%D0%B0%D0%B3%D1%96%D1%87%D0%BD%D1%8B-%D1%81%D1%82%D1%8D%D0%BA) вікі у нас спасылка на 1.2 Мне падаецца, што лепш перанесці інфу у актуальную вікі таксама, а не раскідваць спасылкі. Што думаеш на гэты конт?

**Comment by rizomaa** [comment]
@fr0zen синхранізуй, тое што ведаеш на сёння. 


я запытаю @Tyuba4 @lptn каб дапсалі, што яны ведаюць

**Comment by lptn** [comment]
@rizomaa 
я знайшоў у дакументацыі ХАОС!
![image](https://user-images.githubusercontent.com/5278175/52698447-8b411e80-2f84-11e9-8a89-6d01cc72202e.png)

Штосці ў рідмі, штосці ў вікі і ўсе outdated :(
стэк поўны на маю думку
