### ISSUE TITLE
Бинарные сборки, night builds

### ISSUE THREAD

**Issue by Alexeyvk** [diglabby/doika#785]
Как разработчик хочу предложить решение :) Это я смотрю шаблон сообщения issue )

В документации это не проговорено, прошу акцентировать - если недорогой хостинг не позволяет использовать composer и nodejs то решением является готовая prod сборка релиза в архиве. Эти архивы есть, но в документации по установки для разработчика это не учтено, прошу пофиксить. )

Кроме того, чтобы два раза не вставать, могу помочь с автоматизацией CI/CD и организовать ночные сборки текущего develop бранча. Туда же можно прицепить авто-тесты, к примеру.  

Искренне дойковский, Алексей Костржицкий!

**Comment by alies-dev** [comment]
@Alexeyvk

Дзякуй! Мы тэсты запускалі на Трэвісе, я іх перанёс на GitHub actions. Засталося перанесці стварэнне архіваў для усталёўкі ну і аўта-дэплой было б добра мець. Што збіраешся выкарыстоўваць для аўта-дэплоя?

>Кроме того, чтобы два раза не вставать

Лепей такі розныя issue для розных задач, а то будзе мешаніннна тут, праверана :)

@rizomaa 
Для аўта-дэплоя GitHub трэба каб меў SSH доступ да нашага сэрвера. Прыватны ключ трэба дадаць сюды https://github.com/diglabby/doika/settings/secrets/actions (імя любое, шапрыклад FALASTER_SERVER_PRIVATE_SSH_KEY) , публічны - дадаць на сэрвер. Зробіш?

**Comment by alies-dev** [comment]
@Alexeyvk 

Я стварыў задачу "Ствараць інсалятар дойкі праз GitHub actions/workflows #796", калі ёсць жаданне - можаш браць (але яна не прыярытэтаня зараз)
