### ISSUE TITLE
Праблема з выкананнем composer install

### ISSUE THREAD

**Issue by Tyuba4** [diglabby/doika#786]
Пры разгортваннi плагiна пад час выканання composer install на linux-серверы узнiкая памылка

![Снимок экрана 2021-03-01 в 10 23 00](https://user-images.githubusercontent.com/32882913/110599973-7bf92300-8194-11eb-87c2-b6e847b9fc58.png)

## Тэставыя ўмовы

- Версія Doika: 
- Платформа і версія: Linux
- bash

**Comment by rizomaa** [comment]
@Tyuba4 Зараз мы маем версію 

Composer 1.6.3 2018-01-31 16:28:17

Такое піша факультатыўна на іншых сборках.
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2

Я паўтару усталёўку у нас на сэрверы сёння, каб дакладна праверыць у чым праблема.

**Comment by Alexeyvk** [comment]
Підтверджую, дана проблема установки вирішувалася вже на двох точно линукс середовищах шляхом зниження версії composer до 1.10.20 на macos и на linux.

> debian@debian:/var/www/staging2.dbai.net.ua/public_html/doika# ./composer.phar i
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package carbondate/carbon is abandoned, you should avoid using it. No replacement was suggested.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package martinlindhe/laravel-vue-i18n-generator is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Deprecation Notice: Class Tests\Feature\Http\Controllers\Webhooks\PaymentGateways\BePaidPaymentWebhookHandlerTest located in ./tests/Feature/Http/Controllers/Webhooks/PaymentGateways/Payments/BePaidPaymentWebhookHandlerTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///var/www/staging2.dbai.net.ua/public_html/doika/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Diglabby\Doika\Http\Controllers\Auth\VerificationController located in ./app/Http/Controllers/Dashboard/Auth/VerificationController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///var/www/staging2.dbai.net.ua/public_html/doika/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Diglabby\Doika\Http\Controllers\Auth\LoginController located in ./app/Http/Controllers/Dashboard/Auth/LoginController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///var/www/staging2.dbai.net.ua/public_html/doika/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Diglabby\Doika\Http\Controllers\Auth\ForgotPasswordController located in ./app/Http/Controllers/Dashboard/Auth/ForgotPasswordController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///var/www/staging2.dbai.net.ua/public_html/doika/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Diglabby\Doika\Http\Controllers\Auth\ResetPasswordController located in ./app/Http/Controllers/Dashboard/Auth/ResetPasswordController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///var/www/staging2.dbai.net.ua/public_html/doika/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: anlutro/l4-settings
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-ide-helper
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: carbondate/carbon
Discovered Package: diglabby/laravel-find-missing-translations
Discovered Package: fideloper/proxy
Discovered Package: laravel/dusk
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: martinlindhe/laravel-vue-i18n-generator
Discovered Package: nunomaduro/collision
Discovered Package: spatie/laravel-query-builder
Discovered Package: tightenco/ziggy
Package manifest generated successfully.
63 packages you are using are looking for funding.
Use the \`composer fund\` command to find out more!

**Comment by rizomaa** [comment]
@Tyuba4 @Alexeyvk 

У канфіге composer.json змяніў версію php з 7.1.3 на 7.2.5

43     "config": {
 44         "optimize-autoloader": true,
 45         "platform": {
 46           "php": "**7.2.5**"
 47         },

Больщ нічога не спатрэбілася... бягучую версію кампозера на сэрверы пісаў вышэй = 1.6.3 
Яшчэ на лакальным сэрверы (зараз там 1.8.5 і Doika працуе) праверу з другой версіяй кампозера.

**Comment by Alexeyvk** [comment]
@alexey-shev можем подтянуть composer.json, может багов поменьшеет )

**Comment by alies-dev** [comment]
хлопцы, трэба мяняць стратэгі разготвання, бо з часоў стварэння дойкі выйшла мажорная версія PHP 8 і цяпер ужо Дойка паставіцца далёка не нна ўсе асяроддзі. Трэба пашырыць сьпіс падтрымліваемых версій, прыбраць `config.platform.php`, выдаліць composer.lock. Магу стварыць PR з усім гэтым


**UPD**: Паглядзеў я залежнасці нашы - не атрымаецца на адной галіне падтрымліваць адначасова php7.1+ і php8, але можам пашырыць падтрымку да php7.4 ці гэтым не ламаць php7.1


Але пытанне ў тым, што зараз з версіямі PHP адбываецца у патэнцыйных карыстальнікаў, ці модам павышаць да 7.3? https://www.php.net/supported-versions.php - крайняя версія зараз 7.3 з security updates, у ідыяле трэба прытрымлівацца крайняга рэлізу PHP, мы ж такі з плацяжамі працуем, можам ен падтрымліваць мёрствыя версія PHP

**Comment by alies-dev** [comment]
Праблема вырашага выдаленнем composer.lock каторы быў ствараны з-пад PHP 7.2 стаму інне ставілася на PHP 7.1. Цяпер у рэпазіторыі нняма composer.lock, тэсты заняюцца на розных версіях PHP: 7.1, 7.2, 7.3 і 7.4 (для 8.0 трэба рабіць новы брэнч, нне атрымаецца усе версіі адначасова падтрымліваць)
