### ISSUE TITLE
Mysql-сумяшчальнасць Something wrong with syntax because of need to support JSON

### ISSUE THREAD

**Issue by falanster** [diglabby/doika#79]
sudo mysql -uroot -p123123123 doika13 < doika.sql
ERROR 1064 (42000) at line 32: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json DEFAULT NULL,
 `recipients` text COLLATE utf8mb4_unicode_ci,
 `created_at' at line 4

**Comment by falanster** [comment]
Server version: 10.0.36-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04
PHP 7.0.32-0ubuntu0.16.04.1 (cli) ( NTS )

**Comment by falanster** [comment]
@fr0zen скажы калі ласка я магу перадаць гэту задачу каму-небудзь іншаму, або тут толькі твая рука разуруліць?

**Comment by fr0zen** [comment]
@falanster я спрабую разруліць

**Comment by rizomaa** [comment]
@fr0zen можаш напісаць крокі, якія хочаш для гэтага выканаць, магчыма на нейкім кроку мы зможам дапамагчы. 

Дарэчы траплялася такое пашырэнне https://github.com/grimzy/laravel-mysql-spatial ?

На колькі гэта будзе крытычна перапрацаваць гэта задачу не зараз, а пасля некалькіх спрынтаў

**Comment by rizomaa** [comment]
Карацей зрабілі невялікае даследванне па беларускіх хостынгам @fr0zen 

https://docs.google.com/spreadsheets/d/1Bjj12TP-mcoKCex9FzL0iC4dqzWDLWNl0Geq_40tNi4/edit#gid=0

Звярни увагу наконт версій базы. 

Мяркую гэта зараз супер важная задача зараз становіцца, каб у нас зноў не накаплівалася тэхнічная пазыка.

Калі ласка прагавары, які алгарытм бачых для вырашэння, або ідэі. Бо чым раней ўробім тым менш часу трэба будзе траціць на пераробку.

**Comment by Tyuba4** [comment]
В миграциях JSON нет, значит все решилось и конфликтов нет. @fr0zen @lptn
