### ISSUE TITLE
Аўтаматычна фіксіць coding-style праблемы для JS і vue файлаў

### ISSUE THREAD

**Issue by alies-dev** [diglabby/doika#795]
Праблема: "Пісьменнікаў" у нас шмат, у кожнага сваё кунг-фу, такжа бывае дапускаюцца дзіцячыя памылкі каторыя могуць быць аўтаматычна выпраўлены ці хаця б зарэпорчаны тулзамі (напрыклад ESLint)

**Comment by alies-dev** [comment]
Дадаў workflow, але шмат памылак якія немагчыма аўтаматычнна выправіць, таму пакуль што правярае код-стайл але не фіксіць. Каб аўтаматычна фіксіла трэба:
 - пафіксіць усе існуючыя памылкі
 - замяніць `cs:lint` на `cs:fix` тут: https://github.com/diglabby/doika/blob/ad6cbd02f379a3ae86bdf0d2f549a6fa8be194b3/.github/workflows/format_js.yml#L40

**Comment by alies-dev** [comment]
@Alexeyvk магчыма гэта будзе украінскай камандзе цікава і даклдан патрэбна: выкарыстоўваючы аднолькавы код-стайл будзем мець меней канфліктаў паміж форкамі, думаю варта прыярытэзаваць гэтую задачу. Для PHP у нас гэта наладжана, а вось з JS - не

**Comment by Alexeyvk** [comment]
> @Alexeyvk магчыма гэта будзе украінскай камандзе цікава і даклдан патрэбна: выкарыстоўваючы аднолькавы код-стайл будзем мець меней канфліктаў паміж форкамі, думаю варта прыярытэзаваць гэтую задачу. Для PHP у нас гэта наладжана, а вось з JS - не

Так, звісно - цілком підтримуємо!

**Comment by alies-dev** [comment]
не дачакаўся, пафіксіў  сам :)
