### ISSUE TITLE
Як адмін, хачу праглядаць і змяняць тэксты паведамленняў для разавых і рэкурэнтных плацяжоў

### ISSUE THREAD

**Issue by svetasemashko** [diglabby/doika#8]
Што патрэбна:

- [ ] Рэалізаваць бэкэнд фічы
- [ ] Рэалізаваць фронтэнд фічы
- [ ] Пратэставаць

Базавыя тэксты мэйла браць тут: https://docs.google.com/spreadsheets/d/1rOQv1g7skB_77JRRn6BSyyFLo5V9I5RfpCAQG0sIpr4/edit#gid=0 і тут https://docs.google.com/document/d/1CP19vpVUDnBsbQlVzZ0uP7CrpLjfZrCKk8Kw-6oKsY4/edit

**Comment by falanster** [comment]
@svetasemashko чаму гэта картка у рэфактарынгу знаходзіцца?

**Comment by falanster** [comment]
дадаў  чэк бокс. ці ёсць у нас емсца, дзе мы маем пералік паведамленняў? @nastyafrosty

**Comment by nastyafrosty** [comment]
![i](https://user-images.githubusercontent.com/41231823/49571813-547ad680-f94b-11e8-9fdb-55c7c7468599.jpg)

текст дублируется везде (terms of use, recurrent payment, single payment. Изменение в тексте одного пункта ведет к изменениям в других. так и должно быть?

**Comment by rizomaa** [comment]
@nastyafrosty слушная заўвага, толькі тэгу адразу @maxmatoha @KahjuksEi або @fr0zen

**Comment by maxmatoha** [comment]
Где поля ввода дублируются? Там айдишники надо поменять. Сегодня сдлаюОтправлено со смартфона Samsung Galaxy.
null

**Comment by fr0zen** [comment]
Што патрэбна:
1. Реалізаваць забор дадзенных па наладках сэрвера з базы
2. Рэалізаваць запіс гэтых дадзеных у базу.
3. Пратэсціць

**Comment by rizomaa** [comment]
@Olya147 ці усё тут у норме?

**Comment by rizomaa** [comment]
Бяру гэту картку.

Бэк

- [x] 1. Стварыць табліцу для захавання notifications (палі: purpose (string), message (text), id (integer), regular(boolean)) - мадэлі + міграцыі
- [x] 2. Праглядзець усе паведамленні патрэбныя для аднаразовых і рэкурэнтных плацяжоў
- [ ] 3. Стварыць кантролеры для апрацоўкі паведамленняў.
- [x] 4. Стварыць сіды з дэфолтнымі тэкстамі.
- [x] 5. Дадаць адпаведныя роўты.

Фронт

- [x] 1. Стварыць формы і кампаненты для рэдагавання кожнага паведамлення (папярэдне праглядзець наколькі цяперашнія патрэбны з такім шырокім функцыяналам). Патрэбна поле (мэта (тэкставы радок або выпадаючы спіс), паведамленне (тэкст), рэкурэнтныя або аднаразовыя - радыё кнопка)
- [x] 2. Стварыць апрацоўшчыкі.
- [ ] Факультатыўна 3. Сварыць табліцу для захавання наладак пошты (пакуль магчыма гэта непатрэбна і проста адсылаць праз mail функцыю php - пасля можна будзе падумаць над больш складанымі шляхамі.)

Пратэставаць усё...

Залежныя або камплементарныя задачы:
1. [Папярэджанне пра з'ём сумы згодна падпіскі](https://github.com/diglabby/doika/issues/649)
2. [Наладзіць паведамленні калі адбылася разавая аплата або падпіска ](https://github.com/diglabby/doika/issues/648)
3. [Абнавіць кантэнт імэйлаў па разавым і рэкурэнтным плацяжам (агульны спіс для усіх выпадкаў) ](https://github.com/diglabby/doika/issues/583)
4. Ці ёсць гэтыя паведамленні: [Фіча. Наладзіць паведамленні, калі не адбылася аплата: няма сродкаў, скончыўся тэрмін карты.](https://github.com/diglabby/doika/issues/565#)
5. [Напісаць тэксты мэйлаў 1. вітальны ліст 2. для рэкурэнтных плацяжоў 3 для апрацоўкі памылак](https://github.com/diglabby/doika/issues/222)
6. [Фронт энд. Аформіць табы на старонцы "Паведамленняў"](https://github.com/diglabby/doika/issues/75)

**Comment by rizomaa** [comment]
У гэтым файле цікавы спіс: https://github.com/diglabby/doika/blob/develop/resources/js/dashboard/views/Notifications.vue

- [ ] notificationsAddress: null,
- [ ] notificationsPort: null,
- [ ] notificationsUser: null,
- [ ] notificationsPassword: null,
- [ ] notificationsEmail: null,
- [ ] notificationsSingleEmail:null,
- [ ] messageSingleTransaction: null,
- [ ] messageReccurentTransaction: null,

**Comment by rizomaa** [comment]
Спыніўся на кантролеры і рэсурсах (калекцыях?)... заўтра працягну.

1. Эндпоінты павінны вяртаць джэйсон масіў.
2. Паспрабаваць гэта усё акучыць на пост мэне...

**Comment by rizomaa** [comment]
Зрабіў прамежкава вы ПР https://github.com/diglabby/doika/pull/706 неабходна праглад з боку бэкэнда @Tyuba4 @lptn ці адэкват там...

**Comment by rizomaa** [comment]
Далей вырашыць:

- [x] 1. Як запаўняць палі 'created_at', 'updated_at' , бо нешта яны стварыліся і аўтаматам NULL прапісваюць
- [x] 2. Фронтэнд. Клавішы рэдагавання і адмены.
- [x] 3. Фронтэнд. Рэалізаваць формы рэдагавання.
- [x] 4. Бэкэнд + . Наладзіць абналеўнне ў таліцах БД і каб былі метады у УІ Фронтэнд
- [x] 5. Зрабіць каб абноўленыя значэнні былі адразу бачны на старонцы.
- [x] 6. Зрабіць папапы паспяховасці запісу.

Чытаць яшчэ: 
* https://laravel.com/docs/5.8/eloquent-resources
* https://vuejs.org/v2/guide/list.html#Mutation-Methods
* https://vuejs.org/v2/guide/components-custom-events.html
*

**Comment by rizomaa** [comment]
Дадаў гэту фічу. Прашу тэставаць.

зы

Па пункту:

- [ ] Факультатыўна 3. Сварыць табліцу для захавання наладак пошты (пакуль магчыма гэта непатрэбна і проста адсылаць праз mail функцыю php - пасля можна будзе падумаць над больш складанымі шляхамі.)

Вынесу яго у асбную ішу, бо трэба абмеркаваць, які рухавік для рассылкі прыменім першым... каб шмат не заганяцца. Для гэтага

**Comment by rizomaa** [comment]
Зачыняю картку. Гатова.
