### ISSUE TITLE
 Switch on/off банер уверсе старонкi

### ISSUE THREAD

**Issue by nastyafrosty** [diglabby/doika#82]

**Comment by nastyafrosty** [comment]
Уже есть

**Comment by rizomaa** [comment]
@nastyafrosty што значыць "ужо ёсць"

**Comment by Olya147** [comment]
@nastyafrosty где нужно искать этот баннер?

**Comment by nastyafrosty** [comment]
https://www.figma.com/file/RlVbECuyzs25TCVHZ1Sls87E/Doika-module-%D0%BA%D0%BBi%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%B0%D1%8F-%D1%87%D0%B0%D1%81%D1%82%D0%BA%D0%B0

**Comment by Olya147** [comment]
@nastyafrosty  подскажи, это оно?
![1](https://user-images.githubusercontent.com/46268205/56760194-5ed72900-67a3-11e9-86a6-6d586b5497ad.png)

**Comment by nastyafrosty** [comment]
да, на этих двух картинках - мобильная версия  с баннером

**Comment by Olya147** [comment]
@nastyafrosty закрываю карточку.
