### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by nastyafrosty** [diglabby/doika#85]

**Comment by nastyafrosty** [comment]
- [ ] full version

- [ ] without text

- [ ] without text and picture

**Comment by rizomaa** [comment]
@nastyafrosty напішы як у цябе тут ідзе. ці паспаваеш да аўторка скончыць.

калі ласка даразу залівай гатовыя варыянты у РТБ, каб пракаменціць можна было.

**Comment by nastyafrosty** [comment]
https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346448897741  ртб

https://www.figma.com/file/RlVbECuyzs25TCVHZ1Sls87E/Doika-module-%D0%BA%D0%BBi%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%B0%D1%8F-%D1%87%D0%B0%D1%81%D1%82%D0%BA%D0%B0?node-id=0%3A1    макеты

**Comment by fr0zen** [comment]
Макет зроблены, зачыняю
