### ISSUE TITLE
Скласці адзін спіс патрабаванняў да асяродку

### ISSUE THREAD

**Issue by falanster** [diglabby/doika#86]
**Сітуацыя**
Зараз існуюць асобныя спісы у Readme.md і на вікі. Яны няпоўныя і неаднолькавыя.

**Задача:**
Скласці адзін галоўны спіс патрабаванняў на readme.md 

Кансультавацца з @fr0zen @Tyuba4 @cema93 

Сумежныя задачы:
https://github.com/diglabby/doika/issues/78
https://github.com/diglabby/doika/issues/71

**Comment by rizomaa** [comment]
@ilyaaki дзякуй за пакрокавае апісанне. я гэта пытанне заўтра вынесу на размову з @fr0zen і @Tyuba4

**Comment by rizomaa** [comment]
Яшчэ вось залежная задача https://github.com/diglabby/doika/issues/79

**Comment by rizomaa** [comment]
тут ёсць незачыненыя моманты... асаблива па фронтэнду @fr0zen 
таму будзе дакументаваць у спрынце 3 @Olya147
