### ISSUE TITLE
Перанесці інфармацыю з вікі 1.2 у бягучы рэпазіторый

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#93]
@KahjuksEi пакуль рыхтуем задачы на тэставанне варта:

- [x] 1. Праверыць усе старонкі вікі і іншай дакументацыі 
- [x] 2. Перанесці усю дакументацыю на бягучы рэпазіторый.
- [ ] 3. Даць на праверку @Alexey-Chechukov

**Comment by KahjuksEi** [comment]
Поменял ссылки на Кодынг-стандарт и Прыклад-афармлення-бага в https://github.com/diglabby/doika/blob/dev/README.md
Создал страницы https://github.com/diglabby/doika/wiki/Кодынг-стандарт
и https://github.com/diglabby/doika/wiki/Прыклад-афармлення-бага.

**Comment by rizomaa** [comment]
@KahjuksEi ці звязваўся з @Alexey-Chechukov каб ён праверыў, твае цуды?

**Comment by KahjuksEi** [comment]
> * [x]  1. Праверыць усе старонкі вікі і іншай дакументацыі
> * [x]  2. Перанесці усю дакументацыю на бягучы рэпазіторый.
> * [x]  3. Даць на праверку @Alexey-Chechukov

**Comment by rizomaa** [comment]
+1
