### ISSUE TITLE
Запісаць як працуем з кодам у вікі.

### ISSUE THREAD

**Issue by rizomaa** [diglabby/doika#94]
- [ ] 1. Прачытаць бягучую інфу (у тым ліку): https://trello.com/c/6RT3ooii/ і спасылкі там
- [ ] 2. Стварыць новую старонку і
- [ ] 3. запісаць пакрокава, што рабіў учора пры першым пулрэквэсце і бягучых правілах.

**Comment by KahjuksEi** [comment]
Поменял ссылки на Кодынг-стандарт и Прыклад-афармлення-бага в https://github.com/diglabby/doika/blob/dev/README.md
Создал страницы https://github.com/diglabby/doika/wiki/Кодынг-стандарт
и https://github.com/diglabby/doika/wiki/Прыклад-афармлення-бага.

**Comment by rizomaa** [comment]
@KahjuksEi выдатна, дзякуй

**Comment by rizomaa** [comment]
па ходу ты зрабіў ішу https://github.com/diglabby/doika/issues/93 а не гэту. @KahjuksEi 
таму перапішы там уважліва што зрабіў. і пазначэ чэкбоксы

**Comment by rizomaa** [comment]
@KahjuksEi пакуль чакаем сувязі з @Alexey-Chechukov сфакусуйся на гэтай задачы

**Comment by KahjuksEi** [comment]
> * [x]  1. Прачытаць бягучую інфу (у тым ліку): https://trello.com/c/6RT3ooii/ і спасылкі там
> * [ ]  2. Стварыць новую старонку і
> * [x]  3. запісаць пакрокава, што рабіў учора пры першым пулрэквэсце і бягучых правілах.
> * [x]  4. Поменял ссылки на Кодынг-стандарт и Прыклад-афармлення-бага в https://github.com/diglabby/doika/blob/dev/README.md
> * [x]  5. Создал страницы https://github.com/diglabby/doika/wiki/Кодынг-стандарт
и https://github.com/diglabby/doika/wiki/Прыклад-афармлення-бага.

**Comment by rizomaa** [comment]
@KahjuksEi тут вядзе на пустую старонку https://github.com/diglabby/doika/wiki/Прыклад-афармлення-бага

пракаментуй

**Comment by KahjuksEi** [comment]
@rizomaa  Готово, кто-то недописал название новой страницы.

**Comment by rizomaa** [comment]
Па якой спасылцы ўсё працуе? @KahjuksEi

**Comment by KahjuksEi** [comment]
Прыклад-афармлення-бага-рапарта теперь работает по ссылке https://github.com/diglabby/doika/wiki/Прыклад-афармлення-бага-рапарта

**Comment by rizomaa** [comment]
@KahjuksEi дзякуй.

@Olya147 паглядзі ці бачыш, што можна дадаць на старонку афармлення багаў? дадавай

**Comment by Olya147** [comment]
@rizomaa немного дополнила. 
Всего хватает.

**Comment by rizomaa** [comment]
тады зачыняй картку
