### ISSUE TITLE
Дадаць кнопки пачатковай и фінальнай даты ў форму стварэння кампаніі.

### ISSUE THREAD

**Issue by fr0zen** [diglabby/doika#99]
https://realtimeboard.com/app/board/o9J_k0X88dM=/?moveToWidget=3074457346330533777 макет тут, кнопкі павінны быць пад кнопкамі даты пачатку і даты заканчэння. Павінны быць тэкставым полем з валідацыей (толькі лічбы)

**Comment by fr0zen** [comment]
@KahjuksEi ацаніць задачу да 02.02

**Comment by KahjuksEi** [comment]
Какие кнопки надо? Сабмиты чтобы дропдауны календарей сворачивались после выбора даты что ли, как в 1.2?

**Comment by rizomaa** [comment]
@KahjuksEi як у 1.2.

@nastyafrosty у цябе ёсць заўвагі па знешняму выгляду гэтых прыціскаў?

**Comment by KahjuksEi** [comment]
@fr0zen из какого файла в версии 1.2 подтягиваются эти события в min.js? Хотя если структура доек не аналогичная, то подскажи в каком файле редактятся события в версии 1.3.
![qip shot - screen 702](https://user-images.githubusercontent.com/39082880/52136727-cb85d000-2659-11e9-8ae6-6c5ac258b3da.png)

**Comment by fr0zen** [comment]
@KahjuksEi Дадаць, каб пры націсківанні на дату, каляндар схлопваўся і дата пераходзіла ў поле даты. Прыбраць час с поля даты.

**Comment by nastyafrosty** [comment]
Віджет календаря понравілся, круто!

![screenshot_2019-02-02_15-50-20](https://user-images.githubusercontent.com/41231823/52164444-6f2abb00-2702-11e9-9668-fd665e91df14.png)

mozilla , 1366, шіріну раочей області было бы здорово сделать больше, чтобы слова start at, finish at (календарь), amount помеўалісь в одну строчку

**Comment by rizomaa** [comment]
+1

**Comment by rizomaa** [comment]
@KahjuksEi ці авершана гэта картка?

**Comment by fr0zen** [comment]
@rizomaa завершана тут [#211](https://github.com/diglabby/doika/pull/211)
